library("persqueue") {
  public_deps = [
    # "//library/cpp/containers/absl_flat_hash",
    # "//library/cpp/monlib/dynamic_counters",
    # "//library/cpp/sliding_window",
    # "//library/cpp/time_provider",
    "//ydb/core/base",
    # "//ydb/core/jaeger_tracing",
    "//ydb/core/keyvalue",
    "//ydb/core/persqueue/common",
    "//ydb/core/persqueue/events",
    "//ydb/core/persqueue/pqrb",
    "//ydb/core/persqueue/pqtablet/blob",
    # "//ydb/core/persqueue/pqtablet/cache",
    "//ydb/core/persqueue/pqtablet/quota",
    "//ydb/core/persqueue/public",
    # "//ydb/core/persqueue/public:cluster_tracker",
    "//ydb/core/persqueue/public:counters",
    "//ydb/core/persqueue/public:partition_key_range",
    "//ydb/core/persqueue/public:utils",
    "//ydb/core/protos",
    # "//ydb/core/tablet",
    "//ydb/library/actors/core",
    # "//ydb/library/persqueue/counter_time_keeper",
    "//ydb/library/persqueue/topic_parser",
  ]

  deps = [
    "//contrib/libs/fmt",
    # "//contrib/libs/protobuf",
    # "//library/cpp/containers/stack_vector",
    "//library/cpp/html/escape",
    "//library/cpp/html/pcdata",
    "//library/cpp/json",
    # "//library/cpp/monlib/service/pages",
    "//ydb/core/backup/impl",
    # "//ydb/core/metering",
    # "//ydb/core/persqueue/common:proxy",  # peerdir only
    "//ydb/core/persqueue/pqtablet/common",
    "//ydb/core/persqueue/pqtablet/partition/mirrorer",
    "//ydb/core/persqueue/pqtablet/partition/mlp",
    # "//ydb/core/persqueue/public:fetcher",  # peerdir only
    # "//ydb/core/persqueue/public:list_topics",  # peerdir only
    "//ydb/core/persqueue/public:write_meta",
    "//ydb/core/persqueue/writer",
    # "//ydb/core/quoter:public",
    # "//ydb/core/scheme",
    # "//ydb/core/sys_view:service",
    # "//ydb/core/tx",
    # "//ydb/core/tx/long_tx_service:public",
    "//ydb/core/tx/replication/service",
    # "//ydb/core/tx/replication/ydb_proxy",
    # "//ydb/core/tx/scheme_cache",
    "//ydb/core/tx/time_cast",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/protobuf_printer",
    # "//ydb/library/services",
    # "//ydb/library/wilson_ids",
    # "//ydb/library/yverify_stream",
    # "//ydb/public/api/protos",
    # "//ydb/public/lib/base",
    "//ydb/services/persqueue_v1:actors",
  ]

  sources = [
    "dread_cache_service/caching_service.cpp",
    "pq.cpp",
    "pqtablet/fix_transaction_states.cpp",
    "pqtablet/metering_sink.cpp",
    "pqtablet/partition/autopartitioning_manager.cpp",
    "pqtablet/partition/consumer_offset_tracker.cpp",
    "pqtablet/partition/explicit_message_groups.cpp",
    "pqtablet/partition/message_id_deduplicator.cpp",
    "pqtablet/partition/offload_actor.cpp",
    "pqtablet/partition/ownerinfo.cpp",
    "pqtablet/partition/partition.cpp",
    "pqtablet/partition/partition_blob_encoder.cpp",
    "pqtablet/partition/partition_compactification.cpp",
    "pqtablet/partition/partition_compaction.cpp",
    "pqtablet/partition/partition_init.cpp",
    "pqtablet/partition/partition_mlp.cpp",
    "pqtablet/partition/partition_monitoring.cpp",
    "pqtablet/partition/partition_read.cpp",
    "pqtablet/partition/partition_sourcemanager.cpp",
    "pqtablet/partition/partition_write.cpp",
    "pqtablet/partition/sourceid.cpp",
    "pqtablet/partition/subscriber.cpp",
    "pqtablet/partition/user_info.cpp",
    "pqtablet/pq_impl.cpp",
    "pqtablet/pq_impl_app.cpp",
    "pqtablet/pq_impl_app_sendreadset.cpp",
    "pqtablet/readproxy/readproxy.cpp",
    "pqtablet/transaction.cpp",
  ]
}
