unittest_executable("datastreams") {
  deps = [
    "//contrib/libs/fmt",
    "//library/cpp/protobuf/interop",
    "//library/cpp/threading/local_executor",  # peerdir only
    "//ydb/core/cms/console",
    "//ydb/core/external_sources",
    "//ydb/core/kqp",  # peerdir only
    "//ydb/core/kqp/common",
    "//ydb/core/kqp/common/events",
    "//ydb/core/kqp/common/simple",
    "//ydb/core/kqp/federated_query",
    "//ydb/core/kqp/proxy_service",
    "//ydb/core/kqp/ut/common",
    "//ydb/core/kqp/ut/federated_query/common",
    "//ydb/library/testlib/common",
    "//ydb/library/testlib/pq_helpers",
    "//ydb/library/testlib/s3_recipe_helper",
    "//ydb/library/testlib/solomon_helpers",
    "//ydb/library/yql/dq/actors/compute",
    "//ydb/library/yql/providers/generic/connector/libcpp",
    "//ydb/library/yql/providers/generic/connector/libcpp:ut_helpers",
    "//ydb/library/yql/providers/s3/actors",
    "//ydb/public/sdk/cpp/src/client/draft",
    "//yql/essentials/parser/pg_wrapper",  # peerdir only
    "//yql/essentials/sql/pg",  # peerdir only
  ]

  data_deps = [ "//ydb/apps/ydbd" ]

  sources = [ "datastreams_ut.cpp" ]

  include_dirs = [
    "//ydb/core/kqp",  # peerdir only
  ]

  test_depends_unbuilt = [
    "//contrib/python/moto/bin",
    "//ydb/library/yql/tools/solomon_emulator/bin",
    "//ydb/library/yql/tools/solomon_emulator/recipe",
    "//ydb/public/tools/ydb_recipe",
    "//ydb/tests/tools/s3_recipe",
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_wrapper",
    "yql_pg_sql_translator=pg",
    "yt_codegen=llvm16",
  ]
}
