library("yt") {
  deps = [
    # "//ydb/core/base",
    "//ydb/core/protos",
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx/datashard",
    # "//ydb/library/aclib",  # peerdir only
    # "//ydb/library/actors/core",
    "//ydb/library/services",
    # "//yql/essentials/parser/pg_wrapper/interface",
    # "//yql/essentials/types/binary_json",
    # "//yt/yt/client",
    # "//yt/yt/core",
  ]

  sources = [
    "export_yt.cpp",
    "yt_shutdown.cpp",
    "yt_wrapper.cpp",
  ]
}
