library("yson_value") {
  public_deps = [
    # "//library/cpp/yson",
    # "//library/cpp/yson:node",
    # "//ydb/public/sdk/cpp/src/client/result",
    # "//ydb/public/sdk/cpp/src/client/types/fatal_error_handlers",
    # "//ydb/public/sdk/cpp/src/client/value",
  ]

  sources = [ "ydb_yson_value.cpp" ]
}
