library("commands") {
  public_deps = [
    # "//library/cpp/histogram/hdr",
    # "//library/cpp/logger",
    # "//library/cpp/threading/future",
    # "//ydb/library/workload/abstract",
    # "//ydb/public/lib/json_value",
    # "//ydb/public/lib/ydb_cli/common",
    # "//ydb/public/lib/ydb_cli/topic",
    # "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/topic",
    # "//ydb/public/sdk/cpp/src/client/discovery",
    # "//ydb/public/sdk/cpp/src/client/draft",
    # "//ydb/public/sdk/cpp/src/client/driver",
    # "//ydb/public/sdk/cpp/src/client/persqueue_public",
    # "//ydb/public/sdk/cpp/src/client/query",
    # "//ydb/public/sdk/cpp/src/client/scheme",
    # "//ydb/public/sdk/cpp/src/client/table",
    # "//ydb/public/sdk/cpp/src/client/types",
    # "//ydb/public/sdk/cpp/src/client/types/operation",
  ]

  deps = [
    # "//library/cpp/colorizer",
    # "//library/cpp/digest/md5",
    # "//library/cpp/json",
    # "//library/cpp/regex/pcre",
    # "//library/cpp/string_utils/csv",
    # "//library/cpp/string_utils/url",
    # "//library/cpp/threading/local_executor",
    # "//library/cpp/time_provider",
    # "//ydb/core/base",
    # "//ydb/library/accessor",
    # "//ydb/library/arrow_inference",
    # "//ydb/library/backup",
    # "//ydb/library/formats/arrow/csv/table",
    # "//ydb/library/workload/tpcc",
    # "//ydb/library/workload/vector",
    # "//ydb/library/yaml_config:public",
    # "//ydb/library/yverify_stream",
    # "//ydb/public/api/grpc",
    # "//ydb/public/api/protos",
    # "//ydb/public/lib/stat_visualization",
    # "//ydb/public/lib/ydb_cli/commands/interactive",
    # "//ydb/public/lib/ydb_cli/commands/sqs_workload",
    # "//ydb/public/lib/ydb_cli/commands/topic_workload",
    # "//ydb/public/lib/ydb_cli/commands/transfer_workload",
    # "//ydb/public/lib/ydb_cli/dump",
    # "//ydb/public/lib/ydb_cli/dump:files",
    # "//ydb/public/lib/ydb_cli/dump:util",
    # "//ydb/public/lib/ydb_cli/import",
    # "//ydb/public/lib/yson_value",
    # "//ydb/public/sdk/cpp/src/client/config",
    # "//ydb/public/sdk/cpp/src/client/debug",
    # "//ydb/public/sdk/cpp/src/client/export",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/logger",
    # "//ydb/public/sdk/cpp/src/client/import",
    # "//ydb/public/sdk/cpp/src/client/monitoring",
    # "//ydb/public/sdk/cpp/src/client/operation",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/public/sdk/cpp/src/client/types/credentials:oauth2_token_exchange",
    # "//ydb/public/sdk/cpp/src/client/types/status",
    # "//ydb/public/sdk/cpp/src/library/operation_id",
    # "//yql/essentials/public/decimal",
  ]

  sources = [
    "benchmark_utils.cpp",
    "topic_operations_scenario.cpp",
    "topic_read_scenario.cpp",
    "topic_readwrite_scenario.cpp",
    "topic_write_scenario.cpp",
    "ydb_admin.cpp",
    "ydb_benchmark.cpp",
    "ydb_bridge.cpp",
    "ydb_cluster.cpp",
    "ydb_debug.cpp",
    "ydb_diagnostics.cpp",
    "ydb_dynamic_config.cpp",
    "ydb_latency.cpp",
    "ydb_node_config.cpp",
    "ydb_ping.cpp",
    "ydb_profile.cpp",
    "ydb_root_common.cpp",
    "ydb_service_auth.cpp",
    "ydb_service_export.cpp",
    "ydb_service_import.cpp",
    "ydb_service_monitoring.cpp",
    "ydb_service_operation.cpp",
    "ydb_service_scheme.cpp",
    "ydb_service_scripting.cpp",
    "ydb_service_table.cpp",
    "ydb_service_topic.cpp",
    "ydb_sql.cpp",
    "ydb_storage_config.cpp",
    "ydb_tools.cpp",
    "ydb_tools_infer.cpp",
    "ydb_workload.cpp",
    "ydb_workload_import.cpp",
    "ydb_workload_testshard.cpp",
    "ydb_workload_tpcc.cpp",
    "ydb_yql.cpp",
  ]

  serialize_enum_headers = [
    "ydb_latency.h",
    "ydb_ping.h",
  ]
}
