# yamake2gn: keep  -- hand-written, do not regenerate

library("commands") {
  allow_undefined = true

  public_deps = [
    # "//library/cpp/histogram/hdr",
    # "//library/cpp/logger",
    # "//library/cpp/threading/future",
    # "//ydb/library/workload/abstract",
    # "//ydb/public/lib/json_value",
    "//ydb/public/lib/ydb_cli/common",
    "//ydb/public/lib/ydb_cli/topic",
    # "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/topic",
    "//ydb/public/sdk/cpp/src/client/discovery",
    # "//ydb/public/sdk/cpp/src/client/draft",
    # "//ydb/public/sdk/cpp/src/client/driver",
    # "//ydb/public/sdk/cpp/src/client/persqueue_public",
    # "//ydb/public/sdk/cpp/src/client/query",
    # "//ydb/public/sdk/cpp/src/client/scheme",
    # "//ydb/public/sdk/cpp/src/client/table",
    "//ydb/public/sdk/cpp/src/client/types",
    # "//ydb/public/sdk/cpp/src/client/types/operation",
  ]

  deps = [
    "//contrib/libs/apache/arrow",
    "//contrib/libs/aws-sdk-cpp/aws-cpp-sdk-sqs",
    "//contrib/libs/fmt",
    "//contrib/libs/ftxui",
    # "//contrib/libs/openssl",
    "//library/cpp/colorizer",
    "//library/cpp/containers/concurrent_hash",
    "//library/cpp/digest/md5",
    "//library/cpp/getopt:small",
    "//library/cpp/histogram/hdr",
    "//library/cpp/json",
    "//library/cpp/logger",
    "//library/cpp/regex/pcre",
    # "//library/cpp/string_utils/csv",
    "//library/cpp/string_utils/url",
    "//library/cpp/threading/future",
    "//library/cpp/threading/local_executor",
    "//library/cpp/time_provider",
    "//library/cpp/unified_agent_client",
    "//library/cpp/uri",
    "//ydb/core/base",
    # "//ydb/library/accessor",
    "//ydb/library/arrow_inference",
    "//ydb/library/backup",
    "//ydb/library/formats/arrow/csv/converter",
    "//ydb/library/formats/arrow/csv/table",
    "//ydb/library/plan2svg",
    "//ydb/library/workload/abstract",
    "//ydb/library/workload/benchmark_base",
    "//ydb/library/workload/tpcc",
    "//ydb/library/yaml_config:public",
    # "//ydb/library/yverify_stream",
    # "//ydb/public/api/grpc",
    "//ydb/public/api/protos",
    "//ydb/public/lib/stat_visualization",
    "//ydb/public/lib/ydb_cli/commands/interactive",
    "//ydb/public/lib/ydb_cli/commands/sqs_workload:sqs_json",
    # "//ydb/public/lib/ydb_cli/commands/transfer_workload",
    "//ydb/public/lib/ydb_cli/dump",
    "//ydb/public/lib/ydb_cli/dump:files",
    # "//ydb/public/lib/ydb_cli/dump:util",
    "//ydb/public/lib/ydb_cli/import",
    "//ydb/public/lib/yson_value",
    "//ydb/public/sdk/cpp/src/client/common_client:impl",
    "//ydb/public/sdk/cpp/src/client/config",
    "//ydb/public/sdk/cpp/src/client/debug",
    "//ydb/public/sdk/cpp/src/client/driver",
    # "//ydb/public/sdk/cpp/src/client/export",
    "//ydb/public/sdk/cpp/src/client/impl/internal/logger",
    # "//ydb/public/sdk/cpp/src/client/import",
    "//ydb/public/sdk/cpp/src/client/monitoring",
    "//ydb/public/sdk/cpp/src/client/operation",
    "//ydb/public/sdk/cpp/src/client/proto",
    "//ydb/public/sdk/cpp/src/client/query",
    "//ydb/public/sdk/cpp/src/client/scheme",
    "//ydb/public/sdk/cpp/src/client/table",
    "//ydb/public/sdk/cpp/src/client/topic/impl",
    "//ydb/public/sdk/cpp/src/client/types/credentials:login",
    "//ydb/public/sdk/cpp/src/client/types/credentials:oauth2_token_exchange",
    "//ydb/public/sdk/cpp/src/client/types/status",
    # "//ydb/public/sdk/cpp/src/library/operation_id",
    "//yql/essentials/public/decimal",
  ]

  sources = [
    "benchmark_utils.cpp",
    "topic_operations_scenario.cpp",
    "topic_read_scenario.cpp",
    "topic_readwrite_scenario.cpp",
    "topic_write_scenario.cpp",
    "ydb_admin.cpp",
    "ydb_benchmark.cpp",
    "ydb_bridge.cpp",
    "ydb_cluster.cpp",
    "ydb_command.cpp",
    "ydb_debug.cpp",
    "ydb_diagnostics.cpp",
    "ydb_dynamic_config.cpp",
    "ydb_latency.cpp",
    "ydb_node_config.cpp",
    "ydb_ping.cpp",
    "ydb_profile.cpp",
    "ydb_root_common.cpp",
    "ydb_sdk_core_access.cpp",
    "ydb_service_auth.cpp",
    "ydb_service_discovery.cpp",
    "ydb_service_export.cpp",
    "ydb_service_import.cpp",
    "ydb_service_monitoring.cpp",
    "ydb_service_operation.cpp",
    "ydb_service_scheme.cpp",
    "ydb_service_scripting.cpp",
    "ydb_service_table.cpp",
    "ydb_service_topic.cpp",
    "ydb_sql.cpp",
    "ydb_storage_config.cpp",
    "ydb_tools.cpp",
    "ydb_tools_infer.cpp",
    "ydb_workload.cpp",
    "ydb_workload_import.cpp",
    "ydb_workload_testshard.cpp",
    "ydb_workload_tpcc.cpp",
    "ydb_yql.cpp",
    "topic_workload/topic_workload.cpp",
    "topic_workload/topic_workload_clean.cpp",
    "topic_workload/topic_workload_configurator.cpp",
    "topic_workload/topic_workload_describe.cpp",
    "topic_workload/topic_workload_init.cpp",
    "topic_workload/topic_workload_keyed_writer.cpp",
    "topic_workload/topic_workload_keyed_writer_producer.cpp",
    "topic_workload/topic_workload_params.cpp",
    "topic_workload/topic_workload_reader.cpp",
    "topic_workload/topic_workload_reader_transaction_support.cpp",
    "topic_workload/topic_workload_run_full.cpp",
    "topic_workload/topic_workload_run_read.cpp",
    "topic_workload/topic_workload_run_write.cpp",
    "topic_workload/topic_workload_stats.cpp",
    "topic_workload/topic_workload_stats_collector.cpp",
    "topic_workload/topic_workload_writer.cpp",
    "topic_workload/topic_workload_writer_producer.cpp",
    "transfer_workload/transfer_workload.cpp",
    "transfer_workload/transfer_workload_defines.cpp",
    "transfer_workload/transfer_workload_topic_to_table.cpp",
    "transfer_workload/transfer_workload_topic_to_table_clean.cpp",
    "transfer_workload/transfer_workload_topic_to_table_init.cpp",
    "transfer_workload/transfer_workload_topic_to_table_run.cpp",
    "sqs_workload/http_client.cpp",
    "sqs_workload/message_groups_locker.cpp",
    "sqs_workload/sqs_client_wrapper.cpp",
    "sqs_workload/sqs_workload.cpp",
    "sqs_workload/sqs_workload_clean.cpp",
    "sqs_workload/sqs_workload_clean_scenario.cpp",
    "sqs_workload/sqs_workload_init.cpp",
    "sqs_workload/sqs_workload_init_scenario.cpp",
    "sqs_workload/sqs_workload_read_scenario.cpp",
    "sqs_workload/sqs_workload_reader.cpp",
    "sqs_workload/sqs_workload_run.cpp",
    "sqs_workload/sqs_workload_run_read.cpp",
    "sqs_workload/sqs_workload_run_write.cpp",
    "sqs_workload/sqs_workload_scenario.cpp",
    "sqs_workload/sqs_workload_stats.cpp",
    "sqs_workload/sqs_workload_stats_collector.cpp",
    "sqs_workload/sqs_workload_write_scenario.cpp",
    "sqs_workload/sqs_workload_writer.cpp",
    "//ydb/library/workload/vector/configure_opts.cpp",
    "//ydb/library/workload/vector/vector.cpp",
    "//ydb/library/workload/vector/vector_command_index.cpp",
    "//ydb/library/workload/vector/vector_data_generator.cpp",
    "//ydb/library/workload/vector/vector_recall_evaluator.cpp",
    "//ydb/library/workload/vector/vector_sampler.cpp",
    "//ydb/library/workload/vector/vector_sql.cpp",
    "//ydb/library/workload/vector/vector_workload_generator.cpp",
    "//ydb/library/workload/vector/vector_workload_params.cpp",
    "//ydb/library/workload/tpcc/check.cpp",
    "//ydb/library/workload/tpcc/clean.cpp",
    "//ydb/library/workload/tpcc/common_queries.cpp",
    "//ydb/library/workload/tpcc/data_splitter.cpp",
    "//ydb/library/workload/tpcc/histogram.cpp",
    "//ydb/library/workload/tpcc/import.cpp",
    "//ydb/library/workload/tpcc/import_tui.cpp",
    "//ydb/library/workload/tpcc/init.cpp",
    "//ydb/library/workload/tpcc/log_backend.cpp",
    "//ydb/library/workload/tpcc/logs_scroller.cpp",
    "//ydb/library/workload/tpcc/path_checker.cpp",
    "//ydb/library/workload/tpcc/runner.cpp",
    "//ydb/library/workload/tpcc/runner_tui.cpp",
    "//ydb/library/workload/tpcc/scroller.cpp",
    "//ydb/library/workload/tpcc/task_queue.cpp",
    "//ydb/library/workload/tpcc/terminal.cpp",
    "//ydb/library/workload/tpcc/transaction_delivery.cpp",
    "//ydb/library/workload/tpcc/transaction_neworder.cpp",
    "//ydb/library/workload/tpcc/transaction_orderstatus.cpp",
    "//ydb/library/workload/tpcc/transaction_payment.cpp",
    "//ydb/library/workload/tpcc/transaction_simulation.cpp",
    "//ydb/library/workload/tpcc/transaction_stocklevel.cpp",
    "//ydb/library/workload/tpcc/tui_base.cpp",
    "//ydb/library/workload/tpcc/util.cpp",
  ]

  serialize_enum_headers = [
    "ydb_latency.h",
    "ydb_ping.h",
    "//ydb/library/workload/vector/vector_enums.h",
  ]
}
