library("engines") {
  public_deps = [
    "//ydb/core/base",
    "//ydb/core/formats/arrow:reader",
    ":filter",
    # "//ydb/core/formats/arrow",
    # "//ydb/core/tx",
    # "//ydb/core/tx/columnshard/common",
    "//ydb/core/tx/columnshard/counters",
    "//ydb/core/tx/columnshard/data_accessor",
    "//ydb/core/tx/columnshard/engines/changes/abstract",
    "//ydb/core/tx/columnshard/engines/changes/actualization/controller",
    # "//ydb/core/tx/columnshard/engines/predicate",
    # "//ydb/core/tx/columnshard/engines/protos",
    # "//ydb/core/tx/columnshard/engines/scheme",
    # "//ydb/core/tx/columnshard/engines/scheme/tiering",
    # "//ydb/core/tx/columnshard/engines/scheme/versions",
    # "//ydb/core/tx/columnshard/engines/storage/granule",
    # "//ydb/core/tx/columnshard/resource_subscriber",
    "//ydb/core/tx/columnshard/tx_reader",
    # "//ydb/library/accessor",
    # "//ydb/library/formats/arrow",
  ]

  deps = [
    # "//library/cpp/time_provider",
    # "//ydb/core/formats/arrow/accessor/abstract",
    # "//ydb/core/formats/arrow/accessor/plain",
    # "//ydb/core/protos",
    "//ydb/core/tx/columnshard:background_controller",
    "//ydb/core/tx/columnshard:tables_manager_paths",
    "//ydb/core/tx/columnshard/subscriber/events/tables_erased",
    "//ydb/core/tx/columnshard/data_locks/manager",
    "//ydb/core/tx/columnshard/engines/changes/compaction",
    "//ydb/core/tx/columnshard/engines/storage/actualizer/common",
    "//ydb/core/tx/columnshard/engines/scheme/tiering",
    "//ydb/core/tx/columnshard/engines/storage/indexes/max",
    "//ydb/core/tx/columnshard/engines/storage/optimizer/abstract",
    # "//ydb/core/tx/columnshard/engines/changes/counters",
    "//ydb/core/tx/columnshard/engines/portions",
    "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator",
    # "//ydb/core/tx/columnshard/engines/reader/common",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/constructor",
    "//ydb/core/tx/columnshard/engines/reader/plain_reader/iterator",
    # "//ydb/core/tx/columnshard/engines/scheme/abstract",
    # "//ydb/core/tx/columnshard/hooks/abstract",
    "//ydb/core/tx/columnshard/tracing",
    # "//ydb/core/tx/conveyor_composite/usage",
    # "//ydb/core/tx/sharding",
    # "//ydb/core/tx/tiering",
    # "//ydb/library/actors/core",
    # "//ydb/library/conclusion",
  ]

  sources = [
    "changes/actualization/construction/context.cpp",
    "changes/cleanup_portions.cpp",
    "changes/cleanup_tables.cpp",
    "changes/compaction.cpp",
    "changes/general_compaction.cpp",
    "changes/merge_subset.cpp",
    "changes/move_portions.cpp",
    "changes/remove_portions.cpp",
    "changes/ttl.cpp",
    "changes/with_appended.cpp",
    "column_engine_logs.cpp",
    "column_engine.cpp",
    "db_wrapper.cpp",
    "defs.cpp",
    "loading/stages.cpp",
    "metadata_accessor.cpp",
    "storage/actualizer/index/index.cpp",
    "storage/actualizer/scheme/counters.cpp",
    "storage/actualizer/scheme/scheme.cpp",
    "storage/actualizer/tiering/counters.cpp",
    "storage/actualizer/tiering/tiering.cpp",
    "storage/granule/granule.cpp",
    "storage/granule/portion_interval_tree.cpp",
    "storage/granule/portions_index.cpp",
    "storage/granule/stages.cpp",
    "storage/granule/storage.cpp",
  ]

  serialize_enum_headers = [
    "column_engine_logs.h",
    "storage/granule/granule.h",
  ]
}

library("filter") {
  public_deps = [
    "//ydb/core/formats/arrow",
    "//ydb/core/tx/columnshard/common",
    "//ydb/core/tx/columnshard/engines/scheme/abstract",
  ]

  sources = [ "filter.cpp" ]
}
