library("common") {
  public_deps = [
    # "//ydb/core/formats/arrow/accessor/common",
    # "//ydb/core/tx/schemeshard/olap/operations/alter/abstract",
    # "//ydb/core/tx/schemeshard/olap/table",
  ]

  deps = [
    # "//ydb/core/tx/schemeshard",
  ]

  sources = [
    "object.cpp",
    "update.cpp",
  ]
}
