library("row_dispatcher") {
  public_deps = [
    "//ydb/core/fq/libs/row_dispatcher/common",
    # "//ydb/core/fq/libs/shared_resources",
    # "//ydb/library/actors/core",
    # "//ydb/library/security",
    "//ydb/library/yql/providers/common/token_accessor/client",
    # "//ydb/library/yql/providers/pq/gateway/abstract",
  ]

  deps = [
    # "//library/cpp/lwtrace",
    "//library/cpp/lwtrace/mon",
    # "//ydb/core/base",
    # "//ydb/core/fq/libs/actors",
    # "//ydb/core/fq/libs/actors:logging",
    # "//ydb/core/fq/libs/events",
    "//ydb/core/fq/libs/metrics",
    # "//ydb/core/fq/libs/row_dispatcher/events",
    "//ydb/core/fq/libs/row_dispatcher/format_handler",
    "//ydb/core/fq/libs/row_dispatcher/protos",
    "//ydb/core/fq/libs/row_dispatcher/purecalc_compilation",
    # "//ydb/core/fq/libs/ydb",
    "//ydb/core/grpc_services",
    "//ydb/core/grpc_services/local_rpc",
    "//ydb/core/mind",
    "//ydb/core/mon",
    # "//ydb/library/actors/protos",
    "//ydb/library/logger",
    # "//ydb/library/yql/dq/actors",
    "//ydb/library/yql/dq/actors:common",
    # "//ydb/library/yql/providers/dq/counters",
    # "//ydb/library/yql/providers/pq/common",
    "//ydb/public/sdk/cpp/adapters/issue",
    "//ydb/public/sdk/cpp/src/client/topic/impl",
    # "//ydb/public/sdk/cpp/src/client/driver",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/public/purecalc/common",
  ]

  sources = [
    "actors_factory.cpp",
    "coordinator.cpp",
    "leader_election.cpp",
    "local_leader_election.cpp",
    "probes.cpp",
    "row_dispatcher.cpp",
    "row_dispatcher_service.cpp",
    "topic_session.cpp",
  ]
}
