library("auth") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
    # "//ydb/library/login:protos",
    # ":common",
  ]

  deps = [
    # "//ydb/core/ydb_convert",
  ]

  sources = [
    "auth/group_members.cpp",
    "auth/groups.cpp",
    "auth/owners.cpp",
    "auth/permissions.cpp",
    "auth/users.cpp",
  ]
}

library("common") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/kqp/compute_actor",
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/mind",
    "//ydb/core/protos",
    # "//ydb/core/scheme",
    "//ydb/core/tablet_flat",
    # "//ydb/core/tx/locks",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/library/actors/core",
    # "//ydb/library/yql/dq/actors:compute",
    # "//ydb/library/yql/dq/actors:protos",
    # "//yql/essentials/public/issue",
    # ":service",
  ]

  deps = [
    # "//library/cpp/deprecated/atomic",
    # "//yql/essentials/parser/pg_catalog",
    # "//yql/essentials/parser/pg_wrapper/interface",
  ]

  sources = [
    "common/registry.cpp",
    "common/resolver.cpp",
  ]
}

library("compile_cache") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//library/cpp/protobuf/interop",
    # "//ydb/core/kqp/common:events",
    # "//ydb/core/kqp/common:simple",
    # "//ydb/core/node_whiteboard",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/yql/dq/actors:compute",
    # ":auth",
    # ":common",
  ]

  sources = [ "compile_cache/compile_cache.cpp" ]
}

library("nodes") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/node_whiteboard",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/yql/dq/actors:compute",
    # ":common",
  ]

  sources = [ "nodes/nodes.cpp" ]
}

library("partition_stats") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/library/yql/dq/actors:compute",
    # ":common",
  ]

  sources = [
    "partition_stats/partition_stats.cpp",
    "partition_stats/top_partitions.cpp",
  ]
}

library("pg_tables") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/library/actors/core",
    # ":common",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/library/yql/dq/actors:compute",
  ]

  sources = [ "pg_tables/pg_tables.cpp" ]
}

library("processor") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//library/cpp/monlib/service/pages",
    # "//ydb/core/engine:minikql",
    # "//ydb/core/grpc_services/counters",
    # "//ydb/core/kqp/counters",
    # "//ydb/core/protos",
    # "//ydb/core/tablet",
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/library/actors/util",
    # ":common",
    # ":service",
  ]

  sources = [
    "processor/db_counters.cpp",
    "processor/processor.cpp",
    "processor/processor_impl.cpp",
    "processor/schema.cpp",
    "processor/tx_aggregate.cpp",
    "processor/tx_collect.cpp",
    "processor/tx_configure.cpp",
    "processor/tx_init.cpp",
    "processor/tx_init_schema.cpp",
    "processor/tx_interval_metrics.cpp",
    "processor/tx_interval_summary.cpp",
    "processor/tx_top_partitions.cpp",
  ]
}

library("query_stats") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/yql/dq/actors:compute",
    # ":common",
    # ":service",
  ]

  sources = [
    "query_stats/query_metrics.cpp",
    "query_stats/query_stats.cpp",
  ]
}

library("resource_pool_classifiers") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/kqp/gateway/behaviour/resource_pool_classifier",
    # "//ydb/core/kqp/workload_service:actors",
    # "//ydb/core/node_whiteboard",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/yql/dq/actors:compute",
    # "//ydb/services/metadata",
    # "//yql/essentials/types/binary_json",
    # ":common",
  ]

  sources = [ "resource_pool_classifiers/resource_pool_classifiers.cpp" ]
}

library("resource_pools") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//library/cpp/json",
    # "//library/cpp/protobuf/json",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/table_creator",
    # "//ydb/library/yql/dq/actors:compute",
    # "//yql/essentials/types/binary_json",
    # ":common",
  ]

  sources = [ "resource_pools/resource_pools.cpp" ]
}

library("service") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/protos",
    # "//ydb/core/scheme",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//library/cpp/time_provider",
    # "//ydb/core/graph/api",
    # "//ydb/core/tablet",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/library/services",
    # ":common",
  ]

  sources = [
    "service/db_counters.cpp",
    "service/ext_counters.cpp",
    "service/query_interval.cpp",
    "service/sysview_service.cpp",
  ]
}

library("sessions") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/kqp/common:events",
    # "//ydb/core/kqp/common:simple",
    # "//ydb/core/node_whiteboard",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/yql/dq/actors:compute",
    # ":common",
  ]

  sources = [ "sessions/sessions.cpp" ]
}

library("show_create") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//library/cpp/json",
    # "//library/cpp/protobuf/json",
    # "//library/cpp/protobuf/util",
    # "//ydb/core/base",
    # "//ydb/core/engine",
    # "//ydb/core/formats/arrow:serializer",
    # "//ydb/core/scheme",
    # "//ydb/core/tx/columnshard/engines/scheme/defaults:protos",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/core/tx/sequenceproxy:public",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/core/ydb_convert",
    # "//ydb/library/yql/dq/actors:compute",
    # "//ydb/public/api/protos",
    # "//ydb/public/lib/ydb_cli/dump:util",
    # "//ydb/public/sdk/cpp/src/client/value",
    # "//yql/essentials/ast",
    # "//yql/essentials/minikql",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/sql/v1",
    # "//yql/essentials/sql/v1/lexer:antlr4",
    # "//yql/essentials/sql/v1/lexer:antlr4_ansi",
    # "//yql/essentials/sql/v1/proto_parser:antlr4",
    # "//yql/essentials/sql/v1/proto_parser:antlr4_ansi",
    # "//yql/essentials/sql:settings",
    # ":common",
  ]

  sources = [
    "show_create/create_table_formatter.cpp",
    "show_create/create_view_formatter.cpp",
    "show_create/formatters_common.cpp",
    "show_create/show_create.cpp",
  ]
}

library("storage") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/yql/dq/actors:compute",
    # ":common",
  ]

  sources = [
    "storage/groups.cpp",
    "storage/pdisks.cpp",
    "storage/storage_pools.cpp",
    "storage/storage_stats.cpp",
    "storage/vslots.cpp",
  ]
}

library("streaming_queries") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/scheme",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//contrib/libs/fmt",
    # "//library/cpp/protobuf/json",
    # "//ydb/core/kqp/common",
    # "//ydb/core/kqp/common:events",
    # "//ydb/core/kqp/gateway/behaviour/streaming_query:common",
    # "//ydb/core/kqp/workload_service:actors",
    # "//ydb/library/query_actor",
    # ":common",
  ]

  sources = [ "streaming_queries/streaming_queries.cpp" ]
}

library("sys_view") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/kqp/compute_actor",
    # ":auth",
    # ":common",
    # ":compile_cache",
    # ":nodes",
    # ":partition_stats",
    # ":pg_tables",
    # ":query_stats",
    # ":resource_pool_classifiers",
    # ":resource_pools",
    # ":sessions",
    # ":show_create",
    # ":storage",
    # ":streaming_queries",
    # ":tablets",
  ]

  sources = [ "scan.cpp" ]
}

library("tablets") {
  public_deps = [
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/mind:hive",
    # "//ydb/library/yql/dq/actors:compute",
    # ":common",
  ]

  sources = [ "tablets/tablets.cpp" ]
}
