library("construction") {
  public_deps = [
    "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/changes",
    # "//ydb/core/tx/columnshard/engines/changes/abstract",
    "//ydb/core/tx/columnshard/engines/changes/actualization/controller",
    "//ydb/core/tx/columnshard/engines/storage/actualizer/common",
    # "//ydb/library/accessor",
  ]

  deps = [
    # "//ydb/core/tx/columnshard/common",
    "//ydb/core/tx/columnshard/data_locks/manager",
    "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/hooks/abstract",
  ]

  sources = [ "context.cpp" ]
}
