library("base") {
  public_deps = [ "//library/cpp/deprecated/atomic" ]

  sources = [ "base/immediate_control_board_control.cpp" ]
}

config("lib_public_config") {
  cflags = [ "-Wno-deprecated-volatile" ]
}

library("lib") {
  public_deps = [
    ":base",
    "//library/cpp/monlib/service/pages",
    "//library/cpp/threading/hot_swap",
    # "//ydb/core/base",
    "//ydb/core/control/lib/generated",
    # "//ydb/core/util",
  ]

  deps = [
    # "//library/cpp/containers/absl_flat_hash",  # peerdir only
    # "//library/cpp/deprecated/atomic",  # peerdir only
    "//library/cpp/iterator",
  ]

  sources = [
    "dynamic_control_board_impl.cpp",
    "immediate_control_board_html_renderer.cpp",
    "immediate_control_board_impl.cpp",
  ]

  public_configs = [ ":lib_public_config" ]
}
