library("usage") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/protos",
    # "//ydb/core/tx/conveyor/usage",
    # "//ydb/core/tx/conveyor_composite/service",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/core",
    # "//ydb/library/conclusion",
  ]

  sources = [
    "common.cpp",
    "config.cpp",
    "events.cpp",
    "service.cpp",
  ]

  serialize_enum_headers = [ "common.h" ]
}
