library("check") {
  public_deps = [
    # "//yql/essentials/public/issue",
    # "//yql/essentials/sql/settings",
  ]

  deps = [
    # "//yql/essentials/sql",
    # "//yql/essentials/sql/v1",
    # "//yql/essentials/sql/v1/format",
    # "//yql/essentials/sql/v1/lexer",
    # "//yql/essentials/sql/v1/lexer/antlr4",
    # "//yql/essentials/sql/v1/lexer/antlr4_ansi",
    # "//yql/essentials/sql/v1/proto_parser",
    # "//yql/essentials/sql/v1/proto_parser/antlr4",
    # "//yql/essentials/sql/v1/proto_parser/antlr4_ansi",
  ]

  sources = [ "check_format.cpp" ]
}
