library("ast") {
    deps = [
        "//contrib/libs/openssl",
        "//library/cpp/json",
        "//library/cpp/yson",
        "//yql/essentials/parser/pg_catalog",
        "//yql/essentials/public/issue",
        "//yql/essentials/public/udf:_udf",
        "//yql/essentials/utils",
    ]

    sources = [
        "yql_ast_annotation.cpp",
        "yql_ast_escaping.cpp",
        "yql_ast.cpp",
        "yql_constraint.cpp",
        "yql_errors.cpp",
        "yql_expr_builder.cpp",
        "yql_expr_types.cpp",
        "yql_expr.cpp",
        "yql_gc_nodes.cpp",
        "yql_type_string.cpp",
    ]
}
