unittest_executable("ut") {
  deps = [
    "//contrib/libs/apache/arrow",
    "//library/cpp/testing/gtest",
    "//library/cpp/testing/unittest",
    "//ydb/core/formats/arrow",
    "//ydb/core/fq/libs/common",
    "//ydb/core/security/certificate_check",
    "//ydb/core/testlib",
    "//ydb/library/formats/arrow/switch",
    "//ydb/public/sdk/cpp/src/client/result",
    "//ydb/public/sdk/cpp/src/client/value",
    "//ydb/services/ydb",
    "//yql/essentials/sql/pg_dummy",  # peerdir only
  ]

  sources = [
    "//ydb/core/fq/libs/common/cache_ut.cpp",
    "//ydb/core/fq/libs/common/entity_id_ut.cpp",
    "//ydb/core/fq/libs/common/iceberg_processor_ut.cpp",
    "//ydb/core/fq/libs/common/rows_proto_splitter_ut.cpp",
    "//ydb/core/fq/libs/common/util_ut.cpp",
  ]

  include_dirs = [ "//ydb/core/fq/libs/common" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
