library("abstract") {
  public_deps = [
    # ":tier",
  ]

  deps = [
    # "//ydb/library/actors/core",
  ]

  sources = [ "abstract/manager.cpp" ]
}

library("tier") {
  public_deps = [
    # "//library/cpp/json:writer",
    # "//ydb/core/base",
    # "//ydb/library/accessor",
    # "//ydb/library/conclusion",
    # "//ydb/services/metadata/secret:accessor",
  ]

  deps = [
    # "//library/cpp/protobuf/json",
    # "//library/cpp/uri",
    # "//ydb/core/protos",
  ]

  sources = [
    "tier/identifier.cpp",
    "tier/object.cpp",
    "tier/s3_uri.cpp",
  ]
}

library("tiering") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/formats/arrow:serializer",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/core",
    # "//ydb/public/sdk/cpp/src/client/types",
    # "//ydb/services/metadata",
    # "//ydb/services/metadata/secret",
    # ":abstract",
    # ":tier",
  ]

  deps = [
    # "//library/cpp/retry",
    # "//ydb/core/protos",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/hooks/abstract",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/library/table_creator",
  ]

  sources = [
    "common.cpp",
    "fetcher.cpp",
    "manager.cpp",
  ]
}
