library("blob") {
  public_deps = [
    # "//ydb/core/persqueue/common",
    # "//ydb/core/protos",
  ]

  deps = [
    # "//library/cpp/containers/bitseq",
    # "//library/cpp/packedtypes",
    # "//ydb/core/scheme",
    # "//ydb/library/actors/core",
  ]

  sources = [
    "blob.cpp",
    "blob_serialization.cpp",
    "header.cpp",
    "type_codecs_defs.cpp",
  ]
}
