library("kafka_proxy") {
  public_deps = [
    # "//library/cpp/monlib/dynamic_counters",
    # "//ydb/core/base",
    "//ydb/core/discovery",
    # "//ydb/core/persqueue/events",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    "//ydb/services/persqueue_v1:actors",
  ]

  deps = [
    # "//contrib/libs/cxxsupp/libcxx",
    # "//library/cpp/cache",
    "//library/cpp/ipmath",
    # "//library/cpp/monlib/metrics",
    "//library/cpp/string_utils/base64",
    "//ydb/core/audit",
    # "//ydb/core/client/server",
    "//ydb/core/grpc_services",
    # "//ydb/core/grpc_services/base",
    "//ydb/core/grpc_services/local_rpc",
    "//ydb/core/kqp/common:events",
    # "//ydb/core/kqp/common:simple",
    # "//ydb/core/persqueue/public",
    "//ydb/core/persqueue/public:describer",
    "//ydb/core/persqueue/public:fetcher",
    "//ydb/core/persqueue/public:list_topics",
    "//ydb/core/persqueue/public:write_meta",
    # "//ydb/core/persqueue/writer",
    "//ydb/core/protos",
    "//ydb/core/raw_socket",
    "//ydb/core/security",
    "//ydb/core/security:sasl",
    "//ydb/core/tablet",
    # "//ydb/core/tx/replication/ydb_proxy",
    "//ydb/core/tx/replication/ydb_proxy:local_proxy",
    # "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/util",
    "//ydb/core/ydb_convert",
    "//ydb/library/login:sasl",
    "//ydb/library/persqueue/topic_parser",
    # "//ydb/library/services",
    # "//ydb/library/yverify_stream",
    # "//ydb/public/api/grpc",
    # "//ydb/public/api/protos",
    # "//ydb/public/lib/base",
    # "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/topic",
    "//ydb/public/sdk/cpp/src/client/params",
    "//ydb/public/sdk/cpp/src/client/result",
    "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/services/lib/actors",
    # "//ydb/services/metadata",
    "//ydb/services/metadata/abstract",
    "//ydb/services/metadata/initializer",
    "//ydb/services/persqueue_v1",
    # "//yql/essentials/public/decimal",
  ]

  sources = [
    "actors/kafka_alter_configs_actor.cpp",
    "actors/kafka_api_versions_actor.cpp",
    "actors/kafka_balance_actor_sql.cpp",
    "actors/kafka_balancer_actor.cpp",
    "actors/kafka_create_partitions_actor.cpp",
    "actors/kafka_create_topics_actor.cpp",
    "actors/kafka_describe_configs_actor.cpp",
    "actors/kafka_describe_groups_actor.cpp",
    "actors/kafka_fetch_actor.cpp",
    "actors/kafka_find_coordinator_actor.cpp",
    "actors/kafka_init_producer_id_actor.cpp",
    "actors/kafka_list_groups_actor.cpp",
    "actors/kafka_list_offsets_actor.cpp",
    "actors/kafka_metadata_actor.cpp",
    "actors/kafka_metrics_actor.cpp",
    "actors/kafka_offset_commit_actor.cpp",
    "actors/kafka_offset_fetch_actor.cpp",
    "actors/kafka_produce_actor.cpp",
    "actors/kafka_read_session_actor.cpp",
    "actors/kafka_read_session_proxy.cpp",
    "actors/kafka_read_session_utils.cpp",
    "actors/kafka_sasl_auth_actor.cpp",
    "actors/kafka_sasl_handshake_actor.cpp",
    "actors/kafka_state_name_to_int.cpp",
    "actors/kafka_topic_group_path_struct.cpp",
    "actors/kafka_topic_offsets_actor.cpp",
    "actors/kafka_transaction_actor.cpp",
    "actors/kafka_transaction_actor_sql.cpp",
    "actors/txn_actor_response_builder.cpp",
    "kafka_connection.cpp",
    "kafka_consumer_groups_metadata_initializers.cpp",
    "kafka_consumer_members_metadata_initializers.cpp",
    "kafka_consumer_protocol.cpp",
    "kafka_messages.cpp",
    "kafka_messages_int.cpp",
    "kafka_metrics.cpp",
    "kafka_records.cpp",
    "kafka_transactional_producers_initializers.cpp",
    "kafka_transactions_coordinator.cpp",
    "kqp_helper.cpp",
  ]

  serialize_enum_headers = [
    "actors/actors.h",
    "kafka.h",
  ]
}
