library("load_test") {
  public_deps = [
    # "//ydb/core/base",
  ]

  deps = [
    # "//library/cpp/histogram/hdr",
    # "//library/cpp/json",
    # "//library/cpp/json:writer",
    # "//library/cpp/monlib/dynamic_counters",
    # "//library/cpp/monlib/dynamic_counters:percentile",
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/protobuf/json",
    # "//library/cpp/random_provider",
    # "//library/cpp/time_provider",
    # "//ydb/core/blobstorage",
    # "//ydb/core/blobstorage/backpressure",
    # "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/ddisk",
    # "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/control/lib",
    # "//ydb/core/jaeger_tracing",
    # "//ydb/core/keyvalue",
    # "//ydb/core/kqp/common",
    # "//ydb/core/nbs/cloud/blockstore/libs/common",
    # "//ydb/core/nbs/cloud/blockstore/libs/service",
    # "//ydb/core/nbs/cloud/blockstore/libs/storage/api",
    # "//ydb/core/nbs/cloud/blockstore/tools/testing/loadtest/lib",
    # "//ydb/core/nbs/cloud/storage/core/libs/common",
    # "//ydb/core/nbs/cloud/storage/core/libs/diagnostics",
    # "//ydb/core/protos",
    # "//ydb/core/tx/datashard",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/core/util",
    # "//ydb/core/ydb_convert",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/actors/util",
    # "//ydb/library/mkql_proto:protos",
    # "//ydb/library/services",
    # "//ydb/library/workload/abstract",
    # "//ydb/library/workload/kv",
    # "//ydb/library/workload/stock",
    # "//ydb/library/yverify_stream",
    # "//ydb/public/api/protos",
    # "//ydb/public/lib/base",
    # "//ydb/public/sdk/cpp/src/client/params",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/public/sdk/cpp/src/client/result",
    # "//ydb/public/sdk/cpp/src/library/operation_id",
  ]

  sources = [
    "aggregated_result.cpp",
    "archive.cpp",
    "config_examples.cpp",
    "ddisk_write.cpp",
    "group_write.cpp",
    "interconnect_load.cpp",
    "keyvalue_write.cpp",
    "kqp.cpp",
    "memory.cpp",
    "nbs2_load_actor.cpp",
    "pdisk_log.cpp",
    "pdisk_read.cpp",
    "pdisk_write.cpp",
    "service_actor.cpp",
    "vdisk_write.cpp",
    "ycsb/bulk_mkql_upsert.cpp",
    "ycsb/common.cpp",
    "ycsb/info_collector.cpp",
    "ycsb/kqp_select.cpp",
    "ycsb/kqp_upsert.cpp",
    "ycsb/test_load_actor.cpp",
    "ycsb/test_load_read_iterator.cpp",
    "yql_single_query.cpp",
  ]

  serialize_enum_headers = [ "percentile.h" ]
}
