config("private_config") {
    cflags = [
        "-Wno-bitwise-instead-of-logical",
        "-Wno-unqualified-std-cast-call",
        "-Wno-unused-but-set-variable",
        "-Wno-unused-const-variable",
    ]

    defines = [ "DISABLE_AVX512VBMI_DISPATCH" ]

    include_dirs = [
        ".",
        "include",
        "src",
    ]
}

contrib_library("hyperscan") {
    deps = [
        "//contrib/restricted/boost/config",
        "//contrib/restricted/boost/container",
        "//contrib/restricted/boost/container_hash",
        "//contrib/restricted/boost/dynamic_bitset",
        "//contrib/restricted/boost/graph",
        "//contrib/restricted/boost/icl",
        "//contrib/restricted/boost/iterator",
        "//contrib/restricted/boost/multi_array",
        "//contrib/restricted/boost/range",
        "//contrib/restricted/boost/smart_ptr",
        "//contrib/restricted/boost/variant",
    ]

    sources = [
        "src/alloc.c",
        "src/compiler/asserts.cpp",
        "src/compiler/compiler.cpp",
        "src/compiler/error.cpp",
        "src/crc32.c",
        "src/database.c",
        "src/fdr/engine_description.cpp",
        "src/fdr/fdr_compile_util.cpp",
        "src/fdr/fdr_compile.cpp",
        "src/fdr/fdr_confirm_compile.cpp",
        "src/fdr/fdr_engine_description.cpp",
        "src/fdr/fdr.c",
        "src/fdr/flood_compile.cpp",
        "src/fdr/teddy_avx2.c",
        "src/fdr/teddy_compile.cpp",
        "src/fdr/teddy_engine_description.cpp",
        "src/fdr/teddy.c",
        "src/grey.cpp",
        "src/hs_valid_platform.c",
        "src/hs_version.c",
        "src/hs.cpp",
        "src/hwlm/hwlm_build.cpp",
        "src/hwlm/hwlm_literal.cpp",
        "src/hwlm/hwlm.c",
        "src/hwlm/noodle_build.cpp",
        "src/hwlm/noodle_engine.c",
        "src/nfa/accel_dfa_build_strat.cpp",
        "src/nfa/accel.c",
        "src/nfa/accelcompile.cpp",
        "src/nfa/castle.c",
        "src/nfa/castlecompile.cpp",
        "src/nfa/dfa_build_strat.cpp",
        "src/nfa/dfa_min.cpp",
        "src/nfa/gough.c",
        "src/nfa/goughcompile_accel.cpp",
        "src/nfa/goughcompile_reg.cpp",
        "src/nfa/goughcompile.cpp",
        "src/nfa/lbr.c",
        "src/nfa/limex_64.c",
        "src/nfa/limex_accel.c",
        "src/nfa/limex_compile.cpp",
        "src/nfa/limex_native.c",
        "src/nfa/limex_simd128.c",
        "src/nfa/limex_simd256.c",
        "src/nfa/limex_simd384.c",
        "src/nfa/limex_simd512.c",
        "src/nfa/mcclellan.c",
        "src/nfa/mcclellancompile_util.cpp",
        "src/nfa/mcclellancompile.cpp",
        "src/nfa/mcsheng_compile.cpp",
        "src/nfa/mcsheng_data.c",
        "src/nfa/mcsheng.c",
        "src/nfa/mpv.c",
        "src/nfa/mpvcompile.cpp",
        "src/nfa/nfa_api_dispatch.c",
        "src/nfa/nfa_build_util.cpp",
        "src/nfa/rdfa_graph.cpp",
        "src/nfa/rdfa_merge.cpp",
        "src/nfa/rdfa.cpp",
        "src/nfa/repeat.c",
        "src/nfa/repeatcompile.cpp",
        "src/nfa/sheng.c",
        "src/nfa/shengcompile.cpp",
        "src/nfa/shufti.c",
        "src/nfa/shufticompile.cpp",
        "src/nfa/tamarama.c",
        "src/nfa/tamaramacompile.cpp",
        "src/nfa/truffle.c",
        "src/nfa/trufflecompile.cpp",
        "src/nfagraph/ng_anchored_acyclic.cpp",
        "src/nfagraph/ng_anchored_dots.cpp",
        "src/nfagraph/ng_asserts.cpp",
        "src/nfagraph/ng_builder.cpp",
        "src/nfagraph/ng_calc_components.cpp",
        "src/nfagraph/ng_cyclic_redundancy.cpp",
        "src/nfagraph/ng_depth.cpp",
        "src/nfagraph/ng_dominators.cpp",
        "src/nfagraph/ng_edge_redundancy.cpp",
        "src/nfagraph/ng_equivalence.cpp",
        "src/nfagraph/ng_execute.cpp",
        "src/nfagraph/ng_expr_info.cpp",
        "src/nfagraph/ng_extparam.cpp",
        "src/nfagraph/ng_fixed_width.cpp",
        "src/nfagraph/ng_fuzzy.cpp",
        "src/nfagraph/ng_haig.cpp",
        "src/nfagraph/ng_holder.cpp",
        "src/nfagraph/ng_is_equal.cpp",
        "src/nfagraph/ng_lbr.cpp",
        "src/nfagraph/ng_limex_accel.cpp",
        "src/nfagraph/ng_limex.cpp",
        "src/nfagraph/ng_literal_analysis.cpp",
        "src/nfagraph/ng_literal_component.cpp",
        "src/nfagraph/ng_literal_decorated.cpp",
        "src/nfagraph/ng_mcclellan.cpp",
        "src/nfagraph/ng_misc_opt.cpp",
        "src/nfagraph/ng_netflow.cpp",
        "src/nfagraph/ng_prefilter.cpp",
        "src/nfagraph/ng_prune.cpp",
        "src/nfagraph/ng_puff.cpp",
        "src/nfagraph/ng_redundancy.cpp",
        "src/nfagraph/ng_region_redundancy.cpp",
        "src/nfagraph/ng_region.cpp",
        "src/nfagraph/ng_repeat.cpp",
        "src/nfagraph/ng_reports.cpp",
        "src/nfagraph/ng_restructuring.cpp",
        "src/nfagraph/ng_revacc.cpp",
        "src/nfagraph/ng_sep.cpp",
        "src/nfagraph/ng_small_literal_set.cpp",
        "src/nfagraph/ng_som_add_redundancy.cpp",
        "src/nfagraph/ng_som_util.cpp",
        "src/nfagraph/ng_som.cpp",
        "src/nfagraph/ng_split.cpp",
        "src/nfagraph/ng_squash.cpp",
        "src/nfagraph/ng_stop.cpp",
        "src/nfagraph/ng_uncalc_components.cpp",
        "src/nfagraph/ng_utf8.cpp",
        "src/nfagraph/ng_util.cpp",
        "src/nfagraph/ng_vacuous.cpp",
        "src/nfagraph/ng_violet.cpp",
        "src/nfagraph/ng_width.cpp",
        "src/nfagraph/ng.cpp",
        "src/parser/AsciiComponentClass.cpp",
        "src/parser/buildstate.cpp",
        "src/parser/check_refs.cpp",
        "src/parser/Component.cpp",
        "src/parser/ComponentAlternation.cpp",
        "src/parser/ComponentAssertion.cpp",
        "src/parser/ComponentAtomicGroup.cpp",
        "src/parser/ComponentBackReference.cpp",
        "src/parser/ComponentBoundary.cpp",
        "src/parser/ComponentByte.cpp",
        "src/parser/ComponentClass.cpp",
        "src/parser/ComponentCondReference.cpp",
        "src/parser/ComponentEmpty.cpp",
        "src/parser/ComponentEUS.cpp",
        "src/parser/ComponentRepeat.cpp",
        "src/parser/ComponentSequence.cpp",
        "src/parser/ComponentVisitor.cpp",
        "src/parser/ComponentWordBoundary.cpp",
        "src/parser/ConstComponentVisitor.cpp",
        "src/parser/control_verbs.rl6",
        "src/parser/logical_combination.cpp",
        "src/parser/parse_error.cpp",
        "src/parser/parser_util.cpp",
        "src/parser/Parser.rl6",
        "src/parser/prefilter.cpp",
        "src/parser/shortcut_literal.cpp",
        "src/parser/ucp_table.cpp",
        "src/parser/unsupported.cpp",
        "src/parser/utf8_validate.cpp",
        "src/parser/Utf8ComponentClass.cpp",
        "src/rose/block.c",
        "src/rose/catchup.c",
        "src/rose/init.c",
        "src/rose/match.c",
        "src/rose/program_runtime.c",
        "src/rose/rose_build_add_mask.cpp",
        "src/rose/rose_build_add.cpp",
        "src/rose/rose_build_anchored.cpp",
        "src/rose/rose_build_bytecode.cpp",
        "src/rose/rose_build_castle.cpp",
        "src/rose/rose_build_compile.cpp",
        "src/rose/rose_build_convert.cpp",
        "src/rose/rose_build_dedupe.cpp",
        "src/rose/rose_build_engine_blob.cpp",
        "src/rose/rose_build_exclusive.cpp",
        "src/rose/rose_build_groups.cpp",
        "src/rose/rose_build_infix.cpp",
        "src/rose/rose_build_instructions.cpp",
        "src/rose/rose_build_lit_accel.cpp",
        "src/rose/rose_build_long_lit.cpp",
        "src/rose/rose_build_lookaround.cpp",
        "src/rose/rose_build_matchers.cpp",
        "src/rose/rose_build_merge.cpp",
        "src/rose/rose_build_misc.cpp",
        "src/rose/rose_build_program.cpp",
        "src/rose/rose_build_role_aliasing.cpp",
        "src/rose/rose_build_scatter.cpp",
        "src/rose/rose_build_width.cpp",
        "src/rose/rose_in_util.cpp",
        "src/rose/stream.c",
        "src/runtime.c",
        "src/scratch.c",
        "src/smallwrite/smallwrite_build.cpp",
        "src/som/slot_manager.cpp",
        "src/som/som_runtime.c",
        "src/som/som_stream.c",
        "src/stream_compress.c",
        "src/util/alloc.cpp",
        "src/util/charreach.cpp",
        "src/util/clique.cpp",
        "src/util/compile_context.cpp",
        "src/util/compile_error.cpp",
        "src/util/cpuid_flags.c",
        "src/util/depth.cpp",
        "src/util/dump_mask.cpp",
        "src/util/fatbit_build.cpp",
        "src/util/masked_move.c",
        "src/util/multibit_build.cpp",
        "src/util/multibit.c",
        "src/util/report_manager.cpp",
        "src/util/simd_utils.c",
        "src/util/state_compress.c",
        "src/util/target_info.cpp",
        "src/util/ue2string.cpp",
    ]

    configs = [ ":private_config" ]
}
