library("pq_async_io") {
  testonly = true

  public_deps = [
    # "//library/cpp/testing/unittest",
    # "//ydb/core/testlib/basics",
    # "//ydb/library/yql/dq/actors/compute",
    # "//ydb/library/yql/dq/actors/protos",
    "//ydb/library/yql/providers/common/ut_helpers",
    "//ydb/library/yql/providers/pq/async_io",
    "//ydb/public/sdk/cpp/src/client/topic",
    # "//yql/essentials/minikql/computation",
    # "//yql/essentials/minikql:alloc",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/library/yql/providers/pq/gateway/dummy",  # peerdir only
    "//ydb/library/yql/providers/pq/gateway/native",
    "//ydb/public/sdk/cpp/src/client/datastreams",
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/computation/llvm16",  # link slot
    # "//yql/essentials/providers/common/proto",
  ]

  sources = [ "ut_helpers.cpp" ]
}
