library("counters") {
  public_deps = [
    # "//library/cpp/monlib/metrics",
    # "//ydb/core/kqp/common",
    # "//ydb/core/protos",
    # "//ydb/core/sys_view:common",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/core/util",
    # "//ydb/library/yql/dq/actors:spilling",
    # "//ydb/public/api/protos",
    # "//yql/essentials/minikql",
  ]

  deps = [
    # "//library/cpp/deprecated/enum_codegen",
    # "//ydb/core/base",
    # "//ydb/core/sys_view:service",
    # "//ydb/library/actors/core",
    # "//ydb/library/ydb_issue:proto",
    # "//yql/essentials/core/issue:protos",
  ]

  sources = [ "kqp_counters.cpp" ]
}
