library("resource_pool_classifier") {
  public_deps = [
    # "//ydb/services/metadata/abstract",
  ]

  deps = [
    # "//library/cpp/json",
    # "//ydb/core/base",
    # "//ydb/core/cms/console",
    # "//ydb/core/kqp/workload_service:actors",
    # "//ydb/core/protos",
    "//ydb/core/resource_pools",
    # "//ydb/library/query_actor",
    "//ydb/services/metadata/initializer",
    "//ydb/services/metadata/manager",
  ]

  sources = [
    "behaviour.cpp",
    "checker.cpp",
    "fetcher.cpp",
    "initializer.cpp",
    "manager.cpp",
    "object.cpp",
    "snapshot.cpp",
  ]
}
