library("common") {
  public_deps = [
    # "//library/cpp/string_utils/parse_size",
    # "//library/cpp/yson:node",
    # "//yql/essentials/ast",
    # "//yql/essentials/providers/common/config",
    # "//yql/essentials/public/udf",
    # "//yt/cpp/mapreduce/interface",
  ]

  deps = [
    # "//library/cpp/json",
    # "//library/cpp/regex/pcre",
    # "//yql/essentials/providers/common/codec",
    # "//yql/essentials/utils/log",
  ]

  sources = [
    "yql_configuration.cpp",
    "yql_names.cpp",
    "yql_yt_settings.cpp",
  ]

  serialize_enum_headers = [ "yql_yt_settings.h" ]
}
