# TODO: add resource

library("provider") {
    sources = [
        "phy_opt/yql_yt_phy_opt_content.cpp",
        "phy_opt/yql_yt_phy_opt_create.cpp",
        "phy_opt/yql_yt_phy_opt_field_subset.cpp",
        "phy_opt/yql_yt_phy_opt_fuse.cpp",
        "phy_opt/yql_yt_phy_opt_helper.cpp",
        "phy_opt/yql_yt_phy_opt_helper.h",
        "phy_opt/yql_yt_phy_opt_join.cpp",
        "phy_opt/yql_yt_phy_opt_key_range.cpp",
        "phy_opt/yql_yt_phy_opt_lambda.cpp",
        "phy_opt/yql_yt_phy_opt_map.cpp",
        "phy_opt/yql_yt_phy_opt_merge.cpp",
        "phy_opt/yql_yt_phy_opt_misc.cpp",
        "phy_opt/yql_yt_phy_opt_partition.cpp",
        "phy_opt/yql_yt_phy_opt_push.cpp",
        "phy_opt/yql_yt_phy_opt_sort.cpp",
        "phy_opt/yql_yt_phy_opt_weak_fields.cpp",
        "phy_opt/yql_yt_phy_opt_write.cpp",
        "phy_opt/yql_yt_phy_opt_ytql.cpp",
        "phy_opt/yql_yt_phy_opt.cpp",
        "yql_yt_block_input.cpp",
        "yql_yt_block_io_filter.cpp",
        "yql_yt_block_io_utils.cpp",
        "yql_yt_block_output.cpp",
        "yql_yt_cbo_helpers.cpp",
        "yql_yt_datasink_constraints.cpp",
        "yql_yt_datasink_exec.cpp",
        "yql_yt_datasink_finalize.cpp",
        "yql_yt_datasink_trackable.cpp",
        "yql_yt_datasink_type_ann.cpp",
        "yql_yt_datasink.cpp",
        "yql_yt_datasource_constraints.cpp",
        "yql_yt_datasource_exec.cpp",
        "yql_yt_datasource_type_ann.cpp",
        "yql_yt_datasource.cpp",
        "yql_yt_dq_hybrid.cpp",
        "yql_yt_dq_integration.cpp",
        "yql_yt_dq_optimize.cpp",
        "yql_yt_epoch.cpp",
        "yql_yt_forwarding_gateway.cpp",
        "yql_yt_gateway.cpp",
        "yql_yt_helpers.cpp",
        "yql_yt_horizontal_join.cpp",
        "yql_yt_intent_determination.cpp",
        "yql_yt_io_discovery_partitions.cpp",
        "yql_yt_io_discovery_walk_folders.cpp",
        "yql_yt_io_discovery.cpp",
        "yql_yt_join_impl.cpp",
        "yql_yt_join_reorder.cpp",
        "yql_yt_key.cpp",
        "yql_yt_layers_integration.cpp",
        "yql_yt_load_columnar_stats.cpp",
        "yql_yt_load_table_meta.cpp",
        "yql_yt_logical_optimize.cpp",
        "yql_yt_mkql_compiler.cpp",
        "yql_yt_op_hash.cpp",
        "yql_yt_op_settings.cpp",
        "yql_yt_optimize.cpp",
        "yql_yt_peephole.cpp",
        "yql_yt_physical_finalizing.cpp",
        "yql_yt_physical_optimize.cpp",
        "yql_yt_provider_context.cpp",
        "yql_yt_provider_impl.cpp",
        "yql_yt_provider_impl.h",
        "yql_yt_provider.cpp",
        "yql_yt_provider.h",
        "yql_yt_table_desc.cpp",
        "yql_yt_table.cpp",
        "yql_yt_wide_flow.cpp",
        "yql_yt_ytflow_integration.cpp",
        "yql_yt_ytflow_optimize.cpp",
    ]

    serialize_enum_headers = [ "yql_yt_op_settings.h" ]
}
