library("compstrat") {
  public_deps = [
    "//ydb/core/blobstorage/vdisk/hulldb/generic",
    "//ydb/core/blobstorage/vdisk/hulldb:_self",
    # "//ydb/core/blobstorage/vdisk:defs",
  ]

  deps = [
    "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/blobstorage/vdisk/hulldb/base",  # peerdir only
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [
    "hulldb_compstrat_defs.cpp",
    "hulldb_compstrat_selector.cpp",
  ]
}
