library("credentials") {
  public_deps = [ "//ydb/public/sdk/cpp/src/client/types" ]

  deps = [
    # "//ydb/public/api/grpc",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/types/status",  # peerdir only
    # "//ydb/public/sdk/cpp/src/library/issue",  # peerdir only
  ]

  sources = [ "credentials.cpp" ]
}

library("login") {
  deps = [
    ":credentials",
    "//contrib/libs/jwt-cpp",  # peerdir only
    # "//ydb/public/api/grpc",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/common",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/impl/internal/grpc_connections",
    "//ydb/public/sdk/cpp/src/client/impl/internal/plain_status",
    # "//ydb/public/sdk/cpp/src/client/types/core_facility",
    # "//ydb/public/sdk/cpp/src/client/types/status",  # peerdir only
    # "//ydb/public/sdk/cpp/src/library/issue",  # peerdir only
  ]

  sources = [ "login/login.cpp" ]
}

library("oauth2_token_exchange") {
  public_deps = [
    ":credentials",
    # "//ydb/public/sdk/cpp/src/client/types",
  ]

  deps = [
    "//contrib/libs/jwt-cpp",  # peerdir only
    "//library/cpp/cgiparam",
    "//library/cpp/http/misc",
    "//library/cpp/http/simple",
    "//library/cpp/json",
    # "//library/cpp/retry",
    "//library/cpp/string_utils/base64",
    "//library/cpp/uri",
  ]

  sources = [
    "oauth2_token_exchange/credentials.cpp",
    "oauth2_token_exchange/from_file.cpp",
    "oauth2_token_exchange/jwt_token_source.cpp",
  ]
}
