library("credentials") {
  public_deps = [ "//ydb/public/sdk/cpp/src/client/types" ]

  deps = [
    # "//ydb/public/api/grpc",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/types/status",  # peerdir only
    # "//ydb/public/sdk/cpp/src/library/issue",  # peerdir only
  ]

  sources = [ "credentials.cpp" ]
}
