library("credentials") {
  public_deps = [
    "//ydb/public/sdk/cpp/src/client/types",
  ]

  sources = [ "credentials.cpp" ]
}

library("login") {
  deps = [
    ":credentials",
    "//contrib/libs/jwt-cpp",
    "//library/cpp/threading/future",
    "//ydb/public/sdk/cpp/src/client/impl/internal/grpc_connections",
    "//ydb/public/sdk/cpp/src/client/impl/internal/plain_status",
  ]
  sources = [ "login/login.cpp" ]
}

library("oauth2_token_exchange") {
  public_deps = [
    # "//ydb/public/sdk/cpp/src/client/types",
    # "//ydb/public/sdk/cpp/src/client/types/credentials",
  ]

  deps = [
    # "//library/cpp/cgiparam",
    # "//library/cpp/http/misc",
    # "//library/cpp/http/simple",
    # "//library/cpp/json",
    # "//library/cpp/retry",
    # "//library/cpp/string_utils/base64",
    # "//library/cpp/uri",
  ]

  sources = [
    "oauth2_token_exchange/credentials.cpp",
    "oauth2_token_exchange/from_file.cpp",
    "oauth2_token_exchange/jwt_token_source.cpp",
  ]
}
