library("cli_config_base") {
    public_deps = [
        "//yql/essentials/minikql",
    ]

    deps = [
        "//ydb/public/lib/deprecated/client",
    ]

    sources = [
        "cli_config_base/config_base.cpp",
    ]
}

library("run") {
    public_deps = [
        ":cli_config_base",
        "//ydb/core/base",
        "//ydb/core/config:init",
        "//ydb/core/http_proxy",
        "//ydb/core/kqp/common",
    ]

    deps = [
        "//ydb/core/http_proxy",
        "//ydb/core/protos",
        "//ydb/core/util:memory_tracker",
    ]

    sources = [
        "run/auto_config_initializer.cpp",
        "run/config_helpers.cpp",
        "run/config_parser.cpp",
        "run/config.cpp",
        "run/factories.cpp",
        "run/kikimr_services_initializers.cpp",
        "run/main.cpp",
        "run/run.cpp",
        "run/service_initializer.cpp",
    ]
}
