library("fresh") {
  public_deps = [
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/threading/skip_list",
    # "//ydb/core/base",
    # "//ydb/core/blobstorage/base",
    "//ydb/core/blobstorage/vdisk/hulldb/base",
    "//ydb/core/blobstorage/vdisk/hulldb/base:base_types",
    # "//ydb/core/blobstorage/vdisk/hulldb/generic",
    # "//ydb/core/blobstorage/vdisk/protos",
    "//ydb/core/blobstorage/vdisk:defs",
  ]

  deps = [
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [
    "fresh_appendix.cpp",
    "fresh_data.cpp",
    "fresh_datasnap.cpp",
    "fresh_segment.cpp",
  ]
}
