library("control_plane") {
  public_deps = [
    # "//ydb/core/fq/libs/config/protos",
    # "//ydb/core/fq/libs/shared_resources",
    # "//ydb/core/fq/libs/signer",
    # "//ydb/library/actors/core",
    # "//ydb/library/grpc/actor_client",
    "//ydb/library/security",
  ]

  deps = [
    # "//library/cpp/json",
    "//ydb/core/fq/libs/compute/ydb/synchronization_service",
    # "//ydb/core/fq/libs/compute/ydb:events",
    # "//ydb/core/fq/libs/control_plane_storage/events",
    # "//ydb/core/fq/libs/control_plane_storage/proto",  # peerdir only
    "//ydb/core/fq/libs/control_plane_storage:service_id",
    "//ydb/core/fq/libs/control_plane_storage:util",
    # "//ydb/core/fq/libs/quota_manager/proto",  # peerdir only
    "//ydb/core/fq/libs/ydb",
    "//ydb/core/kqp/workload_service/common",
    # "//ydb/core/protos",  # peerdir only
    "//ydb/library/actors/http",
    # "//ydb/library/actors/protos",  # peerdir only
    # "//ydb/library/db_pool/protos",  # peerdir only
    # "//ydb/library/services",
    "//ydb/library/ycloud/api",
    "//ydb/library/yql/utils/actors",
    "//ydb/public/api/grpc",
    # "//ydb/public/api/grpc/draft",  # peerdir only
    "//ydb/public/lib/fq",
    # "//ydb/public/sdk/cpp/src/client/operation",
    # "//ydb/public/sdk/cpp/src/client/query",
    # "//ydb/public/sdk/cpp/src/client/resources",
    # "//ydb/public/sdk/cpp/src/library/operation_id/protos",  # peerdir only
    # "//yql/essentials/public/issue",
    # "//yql/essentials/utils",
  ]

  sources = [
    "cms_grpc_client_actor.cpp",
    "compute_database_control_plane_service.cpp",
    "compute_databases_cache.cpp",
    "database_monitoring.cpp",
    "monitoring_grpc_client_actor.cpp",
    "monitoring_rest_client_actor.cpp",
    "ydbcp_grpc_client_actor.cpp",
  ]
}
