library("mkql") {
  public_deps = [
    "//yql/essentials/ast",
    "//yql/essentials/minikql",
  ]

  deps = [
    # "//yql/essentials/core",
    # "//yql/essentials/core/expr_nodes",
    "//yql/essentials/core/type_ann",
    # "//yql/essentials/parser/pg_catalog",
    "//yql/essentials/providers/common/schema:expr",
    "//yql/essentials/public/decimal",
    # "//yql/essentials/public/udf",
    # "//yql/essentials/utils",
  ]

  sources = [
    "yql_provider_mkql.cpp",
    "yql_type_mkql.cpp",
  ]
}
