group("all") {
    deps = [
        "//ydb/apps/etcd_proxy",
        "//ydb/apps/pgwire",
        "//ydb/apps/ydb",
        "//ydb/apps/ydbd",
        "//ydb/core/backup/tools/decrypt",
        "//ydb/core/base/generated:codegen",
        "//ydb/core/fq/libs/compute/ydb:events",
        "//ydb/core/fq/libs/pretty_printers",
        "//ydb/core/kqp/tests/tpch",
        "//ydb/core/tx/columnshard/tools/memory_tests/bin:memory_tests",
        "//ydb/core/yt",
        "//ydb/library/actors/core/manual_test/shared_threads",
        "//ydb/library/actors/examples/01_ping_pong:example_01_ping_pong",
        "//ydb/library/actors/examples/02_discovery:example_02_discovery",
        "//ydb/library/persqueue/counter_time_keeper",
        "//ydb/library/pretty_types_print/wilson",
        "//ydb/library/schlab/mon/static:css",
        "//ydb/library/schlab/mon/static:js",
        "//ydb/library/schlab/mon/test:mon-test",
        "//ydb/library/shop:sim_flowctl",
        "//ydb/library/shop:sim_shop",
        "//ydb/library/yaml_config/tools/dump:yaml-to-proto-dump",
        "//ydb/library/yaml_config/tools/dump_ds_init:yaml-to-proto-dump-ds-init",
        "//ydb/library/yaml_config/tools/fuse:yaml-config-fuse",
        "//ydb/library/yql/providers/function/provider",
        "//ydb/library/yql/tools/dq/dq_cli",
        "//ydb/library/yql/tools/dq/service_node",
        "//ydb/library/yql/tools/dq/worker_job",
        "//ydb/library/yql/tools/dq/worker_node",
        "//ydb/library/yql/tools/dqrun",
        "//ydb/mvp/meta:mvp_meta",
        "//ydb/mvp/oidc_proxy:mvp_oidc_proxy",
        "//ydb/public/sdk/cpp/examples/auth/ssa_delegation",
        "//ydb/public/sdk/cpp/examples/basic_example",
        "//ydb/public/sdk/cpp/examples/bulk_upsert_simple",
        "//ydb/public/sdk/cpp/examples/executor",
        "//ydb/public/sdk/cpp/examples/pagination",
        "//ydb/public/sdk/cpp/examples/secondary_index",
        "//ydb/public/sdk/cpp/examples/secondary_index_builtin",
        "//ydb/public/sdk/cpp/examples/time",
        "//ydb/public/sdk/cpp/examples/topic_reader/eventloop:persqueue_reader_eventloop",
        "//ydb/public/sdk/cpp/examples/topic_reader/simple:simple_persqueue_reader",
        "//ydb/public/sdk/cpp/examples/topic_reader/transaction:read_from_topic_in_transaction",
        "//ydb/public/sdk/cpp/examples/topic_writer/transaction:topic_writer_transaction",
        "//ydb/public/sdk/cpp/examples/ttl",
        "//ydb/public/sdk/cpp/examples/vector_index",
        "//ydb/public/sdk/cpp/examples/vector_index_builtin",
        "//ydb/tests/library/compatibility/configs/dump/dumper:ydb-config-meta-dumper",
        "//ydb/tests/stress/kv_volume:workload_keyvalue_volume",
        "//ydb/tests/tools/idx_test",
        "//ydb/tests/tools/pq_read",
        "//ydb/tests/tools/s3_bench:ydb_s3_bench",
        "//ydb/tools/blobsan",
        "//ydb/tools/partcheck",
        "//ydb/tools/stress_tool:ydb_stress_tool",
        "//ydb/tools/tsserver",
    ]
}

group("tests") {
    testonly = true
    deps = [
        "//util/charset/ut",
        "//util/datetime/ut",
        "//util/digest/ut",
        "//util/draft/ut",
        "//util/folder/ut",
        "//util/generic/ut",
        "//util/memory/ut",
        "//util/network/ut",
        "//util/random/ut",
        "//util/stream/ut",
        "//util/string/ut",
        "//util/system/ut",
        "//util/thread/ut",
        "//util/ut",
        "//ydb/apps/ydb/ut",
        "//ydb/core/actorlib_impl/ut",
        "//ydb/core/backup/common/ut",
        "//ydb/core/backup/impl/ut_local_partition_reader",
        "//ydb/core/backup/impl/ut_table_writer",
        "//ydb/core/backup/regexp/ut",
        "//ydb/core/base/generated/ut",
        "//ydb/core/base/ut",
        "//ydb/core/base/ut_auth",
        "//ydb/core/base/ut_board_subscriber",
        "//ydb/core/blob_depot/ut",
        "//ydb/core/blobstorage/backpressure/ut",
        "//ydb/core/blobstorage/backpressure/ut_client",
        "//ydb/core/blobstorage/base/ut",
        "//ydb/core/blobstorage/crypto/ut",
        "//ydb/core/blobstorage/ddisk/ut",
        "//ydb/core/blobstorage/dsproxy/ut",
        "//ydb/core/blobstorage/dsproxy/ut_fat",
        "//ydb/core/blobstorage/dsproxy/ut_ftol",
        "//ydb/core/blobstorage/dsproxy/ut_strategy",
        "//ydb/core/blobstorage/groupinfo/ut",
        "//ydb/core/blobstorage/incrhuge/ut",
        "//ydb/core/blobstorage/nodewarden/ut",
        "//ydb/core/blobstorage/nodewarden/ut_sequence",
        "//ydb/core/blobstorage/pdisk/ut",
        "//ydb/core/blobstorage/storagepoolmon/ut",
        "//ydb/core/blobstorage/ut_blobstorage/ut_balancing",
        "//ydb/core/blobstorage/ut_blobstorage/ut_blob_depot",
        "//ydb/core/blobstorage/ut_blobstorage/ut_blob_depot_fat",
        "//ydb/core/blobstorage/ut_blobstorage/ut_bridge",
        "//ydb/core/blobstorage/ut_blobstorage/ut_check_integrity",
        "//ydb/core/blobstorage/ut_blobstorage/ut_cluster_balancing",
        "//ydb/core/blobstorage/ut_blobstorage/ut_comp_defrag",
        "//ydb/core/blobstorage/ut_blobstorage/ut_ddisk",
        "//ydb/core/blobstorage/ut_blobstorage/ut_donor",
        "//ydb/core/blobstorage/ut_blobstorage/ut_group_reconfiguration",
        "//ydb/core/blobstorage/ut_blobstorage/ut_huge",
        "//ydb/core/blobstorage/ut_blobstorage/ut_move_pdisk",
        "//ydb/core/blobstorage/ut_blobstorage/ut_osiris",
        "//ydb/core/blobstorage/ut_blobstorage/ut_phantom_blobs",
        "//ydb/core/blobstorage/ut_blobstorage/ut_read_only_pdisk",
        "//ydb/core/blobstorage/ut_blobstorage/ut_read_only_vdisk",
        "//ydb/core/blobstorage/ut_blobstorage/ut_replication",
        "//ydb/core/blobstorage/ut_blobstorage/ut_restart_pdisk",
        "//ydb/core/blobstorage/ut_blobstorage/ut_scrub",
        "//ydb/core/blobstorage/ut_blobstorage/ut_statestorage",
        "//ydb/core/blobstorage/ut_blobstorage/ut_stop_pdisk",
        "//ydb/core/blobstorage/ut_blobstorage/ut_vdisk_restart",
        "//ydb/core/blobstorage/ut_group",
        "//ydb/core/blobstorage/ut_mirror3of4",
        "//ydb/core/blobstorage/ut_pdiskfit/pdiskfit",
        "//ydb/core/blobstorage/ut_pdiskfit/ut",
        "//ydb/core/blobstorage/ut_testshard",
        "//ydb/core/blobstorage/ut_vdisk",
        "//ydb/core/blobstorage/ut_vdisk2",
        "//ydb/core/blobstorage/ut_vdisk_io",
        "//ydb/core/blobstorage/vdisk/anubis_osiris/ut",
        "//ydb/core/blobstorage/vdisk/common/ut",
        "//ydb/core/blobstorage/vdisk/defrag/ut",
        "//ydb/core/blobstorage/vdisk/huge/ut",
        "//ydb/core/blobstorage/vdisk/hulldb/barriers/ut",
        "//ydb/core/blobstorage/vdisk/hulldb/base/ut",
        "//ydb/core/blobstorage/vdisk/hulldb/cache_block/ut",
        "//ydb/core/blobstorage/vdisk/hulldb/compstrat/ut",
        "//ydb/core/blobstorage/vdisk/hulldb/fresh/ut",
        "//ydb/core/blobstorage/vdisk/hulldb/generic/ut",
        "//ydb/core/blobstorage/vdisk/hullop/ut",
        "//ydb/core/blobstorage/vdisk/ingress/ut",
        "//ydb/core/blobstorage/vdisk/query/ut",
        "//ydb/core/blobstorage/vdisk/repl/ut",
        "//ydb/core/blobstorage/vdisk/skeleton/ut",
        "//ydb/core/blobstorage/vdisk/syncer/ut",
        "//ydb/core/blobstorage/vdisk/synclog/ut",
        "//ydb/core/client/metadata/ut",
        "//ydb/core/client/minikql_compile/ut",
        "//ydb/core/client/server/ut",
        "//ydb/core/client/ut",
        "//ydb/core/cms/console/ut_configs_dispatcher",
        "//ydb/core/cms/console/ut_console",
        "//ydb/core/cms/console/validators/ut",
        "//ydb/core/cms/ut",
        "//ydb/core/cms/ut_sentinel",
        "//ydb/core/cms/ut_sentinel_unstable",
        "//ydb/core/config/init/ut",
        "//ydb/core/config/tools/protobuf_plugin/ut",
        "//ydb/core/config/ut",
        "//ydb/core/config/validation/auth_config_validator_ut",
        "//ydb/core/config/validation/column_shard_config_validator_ut",
        "//ydb/core/config/validation/ut",
        "//ydb/core/control/ut",
        "//ydb/core/debug_tools/ut",
        "//ydb/core/driver_lib/run/ut",
        "//ydb/core/driver_lib/version/ut",
        "//ydb/core/engine/ut",
        "//ydb/core/erasure/ut_perf",
        "//ydb/core/external_sources/object_storage/inference/ut",
        "//ydb/core/external_sources/ut",
        "//ydb/core/formats/arrow/ut",
        "//ydb/core/fq/libs/actors/ut",
        "//ydb/core/fq/libs/checkpoint_storage/ut",
        "//ydb/core/fq/libs/checkpointing/ut",
        "//ydb/core/fq/libs/common/ut",
        "//ydb/core/fq/libs/compute/common/ut",
        "//ydb/core/fq/libs/control_plane_proxy/ut",
        "//ydb/core/fq/libs/control_plane_storage/internal/ut",
        "//ydb/core/fq/libs/db_id_async_resolver_impl/ut",
        "//ydb/core/fq/libs/hmac/ut",
        "//ydb/core/fq/libs/metrics/ut",
        "//ydb/core/fq/libs/result_formatter/ut",
        "//ydb/core/fq/libs/row_dispatcher/format_handler/ut",
        "//ydb/core/fq/libs/row_dispatcher/ut",
        "//ydb/core/fq/libs/signer/ut",
        "//ydb/core/fq/libs/test_connection/ut",
        "//ydb/core/fq/libs/ydb/ut",
        "//ydb/core/graph/shard/ut",
        "//ydb/core/graph/ut",
        "//ydb/core/grpc_services/grpc_request_check_actor_ut",
        "//ydb/core/grpc_services/tablet/ut",
        "//ydb/core/grpc_services/ut",
        "//ydb/core/grpc_streaming/ut",
        "//ydb/core/health_check/ut",
        "//ydb/core/http_proxy/ut",
        "//ydb/core/http_proxy/ut/inside_ydb_ut",
        "//ydb/core/http_proxy/ut/sqs_topic_ut",
        "//ydb/core/io_formats/arrow/scheme/ut",
        "//ydb/core/jaeger_tracing/ut",
        "//ydb/core/kafka_proxy/ut",
        "//ydb/core/kesus/proxy/ut",
        "//ydb/core/kesus/tablet/ut",
        "//ydb/core/kesus/tablet:quoter_performance_test",
        "//ydb/core/keyvalue/ut",
        "//ydb/core/keyvalue/ut_trace",
        "//ydb/core/kqp/common/result_set_format/ut",
        "//ydb/core/kqp/compile_service/helpers/ut",
        "//ydb/core/kqp/compile_service/ut",
        "//ydb/core/kqp/executer_actor/ut",
        "//ydb/core/kqp/federated_query/actors/ut_service/fast",
        "//ydb/core/kqp/federated_query/actors/ut_service/slow",
        "//ydb/core/kqp/federated_query/ut",
        "//ydb/core/kqp/gateway/ut",
        "//ydb/core/kqp/provider/ut",
        "//ydb/core/kqp/proxy_service/ut",
        "//ydb/core/kqp/rm_service/ut",
        "//ydb/core/kqp/runtime/ut",
        "//ydb/core/kqp/tools/combiner_perf/bin:combiner_perf",
        "//ydb/core/kqp/tools/join_perf/bin:join_perf",
        "//ydb/core/kqp/ut/arrow",
        "//ydb/core/kqp/ut/batch_operations",
        "//ydb/core/kqp/ut/close_with_load",
        "//ydb/core/kqp/ut/cost",
        "//ydb/core/kqp/ut/data",
        "//ydb/core/kqp/ut/data_integrity",
        "//ydb/core/kqp/ut/discovery",
        "//ydb/core/kqp/ut/effects",
        "//ydb/core/kqp/ut/federated_query/datastreams",
        "//ydb/core/kqp/ut/federated_query/generic_ut",
        "//ydb/core/kqp/ut/federated_query/large_results",
        "//ydb/core/kqp/ut/federated_query/s3",
        "//ydb/core/kqp/ut/idx_test",
        "//ydb/core/kqp/ut/indexes",
        "//ydb/core/kqp/ut/indexes/fulltext",
        "//ydb/core/kqp/ut/join",
        "//ydb/core/kqp/ut/knn",
        "//ydb/core/kqp/ut/olap",
        "//ydb/core/kqp/ut/olap/indexes",
        "//ydb/core/kqp/ut/olap/operations",
        "//ydb/core/kqp/ut/olap/reading",
        "//ydb/core/kqp/ut/olap/statistics",
        "//ydb/core/kqp/ut/olap/storage",
        "//ydb/core/kqp/ut/olap/types",
        "//ydb/core/kqp/ut/opt",
        "//ydb/core/kqp/ut/perf",
        "//ydb/core/kqp/ut/pg",
        "//ydb/core/kqp/ut/query",
        "//ydb/core/kqp/ut/rbo",
        "//ydb/core/kqp/ut/runtime",
        "//ydb/core/kqp/ut/scan",
        "//ydb/core/kqp/ut/scheme",
        "//ydb/core/kqp/ut/service",
        "//ydb/core/kqp/ut/sysview",
        "//ydb/core/kqp/ut/tx",
        "//ydb/core/kqp/ut/view",
        "//ydb/core/kqp/ut/yql",
        "//ydb/core/kqp/workload_service/ut",
        "//ydb/core/load_test/ut",
        "//ydb/core/load_test/ut_ycsb",
        "//ydb/core/log_backend/ut",
        "//ydb/core/memory_controller/ut",
        "//ydb/core/metering/ut",
        "//ydb/core/mind/address_classification/ut",
        "//ydb/core/mind/bscontroller/ut",
        "//ydb/core/mind/bscontroller/ut_bscontroller",
        "//ydb/core/mind/bscontroller/ut_selfheal",
        "//ydb/core/mind/hive/ut",
        "//ydb/core/mind/ut",
        "//ydb/core/mind/ut_fat",
        "//ydb/core/mon/audit/ut",
        "//ydb/core/mon/ut",
        "//ydb/core/nbs/cloud/blockstore/libs/service/ut",
        "//ydb/core/nbs/cloud/blockstore/libs/storage/partition_direct/ut",
        "//ydb/core/nbs/cloud/blockstore/libs/vhost/ut",
        "//ydb/core/nbs/cloud/blockstore/libs/vhost/ut_stress",
        "//ydb/core/nbs/cloud/storage/core/libs/common/ut",
        "//ydb/core/persqueue/common/ut",
        "//ydb/core/persqueue/dread_cache_service/ut",
        "//ydb/core/persqueue/pqtablet/blob/ut",
        "//ydb/core/persqueue/pqtablet/partition/mlp/ut",
        "//ydb/core/persqueue/pqtablet/partition/ut",
        "//ydb/core/persqueue/pqtablet/quota/ut",
        "//ydb/core/persqueue/public/codecs/ut",
        "//ydb/core/persqueue/public/describer/ut",
        "//ydb/core/persqueue/public/fetcher/ut",
        "//ydb/core/persqueue/public/list_topics/ut",
        "//ydb/core/persqueue/public/mlp/ut",
        "//ydb/core/persqueue/public/partition_index_generator/ut",
        "//ydb/core/persqueue/public/partition_key_range/ut",
        "//ydb/core/persqueue/ut",
        "//ydb/core/persqueue/ut/slow",
        "//ydb/core/persqueue/ut/ut_with_sdk",
        "//ydb/core/pgproxy/ut",
        "//ydb/core/public_http/ut",
        "//ydb/core/quoter/ut",
        "//ydb/core/quoter:quoter_service_bandwidth_test",
        "//ydb/core/raw_socket/ut",
        "//ydb/core/resource_pools/ut",
        "//ydb/core/scheme/ut",
        "//ydb/core/scheme/ut_pg",
        "//ydb/core/security/certificate_check/ut",
        "//ydb/core/security/ldap_auth_provider/ut",
        "//ydb/core/security/ut",
        "//ydb/core/statistics/aggregator/ut",
        "//ydb/core/statistics/database/ut",
        "//ydb/core/statistics/service/ut",
        "//ydb/core/statistics/service/ut/ut_aggregation",
        "//ydb/core/sys_view/partition_stats/ut",
        "//ydb/core/sys_view/query_stats/ut",
        "//ydb/core/sys_view/service/ut",
        "//ydb/core/sys_view/ut",
        "//ydb/core/sys_view/ut_large",
        "//ydb/core/tablet/ut",
        "//ydb/core/tablet_flat/test/tool/perf:table-perf",
        "//ydb/core/tablet_flat/test/tool/surg",
        "//ydb/core/tablet_flat/ut",
        "//ydb/core/tablet_flat/ut_large",
        "//ydb/core/tablet_flat/ut_pg",
        "//ydb/core/tablet_flat/ut_util",
        "//ydb/core/testlib/actors/ut",
        "//ydb/core/transfer/ut/column_table",
        "//ydb/core/transfer/ut/functional",
        "//ydb/core/transfer/ut/large",
        "//ydb/core/transfer/ut/row_table",
        "//ydb/core/tx/balance_coverage/ut",
        "//ydb/core/tx/columnshard/engines/ut",
        "//ydb/core/tx/columnshard/splitter/ut",
        "//ydb/core/tx/columnshard/ut_rw",
        "//ydb/core/tx/columnshard/ut_schema",
        "//ydb/core/tx/conveyor_composite/ut",
        "//ydb/core/tx/coordinator/ut",
        "//ydb/core/tx/datashard/build_index/ut",
        "//ydb/core/tx/datashard/ut_borrowed_compaction",
        "//ydb/core/tx/datashard/ut_change_collector",
        "//ydb/core/tx/datashard/ut_change_exchange",
        "//ydb/core/tx/datashard/ut_column_stats",
        "//ydb/core/tx/datashard/ut_compaction",
        "//ydb/core/tx/datashard/ut_disk_quotas",
        "//ydb/core/tx/datashard/ut_erase_rows",
        "//ydb/core/tx/datashard/ut_export",
        "//ydb/core/tx/datashard/ut_external_blobs",
        "//ydb/core/tx/datashard/ut_followers",
        "//ydb/core/tx/datashard/ut_incremental_backup",
        "//ydb/core/tx/datashard/ut_incremental_restore_scan",
        "//ydb/core/tx/datashard/ut_init",
        "//ydb/core/tx/datashard/ut_keys",
        "//ydb/core/tx/datashard/ut_kqp",
        "//ydb/core/tx/datashard/ut_kqp_errors",
        "//ydb/core/tx/datashard/ut_kqp_scan",
        "//ydb/core/tx/datashard/ut_locks",
        "//ydb/core/tx/datashard/ut_minikql",
        "//ydb/core/tx/datashard/ut_minstep",
        "//ydb/core/tx/datashard/ut_object_storage_listing",
        "//ydb/core/tx/datashard/ut_order",
        "//ydb/core/tx/datashard/ut_range_ops",
        "//ydb/core/tx/datashard/ut_read_iterator",
        "//ydb/core/tx/datashard/ut_read_table",
        "//ydb/core/tx/datashard/ut_reassign",
        "//ydb/core/tx/datashard/ut_replication",
        "//ydb/core/tx/datashard/ut_rs",
        "//ydb/core/tx/datashard/ut_sequence",
        "//ydb/core/tx/datashard/ut_snapshot",
        "//ydb/core/tx/datashard/ut_snapshot_isolation",
        "//ydb/core/tx/datashard/ut_stats",
        "//ydb/core/tx/datashard/ut_trace",
        "//ydb/core/tx/datashard/ut_truncate",
        "//ydb/core/tx/datashard/ut_upload_rows",
        "//ydb/core/tx/datashard/ut_vacuum",
        "//ydb/core/tx/datashard/ut_volatile",
        "//ydb/core/tx/datashard/ut_write",
        "//ydb/core/tx/limiter/grouped_memory/ut",
        "//ydb/core/tx/long_tx_service/public/ut",
        "//ydb/core/tx/long_tx_service/ut",
        "//ydb/core/tx/mediator/ut",
        "//ydb/core/tx/replication/controller/ut_assign_tx_id",
        "//ydb/core/tx/replication/controller/ut_dst_creator",
        "//ydb/core/tx/replication/controller/ut_replication",
        "//ydb/core/tx/replication/controller/ut_stream_creator",
        "//ydb/core/tx/replication/controller/ut_target_discoverer",
        "//ydb/core/tx/replication/service/ut_json_change_record",
        "//ydb/core/tx/replication/service/ut_s3_writer",
        "//ydb/core/tx/replication/service/ut_table_writer",
        "//ydb/core/tx/replication/service/ut_topic_reader",
        "//ydb/core/tx/replication/service/ut_worker",
        "//ydb/core/tx/replication/ydb_proxy/ut",
        "//ydb/core/tx/scheme_board/ut_cache",
        "//ydb/core/tx/scheme_board/ut_double_indexed",
        "//ydb/core/tx/scheme_board/ut_monitoring",
        "//ydb/core/tx/scheme_board/ut_populator",
        "//ydb/core/tx/scheme_board/ut_replica",
        "//ydb/core/tx/scheme_board/ut_subscriber",
        "//ydb/core/tx/schemeshard/ut_auditsettings",
        "//ydb/core/tx/schemeshard/ut_background_cleaning",
        "//ydb/core/tx/schemeshard/ut_backup",
        "//ydb/core/tx/schemeshard/ut_backup_collection",
        "//ydb/core/tx/schemeshard/ut_backup_collection_reboots",
        "//ydb/core/tx/schemeshard/ut_base",
        "//ydb/core/tx/schemeshard/ut_base_reboots",
        "//ydb/core/tx/schemeshard/ut_bsvolume",
        "//ydb/core/tx/schemeshard/ut_bsvolume_reboots",
        "//ydb/core/tx/schemeshard/ut_cdc_stream",
        "//ydb/core/tx/schemeshard/ut_cdc_stream_reboots",
        "//ydb/core/tx/schemeshard/ut_column_build",
        "//ydb/core/tx/schemeshard/ut_column_build_reboots",
        "//ydb/core/tx/schemeshard/ut_compaction",
        "//ydb/core/tx/schemeshard/ut_consistent_copy_tables",
        "//ydb/core/tx/schemeshard/ut_continuous_backup",
        "//ydb/core/tx/schemeshard/ut_continuous_backup_reboots",
        "//ydb/core/tx/schemeshard/ut_export",
        "//ydb/core/tx/schemeshard/ut_export_reboots_s3",
        "//ydb/core/tx/schemeshard/ut_external_data_source",
        "//ydb/core/tx/schemeshard/ut_external_data_source_reboots",
        "//ydb/core/tx/schemeshard/ut_external_table",
        "//ydb/core/tx/schemeshard/ut_external_table_reboots",
        "//ydb/core/tx/schemeshard/ut_extsubdomain",
        "//ydb/core/tx/schemeshard/ut_extsubdomain_reboots",
        "//ydb/core/tx/schemeshard/ut_failure_injection",
        "//ydb/core/tx/schemeshard/ut_filestore_reboots",
        "//ydb/core/tx/schemeshard/ut_incremental_restore",
        "//ydb/core/tx/schemeshard/ut_incremental_restore_reboots",
        "//ydb/core/tx/schemeshard/ut_index",
        "//ydb/core/tx/schemeshard/ut_index_build",
        "//ydb/core/tx/schemeshard/ut_index_build_reboots",
        "//ydb/core/tx/schemeshard/ut_login",
        "//ydb/core/tx/schemeshard/ut_login_large",
        "//ydb/core/tx/schemeshard/ut_move",
        "//ydb/core/tx/schemeshard/ut_move_reboots",
        "//ydb/core/tx/schemeshard/ut_olap",
        "//ydb/core/tx/schemeshard/ut_olap_reboots",
        "//ydb/core/tx/schemeshard/ut_partition_stats",
        "//ydb/core/tx/schemeshard/ut_pq_reboots",
        "//ydb/core/tx/schemeshard/ut_reboots",
        "//ydb/core/tx/schemeshard/ut_replication",
        "//ydb/core/tx/schemeshard/ut_replication_reboots",
        "//ydb/core/tx/schemeshard/ut_resource_pool",
        "//ydb/core/tx/schemeshard/ut_resource_pool_reboots",
        "//ydb/core/tx/schemeshard/ut_restore",
        "//ydb/core/tx/schemeshard/ut_rtmr",
        "//ydb/core/tx/schemeshard/ut_rtmr_reboots",
        "//ydb/core/tx/schemeshard/ut_ru_calculator",
        "//ydb/core/tx/schemeshard/ut_secret",
        "//ydb/core/tx/schemeshard/ut_secret_reboots",
        "//ydb/core/tx/schemeshard/ut_sequence",
        "//ydb/core/tx/schemeshard/ut_sequence_reboots",
        "//ydb/core/tx/schemeshard/ut_serverless",
        "//ydb/core/tx/schemeshard/ut_serverless_reboots",
        "//ydb/core/tx/schemeshard/ut_shred",
        "//ydb/core/tx/schemeshard/ut_shred_reboots",
        "//ydb/core/tx/schemeshard/ut_split_merge",
        "//ydb/core/tx/schemeshard/ut_split_merge_reboots",
        "//ydb/core/tx/schemeshard/ut_stats",
        "//ydb/core/tx/schemeshard/ut_streaming_query",
        "//ydb/core/tx/schemeshard/ut_streaming_query_reboots",
        "//ydb/core/tx/schemeshard/ut_subdomain",
        "//ydb/core/tx/schemeshard/ut_subdomain_reboots",
        "//ydb/core/tx/schemeshard/ut_system_names",
        "//ydb/core/tx/schemeshard/ut_sysview",
        "//ydb/core/tx/schemeshard/ut_sysview_reboots",
        "//ydb/core/tx/schemeshard/ut_topic_set_boundaries",
        "//ydb/core/tx/schemeshard/ut_topic_splitmerge",
        "//ydb/core/tx/schemeshard/ut_transfer",
        "//ydb/core/tx/schemeshard/ut_truncate_table_reboots",
        "//ydb/core/tx/schemeshard/ut_truncate_table_simple",
        "//ydb/core/tx/schemeshard/ut_ttl",
        "//ydb/core/tx/schemeshard/ut_user_attributes",
        "//ydb/core/tx/schemeshard/ut_user_attributes_reboots",
        "//ydb/core/tx/schemeshard/ut_vector_index_build_reboots",
        "//ydb/core/tx/schemeshard/ut_view",
        "//ydb/core/tx/sequenceproxy/ut",
        "//ydb/core/tx/sequenceshard/public/ut",
        "//ydb/core/tx/sequenceshard/ut",
        "//ydb/core/tx/sharding/ut",
        "//ydb/core/tx/tiering/ut",
        "//ydb/core/tx/time_cast/ut",
        "//ydb/core/tx/tx_allocator/ut",
        "//ydb/core/tx/tx_allocator_client/ut",
        "//ydb/core/tx/tx_proxy/ut_base_tenant",
        "//ydb/core/tx/tx_proxy/ut_encrypted_storage",
        "//ydb/core/tx/tx_proxy/ut_ext_tenant",
        "//ydb/core/tx/tx_proxy/ut_schemereq",
        "//ydb/core/tx/tx_proxy/ut_storage_tenant",
        "//ydb/core/util/ut",
        "//ydb/core/viewer/json/ut",
        "//ydb/core/viewer/ut",
        "//ydb/core/wrappers/ut",
        "//ydb/core/ydb_convert/ut",
        "//ydb/core/ymq/actor/cloud_events/cloud_events_ut",
        "//ydb/core/ymq/actor/yc_search_ut",
        "//ydb/core/ymq/attributes/ut",
        "//ydb/core/ymq/base/ut",
        "//ydb/core/ymq/http/ut",
        "//ydb/core/ymq/ut",
        "//ydb/library/aclib/ut",
        "//ydb/library/actors/async/ut",
        "//ydb/library/actors/core/harmonizer/ut",
        "//ydb/library/actors/core/ut",
        "//ydb/library/actors/core/ut_fat",
        "//ydb/library/actors/dnsresolver/ut",
        "//ydb/library/actors/helpers/ut",
        "//ydb/library/actors/http/ut",
        "//ydb/library/actors/interconnect/rdma/ut",
        "//ydb/library/actors/interconnect/rdma/ut_mem_pool_limit_128",
        "//ydb/library/actors/interconnect/rdma/ut_mem_pool_limit_32",
        "//ydb/library/actors/interconnect/ut",
        "//ydb/library/actors/interconnect/ut_fat",
        "//ydb/library/actors/interconnect/ut_rdma",
        "//ydb/library/actors/prof/ut",
        "//ydb/library/actors/testlib/ut",
        "//ydb/library/actors/util/ut",
        "//ydb/library/actors/wilson/ut",
        "//ydb/library/actors/wilson:test_util",
        "//ydb/library/arrow_clickhouse/ut",
        "//ydb/library/arrow_kernels/ut",
        "//ydb/library/backup/ut",
        "//ydb/library/drr/ut",
        "//ydb/library/formats/arrow/ut",
        "//ydb/library/fyamlcpp/ut",
        "//ydb/library/grpc/server/ut",
        "//ydb/library/http_proxy/authorization/ut",
        "//ydb/library/intersection_tree/ut",
        "//ydb/library/keys/ut",
        "//ydb/library/lockfree_bucket/ut",
        "//ydb/library/login/account_lockout/ut",
        "//ydb/library/login/cache/ut",
        "//ydb/library/login/hashes_checker/ut",
        "//ydb/library/login/password_checker/ut",
        "//ydb/library/login/sasl/ut",
        "//ydb/library/login/ut",
        "//ydb/library/naming_conventions/ut",
        "//ydb/library/ncloud/impl/ut",
        "//ydb/library/pdisk_io/ut",
        "//ydb/library/persqueue/topic_parser/ut",
        "//ydb/library/planner/share/ut",
        "//ydb/library/protobuf_printer/ut",
        "//ydb/library/query_actor/ut",
        "//ydb/library/range_treap/ut_range_treap",
        "//ydb/library/schlab/ut",
        "//ydb/library/security/ut",
        "//ydb/library/shop/ut",
        "//ydb/library/table_creator/ut",
        "//ydb/library/testlib/ut",
        "//ydb/library/time_series_vec/ut",
        "//ydb/library/union_copy_set/ut",
        "//ydb/library/workload/benchmark_base/ut",
        "//ydb/library/workload/tpcc/ut",
        "//ydb/library/workload/tpch/ut",
        "//ydb/library/yaml_config/static_validator/ut",
        "//ydb/library/yaml_config/static_validator/ut/example_configs",
        "//ydb/library/yaml_config/ut",
        "//ydb/library/yaml_config/validator/ut/validator",
        "//ydb/library/yaml_config/validator/ut/validator_builder",
        "//ydb/library/yaml_config/validator/ut/validator_checks",
        "//ydb/library/ycloud/impl/ut",
        "//ydb/library/yql/core/spilling/storage/ut",
        "//ydb/library/yql/core/spilling/ut",
        "//ydb/library/yql/dq/actors/compute/ut",
        "//ydb/library/yql/dq/actors/spilling/ut",
        "//ydb/library/yql/dq/comp_nodes/hash_join_utils/simd/exec/pack_tuple",
        "//ydb/library/yql/dq/comp_nodes/hash_join_utils/simd/exec/runtime_dispatching:main",
        "//ydb/library/yql/dq/comp_nodes/hash_join_utils/simd/exec/stream_store",
        "//ydb/library/yql/dq/comp_nodes/hash_join_utils/simd/exec/tuples_to_bucket",
        "//ydb/library/yql/dq/comp_nodes/hash_join_utils/simd/ut",
        "//ydb/library/yql/dq/comp_nodes/hash_join_utils/ut",
        "//ydb/library/yql/dq/comp_nodes/ut",
        "//ydb/library/yql/dq/opt/ut",
        "//ydb/library/yql/dq/runtime/ut",
        "//ydb/library/yql/dq/state/ut",
        "//ydb/library/yql/providers/common/http_gateway/ut",
        "//ydb/library/yql/providers/dq/actors/ut",
        "//ydb/library/yql/providers/dq/provider/ut",
        "//ydb/library/yql/providers/dq/runtime/ut",
        "//ydb/library/yql/providers/dq/scheduler/ut",
        "//ydb/library/yql/providers/generic/actors/ut",
        "//ydb/library/yql/providers/generic/provider/ut/pushdown",
        "//ydb/library/yql/providers/generic/pushdown/ut",
        "//ydb/library/yql/providers/pq/provider/ut",
        "//ydb/library/yql/providers/s3/actors/ut",
        "//ydb/library/yql/providers/s3/common/ut",
        "//ydb/library/yql/providers/s3/compressors/ut",
        "//ydb/library/yql/providers/s3/credentials/ut",
        "//ydb/library/yql/providers/s3/object_listers/ut",
        "//ydb/library/yql/providers/s3/path_generator/ut",
        "//ydb/library/yql/providers/s3/provider/ut",
        "//ydb/library/yql/providers/s3/range_helpers/ut",
        "//ydb/library/yql/providers/solomon/actors/ut",
        "//ydb/library/yql/providers/solomon/common/ut",
        "//ydb/library/yql/providers/yt/actors/ut",
        "//ydb/library/yql/public/ydb_issue/ut",
        "//ydb/library/yql/utils/bindings/ut",
        "//ydb/library/yql/utils/plan/ut",
        "//ydb/mvp/core/ut",
        "//ydb/mvp/meta/ut",
        "//ydb/mvp/oidc_proxy/ut",
        "//ydb/public/lib/idx_test/ut",
        "//ydb/public/lib/json_value/ut",
        "//ydb/public/lib/validation/ut",
        "//ydb/public/lib/value/ut",
        "//ydb/public/lib/ydb_cli/commands/interactive/highlight/ut",
        "//ydb/public/lib/ydb_cli/commands/topic_workload/ut",
        "//ydb/public/lib/ydb_cli/common/ini_config/ut",
        "//ydb/public/lib/ydb_cli/common/ut",
        "//ydb/public/lib/ydb_cli/common/yql_parser/ut",
        "//ydb/public/lib/ydb_cli/topic/ut",
        "//ydb/public/sdk/cpp/src/client/federated_topic/ut",
        "//ydb/public/sdk/cpp/src/client/persqueue_public/ut",
        "//ydb/public/sdk/cpp/src/client/persqueue_public/ut/with_offset_ranges_mode_ut",
        "//ydb/public/sdk/cpp/src/client/topic/ut",
        "//ydb/public/sdk/cpp/src/client/topic/ut/slow",
        "//ydb/public/sdk/cpp/src/client/topic/ut/with_direct_read_ut",
        "//ydb/public/sdk/cpp/tests/integration/auth",
        "//ydb/public/sdk/cpp/tests/integration/basic_example",
        "//ydb/public/sdk/cpp/tests/integration/bulk_upsert",
        "//ydb/public/sdk/cpp/tests/integration/server_restart",
        "//ydb/public/sdk/cpp/tests/integration/sessions",
        "//ydb/public/sdk/cpp/tests/integration/sessions_pool",
        "//ydb/public/sdk/cpp/tests/integration/topic",
        "//ydb/public/sdk/cpp/tests/integration/topic/with_direct_read",
        "//ydb/public/sdk/cpp/tests/slo_workloads/key_value",
        "//ydb/public/sdk/cpp/tests/unit/client/connection_string",
        "//ydb/public/sdk/cpp/tests/unit/client/coordination",
        "//ydb/public/sdk/cpp/tests/unit/client/discovery_mutator",
        "//ydb/public/sdk/cpp/tests/unit/client/draft",
        "//ydb/public/sdk/cpp/tests/unit/client/driver",
        "//ydb/public/sdk/cpp/tests/unit/client/endpoints",
        "//ydb/public/sdk/cpp/tests/unit/client/oauth2_token_exchange",
        "//ydb/public/sdk/cpp/tests/unit/client/params",
        "//ydb/public/sdk/cpp/tests/unit/client/result",
        "//ydb/public/sdk/cpp/tests/unit/client/value",
        "//ydb/public/sdk/cpp/tests/unit/library/decimal",
        "//ydb/public/sdk/cpp/tests/unit/library/grpc_client",
        "//ydb/public/sdk/cpp/tests/unit/library/issue",
        "//ydb/public/sdk/cpp/tests/unit/library/operation_id",
        "//ydb/public/sdk/cpp/tests/unit/library/time",
        "//ydb/services/cms/ut",
        "//ydb/services/config/ut",
        "//ydb/services/datastreams/ut",
        "//ydb/services/dynamic_config/ut",
        "//ydb/services/ext_index/ut",
        "//ydb/services/fq/ut_integration",
        "//ydb/services/keyvalue/ut",
        "//ydb/services/metadata/initializer/ut",
        "//ydb/services/metadata/secret/ut",
        "//ydb/services/persqueue_cluster_discovery/cluster_ordering/ut",
        "//ydb/services/persqueue_cluster_discovery/ut",
        "//ydb/services/persqueue_v1/ut",
        "//ydb/services/persqueue_v1/ut/describes_ut",
        "//ydb/services/persqueue_v1/ut/new_schemecache_ut",
        "//ydb/services/rate_limiter/ut",
        "//ydb/services/sqs_topic/queue_url/ut",
        "//ydb/services/ydb/table_split_ut",
        "//ydb/services/ydb/ut",
        "//ydb/tests/fq/control_plane_storage",
        "//ydb/tests/fq/pq_async_io/ut",
        "//ydb/tests/functional/backup",
        "//ydb/tests/functional/backup/s3_path_style",
        "//ydb/tests/functional/kqp/kqp_indexes",
        "//ydb/tests/functional/kqp/kqp_query_session",
        "//ydb/tests/functional/kqp/kqp_query_svc",
        "//ydb/tests/functional/replication",
        "//ydb/tests/functional/sdk/cpp/sdk_credprovider",
        "//ydb/tests/olap/high_load",
        "//ydb/tests/tools/fqrun",
        "//ydb/tests/tools/kqprun",
        "//ydb/tools/stress_tool/ut",
    ]
}
