group("all") {
    deps = [
        "//contrib/libs/zlib",
        "//contrib/restricted/abseil-cpp-tstring",
        "//contrib/restricted/abseil-cpp",
        "//contrib/restricted/google/utf8_range",
        "//contrib/libs/protobuf",
        "//contrib/libs/base64/avx2",
        "//contrib/libs/base64/neon32",
        "//contrib/libs/base64/neon64",
        "//contrib/libs/base64/plain32",
        "//contrib/libs/base64/plain64",
        "//contrib/libs/base64/ssse3",
        "//library/cpp/string_utils/base64",
        "//library/cpp/build_info",
        "//library/cpp/malloc/api",
        "//contrib/libs/rapidjson",
        "//library/cpp/monlib/exception",
        "//contrib/libs/xxhash",
        "//contrib/libs/lz4",
        "//contrib/libs/zstd",
        "//library/cpp/iterator",
        "//library/cpp/string_utils/quote",
        "//library/cpp/string_utils/scan",
        "//library/cpp/cgiparam",
        "//contrib/libs/libc_compat",
        "//library/cpp/coroutine/engine",
        "//library/cpp/coroutine/listener",
        "//contrib/libs/libiconv",
        "//library/cpp/charset",
        "//contrib/libs/nayuki_md5",
        "//library/cpp/digest/md5",
        "//library/cpp/digest/murmur",
        "//library/cpp/case_insensitive_string",
        "//library/cpp/digest/lower_case",
        "//library/cpp/http/misc",
        "//library/cpp/mime/types",
        "//contrib/libs/libidn",
        "//library/cpp/uri",
        "//contrib/libs/libbz2",
        "//contrib/libs/fastlz",
        "//contrib/libs/lzmasdk",
        "//contrib/libs/snappy",
        "//library/cpp/streams/brotli",
        "//library/cpp/streams/bzip2",
        "//library/cpp/streams/lzma",
        "//library/cpp/deprecated/atomic",
        "//library/cpp/threading/equeue",
        "//build/scripts/c_templates",
        "//library/cpp/svnversion",
        "//library/cpp/containers/absl_flat_hash",
        "//ydb/core/config/protos",
        "//ydb/library/actors/protos",
        "//ydb/library/yql/dq/proto",
        "//ydb/public/api/protos/annotations",
        "//ydb/public/api/protos",
        "//yql/essentials/public/types",
        "//yql/essentials/protos",
        "//ydb/core/nbs/cloud/blockstore/tools/testing/loadtest/lib/protos",
        "//ydb/core/protos/schemeshard",
        "//ydb/library/services",
        "//ydb/core/graph/protos",
        "//contrib/libs/openssl",
        "//contrib/libs/crcutil",
        "//library/cpp/digest/crc32c",
        "//library/cpp/lwtrace",
        "//library/cpp/containers/stack_vector",
        "//library/cpp/threading/light_rw_lock",
        "//library/cpp/monlib/metrics",
        "//library/cpp/streams/zc_memory_input",
        "//library/cpp/packedtypes",
        "//library/cpp/execprofile",
        "//library/cpp/time_provider",
        "//library/cpp/containers/str_map",
        "//library/cpp/containers/atomizer",
        "//library/cpp/lfalloc/dbg_info",
        "//library/cpp/yt/assert",
        "//library/cpp/yt/malloc",
        "//library/cpp/yt/exception",
        "//library/cpp/yt/misc",
        "//library/cpp/yt/system",
        "//ydb/library/actors/prof",
        "//contrib/libs/ibdrv",
        "//contrib/libs/linuxvdso",
        "//library/cpp/threading/queue",
        "//contrib/libs/c-ares",
        "//contrib/libs/opentelemetry-proto",
        "//library/cpp/colorizer",
        "//library/cpp/getopt",
        "//ydb/library/global_plugins",
        "//library/cpp/html/pcdata",
        "//library/cpp/containers/cow_string",
        "//library/cpp/yt/coding",
        "//library/cpp/yt/compact_containers",
        "//library/cpp/monlib/encode/legacy_protobuf/protos",
        "//library/cpp/sliding_window",
        "//contrib/libs/snowball",
        "//library/cpp/deprecated/enum_codegen",
        "//library/cpp/sse",
        "//ydb/library/actors/util",
        "//ydb/library/actors/actor_type",
        "//ydb/library/actors/memory_log",
        "//contrib/libs/backtrace",
        "//library/cpp/dwarf_backtrace",
        "//library/cpp/l1_distance",
        "//library/cpp/l2_distance",
        "//library/cpp/random_provider",
        "//library/cpp/threading/hot_swap",
        "//ydb/library/yverify_stream",
        "//ydb/core/debug",
        "//library/cpp/digest/old_crc",
        "//ydb/core/erasure",
        "//ydb/core/graph/api",
        "//library/cpp/containers/2d_array",
        "//library/cpp/binsaver",
        "//library/cpp/protobuf/util",
        "//ydb/library/aclib",
        "//contrib/libs/jwt-cpp",
        "//library/cpp/threading/poor_man_openmp",
        "//library/cpp/digest/argonish",
        "//library/cpp/unicode/normalization",
        "//contrib/libs/libaio",
        "//contrib/libs/liburing",
        "//contrib/libs/miniselect",
        "//contrib/libs/apache/orc-format",
        "//contrib/libs/apache/orc",
        "//contrib/libs/double-conversion",
        "//contrib/libs/re2",
        "//contrib/libs/utf8proc",
        "//contrib/libs/libevent",
        "//contrib/restricted/boost/config",
        "//contrib/restricted/boost/assert",
        "//contrib/restricted/boost/move",
        "//contrib/restricted/boost/intrusive",
        "//contrib/restricted/boost/container",
        "//contrib/restricted/boost/throw_exception",
        "//contrib/restricted/boost/core",
        "//contrib/restricted/boost/static_assert",
        "//contrib/restricted/boost/type_traits",
        "//contrib/restricted/boost/integer",
        "//contrib/restricted/boost/mp11",
        "//contrib/restricted/boost/describe",
        "//contrib/restricted/boost/container_hash",
        "//contrib/restricted/boost/preprocessor",
        "//contrib/restricted/boost/detail",
        "//contrib/restricted/boost/predef",
        "//contrib/restricted/boost/smart_ptr",
        "//contrib/restricted/boost/tuple",
        "//contrib/restricted/boost/unordered",
        "//contrib/restricted/boost/interprocess",
        "//contrib/libs/icu",
        "//contrib/restricted/boost/charconv",
        "//contrib/restricted/boost/concept_check",
        "//contrib/restricted/boost/io",
        "//contrib/restricted/boost/utility",
        "//contrib/restricted/boost/mpl",
        "//contrib/restricted/boost/bind",
        "//contrib/restricted/boost/function",
        "//contrib/restricted/boost/functional",
        "//contrib/restricted/boost/optional",
        "//contrib/restricted/boost/iterator",
        "//contrib/restricted/boost/align",
        "//contrib/restricted/boost/atomic",
        "//contrib/restricted/boost/ratio",
        "//contrib/restricted/boost/system",
        "//contrib/restricted/boost/chrono",
        "//contrib/restricted/boost/exception",
        "//contrib/restricted/boost/conversion",
        "//contrib/restricted/boost/regex",
        "//contrib/restricted/boost/range",
        "//contrib/restricted/boost/algorithm",
        "//contrib/restricted/boost/numeric_conversion",
        "//contrib/restricted/boost/tokenizer",
        "//contrib/restricted/boost/date_time",
        "//contrib/restricted/boost/thread",
        "//contrib/restricted/boost/locale",
        "//contrib/restricted/boost/math",
        "//contrib/restricted/thrift",
        "//contrib/restricted/uriparser",
        "//contrib/libs/apache/arrow",
        "//contrib/libs/cctz",
        "//library/cpp/enumbitset",
        "//library/cpp/yson_pull",
        "//yql/essentials/public/decimal",
        "//contrib/libs/libunwind",
        "//yql/essentials/utils/backtrace",
        "//library/cpp/disjoint_sets",
        "//library/cpp/containers/sorted_vector",
        "//library/cpp/string_utils/levenshtein_diff",
        "//yql/essentials/core/credentials",
        "//yql/essentials/core/url_preprocessing/interface",
        "//library/cpp/openssl/holders",
        "//library/cpp/openssl/method",
        "//library/cpp/retry",
        "//yql/essentials/public/langver",
        "//contrib/libs/simdjson",
        "//yql/essentials/types/dynumber",
        "//yql/essentials/types/uuid",
        "//library/cpp/string_utils/url",
        "//ydb/public/sdk/cpp/src/client/types/exceptions",
        "//ydb/public/sdk/cpp/src/client/types",
        "//ydb/public/sdk/cpp/src/client/impl/internal/common",
        "//ydb/public/sdk/cpp/src/client/types/fatal_error_handlers",
        "//ydb/public/sdk/cpp/src/client/impl/internal/value_helpers",
        "//ydb/public/sdk/cpp/src/library/decimal",
        "//ydb/public/sdk/cpp/src/library/uuid",
        "//ydb/public/sdk/cpp/src/client/value",
        "//ydb/public/sdk/cpp/src/client/params",
        "//library/cpp/cache",
        "//library/cpp/threading/cancellation",
        "//library/cpp/threading/future",
        "//yql/essentials/utils",
        "//ydb/public/api/client/yc_public/common",
        "//ydb/public/api/client/yc_public/iam",
        "//ydb/public/api/grpc",
        "//ydb/public/sdk/cpp/src/library/time",
        "//ydb/public/sdk/cpp/src/library/issue",
        "//library/cpp/dns",
        "//contrib/libs/t1ha",
        "//ydb/core/blobstorage/crypto",
        "//contrib/libs/libssh2",
        "//contrib/libs/nghttp2",
        "//contrib/libs/nghttp3",
        "//contrib/libs/ngtcp2",
        "//contrib/libs/curl",
        "//contrib/libs/aws-sdk-cpp/aws-cpp-sdk-core",
        "//library/cpp/html/escape",
        "//library/cpp/int128",
        "//library/cpp/ipv6_address",
        "//library/cpp/ipmath",
        "//library/cpp/containers/bitseq",
        "//ydb/public/lib/scheme_types",
        "//library/cpp/blockcodecs",
        "//library/cpp/http/io",
        "//library/cpp/http/server",
        "//library/cpp/resource",
        "//yql/essentials/public/issue",
        "//ydb/library/yql/public/ydb_issue",
        "//ydb/library/ydb_issue",
        "//yql/essentials/core/issue",
        "//yql/essentials/core/sql_types",
        "//yql/essentials/public/udf",
        "//library/cpp/openssl/io",
        "//contrib/libs/grpc",
        "//library/cpp/http/simple",
        "//ydb/public/sdk/cpp/src/client/resources",
        "//ydb/public/sdk/cpp/src/library/grpc/client",
        "//ydb/public/sdk/cpp/src/client/impl/internal/plain_status",
        "//ydb/public/sdk/cpp/src/client/types/status",
        "//ydb/public/sdk/cpp/adapters/issue",
        "//ydb/public/sdk/cpp/src/library/persqueue/topic_parser_public",
        "//yql/essentials/core/expr_nodes",
        "//yql/essentials/core/histogram",
        "//yql/essentials/core/minsketch",
        "//yql/essentials/minikql/jsonpath/rewrapper",
        "//contrib/libs/antlr3_cpp_runtime",
        "//yql/essentials/parser/proto_ast/antlr3",
        "//library/cpp/deprecated/kmp",
        "//library/cpp/deprecated/split",
        "//yql/essentials/parser/lexer_common",
        "//ydb/core/docapi",
        "//ydb/library/arrow_kernels",
        "//ydb/library/conclusion",
        "//ydb/library/yql/dq/expr_nodes",
        "//ydb/core/kqp/expr_nodes",
        "//yql/essentials/providers/result/expr_nodes",
        "//ydb/library/yql/providers/dq/expr_nodes",
        "//library/cpp/streams/zstd",
        "//ydb/public/sdk/cpp/src/client/impl/stats",
        "//ydb/public/sdk/cpp/src/client/impl/endpoints",
        "//ydb/public/sdk/cpp/src/client/impl/internal/rpc_request_settings",
        "//ydb/public/sdk/cpp/src/client/impl/internal/thread_pool",
        "//ydb/public/sdk/cpp/src/client/impl/executor",
        "//ydb/public/sdk/cpp/src/client/types/executor",
        "//ydb/public/sdk/cpp/src/client/impl/internal/make_request",
        "//ydb/public/sdk/cpp/src/library/operation_id",
        "//ydb/public/sdk/cpp/src/client/types/operation",
        "//ydb/public/sdk/cpp/src/client/impl/session",
        "//ydb/public/sdk/cpp/src/library/persqueue/obfuscate",
        "//library/cpp/string_utils/parse_size",
        "//yql/essentials/providers/pg/expr_nodes",
        "//yql/essentials/parser/proto_ast/collect_issues",
        "//contrib/libs/antlr4_cpp_runtime",
        "//yql/essentials/parser/common",
        "//yql/essentials/parser/proto_ast/antlr4",
        "//library/cpp/regex/pire",
        "//ydb/core/resource_pools",
        "//contrib/restricted/boost/variant",
        "//ydb/core/tx/columnshard/export/protos",
        "//contrib/libs/llvm16/lib/IR",
        "//contrib/libs/llvm16/lib/ExecutionEngine/MCJIT",
        "//contrib/libs/llvm16/lib/Linker",
        "//contrib/libs/llvm16/lib/Transforms/ObjCARC",
        "//contrib/libs/llvm16/lib/Transforms/IPO",
        "//contrib/libs/llvm16/lib/Passes",
        "//contrib/libs/llvm16/lib/Target/X86",
        "//contrib/libs/llvm16/lib/Target/X86/AsmParser",
        "//contrib/libs/llvm16/lib/Target/X86/Disassembler",
        "//contrib/libs/llvm16/lib/ExecutionEngine/PerfJITEvents",
        "//yql/essentials/minikql/codegen/llvm16",
        "//ydb/services/bg_tasks/protos",
        "//contrib/libs/sparsehash",
        "//library/cpp/deprecated/accessors",
        "//library/cpp/bit_io",
        "//library/cpp/on_disk/chunks",
        "//library/cpp/packers",
        "//library/cpp/containers/comptrie",
        "//library/cpp/compproto",
        "//library/cpp/comptable",
        "//library/cpp/codecs",
        "//library/cpp/string_utils/indent_text",
        "//ydb/library/wilson_ids",
        "//contrib/libs/aws-sdk-cpp/aws-cpp-sdk-s3",
        "//ydb/library/chunks_limiter",
        "//library/cpp/protobuf/interop",
        "//ydb/services/lib/sharding",
        "//library/cpp/sighandler",
        "//ydb/library/schlab/probes",
        "//ydb/library/schlab/protos",
        "//ydb/core/blobstorage/vdisk/protos",
        "//library/cpp/openssl/big_integer",
        "//library/cpp/openssl/crypto",
        "//library/cpp/containers/intrusive_avl_tree",
        "//contrib/libs/libfyaml",
        "//ydb/library/fyamlcpp",
        "//contrib/libs/yaml-cpp",
        "//library/cpp/yaml/as",
        "//contrib/libs/pcre",
        "//library/cpp/containers/stack_array",
        "//library/cpp/regex/pcre",
        "//ydb/core/backup/regexp",
        "//ydb/library/yql/providers/pq/proto",
        "//library/cpp/threading/task_scheduler",
        "//ydb/library/yql/providers/dq/config",
        "//ydb/library/yql/providers/dq/interface",
        "//ydb/library/yql/providers/common/token_accessor/grpc",
        "//yql/essentials/core/user_data",
        "//yql/essentials/core/langver",
        "//yql/essentials/core/qplayer/storage/interface",
        "//ydb/core/fq/libs/events",
        "//ydb/library/naming_conventions",
        "//ydb/library/yql/providers/s3/expr_nodes",
        "//ydb/core/nbs/cloud/blockstore/public/api/protos",
        "//ydb/core/nbs/cloud/contrib/vhost",
        "//ydb/core/nbs/cloud/blockstore/config",
        "//ydb/library/formats/arrow/csv/converter",
        "//contrib/libs/fmt",
        "//contrib/libs/lzma",
        "//contrib/libs/expat",
        "//contrib/libs/libxml",
        "//library/cpp/string_utils/ztstrbuf",
        "//library/cpp/xml/init",
        "//library/cpp/xml/document",
        "//yql/essentials/utils/threading",
        "//ydb/core/tx/columnshard/bg_tasks/protos",
        "//library/cpp/containers/ring_buffer",
        "//contrib/libs/ftxui",
        "//contrib/restricted/patched/replxx",
        "//library/cpp/string_utils/csv",
        "//ydb/public/api/client/nc_private",
        "//ydb/public/api/client/nc_private/audit/v1/common",
        "//ydb/public/api/client/nc_private/audit",
        "//ydb/public/api/client/nc_private/common/v1",
        "//ydb/public/api/client/nc_private/iam/v1",
        "//ydb/public/api/client/yc_private/accessservice",
        "//ydb/public/api/client/yc_private/operation",
        "//ydb/public/api/client/yc_private/iam",
        "//ydb/public/api/client/yc_private/servicecontrol",
        "//ydb/public/api/client/yc_private/resourcemanager",
        "//ydb/library/cloud_permissions",
        "//library/cpp/containers/disjoint_interval_tree",
        "//ydb/library/yql/providers/generic/expr_nodes",
        "//ydb/library/yql/providers/pq/expr_nodes",
        "//ydb/public/sdk/cpp/src/client/federated_topic",
        "//ydb/library/yql/providers/pq/gateway/abstract",
        "//yt/yql/providers/ytflow/expr_nodes",
        "//ydb/services/metadata",
        "//ydb/public/api/client/yc_public/events",
        "//ydb/library/http_proxy/error",
        "//ydb/library/http_proxy/authorization",
        "//ydb/core/fq/libs/rate_limiter/utils",
        "//ydb/core/fq/libs/hmac",
        "//ydb/core/fq/libs/signer",
        "//ydb/library/yql/providers/pq/gateway/clients/local",
        "//ydb/library/yql/providers/solomon/solomon_accessor/grpc",
        "//ydb/library/yql/providers/solomon/scheme",
        "//ydb/library/yql/providers/solomon/expr_nodes",
        "//library/cpp/type_info",
        "//library/cpp/containers/concurrent_hash",
        "//library/cpp/threading/skip_list",
        "//library/cpp/yt/containers",
        "//library/cpp/yt/string",
        "//library/cpp/yt/memory",
        "//library/cpp/yt/yson_string",
        "//library/cpp/yt/yson",
        "//library/cpp/json",
        "//library/cpp/yson",
        "//library/cpp/monlib/encode",
        "//library/cpp/logger",
        "//library/cpp/http/fetch",
        "//library/cpp/monlib/service/pages",
        "//library/cpp/monlib/service",
        "//library/cpp/monlib/dynamic_counters",
        "//ydb/library/actors/interconnect/rdma",
        "//ydb/library/actors/core",
        "//ydb/library/actors/dnsresolver",
        "//ydb/library/actors/wilson",
        "//ydb/library/actors/interconnect",
        "//ydb/library/actors/helpers",
        "//library/cpp/lwtrace/mon",
        "//library/cpp/testing/common",
        "//library/cpp/dot_product",
        "//ydb/core/base/services",
        "//ydb/core/control/lib",
        "//ydb/library/login",
        "//yql/essentials/core/pg_settings",
        "//yql/essentials/minikql/dom",
        "//yql/essentials/utils/log",
        "//yql/essentials/parser/pg_catalog",
        "//yql/essentials/core/url_lister/interface",
        "//yql/essentials/utils/fetch",
        "//yql/essentials/providers/common/proto",
        "//yql/essentials/types/binary_json",
        "//yql/essentials/minikql",
        "//yql/essentials/ast",
        "//library/cpp/protobuf/json",
        "//ydb/public/sdk/cpp/src/client/types/credentials",
        "//ydb/public/sdk/cpp/src/library/jwt",
        "//ydb/public/sdk/cpp/src/client/iam",
        "//ydb/library/security",
        "//ydb/library/protobuf_printer",
        "//ydb/library/grpc/server",
        "//ydb/library/actors/http",
        "//ydb/library/actors/async",
        "//yql/essentials/minikql/arrow",
        "//yql/essentials/core/expr_nodes_gen",
        "//yql/essentials/core/file_storage",
        "//yql/essentials/core/layers",
        "//yql/essentials/minikql/jsonpath/parser",
        "//yql/essentials/sql",
        "//yql/essentials/providers/common/schema:parser",
        "//yql/essentials/public/result_format",
        "//yql/essentials/core/cbo",
        "//yql/essentials/parser/pg_wrapper/interface",
        "//yql/essentials/minikql/computation",
        "//yql/essentials/core",
        "//yql/essentials/providers/common/codec",
        "//yql/essentials/providers/common/schema:expr",
        "//yql/essentials/providers/common/provider",
        "//yql/essentials/core/type_ann",
        "//yql/essentials/providers/common/mkql",
        "//ydb/library/mkql_proto",
        "//yql/essentials/core/arrow_kernels/request",
        "//ydb/library/yql/dq/common",
        "//ydb/library/yql/dq/type_ann",
        "//yql/essentials/providers/common/comp_nodes",
        "//yql/essentials/providers/common/schema:mkql",
        "//ydb/public/sdk/cpp/src/client/impl/internal/logger",
        "//ydb/public/sdk/cpp/src/client/common_client",
        "//ydb/public/sdk/cpp/src/client/impl/internal/db_driver_state",
        "//ydb/public/sdk/cpp/src/client/impl/internal/grpc_connections",
        "//ydb/public/sdk/cpp/src/client/driver",
        "//ydb/public/sdk/cpp/src/client/extension_common",
        "//ydb/public/sdk/cpp/src/client/impl/internal/retry",
        "//ydb/public/sdk/cpp/src/client/scheme",
        "//ydb/public/sdk/cpp/src/client/proto",
        "//ydb/public/sdk/cpp/src/client/result",
        "//ydb/public/sdk/cpp/src/client/query",
        "//ydb/public/sdk/cpp/src/client/table",
        "//ydb/public/sdk/cpp/src/client/coordination",
        "//ydb/public/sdk/cpp/src/client/export",
        "//ydb/public/sdk/cpp/src/client/import",
        "//ydb/public/sdk/cpp/src/client/topic/common",
        "//ydb/public/sdk/cpp/src/client/topic/impl",
        "//ydb/services/metadata/optimization",
        "//yql/essentials/core/common_opt",
        "//yql/essentials/providers/common/config",
        "//yql/essentials/providers/common/gateway",
        "//yql/essentials/providers/result/provider",
        "//yql/essentials/sql/v1/lexer",
        "//yql/essentials/sql/v1/proto_parser",
        "//yql/essentials/sql/v1",
        "//yql/essentials/core/peephole_opt",
        "//yql/essentials/core/services",
        "//ydb/library/accessor",
        "//ydb/core/scheme_types",
        "//ydb/core/scheme",
        "//ydb/core/io_formats/cell_maker",
        "//ydb/core/io_formats/ydb_dump",
        "//yql/essentials/minikql/jsonpath",
        "//yql/essentials/core/arrow_kernels/registry",
        "//yql/essentials/minikql/computation/llvm16",
        "//yql/essentials/minikql/invoke_builtins/llvm16",
        "//yql/essentials/minikql/comp_nodes/llvm16",
        "//yql/essentials/minikql/comp_nodes",
        "//yql/essentials/core/dq_integration",
        "//ydb/public/lib/value",
        "//ydb/library/range_treap",
        "//library/cpp/monlib/deprecated/json",
        "//library/cpp/messagebus",
        "//library/cpp/monlib/messagebus",
        "//ydb/library/schlab/schine",
        "//ydb/library/schlab/schoot",
        "//ydb/library/schlab/schemu",
        "//ydb/library/schlab/mon",
        "//ydb/library/actors/retro_tracing",
        "//ydb/library/yaml_json",
        "//ydb/library/yql/providers/common/db_id_async_resolver",
        "//ydb/library/yql/dq/transform",
        "//ydb/library/yql/providers/dq/mkql",
        "//yql/essentials/providers/common/transform",
        "//yql/essentials/minikql/invoke_builtins",
        "//yql/essentials/providers/common/structured_token",
        "//ydb/library/yql/providers/common/token_accessor/client",
        "//yql/essentials/providers/common/metrics",
        "//yql/essentials/utils/failure_injector",
        "//ydb/library/yql/utils/actor_log",
        "//ydb/public/lib/yson_value",
        "//yql/essentials/providers/common/activation",
        "//yql/essentials/core/extract_predicate",
        "//yql/essentials/core/qplayer/udf_resolver",
        "//yql/essentials/core/qplayer/url_lister",
        "//yql/essentials/providers/common/arrow_resolve",
        "//yql/essentials/providers/common/gateways_utils",
        "//yql/essentials/providers/common/udf_resolve",
        "//yql/essentials/providers/config",
        "//yql/essentials/core/facade",
        "//ydb/library/yql/providers/s3/statistics",
        "//ydb/library/yql/utils/plan",
        "//ydb/core/nbs/cloud/storage/core/libs/common",
        "//ydb/core/nbs/cloud/blockstore/libs/common",
        "//ydb/core/nbs/cloud/blockstore/libs/service",
        "//library/cpp/unified_agent_client",
        "//library/cpp/scheme",
        "//ydb/library/yql/providers/common/http_gateway",
        "//yql/essentials/minikql/datetime",
        "//ydb/library/yql/providers/s3/path_generator",
        "//ydb/library/arrow_parquet",
        "//ydb/library/plan2svg",
        "//ydb/public/lib/json_value",
        "//ydb/public/sdk/cpp/src/client/cms",
        "//yql/essentials/sql/v1/format",
        "//ydb/core/nbs/cloud/blockstore/libs/kikimr",
        "//ydb/public/lib/fq",
        "//ydb/library/logger",
        "//ydb/public/sdk/cpp/src/client/persqueue_public",
        "//ydb/library/yql/providers/common/pushdown",
        "//ydb/core/fq/libs/result_formatter",
        "//ydb/library/yql/providers/generic/connector/api/service",
        "//ydb/library/yql/providers/generic/proto",
        "//yql/essentials/providers/common/dq",
        "//ydb/library/yql/providers/pq/cm_client",
        "//ydb/library/yql/providers/pq/common",
        "//yt/yql/providers/ytflow/integration/interface",
        "//yt/yql/providers/ytflow/integration/proto",
        "//ydb/public/sdk/cpp/src/client/iam_private",
        "//ydb/public/sdk/cpp/src/client/discovery",
        "//ydb/public/sdk/cpp/src/client/config",
        "//ydb/core/fq/libs/db_schema",
        "//ydb/library/db_pool",
        "//ydb/public/sdk/cpp/src/client/extensions/solomon_stats",
        "//ydb/core/fq/libs/rate_limiter/events",
        "//ydb/public/sdk/cpp/src/client/rate_limiter",
        "//ydb/library/yql/providers/pq/gateway/clients/external",
        "//ydb/public/sdk/cpp/src/client/datastreams",
        "//ydb/library/yql/providers/pq/gateway/native",
        "//ydb/public/sdk/cpp/src/client/extensions/discovery_mutator",
        "//library/cpp/yt/cpu_clock",
        "//library/cpp/yt/logging",
        "//library/cpp/yt/threading",
        "//yt/yt/library/profiling",
        "//yt/yt_proto/yt/core",
        "//yt/yt/library/tvm",
        "//yt/yt_proto/yt/formats",
        "//library/cpp/skiff",
        "//yt/cpp/mapreduce/skiff",
        "//yt/cpp/mapreduce/interface",
        "//yt/cpp/mapreduce/common",
        "//yt/yql/providers/yt/common",
        "//yt/yql/providers/yt/lib/mkql_helpers",
        "//yql/essentials/providers/common/schema:skiff",
        "//yt/yql/providers/yt/lib/skiff",
        "//yt/yt/library/decimal",
        "//yt/yql/providers/yt/expr_nodes",
        "//library/cpp/threading/blocking_queue",
        "//contrib/deprecated/http-parser",
        "//yt/yt/core/http",
        "//yt/yt/core/https",
        "//yt/cpp/mapreduce/io",
        "//yt/cpp/mapreduce/http",
        "//yt/cpp/mapreduce/http_client",
        "//yt/cpp/mapreduce/client",
        "//yt/yt/library/auth",
        "//yt/yql/providers/yt/lib/hash",
        "//yt/yql/providers/yt/lib/url_mapper",
        "//yt/yql/providers/yt/lib/yson_helpers",
        "//yt/yql/providers/yt/lib/dump_helpers",
        "//yt/yql/providers/yt/lib/expr_traits",
        "//yt/yql/providers/yt/lib/schema",
        "//yt/yql/providers/yt/lib/yt_token_resolver",
        "//yt/yql/providers/yt/provider", # <== we are here
        "//yt/cpp/mapreduce/library/user_job_statistics",
        "//yt/yql/providers/yt/lib/yt_rpc_helpers",
        "//yt/yql/providers/yt/lib/infer_schema",
        "//yt/yql/providers/yt/lib/lambda_builder",
        "//yt/yql/providers/yt/lib/config_clusters",
        "//yt/yql/providers/yt/lib/init_yt_api",
        "//yt/yql/providers/yt/lib/log",
        "//yt/yql/providers/yt/lib/secret_masker",
        "//yt/yql/providers/yt/lib/yt_download",
        "//yt/yql/providers/yt/mkql_dq",
        "//ydb/library/yql/providers/generic/pushdown",
        "//ydb/library/yql/providers/s3/serializations",
        "//ydb/public/sdk/cpp/src/client/ss_tasks",
        "//ydb/public/sdk/cpp/src/client/operation",
        "//ydb/public/sdk/cpp/src/client/draft",
        "//ydb/public/lib/ydb_cli/common",
        "//ydb/library/actors/log_backend",
        "//ydb/core/fq/libs/tasks_packer",
        "//contrib/restricted/nlohmann_json",
        "//ydb/services/sqs_topic/protos/receipt",
        "//ydb/core/raw_socket",
        "//yql/essentials/providers/pg/provider",
        "//yql/essentials/sql/v0",
        "//ydb/core/tx/columnshard/engines/scheme/common",
        "//contrib/libs/hdr_histogram",
        "//library/cpp/histogram/hdr",
        "//ydb/core/nbs/cloud/storage/core/libs/diagnostics",
        "//ydb/core/nbs/cloud/blockstore/libs/diagnostics",
        "//ydb/core/nbs/cloud/blockstore/libs/vhost",
        "//ydb/core/nbs/cloud/blockstore/bootstrap",
        "//ydb/core/nbs/cloud/blockstore/tools/testing/loadtest/lib",
        "//ydb/core/tx/limiter/grouped_memory/tracing",
        "//ydb/core/tx/columnshard/engines/reader/tracing",
        "//ydb/core/tx/columnshard/tracing",
        "//ydb/library/actors/testlib/common",
        "//ydb/core/tx/columnshard/subscriber/abstract/events",
        "//ydb/core/tx/columnshard/subscriber/abstract/subscriber",
        "//ydb/core/tx/columnshard/subscriber/events/tx_completed",
        "//ydb/core/tx/conveyor_composite/tracing",
        "//ydb/core/tx/tracing/usage",
        "//ydb/core/tx/tracing/service",
        "//ydb/library/workload/abstract",
        "//ydb/library/workload/stock",
        "//ydb/core/tx/conveyor/tracing",
        "//ydb/library/signal_backtrace",
        "//ydb/services/deprecated/persqueue_v0/api/protos",
        "//ydb/library/persqueue/deprecated/read_batch_converter",
        "//ydb/services/deprecated/persqueue_v0/api/grpc",
        "//yt/yql/providers/yt/codec/codegen/llvm16",
        "//yt/yql/providers/yt/codec",
        "//yt/yql/providers/yt/lib/res_pull",
        "//yt/yql/providers/yt/job",
        "//yt/yql/providers/yt/gateway/lib",
        "//yt/yql/providers/yt/lib/yt_file_download",
        "//yt/yql/providers/yt/gateway/native",
        "//yt/yql/providers/yt/comp_nodes/dq/llvm16",
        "//yql/essentials/parser/pg_wrapper",
        "//ydb/library/formats/arrow",
        "//ydb/core/formats",
        "//ydb/core/tx/columnshard/engines/protos",
        "//ydb/core/protos",
        "//ydb/core/driver_lib/version",
        "//ydb/core/jaeger_tracing",
        "//ydb/library/pdisk_io",
        "//ydb/core/base",
        "//ydb/core/grpc_services/counters",
        "//ydb/core/grpc_streaming",
        "//ydb/core/grpc_services/base",
        "//ydb/core/audit",
        "//ydb/core/mon",
        "//ydb/core/blobstorage/base",
        "//ydb/core/blobstorage/vdisk/ingress",
        "//ydb/core/blobstorage/groupinfo",
        "//ydb/core/node_whiteboard",
        "//ydb/core/util",
        "//ydb/core/actorlib_impl",
        "//ydb/core/backup/common",
        "//ydb/core/change_exchange",
        "//ydb/core/graph/shard/protos",
        "//ydb/core/mon_alloc",
        "//ydb/core/tracing",
        "//ydb/library/persqueue/topic_parser",
        "//ydb/core/tablet",
        "//ydb/core/engine",
        "//ydb/library/yql/dq/runtime",
        "//ydb/library/yql/dq/actors",
        "//ydb/core/kqp/query_data",
        "//ydb/core/kqp/provider",
        "//ydb/core/client/minikql_compile",
        "//ydb/core/tablet_flat",
        "//ydb/core/grpc_services/cancelation",
        "//ydb/services/metadata/abstract",
        "//ydb/library/signals",
        "//ydb/core/formats/arrow",
        "//ydb/core/tx/columnshard/data_sharing/protos",
        "//ydb/core/tx/columnshard/common",
        "//ydb/core/tx/schemeshard/olap/common",
        "//ydb/core/tx/schemeshard/olap/columns",
        "//ydb/core/tx/columnshard/engines/scheme/indexes/abstract",
        "//ydb/services/bg_tasks/abstract",
        "//ydb/core/tx/schemeshard/olap/indexes",
        "//ydb/core/tx/schemeshard/olap/options",
        "//ydb/core/tx/schemeshard/olap/schema",
        "//ydb/core/tx/sharding",
        "//ydb/core/kqp/common",
        "//ydb/core/ydb_convert",
        "//ydb/core/kqp/runtime",
        "//ydb/core/tx",
        "//ydb/public/lib/base",
        "//ydb/core/keyvalue",
        "//ydb/core/persqueue/events",
        "//ydb/public/lib/deprecated/client",
        "//ydb/public/lib/deprecated/kicli",
        "//ydb/core/persqueue/writer",
        "//ydb/core/tx/locks",
        "//ydb/core/wrappers",
        "//ydb/library/yql/dq/tasks",
        "//ydb/core/tx/datashard",
        "//ydb/core/backup/controller",
        "//ydb/core/blobstorage/lwtrace_probes",
        "//ydb/core/blobstorage/pdisk",
        "//ydb/core/blobstorage/vdisk/common",
        "//ydb/core/blob_depot",
        "//ydb/core/retro_tracing_impl",
        "//ydb/core/blobstorage/backpressure",
        "//ydb/core/blobstorage/common",
        "//ydb/core/blobstorage/storagepoolmon",
        "//ydb/core/blobstorage/dsproxy",
        "//ydb/core/blobstorage/incrhuge",
        "//ydb/core/blobstorage/bridge/proxy",
        "//ydb/core/blobstorage/bridge/syncer",
        "//ydb/core/blobstorage/ddisk",
        "//ydb/core/blobstorage/vdisk/anubis_osiris",
        "//ydb/core/blobstorage/vdisk/hulldb",
        "//ydb/core/blobstorage/vdisk/defrag",
        "//ydb/core/blobstorage/vdisk/huge",
        "//ydb/core/blobstorage/vdisk/synclog",
        "//ydb/core/blobstorage/vdisk/hullop",
        "//ydb/core/blobstorage/vdisk/localrecovery",
        "//ydb/core/blobstorage/vdisk/query",
        "//ydb/core/blobstorage/vdisk/repl",
        "//ydb/core/blobstorage/vdisk/balance",
        "//ydb/core/blobstorage/vdisk/metadata",
        "//ydb/core/blobstorage/vdisk/skeleton",
        "//ydb/core/blobstorage/vdisk/scrub",
        "//ydb/core/blobstorage/vdisk/syncer",
        "//ydb/core/blobstorage/vdisk",
        "//ydb/core/config/validation",
        "//ydb/library/yaml_config",
        "//ydb/core/blobstorage/nodewarden",
        "//ydb/core/blobstorage/other",
        "//ydb/core/blobstorage",
        "//ydb/core/client/scheme_cache_lib",
        "//ydb/core/client/metadata",
        "//ydb/core/counters_info",
        "//ydb/core/tx/scheme_cache",
        "//ydb/core/discovery",
        "//ydb/core/fq/libs/protos",
        "//ydb/library/yql/providers/dq/api/protos",
        "//ydb/core/fq/libs/graph_params/proto",
        "//ydb/core/fq/libs/row_dispatcher/protos",
        "//ydb/library/yql/providers/dq/api/grpc",
        "//ydb/library/yql/providers/dq/common",
        "//ydb/library/yql/providers/dq/counters",
        "//ydb/library/yql/dq/opt",
        "//ydb/library/yql/providers/dq/opt",
        "//ydb/library/yql/providers/dq/planner",
        "//ydb/library/yql/providers/dq/task_runner",
        "//ydb/library/yql/providers/solomon/proto",
        "//ydb/library/yql/utils/actors",
        "//ydb/library/yql/providers/dq/runtime",
        "//ydb/library/yql/providers/dq/task_runner_actor",
        "//ydb/library/yql/providers/dq/worker_manager",
        "//ydb/library/yql/providers/dq/actors",
        "//ydb/library/yql/providers/dq/provider",
        "//ydb/core/grpc_services/local_rpc",
        "//ydb/core/health_check",
        "//ydb/core/metering",
        "//ydb/core/kesus/tablet",
        "//ydb/core/kqp/opt/logical",
        "//ydb/core/kqp/opt/physical",
        "//ydb/core/kqp/opt/peephole",
        "//ydb/core/kqp/opt/rbo",
        "//ydb/core/kqp/opt",
        "//ydb/core/nbs/cloud/blockstore/libs/storage/api",
        "//ydb/core/io_formats/arrow/scheme",
        "//ydb/core/tx/balance_coverage",
        "//ydb/core/blockstore/core",
        "//ydb/library/yql/providers/s3/proto",
        "//ydb/library/yql/providers/s3/events",
        "//ydb/library/yql/providers/s3/common",
        "//ydb/library/yql/providers/s3/credentials",
        "//ydb/core/external_sources/object_storage",
        "//ydb/library/yql/providers/s3/compressors",
        "//ydb/library/yql/providers/s3/object_listers",
        "//ydb/core/external_sources",
        "//ydb/core/filestore/core",
        "//ydb/core/persqueue/public",
        "//ydb/library/query_actor",
        "//ydb/core/statistics",
        "//ydb/core/tx/columnshard/bg_tasks/abstract",
        "//ydb/core/tx/columnshard/bg_tasks/manager",
        "//ydb/core/tx/scheme_board",
        "//ydb/core/tx/columnshard/bg_tasks/events",
        "//ydb/core/tx/columnshard/bg_tasks/session",
        "//ydb/core/tx/columnshard/bg_tasks/transactions",
        "//ydb/core/tx/schemeshard/olap/bg_tasks/adapter",
        "//ydb/core/tx/schemeshard/olap/bg_tasks/protos",
        "//ydb/core/tx/schemeshard/olap/bg_tasks/events",
        "//ydb/core/tx/schemeshard/olap/bg_tasks/transactions",
        "//ydb/core/tx/schemeshard/olap/bg_tasks/tx_chain",
        "//ydb/core/tx/schemeshard/olap/layout",
        "//ydb/core/tx/schemeshard/olap/operations/alter/abstract",
        "//ydb/core/tx/schemeshard/olap/operations/alter/common",
        "//ydb/core/tx/columnshard/data_sharing/initiator/status",
        "//ydb/core/tx/columnshard/data_sharing/initiator/controller",
        "//ydb/core/tx/schemeshard/olap/store",
        "//ydb/core/tx/schemeshard/olap/ttl",
        "//ydb/core/tx/schemeshard/olap/operations/alter/in_store",
        "//ydb/core/tx/schemeshard/olap/operations/alter/standalone",
        "//ydb/core/tx/tx_allocator",
        "//ydb/core/tx/tx_allocator_client",
        "//ydb/core/tx/schemeshard",
        "//ydb/core/tx/tx_proxy",
        "//ydb/core/nbs/cloud/blockstore/libs/storage/direct_block_group",
        "//ydb/core/nbs/cloud/blockstore/libs/service/fast_path_service",
        "//ydb/core/nbs/cloud/blockstore/libs/storage/partition_direct",
        "//ydb/library/grpc/actor_client",
        "//ydb/library/ncloud/api",
        "//ydb/library/ncloud/impl",
        "//ydb/core/grpc_caching",
        "//ydb/library/ycloud/api",
        "//ydb/library/ycloud/impl",
        "//ydb/core/security",
        "//ydb/core/tx/sequenceproxy",
        "//ydb/library/table_creator",
        "//ydb/core/sys_view",
        "//ydb/core/tx/data_events",
        "//ydb/services/ext_index/common",
        "//ydb/core/grpc_services",
        "//ydb/core/persqueue/common",
        "//ydb/core/persqueue/pqrb",
        "//ydb/core/persqueue/pqtablet/blob",
        "//ydb/core/persqueue/pqtablet/cache",
        "//ydb/core/persqueue/pqtablet/common",
        "//ydb/core/fq/libs/common",
        "//ydb/library/yql/providers/generic/connector/libcpp",
        "//ydb/library/yql/providers/generic/provider",
        "//ydb/library/yql/providers/pq/provider",
        "//ydb/core/fq/libs/row_dispatcher/events",
        "//ydb/core/tx/replication/common",
        "//ydb/core/tx/replication/ydb_proxy",
        "//ydb/core/tx/replication/service",
        "//ydb/core/backup/impl",
        "//ydb/core/persqueue/pqtablet/quota",
        "//ydb/core/persqueue/pqtablet/partition",
        "//ydb/core/persqueue/pqtablet/readproxy",
        "//ydb/core/persqueue/pqtablet",
        "//ydb/core/persqueue",
        "//ydb/core/driver_lib/cli_config_base",
        "//ydb/core/driver_lib/cli_base",
        "//ydb/core/config/init",
        "//ydb/core/kqp/counters",
        "//ydb/core/test_tablet",
        "//ydb/services/metadata/request",
        "//ydb/services/metadata/secret",
        "//ydb/services/metadata/initializer",
        "//ydb/services/metadata/manager",
        "//ydb/core/tx/replication/controller",
        "//ydb/core/mind",
        "//ydb/core/cms/console",
        "//ydb/core/ymq/actor/cfg",
        "//ydb/core/ymq/proto",
        "//ydb/core/ymq/base",
        "//ydb/core/ymq/actor/cloud_events",
        "//ydb/core/ymq/attributes",
        "//ydb/core/ymq/error",
        "//ydb/core/ymq/queues/common",
        "//ydb/core/ymq/queues/fifo",
        "//ydb/core/ymq/queues/std",
        "//ydb/core/ymq/actor",
        "//ydb/services/lib/actors",
        "//ydb/services/persqueue_v1",
        "//ydb/core/client/server",
        "//ydb/core/cms",
        "//ydb/core/control",
        "//ydb/core/driver_lib/base_utils",
        "//ydb/core/driver_lib/cli_utils",
        "//ydb/core/fq/libs/checkpointing_common",
        "//ydb/library/yql/providers/pq/task_meta",
        "//ydb/library/yql/dq/state",
        "//ydb/core/fq/libs/checkpointing",
        "//ydb/core/fq/libs/db_id_async_resolver_impl",
        "//ydb/core/fq/libs/grpc",
        "//ydb/core/fq/libs/config",
        "//ydb/core/fq/libs/shared_resources",
        "//ydb/library/yql/providers/s3/actors_factory",
        "//ydb/core/fq/libs/compute/common",
        "//ydb/core/fq/libs/compute/ydb",
        "//ydb/core/fq/libs/metrics",
        "//ydb/core/fq/libs/quota_manager",
        "//ydb/core/fq/libs/ydb",
        "//ydb/core/fq/libs/control_plane_storage",
        "//ydb/core/fq/libs/private_client",
        "//ydb/core/local_proxy/local_pq_client",
        "//ydb/library/yql/providers/solomon/common",
        "//ydb/library/yql/providers/solomon/solomon_accessor/client",
        "//ydb/library/yql/providers/solomon/events",
        "//ydb/library/yql/providers/solomon/actors",
        "//ydb/library/yql/providers/solomon/provider",
        "//ydb/library/yql/providers/solomon/gateway",
        "//ydb/core/kqp/federated_query",
        "//ydb/library/yql/providers/s3/range_helpers",
        "//ydb/library/yql/providers/s3/actors",
        "//ydb/library/yql/providers/s3/provider",
        "//ydb/core/fq/libs/actors",
        "//ydb/core/fq/libs/audit",
        "//ydb/core/fq/libs/checkpoint_storage",
        "//ydb/library/folder_service",
        "//ydb/core/fq/libs/cloud_audit",
        "//ydb/core/fq/libs/control_plane_config",
        "//ydb/core/fq/libs/control_plane_proxy",
        "//ydb/core/fq/libs/read_rule",
        "//ydb/core/fq/libs/gateway",
        "//ydb/core/fq/libs/health",
        "//ydb/core/fq/libs/rate_limiter/control_plane_service",
        "//ydb/core/fq/libs/rate_limiter/quoter_service",
        "//ydb/core/fq/libs/row_dispatcher/common",
        "//ydb/core/fq/libs/row_dispatcher/format_handler",
        "//ydb/core/fq/libs/row_dispatcher/purecalc_compilation",
        "//ydb/core/fq/libs/row_dispatcher",
        "//ydb/core/fq/libs/test_connection",
        "//ydb/library/yql/providers/generic/actors",
        "//ydb/library/yql/providers/pq/gateway/clients/composite",
        "//ydb/library/yql/providers/pq/async_io",
        "//ydb/core/fq/libs/init",
        "//ydb/core/fq/libs/logs",
        "//ydb/services/ydb",
        "//ydb/services/datastreams",
        "//ydb/services/sqs_topic/queue_url",
        "//ydb/services/sqs_topic",
        "//ydb/services/ymq",
        "//ydb/core/http_proxy",
        "//ydb/core/kafka_proxy",
        "//ydb/core/kesus/proxy",
        "//ydb/library/yql/providers/dq/helper",
        "//ydb/core/kqp/host",
        "//ydb/core/kqp/compile_service",
        "//ydb/library/yql/dq/comp_nodes/llvm16",
        "//ydb/library/yql/dq/comp_nodes",
        "//ydb/core/kqp/compute_actor",
        "//ydb/core/kqp/query_compiler",
        "//ydb/core/kqp/rm_service",
        "//ydb/core/kqp/topics",
        "//ydb/core/kqp/executer_actor",
        "//ydb/core/kqp/gateway/behaviour/resource_pool_classifier",
        "//ydb/core/kqp/gateway/behaviour/streaming_query",
        "//ydb/core/tx/columnshard/hooks/abstract",
        "//ydb/core/tx/columnshard/engines/scheme/abstract",
        "//ydb/core/tx/columnshard/engines/scheme/column",
        "//ydb/core/tx/columnshard/engines/scheme/tiering",
        "//ydb/core/tx/columnshard/engines/scheme/versions",
        "//ydb/core/tx/columnshard/engines/scheme",
        "//ydb/core/tx/columnshard/splitter",
        "//ydb/core/tx/columnshard/engines/portions",
        "//ydb/core/tx/tiering",
        "//ydb/core/tx/columnshard/blobs_action",
        "//ydb/core/tx/columnshard/engines/changes/counters",
        "//ydb/core/tx/columnshard/engines/changes/abstract",
        "//ydb/core/tx/columnshard/engines/storage/optimizer/abstract",
        "//ydb/core/kqp/gateway",
        "//ydb/core/kqp/node_service",
        "//ydb/core/kqp/run_script_actor",
        "//ydb/core/kqp/workload_service",
        "//ydb/core/kqp/proxy_service",
        "//ydb/core/kqp/session_actor",
        "//ydb/core/kqp/finalize_script_service",
        "//ydb/core/tx/columnshard/data_sharing/common/context",
        "//ydb/core/tx/columnshard/data_sharing/common/session",
        "//ydb/core/tx/columnshard/tablet",
        "//ydb/core/tx/columnshard/data_sharing/destination/transactions",
        "//ydb/core/tx/columnshard/data_sharing/destination/session",
        "//ydb/core/tx/columnshard/data_sharing/destination/events",
        "//ydb/core/tx/columnshard/data_sharing/source/transactions",
        "//ydb/core/tx/columnshard/data_sharing/source/session",
        "//ydb/core/tx/columnshard/data_sharing/manager",
        "//ydb/core/tx/columnshard/blobs_reader",
        "//ydb/core/tx/columnshard/resource_subscriber",
        "//ydb/core/tx/general_cache/service",
        "//ydb/core/tx/general_cache/source",
        "//ydb/core/tx/general_cache/usage",
        "//ydb/core/tx/columnshard/column_fetching",
        "//ydb/core/tx/columnshard/counters",
        "//ydb/core/tx/columnshard/data_accessor",
        "//ydb/core/tx/columnshard/engines/storage/actualizer/abstract",
        "//ydb/core/tx/columnshard/engines/storage/actualizer/common",
        "//ydb/core/tx/columnshard/engines/storage/actualizer/counters",
        "//ydb/core/tx/columnshard/engines/storage/actualizer/scheme",
        "//ydb/core/tx/columnshard/engines/storage/indexes/bits_storage",
        "//ydb/core/tx/columnshard/engines/storage/indexes/portions",
        "//ydb/core/tx/columnshard/engines/storage/indexes/count_min_sketch",
        "//ydb/core/tx/columnshard/engines/storage/indexes/max",
        "//ydb/core/tx/columnshard/engines/storage/indexes/skip_index",
        "//ydb/core/tx/columnshard/data_locks/locks",
        "//ydb/core/tx/columnshard/data_locks/manager",
        "//ydb/core/tx/columnshard/data_sharing/modification/events",
        "//ydb/core/tx/columnshard/data_sharing/modification/tasks",
        "//ydb/core/tx/columnshard/data_sharing/modification/transactions",
        "//ydb/core/tx/columnshard/data_sharing/source/events",
        "//ydb/core/tx/columnshard/diagnostics",
        "//ydb/core/tx/columnshard/engines/changes/actualization/controller",
        "//ydb/core/tx/columnshard/engines/changes/compaction",
        "//ydb/core/tx/columnshard/engines/changes",
        "//ydb/core/tx/columnshard/tx_reader",
        "//ydb/core/tx/columnshard/engines/predicate",
        "//ydb/core/tx/conveyor/usage",
        "//ydb/core/tx/program",
        "//ydb/core/tx/columnshard/engines/reader/abstract",
        "//ydb/core/tx/columnshard/engines/reader/actor",
        "//ydb/core/tx/columnshard/engines/reader/common",
        "//ydb/core/tx/columnshard/engines/reader/common_reader/constructor",
        "//ydb/core/tx/columnshard/engines/reader/common_reader/iterator",
        "//ydb/core/tx/columnshard/engines/reader/plain_reader/constructor",
        "//ydb/core/tx/limiter/grouped_memory/service",
        "//ydb/core/tx/limiter/grouped_memory/usage",
        "//ydb/core/tx/columnshard/engines/reader/plain_reader/iterator",
        "//ydb/core/tx/columnshard/engines/reader/simple_reader/constructor",
        "//ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates",
        "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/abstract",
        "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator",
        "//ydb/core/tx/columnshard/engines/reader/transaction",
        "//ydb/core/tx/columnshard/resources",
        "//ydb/core/tx/columnshard/engines",
        "//ydb/core/tx/columnshard/engines/writer",
        "//ydb/core/tx/columnshard/loading",
        "//ydb/core/tx/columnshard/normalizer/abstract",
        "//ydb/core/tx/columnshard/data_reader",
        "//ydb/core/tx/columnshard/operations",
        "//ydb/core/tx/columnshard/overload_manager",
        "//ydb/core/tx/columnshard/subscriber/events/tables_erased",
        "//ydb/core/tx/columnshard/transactions/operators/ev_write",
        "//ydb/core/tx/conveyor_composite/usage",
        "//ydb/core/tx/conveyor_composite/service",
        "//ydb/core/tx/priorities/usage",
        "//ydb/core/tx/priorities/service",
        "//ydb/core/tx/time_cast",
        "//ydb/core/tx/columnshard",
        "//ydb/library/workload/kv",
        "//ydb/services/kesus",
        "//ydb/services/persqueue_cluster_discovery",
        "//ydb/core/load_test",
        "//ydb/core/pgproxy",
        "//ydb/core/local_pgwire",
        "//ydb/core/log_backend",
        "//ydb/core/memory_controller",
        "//ydb/core/public_http",
        "//ydb/core/quoter",
        "//ydb/core/transfer",
        "//ydb/core/tx/conveyor/service",
        "//ydb/core/tx/coordinator",
        "//ydb/core/tx/long_tx_service",
        "//ydb/core/tx/mediator",
        "//ydb/core/tx/sequenceshard",
        "//ydb/services/lib/auth",
        "//ydb/core/viewer",
        "//ydb/core/ymq/http",
        "//ydb/library/slide_limiter/usage",
        "//ydb/library/slide_limiter/service",
        "//ydb/services/auth",
        "//ydb/services/backup",
        "//ydb/services/bridge",
        "//ydb/services/cms",
        "//ydb/services/config",
        "//ydb/services/deprecated/persqueue_v0",
        "//ydb/services/discovery",
        "//ydb/services/dynamic_config",
        "//ydb/services/ext_index/metadata",
        "//ydb/services/ext_index/service",
        "//ydb/services/fq",
        "//ydb/services/keyvalue",
        "//ydb/services/local_discovery",
        "//ydb/services/maintenance",
        "//ydb/services/metadata/common",
        "//ydb/services/metadata/ds_table",
        "//ydb/services/monitoring",
        "//ydb/services/rate_limiter",
        "//ydb/services/replication",
        "//ydb/core/grpc_services/tablet",
        "//ydb/services/tablet",
        "//ydb/services/test_shard",
        "//ydb/services/view",
        "//ydb/core/driver_lib/run",
        "//ydb/core/base/generated",
        "//ydb/core/control/lib/generated",
        "//ydb/apps/ydbd",
    ]
}
