group("all") {
    deps = [
        "//ydb/apps/ydb",
        "//ydb/apps/ydbd",
    ]
}

group("tests") {
    testonly = true
    deps = [
        "//util/charset/ut",
        "//util/datetime/ut",
        "//util/digest/ut",
        "//util/draft/ut",
        "//util/folder/ut",
        "//util/generic/ut",
        "//util/memory/ut",
        "//util/network/ut",
        "//util/random/ut",
        "//util/stream/ut",
        "//util/string/ut",
        "//util/system/ut",
        "//util/thread/ut",
        "//util/ut",
    ]
}
