library("arrow") {
    public_deps = [
        "//contrib/libs/apache/arrow",
    ]

    deps = [
        ":arrow_type",
        ":common",
        ":serializer",
        "//ydb/core/kqp/common:arrow",
        "//ydb/core/scheme",
        "//ydb/library/conclusion",
        "//ydb/library/formats/arrow",
        "//yql/essentials/types:binary_json",
        "//yql/essentials/types:dynumber",
    ]

    sources = [
        "arrow_batch_builder.cpp",
        "arrow_filter.cpp",
        "arrow_helpers_minikql.cpp",
        "arrow_helpers.cpp",
        "converter.cpp",
        "converter.h",
        "permutations.cpp",
        "process_columns.cpp",
        "size_calcer.cpp",
        "special_keys.cpp",
    ]
}

library("arrow_type") {
    public_deps = [
        "//contrib/libs/apache/arrow",
    ]

    deps = [
        "//ydb/core/scheme",
        "//ydb/core/scheme_types",
        "//ydb/library/formats/arrow",
        "//yql/essentials/parser/pg_wrapper",
    ]

    sources = [
        "arrow_type.cpp",
    ]
}

source_set("common") {
    public_deps = [ "accessor:abstract" ]

    sources = [
        "common/adapter.cpp",
        "common/container.cpp",
    ]
}

library("serializer") {
    deps = [
        "//contrib/libs/apache/arrow",
        "//ydb/core/protos",
        "//ydb/library/formats/arrow",
        "//ydb/services/bg_tasks:abstract",
        "//ydb/services/metadata:abstract",
    ]

    sources = [
        "serializer/abstract.cpp",
        "serializer/native.cpp",
        "serializer/parsing.cpp",
        "serializer/stream.cpp",
        "serializer/utils.cpp",
    ]
}
