library("actor") {
  public_deps = [
    # "//ydb/core/formats/arrow",
    # "//ydb/core/kqp/compute_actor",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/blobs_action:abstract",
    # "//ydb/core/tx/columnshard/column_fetching",
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/engines/reader/abstract",
    # "//ydb/core/tx/conveyor_composite/usage",
    # "//ydb/core/tx/tracing/usage",
    # "//ydb/library/actors/core",
    # "//ydb/library/chunks_limiter",
  ]

  deps = [
    # "//ydb/core/formats/arrow:reader",
    # "//ydb/core/tx/columnshard/blobs_reader",
    # "//ydb/core/tx/columnshard/engines/reader/tracing",
    # "//ydb/core/tx/columnshard/resource_subscriber",
    # "//yql/essentials/core/issue",
  ]

  sources = [ "actor.cpp" ]
}
