library("abstract") {
  public_deps = [
    # "//contrib/libs/apache/arrow",
    # "//library/cpp/json:writer",
    # "//ydb/core/formats/arrow/accessor/common",
    # "//ydb/library/accessor",
    # "//ydb/library/formats/arrow:protos",
    # "//ydb/library/formats/arrow:splitter",
    # "//ydb/services/bg_tasks/abstract",
    # "//ydb/services/metadata/abstract",
  ]

  deps = [
    # "//ydb/core/formats/arrow",
    # "//ydb/core/formats/arrow/accessor/plain",
    # "//ydb/core/scheme_types",
    # "//ydb/library/actors/core",
    # "//ydb/library/formats/arrow",
    # "//ydb/library/formats/arrow:switch",
  ]

  sources = [
    "accessor.cpp",
    "common.cpp",
    "constructor.cpp",
    "request.cpp",
  ]

  serialize_enum_headers = [ "accessor.h" ]
}
