library("tracing") {
  public_deps = [
    "//ydb/library/actors/core",
  ]

  deps = [
    "//library/cpp/monlib/dynamic_counters",
    "//ydb/core/base",
    "//ydb/core/mon",
    "//ydb/core/node_whiteboard",
    "//ydb/core/protos",
    "//ydb/library/actors/interconnect",
  ]

  sources = [
    "http.cpp",
    "tablet_info.cpp",
    "trace.cpp",
    "trace_collection.cpp",
  ]
}
