unittest_executable("ut") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/mind",  # peerdir only
    "//ydb/core/testlib",
    "//ydb/core/testlib/basics",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx",
    "//ydb/core/tx/tx_allocator",
    "//ydb/core/tx/tx_allocator_client",
  ]

  sources = [
    "//ydb/core/tx/tx_allocator_client/actor_client_ut.cpp",
    "//ydb/core/tx/tx_allocator_client/ut_helpers.cpp",
  ]

  include_dirs = [ "//ydb/core/tx/tx_allocator_client" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
