library("tiering") {
  public_deps = [
    # "//contrib/libs/apache/arrow",
    # "//ydb/core/base",
    "//ydb/core/formats/arrow",
    # "//ydb/core/formats/arrow:serializer",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/tiering:tier",
    # "//ydb/library/formats/arrow:validation",
  ]

  deps = [
    # "//ydb/core/tx/columnshard/blobs_action:abstract",
    "//ydb/library/actors/util",
  ]

  sources = [
    "common.cpp",
    "tier_info.cpp",
  ]
}
