library("fast_path_service") {
  public_deps = [
    # "//ydb/core/mind/bscontroller:group_mapper",
    # "//ydb/core/mon",
    "//ydb/core/nbs/cloud/blockstore/config",
    "//ydb/core/nbs/cloud/blockstore/libs/diagnostics",
    # "//ydb/core/nbs/cloud/blockstore/libs/service",
    "//ydb/core/nbs/cloud/blockstore/libs/storage/direct_block_group",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/blobstorage/ddisk",  # peerdir only
    # "//ydb/core/mind/bscontroller",  # peerdir only
    "//ydb/core/nbs/cloud/storage/core/protos",
  ]

  sources = [ "fast_path_service.cpp" ]
}
