library("inference") {
  public_deps = [ "//ydb/library/actors/core" ]

  deps = [
    ":object_storage",
    "//contrib/libs/apache/arrow",
    "//ydb/library/yql/providers/s3/compressors",
    "//ydb/library/yql/udfs/common/clickhouse/client", # ADDINCL
    # "//ydb/public/api/protos",
  ]

  sources = [
    "inference/arrow_fetcher.cpp",
    "inference/arrow_inferencinator.cpp",
    "inference/infer_config.cpp",
  ]
}

library("object_storage") {
  public_deps = [
    # ":inference",
    "//contrib/libs/apache/arrow",
    # "//contrib/libs/curl",
    # "//ydb/core/fq/libs/config:protos",
    "//ydb/library/actors/core",
    "//ydb/library/yql/providers/common/http_gateway",
    "//ydb/library/yql/providers/s3/common",
    "//ydb/library/yql/providers/s3/credentials",
    # "//ydb/public/api/protos",
    "//ydb/public/sdk/cpp/adapters/issue",
    "//ydb/public/sdk/cpp/src/client/types/status",
  ]

  sources = [ "s3_fetcher.cpp" ]
}
