unittest_executable("ut") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/persqueue",
    "//ydb/core/persqueue/ut/common",  # peerdir only
    "//ydb/core/persqueue/ut/common:pq_ut_common",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/persqueue_public/ut/ut_utils",  # peerdir only
  ]

  sources = [ "caching_proxy_ut.cpp" ]

  include_dirs = [ "//ydb/core/persqueue" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
