unittest_executable("ut_cluster_balancing") {
  deps = [
    "//library/cpp/iterator",
    "//ydb/core/blobstorage/ut_blobstorage/lib",
    "//ydb/core/util",
  ]

  sources = [ "//ydb/core/blobstorage/ut_blobstorage/cluster_balancing.cpp" ]

  include_dirs = [ "//ydb/core/blobstorage/ut_blobstorage" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
