library("constructor") {
  public_deps = [
    ":level",
    ":selector",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/abstract",
  ]

  deps = [
    # "//contrib/libs/apache/arrow",  # peerdir only
    # "//ydb/core/formats/arrow",  # peerdir only
    # "//ydb/core/protos",  # peerdir only
    # "//ydb/core/tx/columnshard/engines/changes/abstract",  # peerdir only
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner:level",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner:selector",
  ]

  sources = [ "constructor.cpp" ]
}

library("level") {
  public_deps = [
    # "//library/cpp/json",
    # "//ydb/core/protos",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner:level",
    # "//ydb/services/bg_tasks:abstract",
  ]

  deps = [
    # "//contrib/libs/apache/arrow",  # peerdir only
    # "//ydb/core/formats/arrow",  # peerdir only
    # "//ydb/core/tx/columnshard/engines/changes/abstract",  # peerdir only
  ]

  sources = [
    "level/constructor.cpp",
    "level/one_layer.cpp",
    "level/zero_level.cpp",
  ]
}

library("selector") {
  public_deps = [
    # "//library/cpp/json",
    # "//ydb/core/protos",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner:selector",
    # "//ydb/services/bg_tasks:abstract",
  ]

  deps = [
    # "//contrib/libs/apache/arrow",  # peerdir only
    # "//ydb/core/formats/arrow",  # peerdir only
    # "//ydb/core/tx/columnshard/engines/changes/abstract",  # peerdir only
  ]

  sources = [
    "selector/constructor.cpp",
    "selector/empty.cpp",
    "selector/snapshot.cpp",
    "selector/transparent.cpp",
  ]
}
