library("ttl") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/core/tx/schemeshard/olap/columns",
    # "//ydb/core/tx/schemeshard/olap/indexes",
    # "//ydb/library/conclusion",
  ]

  deps = [
    # "//ydb/core/base",  # peerdir only
    # "//ydb/core/tx/tiering:tier",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/params",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/types/credentials",  # peerdir only
  ]

  sources = [
    "schema.cpp",
    "update.cpp",
  ]
}
