protobuf_library("protos") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/core/tx/columnshard/blobs_action:protos",
    "//ydb/core/tx/columnshard/common:protos",
    "//ydb/core/tx/columnshard/engines/protos",
  ]

  sources = [
    "data.proto",
    "events.proto",
    "initiator.proto",
    "links.proto",
    "sessions.proto",
  ]
}
