import("//contrib/libs/llvm16/llvm.gni")

llvm_library("Reader") {
    deps = [
        "//contrib/libs/llvm16/lib/Bitstream/Reader",
        "//contrib/libs/llvm16/lib/IR",
        "//contrib/libs/llvm16/lib/TargetParser",
    ]

    sources = [
        "Reader/BitcodeAnalyzer.cpp",
        "Reader/BitcodeReader.cpp",
        "Reader/BitReader.cpp",
        "Reader/MetadataLoader.cpp",
        "Reader/ValueList.cpp",
    ]
}

llvm_library("Writer") {
    deps = [
        "//contrib/libs/llvm16/lib/Analysis",
        "//contrib/libs/llvm16/lib/IR",
        "//contrib/libs/llvm16/lib/MC",
        "//contrib/libs/llvm16/lib/Object",
        "//contrib/libs/llvm16/lib/TargetParser",
    ]

    sources = [
        "Writer/BitcodeWriter.cpp",
        "Writer/BitcodeWriterPass.cpp",
        "Writer/BitWriter.cpp",
        "Writer/ValueEnumerator.cpp",
    ]
}
