library("predicate") {
  public_deps = [
    # "//contrib/libs/apache/arrow",
    "//ydb/core/formats/arrow",
    # "//ydb/core/protos",
    # "//ydb/core/scheme",
    "//ydb/core/tx/columnshard/engines/portions",
    "//ydb/core/tx/columnshard/engines/scheme",
    # "//ydb/library/accessor",
    # "//ydb/library/arrow_kernels",
    # "//ydb/library/conclusion",
    # "//ydb/library/formats/arrow",
  ]

  deps = [
    # "//ydb/core/formats/arrow/program",
    # "//ydb/library/actors/core",
    # "//ydb/library/formats/arrow:switch",
  ]

  sources = [
    "container.cpp",
    "filter.cpp",
    "predicate.cpp",
    "range.cpp",
  ]
}
