library("predicate") {
  public_deps = [
    # "//contrib/libs/apache/arrow",
    # "//ydb/core/formats/arrow",
    # "//ydb/core/formats/arrow/accessor/abstract",
    # "//ydb/core/formats/arrow:common",
    # "//ydb/core/formats/arrow:reader",
    # "//ydb/core/formats/arrow:rows",
    # "//ydb/core/protos",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/scheme",
    # "//ydb/library/accessor",
    # "//ydb/library/conclusion",
    # "//ydb/library/formats/arrow",
  ]

  deps = [
    # "//ydb/core/formats/arrow:program",
    # "//ydb/core/formats/arrow:serializer",
    # "//ydb/core/scheme",
    # "//ydb/library/actors/core",
    # "//ydb/library/arrow_kernels",
    # "//ydb/library/formats/arrow:switch",
  ]

  sources = [
    "container.cpp",
    "filter.cpp",
    "predicate.cpp",
    "range.cpp",
  ]
}
