library("result_format") {
  public_deps = [
    # "//library/cpp/yson",
  ]

  deps = [
    # "//library/cpp/string_utils/base64",
    # "//library/cpp/yson:node",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/utils",
  ]

  sources = [
    "yql_codec_results.cpp",
    "yql_restricted_yson.cpp",
    "yql_result_format_data.cpp",
    "yql_result_format_response.cpp",
    "yql_result_format_type.cpp",
  ]
}
