library("buffer") {
  public_deps = [
    # "//ydb/core/formats/arrow",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/engines/writer",
    # "//ydb/core/tx/columnshard/operations",
    # "//ydb/core/tx/columnshard/operations:common",
    # "//ydb/core/tx/columnshard/operations:slice_builder",
    # "//ydb/core/tx/data_events",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/testlib/common",
  ]

  deps = [
    # "//ydb/core/tx/conveyor/usage",
    # "//ydb/core/tx/conveyor_composite/usage",
  ]

  sources = [
    "buffer/actor2.cpp",
    "buffer/events.cpp",
  ]
}

library("writer") {
  public_deps = [
    # "//ydb/core/formats/arrow",
    "//ydb/core/protos",
    # "//ydb/core/tx/columnshard",
    "//ydb/core/tx/columnshard/blobs_action:abstract",
    "//ydb/core/tx/columnshard/blobs_action:counters",
    "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/data_events",
    # "//ydb/library/actors/core",
    # "//ydb/library/signals",
  ]

  deps = [
    "//ydb/core/tx/columnshard/engines/changes/abstract",
    # "//ydb/core/tx/columnshard/hooks/abstract",
    # "//ydb/library/accessor",
  ]

  sources = [
    "blob_constructor.cpp",
    "compacted_blob_constructor.cpp",
    "indexed_blob_constructor.cpp",
    "put_status.cpp",
    "write_controller.cpp",
  ]
}
