# group("common") {
#   public_deps = [
#     "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/iam/common",
#     "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/iam_private/common",
#   ]
# }

library("iam_private") {
  public_deps = [
    "//contrib/libs/grpc",
    # "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/iam/common",
    # "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/iam_private/common",
  ]

  deps = [
    "//library/cpp/threading/future",
    "//ydb/public/api/client/yc_private/iam",
    "//ydb/public/sdk/cpp/src/client/types/credentials",
    "//ydb/public/sdk/cpp/src/library/jwt",
    # ":common",
  ]

  sources = [ "iam.cpp" ]
}
