import("//build/gn/contrib.gni")

contrib_tool("config_proto_plugin") {
    deps = [
        "//contrib/libs/protoc",
        "//library/cpp/protobuf/json",
        "//ydb/core/config:protos",
        "//ydb/core/config:utils",
        "//ydb/public/lib/protobuf",
    ]
    sources = [ "main.cpp" ]
}
