import("//contrib/libs/llvm16/llvm.gni")

llvm_library("CodeView") {
    sources = [
        "CodeView/AppendingTypeTableBuilder.cpp",
        "CodeView/CodeViewError.cpp",
        "CodeView/CodeViewRecordIO.cpp",
        "CodeView/ContinuationRecordBuilder.cpp",
        "CodeView/CVSymbolVisitor.cpp",
        "CodeView/CVTypeVisitor.cpp",
        "CodeView/DebugChecksumsSubsection.cpp",
        "CodeView/DebugCrossExSubsection.cpp",
        "CodeView/DebugCrossImpSubsection.cpp",
        "CodeView/DebugFrameDataSubsection.cpp",
        "CodeView/DebugInlineeLinesSubsection.cpp",
        "CodeView/DebugLinesSubsection.cpp",
        "CodeView/DebugStringTableSubsection.cpp",
        "CodeView/DebugSubsection.cpp",
        "CodeView/DebugSubsectionRecord.cpp",
        "CodeView/DebugSubsectionVisitor.cpp",
        "CodeView/DebugSymbolRVASubsection.cpp",
        "CodeView/DebugSymbolsSubsection.cpp",
        "CodeView/EnumTables.cpp",
        "CodeView/Formatters.cpp",
        "CodeView/GlobalTypeTableBuilder.cpp",
        "CodeView/LazyRandomTypeCollection.cpp",
        "CodeView/Line.cpp",
        "CodeView/MergingTypeTableBuilder.cpp",
        "CodeView/RecordName.cpp",
        "CodeView/RecordSerialization.cpp",
        "CodeView/SimpleTypeSerializer.cpp",
        "CodeView/StringsAndChecksums.cpp",
        "CodeView/SymbolDumper.cpp",
        "CodeView/SymbolRecordHelpers.cpp",
        "CodeView/SymbolRecordMapping.cpp",
        "CodeView/SymbolSerializer.cpp",
        "CodeView/TypeDumpVisitor.cpp",
        "CodeView/TypeHashing.cpp",
        "CodeView/TypeIndex.cpp",
        "CodeView/TypeIndexDiscovery.cpp",
        "CodeView/TypeRecordHelpers.cpp",
        "CodeView/TypeRecordMapping.cpp",
        "CodeView/TypeStreamMerger.cpp",
        "CodeView/TypeTableCollection.cpp",
    ]
}

llvm_library("DWARF") {
    deps = [
        "//contrib/libs/llvm16/lib/BinaryFormat",
        "//contrib/libs/llvm16/lib/Object",
        "//contrib/libs/llvm16/lib/TargetParser",
    ]

    sources = [
        "DWARF/DWARFAbbreviationDeclaration.cpp",
        "DWARF/DWARFAcceleratorTable.cpp",
        "DWARF/DWARFAddressRange.cpp",
        "DWARF/DWARFCompileUnit.cpp",
        "DWARF/DWARFContext.cpp",
        "DWARF/DWARFDataExtractor.cpp",
        "DWARF/DWARFDebugAbbrev.cpp",
        "DWARF/DWARFDebugAddr.cpp",
        "DWARF/DWARFDebugAranges.cpp",
        "DWARF/DWARFDebugArangeSet.cpp",
        "DWARF/DWARFDebugFrame.cpp",
        "DWARF/DWARFDebugInfoEntry.cpp",
        "DWARF/DWARFDebugLine.cpp",
        "DWARF/DWARFDebugLoc.cpp",
        "DWARF/DWARFDebugMacro.cpp",
        "DWARF/DWARFDebugPubTable.cpp",
        "DWARF/DWARFDebugRangeList.cpp",
        "DWARF/DWARFDebugRnglists.cpp",
        "DWARF/DWARFDie.cpp",
        "DWARF/DWARFExpression.cpp",
        "DWARF/DWARFFormValue.cpp",
        "DWARF/DWARFGdbIndex.cpp",
        "DWARF/DWARFListTable.cpp",
        "DWARF/DWARFLocationExpression.cpp",
        "DWARF/DWARFTypePrinter.cpp",
        "DWARF/DWARFTypeUnit.cpp",
        "DWARF/DWARFUnit.cpp",
        "DWARF/DWARFUnitIndex.cpp",
        "DWARF/DWARFVerifier.cpp",
    ]
}

llvm_library("MSF") {
    sources = [
        "MSF/MappedBlockStream.cpp",
        "MSF/MSFBuilder.cpp",
        "MSF/MSFCommon.cpp",
        "MSF/MSFError.cpp",
    ]
}

llvm_library("PDB") {
    deps = [
        ":CodeView",
        ":MSF",
        "//contrib/libs/llvm16/lib/BinaryFormat",
        "//contrib/libs/llvm16/lib/Object",
    ]

    sources = [
        "PDB/GenericError.cpp",
        "PDB/IPDBSourceFile.cpp",
        "PDB/Native/DbiModuleDescriptor.cpp",
        "PDB/Native/DbiModuleDescriptorBuilder.cpp",
        "PDB/Native/DbiModuleList.cpp",
        "PDB/Native/DbiStream.cpp",
        "PDB/Native/DbiStreamBuilder.cpp",
        "PDB/Native/EnumTables.cpp",
        "PDB/Native/FormatUtil.cpp",
        "PDB/Native/GlobalsStream.cpp",
        "PDB/Native/GSIStreamBuilder.cpp",
        "PDB/Native/Hash.cpp",
        "PDB/Native/HashTable.cpp",
        "PDB/Native/InfoStream.cpp",
        "PDB/Native/InfoStreamBuilder.cpp",
        "PDB/Native/InjectedSourceStream.cpp",
        "PDB/Native/InputFile.cpp",
        "PDB/Native/LinePrinter.cpp",
        "PDB/Native/ModuleDebugStream.cpp",
        "PDB/Native/NamedStreamMap.cpp",
        "PDB/Native/NativeCompilandSymbol.cpp",
        "PDB/Native/NativeEnumGlobals.cpp",
        "PDB/Native/NativeEnumInjectedSources.cpp",
        "PDB/Native/NativeEnumLineNumbers.cpp",
        "PDB/Native/NativeEnumModules.cpp",
        "PDB/Native/NativeEnumSymbols.cpp",
        "PDB/Native/NativeEnumTypes.cpp",
        "PDB/Native/NativeExeSymbol.cpp",
        "PDB/Native/NativeFunctionSymbol.cpp",
        "PDB/Native/NativeInlineSiteSymbol.cpp",
        "PDB/Native/NativeLineNumber.cpp",
        "PDB/Native/NativePublicSymbol.cpp",
        "PDB/Native/NativeRawSymbol.cpp",
        "PDB/Native/NativeSession.cpp",
        "PDB/Native/NativeSourceFile.cpp",
        "PDB/Native/NativeSymbolEnumerator.cpp",
        "PDB/Native/NativeTypeArray.cpp",
        "PDB/Native/NativeTypeBuiltin.cpp",
        "PDB/Native/NativeTypeEnum.cpp",
        "PDB/Native/NativeTypeFunctionSig.cpp",
        "PDB/Native/NativeTypePointer.cpp",
        "PDB/Native/NativeTypeTypedef.cpp",
        "PDB/Native/NativeTypeUDT.cpp",
        "PDB/Native/NativeTypeVTShape.cpp",
        "PDB/Native/PDBFile.cpp",
        "PDB/Native/PDBFileBuilder.cpp",
        "PDB/Native/PDBStringTable.cpp",
        "PDB/Native/PDBStringTableBuilder.cpp",
        "PDB/Native/PublicsStream.cpp",
        "PDB/Native/RawError.cpp",
        "PDB/Native/SymbolCache.cpp",
        "PDB/Native/SymbolStream.cpp",
        "PDB/Native/TpiHashing.cpp",
        "PDB/Native/TpiStream.cpp",
        "PDB/Native/TpiStreamBuilder.cpp",
        "PDB/PDB.cpp",
        "PDB/PDBContext.cpp",
        "PDB/PDBExtras.cpp",
        "PDB/PDBInterfaceAnchors.cpp",
        "PDB/PDBSymbol.cpp",
        "PDB/PDBSymbolAnnotation.cpp",
        "PDB/PDBSymbolBlock.cpp",
        "PDB/PDBSymbolCompiland.cpp",
        "PDB/PDBSymbolCompilandDetails.cpp",
        "PDB/PDBSymbolCompilandEnv.cpp",
        "PDB/PDBSymbolCustom.cpp",
        "PDB/PDBSymbolData.cpp",
        "PDB/PDBSymbolExe.cpp",
        "PDB/PDBSymbolFunc.cpp",
        "PDB/PDBSymbolFuncDebugEnd.cpp",
        "PDB/PDBSymbolFuncDebugStart.cpp",
        "PDB/PDBSymbolLabel.cpp",
        "PDB/PDBSymbolPublicSymbol.cpp",
        "PDB/PDBSymbolThunk.cpp",
        "PDB/PDBSymbolTypeArray.cpp",
        "PDB/PDBSymbolTypeBaseClass.cpp",
        "PDB/PDBSymbolTypeBuiltin.cpp",
        "PDB/PDBSymbolTypeCustom.cpp",
        "PDB/PDBSymbolTypeDimension.cpp",
        "PDB/PDBSymbolTypeEnum.cpp",
        "PDB/PDBSymbolTypeFriend.cpp",
        "PDB/PDBSymbolTypeFunctionArg.cpp",
        "PDB/PDBSymbolTypeFunctionSig.cpp",
        "PDB/PDBSymbolTypeManaged.cpp",
        "PDB/PDBSymbolTypePointer.cpp",
        "PDB/PDBSymbolTypeTypedef.cpp",
        "PDB/PDBSymbolTypeUDT.cpp",
        "PDB/PDBSymbolTypeVTable.cpp",
        "PDB/PDBSymbolTypeVTableShape.cpp",
        "PDB/PDBSymbolUnknown.cpp",
        "PDB/PDBSymbolUsingNamespace.cpp",
        "PDB/PDBSymDumper.cpp",
        "PDB/UDTLayout.cpp",
    ]
}

llvm_library("Symbolize") {
    deps = [
        ":DWARF",
        ":PDB",
        "//contrib/libs/llvm16/lib/Demangle",
        "//contrib/libs/llvm16/lib/Object",
        "//contrib/libs/llvm16/lib/TargetParser",
    ]

    sources = [
        "Symbolize/DIPrinter.cpp",
        "Symbolize/Markup.cpp",
        "Symbolize/MarkupFilter.cpp",
        "Symbolize/SymbolizableObjectFile.cpp",
        "Symbolize/Symbolize.cpp",
    ]
}
