unittest_executable("cost") {
  deps = [
    "//library/cpp/json",
    "//ydb/core/kqp",  # peerdir only
    "//ydb/core/kqp/counters",
    "//ydb/core/kqp/executer_actor",
    "//ydb/core/kqp/ut/common",
    "//ydb/core/tx/schemeshard",
    "//ydb/core/tx/tx_proxy:public",
    "//ydb/public/sdk/cpp/src/client/proto",
    "//yql/essentials/sql/pg_dummy",  # peerdir only
  ]

  sources = [ "kqp_cost_ut.cpp" ]

  include_dirs = [
    "//ydb/core/kqp",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
