library("issue") {
  public_deps = [
    "//yql/essentials/core/issue/protos",
    "//yql/essentials/public/issue",
  ]

  deps = [
    # "//contrib/libs/protobuf",  # peerdir only
    # "//library/cpp/resource",  # peerdir only
  ]

  sources = [ "yql_issue.cpp" ]

  resources = [
    {
      path = "yql_issue.txt"
      key = "yql_issue.txt"
    },
  ]
}
