library("v1") {
  public_deps = [
    "lexer",
    # "//library/cpp/enumbitset",
    "//yql/essentials/ast",
    # "//yql/essentials/parser/lexer_common",
    # "//yql/essentials/parser/proto_ast",
    "//yql/essentials/public/issue",
    # "//yql/essentials/public/udf",
    "//yql/essentials/sql/v1/proto_parser",
    "//yql/essentials/sql:settings",
    # "//yql/essentials/utils",
  ]

  deps = [
    "//library/cpp/charset",
    # "//library/cpp/containers/sorted_vector",
    # "//library/cpp/containers/stack_vector",
    # "//library/cpp/protobuf/util",
    # "//library/cpp/yson:node",
    # "//yql/essentials/core/issue:protos",
    "//yql/essentials/core/sql_types",
    "//yql/essentials/minikql",
    "//yql/essentials/parser/pg_catalog",
    # "//yql/essentials/parser/proto_ast/collect_issues",
    # "//yql/essentials/providers/common/provider",
    "//yql/essentials/parser/proto_ast/gen/v1_antlr4",
    "//yql/essentials/public/langver",
    "//yql/essentials/sql",
  ]

  sources = [
    "aggregation.cpp",
    "builtin.cpp",
    "context.cpp",
    "insert.cpp",
    "join.cpp",
    "list_builtin.cpp",
    "match_recognize.cpp",
    "node.cpp",
    "object_processing.cpp",
    "query.cpp",
    "result.cpp",
    "secret_settings.cpp",
    "select.cpp",
    "select_yql.cpp",
    "select_yql_aggregation.cpp",
    "source.cpp",
    "sql.cpp",
    "sql_call_expr.cpp",
    "sql_expression.cpp",
    "sql_group_by.cpp",
    "sql_into_tables.cpp",
    "sql_match_recognize.cpp",
    "sql_query.cpp",
    "sql_select.cpp",
    "sql_select_yql.cpp",
    "sql_translation.cpp",
    "sql_values.cpp",
  ]

  serialize_enum_headers = [
    "match_recognize.h",
    "node.h",
    "sql_call_param.h",
  ]
}
