library("impl") {
  public_deps = [
    # "//library/cpp/threading/future",
    # "//yql/essentials/core/file_storage",
    # "//yt/yql/providers/yt/fmr/job_preparer/interface",
  ]

  deps = [
    # "//library/cpp/random_provider",
    "//yql/essentials/core/file_storage/proto",
    # "//yql/essentials/utils",
    # "//yql/essentials/utils/log",
    # "//yt/yql/providers/yt/fmr/job/impl",
    # "//yt/yql/providers/yt/fmr/request_options",
    # "//yt/yql/providers/yt/fmr/table_data_service/client/impl",
    # "//yt/yql/providers/yt/fmr/table_data_service/discovery/file",
    # "//yt/yql/providers/yt/fmr/utils",
    # "//yt/yql/providers/yt/fmr/yt_job_service/impl",
  ]

  sources = [ "yql_yt_job_preparer_impl.cpp" ]
}
