library("granule") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/formats/arrow:reader",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/blobs_action:abstract",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/data_accessor",
    # "//ydb/core/tx/columnshard/data_accessor:abstract",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/storage/actualizer/index",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/abstract",
    # "//ydb/core/tx/columnshard/hooks/abstract",
    # "//ydb/core/tx/columnshard/tx_reader",
  ]

  deps = [
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx/columnshard/data_accessor:in_mem",
    # "//ydb/core/tx/columnshard/data_accessor:local_db",
    # "//ydb/core/tx/columnshard/data_locks/manager",
    # "//ydb/core/tx/columnshard/engines/changes/actualization/construction",
    # "//ydb/library/actors/core",
    # "//ydb/library/range_treap",
  ]

  sources = [
    "granule.cpp",
    "portion_interval_tree.cpp",
    "portions_index.cpp",
    "stages.cpp",
    "storage.cpp",
  ]

  serialize_enum_headers = [ "granule.h" ]
}
