unittest_executable("ut") {
  deps = [
    "//contrib/libs/protobuf",
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/json",
    "//library/cpp/malloc/api",
    "//library/cpp/protobuf/json",
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//library/cpp/threading/future",
    "//ydb/core/base",
    "//ydb/core/blobstorage/crypto",
    "//ydb/core/blobstorage/events",
    "//ydb/core/blobstorage/nodewarden",
    "//ydb/core/blobstorage/pdisk",
    "//ydb/core/cms",
    "//ydb/core/grpc_services/local_rpc",
    "//ydb/core/mind",
    "//ydb/core/mind/bscontroller",
    "//ydb/core/mind/hive",
    "//ydb/core/node_whiteboard",
    "//ydb/core/protos",
    "//ydb/core/protos/schemeshard",
    "//ydb/core/tablet",
    "//ydb/core/tablet_flat",
    "//ydb/core/testlib",
    "//ydb/core/testlib/actors",
    "//ydb/core/testlib/basics",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx/columnshard",
    "//ydb/core/tx/mediator",
    "//ydb/core/tx/schemeshard",
    "//ydb/core/util",
    "//ydb/library/actors/core",
    "//ydb/library/actors/helpers",
    "//ydb/library/actors/interconnect",
    "//ydb/public/api/grpc",
    "//ydb/public/api/grpc/draft",
  ]

  sources = [
    "//ydb/core/mind/hive/hive_impl_ut.cpp",
    "//ydb/core/mind/hive/hive_ut.cpp",
    "//ydb/core/mind/hive/object_distribution_ut.cpp",
    "//ydb/core/mind/hive/scale_recommender_policy_ut.cpp",
    "//ydb/core/mind/hive/sequencer_ut.cpp",
    "//ydb/core/mind/hive/storage_pool_info_ut.cpp",
    "//ydb/core/mind/hive/tenants_ut.cpp",
    "//ydb/core/mind/hive/ut_common.cpp",
  ]

  include_dirs = [ "//ydb/core/mind/hive" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
