unittest_executable("ut_consistent_copy_tables") {
  deps = [
    "//ydb/core/kqp/ut/common",  # peerdir only
    "//ydb/core/protos/schemeshard",
    "//ydb/core/tx/schemeshard",  # peerdir only
    "//ydb/core/tx/schemeshard/ut_helpers",
    "//yql/essentials/parser/pg_wrapper",  # peerdir only
    "//yql/essentials/sql/pg",  # peerdir only
  ]

  sources = [ "ut_consistent_copy_tables.cpp" ]

  include_dirs = [
    "//ydb/core/tx/schemeshard",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_wrapper",
    "yql_pg_sql_translator=pg",
    "yt_codegen=llvm16",
  ]
}
