unittest_executable("ut_group") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/base",
    "//ydb/core/blobstorage/crypto",
    "//ydb/core/blobstorage/dsproxy",
    "//ydb/core/blobstorage/groupinfo",
    "//ydb/core/blobstorage/pdisk/mock",
    "//ydb/core/blobstorage/vdisk",
    "//ydb/core/blobstorage/vdisk/common",
    "//ydb/core/driver_lib/version",  # peerdir only
    "//ydb/core/node_whiteboard",
    "//ydb/core/tx/scheme_board",  # peerdir only
    "//ydb/core/util",  # peerdir only
    "//ydb/core/util/actorsys_test",
    "//ydb/library/actors/core",
    "//ydb/library/actors/interconnect/mock",  # peerdir only
  ]

  sources = [ "main.cpp" ]

  link_select = [
    "YqlServicePolicy=stub",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
