unittest_executable("ut") {
  deps = [
    "//library/cpp/digest/md5",
    "//library/cpp/testing/hook",
    "//library/cpp/testing/unittest",
    "//ydb/core/protos",  # peerdir only
    "//ydb/core/testlib/basics",
    "//ydb/core/testlib/basics:default",  # peerdir only
    "//ydb/core/util",
    "//ydb/core/wrappers",
    "//ydb/core/wrappers:ut_helpers",
    "//ydb/library/actors/core",
    "//ydb/library/services",
    "//yql/essentials/minikql/comp_nodes/llvm16",  # peerdir only
  ]

  sources = [ "//ydb/core/wrappers/s3_wrapper_ut.cpp" ]

  include_dirs = [ "//ydb/core/wrappers" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
