library("health_check") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/node_whiteboard",
    # "//ydb/public/api/protos",
  ]

  deps = [
    # "//library/cpp/digest/old_crc",
    # "//library/cpp/protobuf/json",
    # "//ydb/core/cms/console",
    # "//ydb/core/mind",
    # "//ydb/core/mon",
    # "//ydb/core/protos",
    # "//ydb/core/sys_view:common",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/core/util",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/actors/wilson",
    # "//ydb/library/wilson_ids",
    # "//ydb/public/api/grpc",
    # "//ydb/public/sdk/cpp/src/library/grpc/client",
    # "//yql/essentials/public/issue",
  ]

  sources = [ "health_check.cpp" ]
}
