# yamake2gn: keep  -- hand-written, do not regenerate

library("shared_blobs") {
  public_deps = [ "//ydb/core/tablet_flat" ]

  deps = [
    "//ydb/core/tx/columnshard/blobs_action",
    "//ydb/library/actors/core",
  ]

  sources = [ "shared_blobs.cpp" ]
}

group("manager") {
  public_deps = [
    ":shared_blobs",
    "//ydb/core/tx/columnshard",
  ]
}
