library("storage_transport") {
  public_deps = [
    "//ydb/core/blobstorage/ddisk",
    "//ydb/core/mind/bscontroller:group_mapper",
    "//ydb/core/nbs/cloud/blockstore/libs/kikimr",
    "//ydb/core/nbs/cloud/storage/core/libs/common",
    "//ydb/core/protos",
  ]

  deps = [
    "//ydb/core/mind/bscontroller",  # peerdir only
  ]

  sources = [ "ic_storage_transport.cpp" ]
}
