unittest_executable("ut") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/ymq/http",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
    "//yql/essentials/sql/pg_dummy",  # peerdir only
  ]

  sources = [ "xml_builder_ut.cpp" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
