library("init") {
    public_deps = [
        "//ydb/library/yaml_config",
    ]

    deps = [
        "//ydb/core/base",
        # "//ydb/core/driver_lib:run", - circular dependencies
        "//ydb/core/protos",
    ]

    sources = [
        "init/init.cpp",
        "init/init_noop.cpp",
        "init/dummy.cpp",
    ]

    serialize_enum_headers = [ "init/init.h" ]
}

protobuf_library("protos") {
    sources = [ "protos/marker.proto" ]
}

library("utils") {
    deps = [ "//contrib/libs/protobuf" ]
    sources = [ "utils/config_traverse.cpp" ]
}
