library("local_proxy") {
  public_deps = [
    # "//ydb/core/grpc_services/base",
    ":ydb_proxy",
    # "//ydb/library/actors/core",
  ]

  deps = [
    "//ydb/core/grpc_services",
    # "//ydb/core/persqueue/events",
    "//ydb/core/persqueue/public",
    # "//ydb/core/persqueue/writer",
    # "//ydb/core/protos",
    "//ydb/core/tablet",
    "//ydb/core/tx/scheme_cache",
    # "//ydb/library/services",
    # "//ydb/library/yverify_stream",
    # "//ydb/public/api/protos",
    "//ydb/services/persqueue_v1",
  ]

  sources = [
    "local_proxy/local_partition_actor.cpp",
    "local_proxy/local_partition_committer.cpp",
    "local_proxy/local_partition_reader.cpp",
    "local_proxy/local_proxy.cpp",
  ]
}

library("ydb_proxy") {
  public_deps = [
    "//ydb/core/base",
    "//ydb/public/sdk/cpp/src/client/scheme",
    "//ydb/public/sdk/cpp/src/client/table",
    "//ydb/public/sdk/cpp/src/client/topic/impl",
  ]

  deps = [
    "//library/cpp/threading/future",
    # "//ydb/core/protos",
    "//ydb/library/actors/core",
    "//ydb/public/sdk/cpp/src/client/common_client",
    # "//ydb/public/sdk/cpp/src/client/driver",
    "//ydb/public/sdk/cpp/src/client/iam",
    "//ydb/public/sdk/cpp/src/client/iam_private",
    "//ydb/public/sdk/cpp/src/client/types/credentials:login",
  ]

  sources = [
    "topic_message.cpp",
    "ydb_proxy.cpp",
  ]
}
