library("events") {
  public_deps = [
    # "//contrib/libs/protobuf",
    "//ydb/core/grpc_services/base",
    "//ydb/core/grpc_services/cancelation",
    # "//ydb/core/kqp/common",
    # "//ydb/core/kqp/common/compilation",
    # "//ydb/core/kqp/common/result_set_format",
    # "//ydb/core/kqp/common/shutdown",
    "//ydb/core/kqp/common/simple",
    "//ydb/core/protos",
    # "//ydb/core/resource_pools",
    # "//ydb/core/scheme",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    "//ydb/library/yql/dq/actors",
    "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/library/operation_id",
    # "//yql/essentials/core/issue",
    # "//yql/essentials/public/issue",
  ]

  deps = [
    # "//ydb/core/base",  # peerdir only
    # "//ydb/core/kqp/topics",  # peerdir only
  ]

  sources = [
    "events.cpp",
    "query.cpp",
    "script_executions.cpp",
    "workload_service.cpp",
  ]
}
