library("hive") {
  public_deps = [
    # "//library/cpp/containers/absl_flat_hash",
    # "//library/cpp/containers/ring_buffer",
    "//ydb/core/base",
    "//ydb/core/blobstorage/events",
    # "//ydb/core/cms/console",
    "//ydb/core/engine/minikql",
    # "//ydb/core/mind",
    # "//ydb/core/node_whiteboard",
    # "//ydb/core/protos",
    # "//ydb/core/scheme",
    # "//ydb/core/sys_view/common",
    "//ydb/core/tablet",
    "//ydb/core/tablet_flat",
    "//ydb/core/tx",
    "//ydb/core/tx/scheme_cache",
    # "//ydb/core/util",
    # "//ydb/library/actors/core",
  ]

  deps = [
    "//library/cpp/digest/md5",
    # "//library/cpp/json",
    # "//library/cpp/monlib/dynamic_counters",  # peerdir only
    # "//library/cpp/monlib/service/pages",
    "//library/cpp/protobuf/json",
    # "//library/cpp/random_provider",
    # "//library/cpp/time_provider",
    # "//ydb/core/blobstorage/base",  # peerdir only
    # "//ydb/core/blobstorage/crypto",  # peerdir only
    # "//ydb/core/blobstorage/nodewarden",  # peerdir only
    "//ydb/library/aclib",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/yverify_stream",
  ]

  sources = [
    "balancer.cpp",
    "boot_queue.cpp",
    "domain_info.cpp",
    "drain.cpp",
    "fill.cpp",
    "follower_tablet_info.cpp",
    "hive.cpp",
    "hive_domains.cpp",
    "hive_impl.cpp",
    "hive_log.cpp",
    "hive_statics.cpp",
    "leader_tablet_info.cpp",
    "monitoring.cpp",
    "node_info.cpp",
    "reassign_actor.cpp",
    "sequencer.cpp",
    "storage_balancer.cpp",
    "storage_group_info.cpp",
    "storage_pool_info.cpp",
    "tablet_info.cpp",
    "tablet_move_info.cpp",
    "tx__adopt_tablet.cpp",
    "tx__block_storage_result.cpp",
    "tx__configure_scale_recommender.cpp",
    "tx__configure_subdomain.cpp",
    "tx__create_tablet.cpp",
    "tx__cut_tablet_history.cpp",
    "tx__delete_node.cpp",
    "tx__delete_tablet.cpp",
    "tx__delete_tablet_result.cpp",
    "tx__disconnect_node.cpp",
    "tx__generate_data_ut.cpp",
    "tx__init_scheme.cpp",
    "tx__kill_node.cpp",
    "tx__load_everything.cpp",
    "tx__lock_tablet.cpp",
    "tx__process_boot_queue.cpp",
    "tx__process_metrics.cpp",
    "tx__process_pending_operations.cpp",
    "tx__reassign_groups.cpp",
    "tx__reassign_groups_on_decommit.cpp",
    "tx__register_node.cpp",
    "tx__release_tablets.cpp",
    "tx__release_tablets_reply.cpp",
    "tx__request_tablet_owners.cpp",
    "tx__request_tablet_seq.cpp",
    "tx__response_tablet_seq.cpp",
    "tx__restart_tablet.cpp",
    "tx__resume_tablet.cpp",
    "tx__seize_tablets.cpp",
    "tx__seize_tablets_reply.cpp",
    "tx__set_down.cpp",
    "tx__start_tablet.cpp",
    "tx__status.cpp",
    "tx__stop_tablet.cpp",
    "tx__switch_drain.cpp",
    "tx__sync_tablets.cpp",
    "tx__tablet_owners_reply.cpp",
    "tx__unlock_tablet.cpp",
    "tx__update_dc_followers.cpp",
    "tx__update_domain.cpp",
    "tx__update_pile.cpp",
    "tx__update_tablet_groups.cpp",
    "tx__update_tablet_metrics.cpp",
    "tx__update_tablet_status.cpp",
    "tx__update_tablets_object.cpp",
  ]
}
