library("peephole_opt") {
  public_deps = [ "//yql/essentials/core" ]

  deps = [
    "//library/cpp/svnversion",
    # "//library/cpp/yson",
    # "//yql/essentials/ast",
    # "//yql/essentials/core/common_opt",
    # "//yql/essentials/core/expr_nodes",
    "//yql/essentials/core/services:pipeline",
    # "//yql/essentials/core/sql_types",
    # "//yql/essentials/core/type_ann",
    # "//yql/essentials/minikql",
    # "//yql/essentials/utils",
    "//yql/essentials/utils/log",
  ]

  sources = [
    "yql_opt_json_peephole_physical.cpp",
    "yql_opt_peephole_physical.cpp",
  ]
}
