unittest_executable("ut_strategy") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/blobstorage/dsproxy",
  ]

  sources = [ "strategy_ut.cpp" ]

  link_select = [
    "YqlServicePolicy=stub",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
