group("node_whiteboard") {
  public_deps = [
    "//ydb/core/base",
    "//ydb/core/blobstorage/groupinfo",
    "//ydb/core/debug",
    "//ydb/core/protos",
    "//ydb/library/actors/core",
    "//ydb/library/actors/interconnect",
    "//ydb/library/services",
  ]

  deps = [
    # "//library/cpp/deprecated/enum_codegen",  # peerdir only
    "//library/cpp/logger",  # peerdir only
    "//library/cpp/lwtrace/mon",  # peerdir only
    # "//library/cpp/random_provider",  # peerdir only
    # "//library/cpp/time_provider",  # peerdir only
    # "//ydb/core/base:services",  # peerdir only
    # "//ydb/core/blobstorage/base",  # peerdir only
    # "//ydb/core/erasure",  # peerdir only
    # "//ydb/library/actors/helpers",  # peerdir only
    # "//ydb/library/actors/protos",  # peerdir only
  ]
}
