protobuf_library("protos") {
  public_deps = [ "//ydb/public/api/protos" ]

  sources = [ "protos/fq.proto" ]
}

library("public_http") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # ":protos",
    # "//library/cpp/protobuf/json",
    # "//library/cpp/resource",
    # "//ydb/core/fq/libs/result_formatter",
    # "//ydb/core/grpc_services",
    # "//ydb/core/http_proxy",
    # "//ydb/core/viewer:json",
    # "//ydb/library/actors/http",
    # "//ydb/library/grpc/server",
    # "//ydb/library/http_proxy/error",
    # "//ydb/library/services",
    # "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/client/types",
  ]

  sources = [
    "grpc_request_context_wrapper.cpp",
    "http_req.cpp",
    "http_router.cpp",
    "http_service.cpp",
  ]
}
