import("//contrib/libs/llvm16/llvm.gni")

llvm_library("Scalar") {
    deps = [
        "//contrib/libs/llvm16/lib/Analysis",
        "//contrib/libs/llvm16/lib/Transforms/Utils",
    ]

    sources = [
        "ADCE.cpp",
        "AlignmentFromAssumptions.cpp",
        "AnnotationRemarks.cpp",
        "BDCE.cpp",
        "CallSiteSplitting.cpp",
        "ConstantHoisting.cpp",
        "ConstraintElimination.cpp",
        "CorrelatedValuePropagation.cpp",
        "DCE.cpp",
        "DeadStoreElimination.cpp",
        "DFAJumpThreading.cpp",
        "DivRemPairs.cpp",
        "EarlyCSE.cpp",
        "FlattenCFGPass.cpp",
        "Float2Int.cpp",
        "GuardWidening.cpp",
        "GVN.cpp",
        "GVNHoist.cpp",
        "GVNSink.cpp",
        "InductiveRangeCheckElimination.cpp",
        "IndVarSimplify.cpp",
        "InferAddressSpaces.cpp",
        "InstSimplifyPass.cpp",
        "IVUsersPrinter.cpp",
        "JumpThreading.cpp",
        "LICM.cpp",
        "LoopAccessAnalysisPrinter.cpp",
        "LoopBoundSplit.cpp",
        "LoopDataPrefetch.cpp",
        "LoopDeletion.cpp",
        "LoopDistribute.cpp",
        "LoopFlatten.cpp",
        "LoopFuse.cpp",
        "LoopIdiomRecognize.cpp",
        "LoopInstSimplify.cpp",
        "LoopInterchange.cpp",
        "LoopLoadElimination.cpp",
        "LoopPassManager.cpp",
        "LoopPredication.cpp",
        "LoopRerollPass.cpp",
        "LoopRotation.cpp",
        "LoopSimplifyCFG.cpp",
        "LoopSink.cpp",
        "LoopStrengthReduce.cpp",
        "LoopUnrollAndJamPass.cpp",
        "LoopUnrollPass.cpp",
        "LoopVersioningLICM.cpp",
        "LowerAtomicPass.cpp",
        "LowerConstantIntrinsics.cpp",
        "LowerExpectIntrinsic.cpp",
        "LowerGuardIntrinsic.cpp",
        "LowerMatrixIntrinsics.cpp",
        "LowerWidenableCondition.cpp",
        "MakeGuardsExplicit.cpp",
        "MemCpyOptimizer.cpp",
        "MergedLoadStoreMotion.cpp",
        "MergeICmps.cpp",
        "NaryReassociate.cpp",
        "NewGVN.cpp",
        "PartiallyInlineLibCalls.cpp",
        "PlaceSafepoints.cpp",
        "Reassociate.cpp",
        "Reg2Mem.cpp",
        "RewriteStatepointsForGC.cpp",
        "Scalar.cpp",
        "ScalarizeMaskedMemIntrin.cpp",
        "Scalarizer.cpp",
        "SCCP.cpp",
        "SeparateConstOffsetFromGEP.cpp",
        "SimpleLoopUnswitch.cpp",
        "SimplifyCFGPass.cpp",
        "Sink.cpp",
        "SpeculativeExecution.cpp",
        "SROA.cpp",
        "StraightLineStrengthReduce.cpp",
        "StructurizeCFG.cpp",
        "TailRecursionElimination.cpp",
        "TLSVariableHoist.cpp",
        "WarnMissedTransforms.cpp",
    ]
}
