unittest_executable("ut") {
  deps = [
    "//contrib/libs/protobuf",
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//ydb/core/base",  # peerdir only
    "//ydb/core/blobstorage/groupinfo",  # peerdir only
    "//ydb/core/blobstorage/vdisk/common",
    "//ydb/core/erasure",  # peerdir only
  ]

  sources = [
    "//ydb/core/blobstorage/vdisk/common/circlebuf_ut.cpp",
    "//ydb/core/blobstorage/vdisk/common/circlebufresize_ut.cpp",
    "//ydb/core/blobstorage/vdisk/common/circlebufstream_ut.cpp",
    "//ydb/core/blobstorage/vdisk/common/memusage_ut.cpp",
    "//ydb/core/blobstorage/vdisk/common/vdisk_config_ut.cpp",
    "//ydb/core/blobstorage/vdisk/common/vdisk_lsnmngr_ut.cpp",
    "//ydb/core/blobstorage/vdisk/common/vdisk_outofspace_ut.cpp",
    "//ydb/core/blobstorage/vdisk/common/vdisk_pdisk_error_ut.cpp",
    "//ydb/core/blobstorage/vdisk/common/vdisk_syncneighbors_ut.cpp",
  ]

  include_dirs = [ "//ydb/core/blobstorage/vdisk/common" ]

  link_select = [
    "YqlServicePolicy=stub",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
