unittest_executable("ut") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx/balance_coverage",
  ]

  sources = [ "//ydb/core/tx/balance_coverage/balance_coverage_builder_ut.cpp" ]

  include_dirs = [ "//ydb/core/tx/balance_coverage" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
