library("run") {
  public_deps = [
    # "//library/cpp/monlib/dynamic_counters",
    "//ydb/core/base",
    # "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/client/server",
    # "//ydb/core/config/init",
    # "//ydb/core/driver_lib/cli_config_base",
    # "//ydb/core/formats",
    # "//ydb/core/fq/libs/config:protos",
    # "//ydb/core/fq/libs/shared_resources:interface",
    # "//ydb/core/http_proxy",
    # "//ydb/core/kqp/common",
    # "//ydb/core/memory_controller",
    # "//ydb/core/persqueue/common:proxy",
    # "//ydb/core/protos",
    # "//ydb/core/scheme_types",
    # "//ydb/core/tablet",
    # "//ydb/core/tx/datashard",
    # "//ydb/core/tx/replication/service",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/core/ymq/actor",
    # "//ydb/core/ymq/http",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/interconnect:poller",
    # "//ydb/library/actors/util",
    # "//ydb/library/actors/wilson",
    # "//ydb/library/folder_service",
    # "//ydb/library/folder_service:proto",
    # "//ydb/library/global_plugins",
    # "//ydb/library/grpc/server",
    # "//ydb/library/pdisk_io",
    "//ydb/library/yaml_config",
    # "//ydb/library/yql/providers/pq/cm_client",
    # "//ydb/public/lib/base",
    # "//yql/essentials/minikql/computation",
  ]

  deps = [
    # "//library/cpp/deprecated/enum_codegen",
    # "//library/cpp/getopt",
    # "//library/cpp/json",
    # "//library/cpp/logger",
    # "//library/cpp/logger:global",
    # "//library/cpp/lwtrace/mon",
    # "//library/cpp/malloc/api",
    # "//library/cpp/messagebus",
    # "//library/cpp/monlib/messagebus",
    # "//library/cpp/protobuf/json",
    # "//library/cpp/sighandler",
    # "//library/cpp/string_utils/parse_size",
    # "//library/cpp/svnversion",
    # "//ydb/core/actorlib_impl",
    # "//ydb/core/audit",
    # "//ydb/core/audit:audit_config",
    # "//ydb/core/audit:heartbeat_actor",
    # "//ydb/core/backup/controller",
    # "//ydb/core/blob_depot",
    # "//ydb/core/blobstorage",
    # "//ydb/core/blobstorage/backpressure",
    # "//ydb/core/blobstorage/nodewarden",
    # "//ydb/core/blobstorage/other",
    # "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/client/minikql_compile",
    # "//ydb/core/cms",
    # "//ydb/core/cms/console",
    # "//ydb/core/cms/console:validators",
    # "//ydb/core/control",
    # "//ydb/core/counters_info",
    # "//ydb/core/discovery",
    # "//ydb/core/driver_lib/base_utils",
    # "//ydb/core/driver_lib/cli_utils",
    # "//ydb/core/driver_lib/version",
    # "//ydb/core/fq/libs/checkpoint_storage",
    "//ydb/core/fq/libs/init",
    # "//ydb/core/fq/libs/logs",
    # "//ydb/core/graph/api",
    # "//ydb/core/grpc_services",
    # "//ydb/core/health_check",
    "//ydb/core/kafka_proxy",
    # "//ydb/core/kesus/proxy",
    # "//ydb/core/kesus/tablet",
    # "//ydb/core/keyvalue",
    # "//ydb/core/kqp/federated_query:actors",
    # "//ydb/core/kqp/finalize_script_service",
    # "//ydb/core/kqp/proxy_service",
    # "//ydb/core/kqp/rm_service",
    # "//ydb/core/load_test",
    "//ydb/core/local_pgwire",
    # "//ydb/core/log_backend",
    # "//ydb/core/metering",
    # "//ydb/core/mind",
    # "//ydb/core/mind:address_classification",
    # "//ydb/core/mind:bscontroller",
    # "//ydb/core/mon",
    # "//ydb/core/mon_alloc",
    # "//ydb/core/node_whiteboard",
    # "//ydb/core/persqueue",
    # "//ydb/core/pgproxy",
    # "//ydb/core/public_http",
    # "//ydb/core/quoter",
    # "//ydb/core/scheme",
    # "//ydb/core/security",
    # "//ydb/core/security:ldap_auth_provider",
    # "//ydb/core/security:token_manager",
    # "//ydb/core/statistics:aggregator",
    # "//ydb/core/statistics:service",
    # "//ydb/core/sys_view:processor",
    # "//ydb/core/sys_view:service",
    # "//ydb/core/tablet_flat",
    # "//ydb/core/test_tablet",
    # "//ydb/core/tracing",
    # "//ydb/core/transfer",
    # "//ydb/core/tx",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/column_fetching",
    # "//ydb/core/tx/columnshard/data_accessor:cache_policy",
    # "//ydb/core/tx/columnshard/overload_manager",
    # "//ydb/core/tx/conveyor/service",
    # "//ydb/core/tx/conveyor/usage",
    # "//ydb/core/tx/conveyor_composite/service",
    # "//ydb/core/tx/conveyor_composite/usage",
    # "//ydb/core/tx/coordinator",
    # "//ydb/core/tx/general_cache/usage",
    # "//ydb/core/tx/limiter/grouped_memory/usage",
    # "//ydb/core/tx/long_tx_service",
    # "//ydb/core/tx/long_tx_service:public",
    # "//ydb/core/tx/mediator",
    # "//ydb/core/tx/priorities/usage",
    # "//ydb/core/tx/replication/controller",
    # "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/sequenceproxy",
    # "//ydb/core/tx/sequenceshard",
    # "//ydb/core/tx/time_cast",
    # "//ydb/core/tx/tx_allocator",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/core/util",
    # "//ydb/core/viewer",
    # "//ydb/library/actors/dnsresolver",
    # "//ydb/library/actors/helpers",
    # "//ydb/library/actors/http",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/actors/interconnect/rdma",
    # "//ydb/library/actors/interconnect/rdma:cq_actor",
    # "//ydb/library/actors/prof",
    # "//ydb/library/actors/protos",
    # "//ydb/library/actors/retro_tracing",
    # "//ydb/library/grpc/server:actors",
    # "//ydb/library/security",
    # "//ydb/library/services",
    # "//ydb/library/signal_backtrace",
    # "//ydb/library/slide_limiter/service",
    # "//ydb/library/slide_limiter/usage",
    # "//ydb/library/yql/providers/s3/actors",
    # "//ydb/library/yql/utils/actor_log",
    # "//ydb/library/yverify_stream",
    # "//ydb/public/lib/deprecated/client",
    # "//ydb/services/auth",
    # "//ydb/services/backup",
    # "//ydb/services/bridge",
    # "//ydb/services/cms",
    # "//ydb/services/config",
    # "//ydb/services/datastreams",
    # "//ydb/services/deprecated/persqueue_v0",
    # "//ydb/services/discovery",
    # "//ydb/services/dynamic_config",
    # "//ydb/services/ext_index/common",
    # "//ydb/services/ext_index/service",
    # "//ydb/services/fq",
    # "//ydb/services/kesus",
    # "//ydb/services/keyvalue",
    # "//ydb/services/local_discovery",
    # "//ydb/services/maintenance",
    # "//ydb/services/metadata",
    # "//ydb/services/metadata/ds_table",
    # "//ydb/services/monitoring",
    # "//ydb/services/persqueue_cluster_discovery",
    # "//ydb/services/persqueue_v1",
    # "//ydb/services/rate_limiter",
    # "//ydb/services/replication",
    # "//ydb/services/tablet",
    # "//ydb/services/test_shard",
    # "//ydb/services/view",
    # "//ydb/services/ydb",
    # "//yql/essentials/minikql/comp_nodes",
    # "//yql/essentials/minikql/invoke_builtins",
    # "//yql/essentials/parser/pg_wrapper/interface",
  ]

  sources = [
    "auto_config_initializer.cpp",
    "config.cpp",
    "config_helpers.cpp",
    "config_parser.cpp",
    "factories.cpp",
    "kikimr_services_initializers.cpp",
    "main.cpp",
    "run.cpp",
    "service_initializer.cpp",
  ]
}
