library("query") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/blobstorage/vdisk/hulldb",
  ]

  deps = [
    # "//library/cpp/streams/bzip2",
    # "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/blobstorage/vdisk",
    # "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/blobstorage/vdisk/hulldb:base",
    # "//ydb/core/blobstorage/vdisk/scrub",
    # "//ydb/core/util",
    # "//ydb/library/actors/wilson",
    # "//ydb/library/wilson_ids",
  ]

  sources = [
    "assimilation.cpp",
    "query_barrier.cpp",
    "query_extr.cpp",
    "query_public.cpp",
    "query_range.cpp",
    "query_readactor.cpp",
    "query_readbatch.cpp",
    "query_statdb.cpp",
    "query_stathuge.cpp",
    "query_stattablet.cpp",
  ]
}
