# yamake2gn: keep  -- hand-written, do not regenerate

source_set("_srcs") {
  deps += [
    "//contrib/libs/apache/arrow",
    "//ydb/core/formats/arrow/rows:_srcs",
    # "//ydb/core/formats/arrow:switch",
    # "//ydb/core/protos",
    "//ydb/library/conclusion",
    # "//ydb/library/formats/arrow:simple_builder",
    # "//ydb/library/formats/arrow:transformer",
    # "//ydb/library/formats/arrow:validation",
    # "//ydb/services/metadata/abstract",
  ]

  sources = [
    "conversion.cpp",
    "diff.cpp",
    "object.cpp",
  ]
}
