library("constructor") {
  public_deps = [
    # "//ydb/core/tx/columnshard/engines/reader/abstract",
    "//ydb/core/tx/columnshard/engines/reader/common_reader/constructor:shard",
  ]

  deps = [
    # "//ydb/core/kqp/compute_actor",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator",
  ]

  sources = [
    "constructor.cpp",
    "read_metadata.cpp",
  ]
}
