library("abstract") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/core/tablet_flat",
    "//ydb/core/tx/columnshard/common",
    "//ydb/core/tx/columnshard/splitter",
    "//ydb/core/tx/tiering:tier",
    "//ydb/library/accessor",
    "//ydb/services/metadata/abstract",
  ]

  deps = []

  sources = [ "abstract.cpp" ]
}
