library("cache") {
  public_deps = [
    # "//library/cpp/threading/future",
  ]

  sources = [
    "byte_size.cpp",
    "cache.cpp",
    "cached.cpp",
  ]
}

library("local") {
  public_deps = [
    ":cache",
    "//library/cpp/cache",
    "//library/cpp/time_provider",
  ]

  sources = [ "local/cache.cpp" ]
}
