library("collections") {
  public_deps = [
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/common",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/constructor",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator",
    # "//ydb/library/accessor",
  ]

  deps = [
    # "//ydb/core/tx/columnshard/engines/predicate",
  ]

  sources = [
    "collections/abstract.cpp",
    "collections/constructors.cpp",
    "collections/full_scan_sorted.cpp",
    "collections/limit_sorted.cpp",
    "collections/not_sorted.cpp",
  ]
}

library("iterator") {
  public_deps = [
    # "//ydb/core/formats/arrow",
    # "//ydb/core/formats/arrow:reader",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/blobs_action:abstract",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/predicate",
    # "//ydb/core/tx/columnshard/engines/reader/abstract",
    # "//ydb/core/tx/columnshard/engines/reader/common",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/common",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/iterator",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/constructor",
    # "//ydb/core/tx/columnshard/engines/scheme/versions",
    # "//ydb/core/tx/columnshard/hooks/abstract",
    # "//ydb/core/tx/columnshard/resource_subscriber",
    # "//ydb/core/tx/limiter/grouped_memory/usage",
    # ":collections",
    # ":sync_points",
  ]

  deps = [
    # "//ydb/core/formats/arrow/accessor/sub_columns",
    # "//ydb/core/tx/columnshard/blobs_reader",
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/constructor",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates",
    # "//ydb/core/tx/columnshard/engines/scheme",
    # "//ydb/core/tx/columnshard/engines/storage/indexes/portions",
    # "//ydb/core/tx/columnshard/engines/storage/indexes/skip_index",
    # "//ydb/core/tx/conveyor_composite/usage",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/core",
    # "//ydb/library/formats/arrow",
  ]

  sources = [
    "context.cpp",
    "fetched_data.cpp",
    "fetching.cpp",
    "index_fetcher.cpp",
    "iterator.cpp",
    "plain_read_data.cpp",
    "scanner.cpp",
    "source.cpp",
  ]

  serialize_enum_headers = [ "source.h" ]
}

library("sync_points") {
  public_deps = [
    # "//ydb/core/tx/columnshard/engines/reader/common",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator",
    # "//ydb/library/accessor",
  ]

  deps = [
    # ":collections",
  ]

  sources = [
    "sync_points/abstract.cpp",
    "sync_points/aggr.cpp",
    "sync_points/limit.cpp",
    "sync_points/result.cpp",
  ]
}
