library("solomon_stats") {
  public_deps = [
    # "//library/cpp/monlib/encode:json",
    # "//library/cpp/monlib/metrics",
    # "//library/cpp/monlib/service",
    # "//library/cpp/monlib/service/pages",
    # "//ydb/public/sdk/cpp/src/client/extension_common",
  ]

  sources = [
    "pull_client.cpp",
    "pull_connector.cpp",
  ]
}
