library("common") {
  public_deps = [
    # "//library/cpp/random_provider",
    # "//library/cpp/time_provider",
    "//ydb/core/fq/libs/config:protos",
    "//ydb/core/fq/libs/events",
    # "//ydb/core/fq/libs/protos",
    # "//ydb/core/fq/libs/shared_resources",
    # "//ydb/core/fq/libs/ydb",
    # "//ydb/core/kqp/proxy_service:script_executions_utils",
    "//ydb/library/actors/core",
    # "//ydb/library/yql/providers/common/token_accessor/client",
    # "//ydb/library/yql/providers/dq/provider",
    # "//ydb/library/yql/providers/dq/worker_manager:interface",
    # "//ydb/library/yql/providers/generic/connector/libcpp",
    # "//ydb/library/yql/providers/pq/cm_client",
    # "//ydb/library/yql/providers/pq/gateway/abstract",
    "//ydb/library/yql/providers/s3/actors_factory",
    # "//ydb/library/yql/providers/solomon/provider",
    # "//ydb/public/lib/fq",
    # "//ydb/public/sdk/cpp/src/client/query",
    # "//ydb/public/sdk/cpp/src/client/table",
    # "//yql/essentials/minikql/computation",
    # "//yql/essentials/providers/common/metrics",
  ]

  deps = [
    # "//library/cpp/json",
    # "//library/cpp/json:yson",
    # "//library/cpp/protobuf/interop",
    # "//ydb/core/fq/libs/control_plane_storage",
    # "//ydb/core/fq/libs/control_plane_storage:events",
    # "//ydb/core/fq/libs/db_id_async_resolver_impl",
    "//ydb/core/fq/libs/private_client",
    # "//ydb/public/lib/ydb_cli/common",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/public/issue:protos",
  ]

  sources = [
    "pinger.cpp",
    "run_actor_params.cpp",
    "utils.cpp",
  ]
}
