library("common") {
  public_deps = [
    # "//library/cpp/monlib/service/pages",
    # "//ydb/core/kafka_proxy",
    # "//ydb/core/persqueue/public",
    "//ydb/core/tablet",
    # "//ydb/library/actors/core",
    # "//ydb/library/services",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/protos",
  ]

  sources = [
    "actor.cpp",
    "common_app.cpp",
    "heartbeat.cpp",
    "key.cpp",
    "microseconds_sliding_window.cpp",
    "percentiles.cpp",
  ]

  serialize_enum_headers = [ "sourceid_info.h" ]
}

library("proxy") {
  public_deps = [
    # "//library/cpp/logger",
    "//ydb/core/protos",
    # "//ydb/library/actors/core",
    "//ydb/library/logger",
    # "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/topic",
    # "//ydb/public/sdk/cpp/src/client/driver",
  ]

  sources = [ "proxy/actor_persqueue_client_iface.cpp" ]
}
