library("abstract") {
  public_deps = [
    # "//library/cpp/json:writer",
    "//ydb/core/base",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/core",
    # "//ydb/library/services",
    # "//ydb/public/api/protos",
    # "//ydb/services/metadata/initializer",
    # "//ydb/services/metadata/manager",
    # "//yql/essentials/core/expr_nodes",
  ]

  deps = [
    "//library/cpp/json",
    # "//library/cpp/protobuf/json",
    # "//ydb/services/metadata",
    "//yql/essentials/ast",
    "//yql/essentials/utils",
  ]

  sources = [
    "common.cpp",
    "decoder.cpp",
    "events.cpp",
    "fetcher.cpp",
    "initialization.cpp",
    "kqp_common.cpp",
    "parsing.cpp",
    "request_features.cpp",
  ]

  serialize_enum_headers = [ "kqp_common.h" ]
}
