library("counters") {
  public_deps = [
    # "//library/cpp/monlib/dynamic_counters",
    # "//ydb/core/sys_view:common",
    # "//ydb/library/grpc/server",
  ]

  deps = [
    # "//library/cpp/deprecated/enum_codegen",
    # "//ydb/core/base",
    # "//ydb/core/sys_view:service",
    # "//ydb/core/util",
    # "//ydb/library/actors/core",
    # "//ydb/public/api/protos",
  ]

  sources = [
    "counters.cpp",
    "proxy_counters.cpp",
  ]
}
