slot_interface_group("comp_nodes") {
  public_deps = [
    "//yql/essentials/minikql",
    "//yql/essentials/minikql/computation",
    # "//yql/essentials/public/udf",
    # "//yql/essentials/utils",
  ]

  link_slot_interface = "minikql_codegen"

  link_slot_headers = [
    "mkql_factories.h",
    "mkql_multihopping.h",
  ]

  link_slot_flags_from = [ "mkql_multihopping.cpp" ]
}
