unittest_executable("ut") {
  deps = [
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//ydb/core/blobstorage/storagepoolmon",
    "//ydb/core/testlib/actors",  # peerdir only
    "//ydb/core/testlib/basics",  # peerdir only
    "//ydb/core/testlib/default",  # peerdir only
  ]

  sources = [ "storagepoolmon_ut.cpp" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
