library("common") {
  public_deps = [
    # "//library/cpp/monlib/dynamic_counters",
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/string_utils/base64",
    # "//library/cpp/time_provider",
    # "//ydb/core/base",
    # "//ydb/core/blobstorage/backpressure",
    # "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/groupinfo",
    # "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/blobstorage/storagepoolmon",
    # "//ydb/core/blobstorage/vdisk/ingress",
    # "//ydb/core/blobstorage/vdisk/protos",
    # "//ydb/core/control/lib",
    # "//ydb/core/protos",
    # "//ydb/core/util",
    # "//ydb/library/actors/interconnect",
  ]

  deps = [
    # "//library/cpp/bucket_quoter",
    # "//library/cpp/monlib/dynamic_counters:percentile",
    # "//library/cpp/monlib/metrics",
    # "//library/cpp/random_provider",
    # "//ydb/core/blobstorage/lwtrace_probes",
    # "//ydb/core/blobstorage/vdisk",
    # "//ydb/core/blobstorage/vdisk/huge",
    # "//ydb/core/blobstorage/vdisk/hulldb:base",
    # "//ydb/core/blobstorage/vdisk/skeleton",
    # "//ydb/library/actors/protos",
    # "//ydb/library/lockfree_bucket",
    # "//ydb/library/pdisk_io",
  ]

  sources = [
    "blobstorage_cost_tracker.cpp",
    "blobstorage_dblogcutter.cpp",
    "blobstorage_event_filter.cpp",
    "blobstorage_status.cpp",
    "blobstorage_vdisk_guids.cpp",
    "vdisk_config.cpp",
    "vdisk_context.cpp",
    "vdisk_costmodel.cpp",
    "vdisk_events.cpp",
    "vdisk_handle_class.cpp",
    "vdisk_histogram_latency.cpp",
    "vdisk_histograms.cpp",
    "vdisk_hugeblobctx.cpp",
    "vdisk_log.cpp",
    "vdisk_mongroups.cpp",
    "vdisk_outofspace.cpp",
    "vdisk_performance_params.cpp",
    "vdisk_recoverylogwriter.cpp",
    "vdisk_response.cpp",
  ]
}
