library("service") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/change_exchange",
    # "//ydb/core/protos",
    # "//ydb/core/scheme",
    # "//ydb/core/scheme_types",
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx/replication/common",
  ]

  deps = [
    # "//library/cpp/json",
    # "//ydb/core/fq/libs/row_dispatcher/purecalc_compilation",
    # "//ydb/core/io_formats/cell_maker",
    # "//ydb/core/tx/datashard",
    # "//ydb/core/tx/replication/ydb_proxy",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/core/wrappers",
    # "//ydb/library/actors/core",
    # "//ydb/library/services",
  ]

  sources = [
    "base_table_writer.cpp",
    "json_change_record.cpp",
    "s3_writer.cpp",
    "service.cpp",
    "table_writer.cpp",
    "topic_reader.cpp",
    "worker.cpp",
  ]

  serialize_enum_headers = [ "worker.h" ]
}
