library("memory_controller") {
  public_deps = [
    # "//library/cpp/monlib/dynamic_counters",
    # "//ydb/core/base",
    # "//ydb/core/mon_alloc",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//contrib/libs/apache/arrow",
    # "//contrib/libs/tcmalloc",
    # "//ydb/core/cms/console",
    # "//ydb/core/node_whiteboard",
    # "//ydb/core/tablet",
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/data_accessor:cache_policy",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/abstract",
    # "//ydb/library/services",
    # "//yql/essentials/minikql",
    # "//yql/essentials/public/udf:arrow",
  ]

  sources = [
    "memory_controller.cpp",
    "memtable_collection.cpp",
  ]
}
