library("syncer") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/groupinfo",
    # "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/blobstorage/vdisk/hulldb",
    # "//ydb/core/blobstorage/vdisk/ingress",
    # "//ydb/core/driver_lib/version",
  ]

  deps = [
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/random_provider",
    # "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/blobstorage/vdisk/anubis_osiris",
    # "//ydb/core/blobstorage/vdisk/hulldb:base",
    # "//ydb/core/blobstorage/vdisk/hulldb:generic",
    # "//ydb/core/blobstorage/vdisk/synclog",
    # "//ydb/core/control/lib",
    # "//ydb/core/protos",
    # "//ydb/core/util",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/services",
  ]

  sources = [
    "blobstorage_syncer.cpp",
    "blobstorage_syncer_broker.cpp",
    "blobstorage_syncer_committer.cpp",
    "blobstorage_syncer_data.cpp",
    "blobstorage_syncer_localwriter.cpp",
    "blobstorage_syncer_recoverlostdata.cpp",
    "blobstorage_syncer_recoverlostdata_proxy.cpp",
    "blobstorage_syncer_scheduler.cpp",
    "guid_firstrun.cpp",
    "guid_propagator.cpp",
    "guid_proxyobtain.cpp",
    "guid_proxywrite.cpp",
    "guid_recovery.cpp",
    "syncer_job_actor.cpp",
    "syncer_job_task.cpp",
  ]
}
