unittest_executable("describes_ut") {
  deps = [
    "//contrib/libs/grpc",
    "//contrib/libs/protobuf",
    "//library/cpp/testing/unittest",
    "//ydb/core/client/server",
    "//ydb/core/testlib",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/public/api/grpc",
    "//ydb/public/api/protos",
    "//ydb/public/sdk/cpp/src/client/persqueue_public/ut/ut_utils",
    "//ydb/services/persqueue_v1",  # peerdir only
    "//ydb/services/persqueue_v1/actors",
  ]

  sources = [
    "describe_topic_ut.cpp",
    "ic_cache_ut.cpp",
  ]

  include_dirs = [
    "//ydb/services/persqueue_v1",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
