library("registry") {
  public_deps = [
    "//contrib/libs/apache/arrow",
    "//yql/essentials/minikql",
    "//yql/essentials/minikql/computation/llvm16",
    # "//yql/essentials/public/langver",
  ]

  deps = [
    "//library/cpp/random_provider",
    "//library/cpp/time_provider",
  ]

  sources = [ "registry.cpp" ]
}
