library("cms") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/library/actors/core",
    "//ydb/library/actors/interconnect",
  ]

  deps = [
    "//library/cpp/json",
    "//library/cpp/mime/types",
    "//library/cpp/monlib/service/pages",
    "//library/cpp/protobuf/json",
    "//library/cpp/resource",
    "//library/cpp/svnversion",
    "//library/cpp/time_provider",
    "//ydb/core/actorlib_impl",
    "//ydb/core/base",
    "//ydb/core/blobstorage/base",
    "//ydb/core/blobstorage/nodewarden",
    "//ydb/core/cms/console",
    "//ydb/core/engine:minikql",
    "//ydb/core/erasure",
    "//ydb/core/mind",
    "//ydb/core/mon",
    "//ydb/core/node_whiteboard",
    "//ydb/core/scheme",
    "//ydb/core/tablet",
    "//ydb/core/tablet_flat",
    "//ydb/core/tx/datashard",
    "//ydb/library/services",
    "//ydb/library/yverify_stream",
    "//ydb/public/api/protos",
    "//yql/essentials/public/issue:protos",
  ]

  sources = [
    "api_adapters.cpp",
    "audit_log.cpp",
    "cluster_info.cpp",
    "cms.cpp",
    "cms_tx_get_log_tail.cpp",
    "cms_tx_init_scheme.cpp",
    "cms_tx_load_state.cpp",
    "cms_tx_log_and_send.cpp",
    "cms_tx_log_cleanup.cpp",
    "cms_tx_process_notification.cpp",
    "cms_tx_reject_notification.cpp",
    "cms_tx_remove_expired_notifications.cpp",
    "cms_tx_remove_permissions.cpp",
    "cms_tx_remove_request.cpp",
    "cms_tx_remove_task.cpp",
    "cms_tx_store_first_boot_timestamp.cpp",
    "cms_tx_store_permissions.cpp",
    "cms_tx_store_walle_task.cpp",
    "cms_tx_update_config.cpp",
    "cms_tx_update_downtimes.cpp",
    "downtime.cpp",
    "erasure_checkers.cpp",
    "http.cpp",
    "info_collector.cpp",
    "logger.cpp",
    "node_checkers.cpp",
    "sentinel.cpp",
    "services.cpp",
    "walle_api_handler.cpp",
    "walle_check_task_adapter.cpp",
    "walle_create_task_adapter.cpp",
    "walle_list_tasks_adapter.cpp",
    "walle_remove_task_adapter.cpp",
  ]

  serialize_enum_headers = [
    "node_checkers.h",
    "services.h",
  ]
}
