library("console") {
    public_deps = [
        "//ydb/core/config:init",
    ]

    deps = [
        "//ydb/core/base",
        "//ydb/public/sdk/cpp/src/library/operation_id:protos",
    ]

    sources = [
        "console/config_helpers.cpp",
        "console/configs_cache.cpp",
        "console/configs_config.cpp",
        "console/configs_dispatcher_proxy.cpp",
        "console/configs_dispatcher.cpp",
        "console/console__add_config_subscription.cpp",
        "console/console__alter_tenant.cpp",
        "console/console__cleanup_subscriptions.cpp",
        "console/console__configure.cpp",
        "console/console__create_tenant.cpp",
        "console/console__drop_yaml_config.cpp",
        "console/console__get_log_tail.cpp",
        "console/console__get_yaml_config.cpp",
        "console/console__get_yaml_metadata.cpp",
        "console/console__init_scheme.cpp",
        "console/console__load_state.cpp",
        "console/console__log_cleanup.cpp",
        "console/console__remove_computational_units.cpp",
        "console/console__remove_config_subscription.cpp",
        "console/console__remove_config_subscriptions.cpp",
        "console/console__remove_tenant_done.cpp",
        "console/console__remove_tenant_failed.cpp",
        "console/console__remove_tenant.cpp",
        "console/console__replace_config_subscriptions.cpp",
        "console/console__replace_yaml_config.cpp",
        "console/console__revert_pool_state.cpp",
        "console/console__set_config.cpp",
        "console/console__toggle_config_validator.cpp",
        "console/console__update_confirmed_subdomain.cpp",
        "console/console__update_last_provided_config.cpp",
        "console/console__update_pool_state.cpp",
        "console/console__update_subdomain_key.cpp",
        "console/console__update_tenant_pool_config.cpp",
        "console/console__update_tenant_state.cpp",
        "console/console_audit.cpp",
        "console/console_configs_manager.cpp",
        "console/console_configs_provider.cpp",
        "console/console_configs_subscriber.cpp",
        "console/console_configuration_info_collector.cpp",
        "console/console_handshake.cpp",
        "console/console_tenants_manager.cpp",
        "console/console.cpp",
        "console/feature_flags_configurator.cpp",
        "console/grpc_library_helper.cpp",
        "console/http.cpp",
        "console/immediate_controls_configurator.cpp",
        "console/jaeger_tracing_configurator.cpp",
        "console/log_settings_configurator.cpp",
        "console/logger.cpp",
        "console/modifications_validator.cpp",
        "console/net_classifier_updater.cpp",
        "console/tx_processor.cpp",
        "console/util.cpp",
    ]
}
