library("ingress") {
  public_deps = [
    "//ydb/core/blobstorage/groupinfo",
    # "//ydb/core/util",
  ]

  deps = [
    "//ydb/core/base",
    # "//ydb/library/actors/core",
    # "//ydb/library/services",
  ]

  sources = [
    "blobstorage_ingress.cpp",
    "blobstorage_ingress_matrix.cpp",
    "blobstorage_ingress_partlayout.cpp",
  ]
}
