library("login") {
  deps = [
    "//contrib/libs/jwt-cpp",  # peerdir only
    # "//ydb/public/api/grpc",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/common",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/impl/internal/grpc_connections",
    "//ydb/public/sdk/cpp/src/client/impl/internal/plain_status",
    # "//ydb/public/sdk/cpp/src/client/types/core_facility",
    "//ydb/public/sdk/cpp/src/client/types/credentials",
    # "//ydb/public/sdk/cpp/src/client/types/status",  # peerdir only
    # "//ydb/public/sdk/cpp/src/library/issue",  # peerdir only
  ]

  sources = [ "login.cpp" ]
}
