unittest_executable("ut") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/tablet",
    "//ydb/core/testlib",
    "//ydb/core/testlib/actors",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx",
    "//ydb/core/tx/coordinator/public",
    "//ydb/core/tx/mediator",
    "//ydb/core/tx/time_cast",
    "//ydb/library/actors/core",
    "//ydb/public/api/grpc",  # peerdir only
  ]

  sources = [ "//ydb/core/tx/mediator/mediator_ut.cpp" ]

  include_dirs = [ "//ydb/core/tx/mediator" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
