library("abstract") {
  public_deps = [
    ":common",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/library/accessor",
  ]

  sources = [ "abstract/merger.cpp" ]
}

library("common") {
  public_deps = [
    # "//contrib/libs/apache/arrow",
    # "//ydb/core/tx/columnshard/counters",
    "//ydb/core/tx/columnshard/engines/scheme",
    "//ydb/core/tx/columnshard/splitter:abstract",
    # "//ydb/library/formats/arrow:splitter",
  ]

  sources = [
    "common/context.cpp",
    "common/result.cpp",
  ]
}

library("compaction") {
  public_deps = [
    "//ydb/core/formats/arrow",
    # "//ydb/core/tx/columnshard/common",
    "//ydb/core/tx/columnshard/engines/changes/abstract",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/scheme/versions",
    # "//ydb/library/formats/arrow:splitter",
  ]

  deps = [
    ":abstract",
    # ":common",  # peerdir only
    # ":dictionary",  # peerdir only
    ":plain",
    ":sparsed",
    # ":sub_columns",  # peerdir only
    # "//ydb/core/tx/columnshard/splitter",
    # "//ydb/core/tx/tiering",  # peerdir only
    # "//ydb/library/formats/arrow:simple_builder",
  ]

  sources = [ "merger.cpp" ]
}

library("plain") {
  public_deps = [
    # ":abstract",
  ]

  deps = [
    # "//contrib/libs/apache/arrow",
    # "//ydb/core/formats/arrow/accessor/plain",
    "//ydb/core/formats/arrow:save_load",
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/engines/changes/counters",
    # "//ydb/core/tx/columnshard/engines/portions",
    "//ydb/core/tx/columnshard/engines/scheme",
    "//ydb/core/tx/columnshard/engines/storage/chunks",
    # "//ydb/core/tx/columnshard/splitter",
    "//ydb/library/actors/util",
    "//ydb/library/formats/arrow",
    "//ydb/library/formats/arrow:validation",
    # ":common",
  ]

  sources = [
    "plain/column_cursor.cpp",
    "plain/column_portion_chunk.cpp",
    "plain/logic.cpp",
    "plain/merged_column.cpp",
  ]
}

library("sparsed") {
  public_deps = [
    "//ydb/core/formats/arrow/accessor:abstract",
    # "//ydb/core/formats/arrow/accessor/common",
    "//ydb/core/formats/arrow/accessor/sparsed",
    # ":abstract",
  ]

  deps = [
    # "//ydb/core/formats/arrow:switch",
    "//ydb/core/tx/columnshard/engines/scheme",
    "//ydb/core/tx/columnshard/engines/storage/chunks",
    "//ydb/library/actors/util",
  ]

  sources = [ "sparsed/logic.cpp" ]
}
