library("accessor") {
  public_deps = [
    "//ydb/core/base",
    # "//ydb/core/protos",
    # "//ydb/library/accessor",
    # "//ydb/library/aclib",
    # "//ydb/library/conclusion",
  ]

  deps = [
    "//library/cpp/digest/md5",
    # "//ydb/library/actors/core",  # peerdir only
    # "//ydb/services/metadata/manager",
  ]

  sources = [ "secret_id.cpp" ]
}
