library("cached") {
  public_deps = [
    ":simple",
    # "//yql/essentials/sql/v1/complete/name/cache",
  ]

  deps = [ "//library/cpp/threading/future" ]

  sources = [ "cached/schema.cpp" ]
}

library("simple") {
  public_deps = [
    "//library/cpp/case_insensitive_string",
    "//library/cpp/threading/future",
    "//yql/essentials/sql/v1/complete/name/object",
  ]

  sources = [ "schema.cpp" ]
}

library("static") {
  public_deps = [
    ":simple",
  ]

  deps = [
    # "//library/cpp/iterator",
    "//library/cpp/json",
  ]

  sources = [
    "static/schema.cpp",
    "static/schema_json.cpp",
  ]
}
