library("cached") {
  public_deps = [
    # "//yql/essentials/sql/v1/complete/name/cache",
    # "//yql/essentials/sql/v1/complete/name/object/simple",
  ]

  sources = [ "cached/schema.cpp" ]
}

library("simple") {
  public_deps = [
    # "//yql/essentials/sql/v1/complete/name/object",
  ]

  deps = [
    # "//library/cpp/case_insensitive_string",
  ]

  sources = [ "schema.cpp" ]
}

library("static") {
  public_deps = [
    # "//yql/essentials/sql/v1/complete/name/object/simple",
  ]

  deps = [
    # "//library/cpp/iterator",
    # "//library/cpp/json",
  ]

  sources = [
    "static/schema.cpp",
    "static/schema_json.cpp",
  ]
}
