library("pg_catalog") {
  public_deps = [ "//yql/essentials/public/issue" ]

  deps = [
    ":proto",
    "//library/cpp/digest/md5",
    # "//library/cpp/resource",
    "//yql/essentials/utils/log",
  ]

  sources = [ "catalog.cpp" ]

  resources = [
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_operator.dat"
      key = "pg_operator.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_proc.dat"
      key = "pg_proc.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_type.dat"
      key = "pg_type.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_cast.dat"
      key = "pg_cast.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_aggregate.dat"
      key = "pg_aggregate.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_opfamily.dat"
      key = "pg_opfamily.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_opclass.dat"
      key = "pg_opclass.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_amproc.dat"
      key = "pg_amproc.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_amop.dat"
      key = "pg_amop.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_am.dat"
      key = "pg_am.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_conversion.dat"
      key = "pg_conversion.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/include/catalog/pg_language.dat"
      key = "pg_language.dat"
    },
    {
      path = "//yql/essentials/parser/pg_wrapper/postgresql/src/backend/catalog/system_functions.sql"
      key = "system_functions.sql"
    },
  ]
}

protobuf_library("proto") {
  public_deps = [ "//yql/essentials/protos" ]

  sources = [ "proto/pg_catalog.proto" ]
}
