library("lib") {
  public_deps = [
    ":protos",
    "//library/cpp/threading/future",
    "//ydb/core/nbs/cloud/blockstore/libs/common",
    "//ydb/core/nbs/cloud/blockstore/libs/diagnostics",
    "//ydb/core/nbs/cloud/blockstore/libs/service",
    "//ydb/core/nbs/cloud/storage/core/libs/common",
    "//ydb/core/nbs/cloud/storage/core/libs/diagnostics",
  ]

  sources = [
    "app_context.cpp",
    "buffer_pool.cpp",
    "helpers.cpp",
    "range_allocator.cpp",
    "range_map.cpp",
    "request_generator.cpp",
    "test_runner.cpp",
  ]
}

protobuf_library("protos") {
  sources = [ "protos/nbs2_load.proto" ]

  extra_plugins = [
    {
      name = "validation"
      target = "//ydb/public/lib/validation"
    },
  ]
}
