library("highlight") {
  public_deps = [
    # "//yql/essentials/sql/v1/lexer/regex",
    # "//yql/essentials/sql/v1/reflect",
  ]

  deps = [
    # "//contrib/libs/re2",
    # "//library/cpp/json",
    # "//library/cpp/resource",
  ]

  sources = [
    "data_language_json.cpp",
    "sql_highlight.cpp",
    "sql_highlight_json.cpp",
    "sql_highlighter.cpp",
  ]
}
