unittest_executable("ut") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/backup/common",
  ]

  sources = [
    "//ydb/core/backup/common/encryption_ut.cpp",
    "//ydb/core/backup/common/metadata_ut.cpp",
  ]

  include_dirs = [ "//ydb/core/backup/common" ]

  link_select = [
    "YqlServicePolicy=stub",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
