library("http_proxy") {
  public_deps = [
    "//library/cpp/http/server",
    "//library/cpp/json",
    "//ydb/core/protos",
    "//ydb/library/http_proxy/authorization",
    "//ydb/public/api/grpc",
    "//ydb/public/api/grpc:draft",
    "//ydb/public/api/protos",
    "//ydb/public/sdk/cpp/src/client/driver",
    "//ydb/public/sdk/cpp/src/library/grpc/client",
    "//ydb/services/datastreams:codes",
  ]

  deps = [
    "//library/cpp/cache",
    "//library/cpp/cgiparam",
    "//library/cpp/digest/old_crc",
    "//library/cpp/http/misc",
    "//library/cpp/monlib/dynamic_counters",
    "//library/cpp/monlib/metrics",
    "//library/cpp/protobuf/json",
    "//library/cpp/string_utils/base64",
    "//library/cpp/uri",
    "//ydb/core/base",
    "//ydb/core/grpc_caching",
    "//ydb/core/grpc_services",
    "//ydb/core/grpc_services/local_rpc",
    "//ydb/core/security",
    "//ydb/core/tx/scheme_board",
    "//ydb/core/viewer:json",
    "//ydb/core/ymq/actor",
    "//ydb/library/actors/core",
    "//ydb/library/actors/http",
    "//ydb/library/folder_service",
    "//ydb/library/grpc/actor_client",
    "//ydb/library/grpc/server",
    "//ydb/library/http_proxy/error",
    "//ydb/library/naming_conventions",
    "//ydb/library/ycloud/api",
    "//ydb/library/ycloud/impl",
    "//ydb/public/sdk/cpp/adapters/issue",
    "//ydb/public/sdk/cpp/src/client/datastreams",
    "//ydb/public/sdk/cpp/src/client/iam_private",
    "//ydb/public/sdk/cpp/src/client/topic/impl",
    "//ydb/public/sdk/cpp/src/client/types/credentials",
    "//ydb/services/datastreams",
    "//ydb/services/lib/sharding",
    "//ydb/services/persqueue_v1:actors",
    "//ydb/services/sqs_topic",
    "//ydb/services/sqs_topic/queue_url",
    "//ydb/services/ymq",
    "//yql/essentials/public/issue",
  ]

  sources = [
    "auth_actors.cpp",
    "auth_factory.cpp",
    "discovery_actor.cpp",
    "exceptions_mapping.cpp",
    "grpc_service.cpp",
    "http_req.cpp",
    "http_service.cpp",
    "metrics_actor.cpp",
  ]
}
