library("chunks") {
  deps = [
    "//ydb/core/formats/arrow",
    # "//ydb/core/sys_view/common",
    "//ydb/core/tx/columnshard/blobs_reader",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/constructor",
    "//ydb/core/tx/columnshard/engines/reader/common_reader/iterator",
    "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator",
    "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/abstract",
    # "//ydb/core/tx/conveyor_composite/usage",
    # "//ydb/library/formats/arrow",
  ]

  sources = [
    "constructor.cpp",
    "metadata.cpp",
    "schema.cpp",
    "source.cpp",
  ]
}
