protobuf_library("grpc") {
    deps = [
        "protos",
    ]

    sources = [
        "grpc/draft/dummy.proto",
        "grpc/draft/fq_v1.proto",
        "grpc/draft/ydb_backup_v1.proto",
        "grpc/draft/ydb_bridge_v1.proto",
        "grpc/draft/ydb_clickhouse_internal_v1.proto",
        "grpc/draft/ydb_datastreams_v1.proto",
        "grpc/draft/ydb_dynamic_config_v1.proto",
        "grpc/draft/ydb_logstore_v1.proto",
        "grpc/draft/ydb_maintenance_v1.proto",
        "grpc/draft/ydb_nbs_v1.proto",
        "grpc/draft/ydb_object_storage_v1.proto",
        "grpc/draft/ydb_persqueue_v1.proto",
        "grpc/draft/ydb_replication_v1.proto",
        "grpc/draft/ydb_sqs_topic_v1.proto",
        "grpc/draft/ydb_tablet_v1.proto",
        "grpc/draft/ydb_test_shard_v1.proto",
        "grpc/draft/ydb_view_v1.proto",
        "grpc/draft/ydb_ymq_v1.proto",
        "grpc/ydb_auth_v1.proto",
        "grpc/ydb_cms_v1.proto",
        "grpc/ydb_config_v1.proto",
        "grpc/ydb_coordination_v1.proto",
        "grpc/ydb_debug_v1.proto",
        "grpc/ydb_discovery_v1.proto",
        "grpc/ydb_export_v1.proto",
        "grpc/ydb_federation_discovery_v1.proto",
        "grpc/ydb_import_v1.proto",
        "grpc/ydb_keyvalue_v1.proto",
        "grpc/ydb_keyvalue_v2.proto",
        "grpc/ydb_monitoring_v1.proto",
        "grpc/ydb_operation_v1.proto",
        "grpc/ydb_query_v1.proto",
        "grpc/ydb_rate_limiter_v1.proto",
        "grpc/ydb_scheme_v1.proto",
        "grpc/ydb_scripting_v1.proto",
        "grpc/ydb_table_v1.proto",
        "grpc/ydb_topic_v1.proto",
    ]
}
