library("common") {
  public_deps = [
    # "//library/cpp/logger",
    # "//library/cpp/yson/node",
    # "//yql/essentials/ast",
    # "//yql/essentials/core",
    "//yql/essentials/core/services/mounts",
    "//yql/essentials/core/user_data",
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/computation",
    "//yql/essentials/minikql/invoke_builtins",
    # "//yql/essentials/minikql:alloc",
    "//yql/essentials/providers/common/mkql",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/public/langver",
    "//yql/essentials/public/udf",
    "//yql/essentials/utils/backtrace",
  ]

  deps = [
    # "//library/cpp/random_provider",
    # "//library/cpp/time_provider",
    # "//yql/essentials/core/expr_nodes",
    "//yql/essentials/core/langver",
    "//yql/essentials/core/peephole_opt",
    "//yql/essentials/core/services",  # peerdir only
    "//yql/essentials/core/services:pipeline",
    "//yql/essentials/core/type_ann",
    "//yql/essentials/minikql/comp_nodes",
    # "//yql/essentials/minikql/comp_nodes/llvm16",  # link slot
    # "//yql/essentials/minikql/computation/llvm16",  # link slot
    # "//yql/essentials/minikql/invoke_builtins/llvm16",  # link slot
    # "//yql/essentials/parser/pg_wrapper",  # link slot
    # "//yql/essentials/parser/pg_wrapper/interface",
    # "//yql/essentials/parser/pg_wrapper/interface:yql_pg_sql_translator",
    "//yql/essentials/providers/common/arrow_resolve",
    "//yql/essentials/providers/common/codec",
    "//yql/essentials/providers/common/comp_nodes",
    "//yql/essentials/providers/common/provider",
    "//yql/essentials/providers/common/schema/expr",
    "//yql/essentials/providers/common/udf_resolve",
    "//yql/essentials/providers/config",
    # "//yql/essentials/sql",
    # "//yql/essentials/sql/pg",  # link slot
    "//yql/essentials/sql/v1",
    "//yql/essentials/sql/v1/lexer/antlr4",
    "//yql/essentials/sql/v1/lexer/antlr4_ansi",
    "//yql/essentials/sql/v1/proto_parser/antlr4",
    "//yql/essentials/sql/v1/proto_parser/antlr4_ansi",
    "//yql/essentials/utils/log",
    # "//yt/yql/providers/yt/codec/codegen",  # peerdir only
  ]

  sources = [
    "compile_mkql.cpp",
    "fwd.cpp",
    "inspect_input.cpp",
    "interface.cpp",
    "logger_init.cpp",
    "names.cpp",
    "processor_mode.cpp",
    "program_factory.cpp",
    "transformations/align_output_schema.cpp",
    "transformations/extract_used_columns.cpp",
    "transformations/output_columns_filter.cpp",
    "transformations/replace_table_reads.cpp",
    "transformations/root_to_blocks.cpp",
    "transformations/type_annotation.cpp",
    "transformations/utils.cpp",
    "type_from_schema.cpp",
    "worker.cpp",
    "worker_factory.cpp",
    "wrappers.cpp",
  ]

  serialize_enum_headers = [ "interface.h" ]
}
