library("cloud_events") {
  public_deps = [
    # "//ydb/core/kqp/common",
    # "//ydb/core/ymq/base",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/public/sdk/cpp/src/client/table",
    # ":proto",
  ]

  deps = [
    # "//ydb/core/audit",
  ]

  sources = [ "cloud_events.cpp" ]
}

protobuf_library("proto") {
  public_deps = [
    "//contrib/libs/googleapis-common-protos",
    "//ydb/public/api/client/yc_public/common",
    "//ydb/public/api/client/yc_public/events",
  ]

  sources = [ "proto/ymq.proto" ]
}
