library("engine") {
  public_deps = [
    # "//library/cpp/deprecated/enum_codegen",
    # "//library/cpp/random_provider",
    # "//library/cpp/time_provider",
    # "//ydb/core/protos",
    "//ydb/core/scheme",
    # "//ydb/core/scheme_types",
    "//ydb/library/mkql_proto",
    # "//ydb/library/mkql_proto:protos",
    # "//ydb/public/api/protos",
    "//yql/essentials/minikql",
    # "//yql/essentials/minikql/computation",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/tablet",
    "//ydb/core/tablet_flat",
    "//ydb/library/actors/core",
    # "//ydb/public/lib/scheme_types",
    "//yql/essentials/minikql/comp_nodes",
    # "//yql/essentials/parser/pg_wrapper/interface",
    # "//yql/essentials/public/decimal",
  ]

  sources = [
    "kikimr_program_builder.cpp",
    "mkql_engine_flat.cpp",
    "mkql_engine_flat_extfunc.cpp",
    "mkql_engine_flat_host.cpp",
    "mkql_keys.cpp",
    "mkql_proto.cpp",
  ]
}

library("minikql") {
  public_deps = [
    # "//ydb/core/engine",
    "//ydb/core/scheme",
    # "//ydb/core/tablet",
    "//ydb/core/tablet_flat",
    # "//yql/essentials/minikql",
  ]

  deps = [
    # "//library/cpp/containers/stack_vector",
    "//ydb/core/base",
    "//ydb/core/client/minikql_compile",
    # "//ydb/core/formats",
    # "//ydb/core/protos",
    # "//ydb/core/tx/locks",
    # "//ydb/library/ydb_issue:proto",
    "//ydb/library/yql/public/ydb_issue",
    # "//ydb/public/api/protos",
    "//yql/essentials/minikql/computation",
    # "//yql/essentials/parser/pg_wrapper/interface",
    "//yql/essentials/public/issue",
  ]

  sources = [
    "minikql/flat_local_tx_factory.cpp",
    "minikql/minikql_engine_host.cpp",
  ]
}
