unittest_executable("ut_board_subscriber") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/base",
    "//ydb/core/scheme",
    "//ydb/core/testlib/basics",
    "//ydb/core/testlib/basics:default",  # peerdir only
    "//ydb/library/actors/core",
    "//ydb/library/actors/interconnect",
    "//yql/essentials/minikql/comp_nodes/llvm16",  # peerdir only
  ]

  sources = [ "//ydb/core/base/board_subscriber_ut.cpp" ]

  include_dirs = [ "//ydb/core/base" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
