library("dom") {
  public_deps = [ "//yql/essentials/public/udf" ]

  deps = [
    "//library/cpp/containers/stack_vector",
    "//library/cpp/json",
    "//library/cpp/yson_pull",
    "//yql/essentials/utils",
  ]

  sources = [
    "hash.cpp",
    "json.cpp",
    "make.cpp",
    "node.cpp",
    "peel.cpp",
    "yson.cpp",
  ]
}
