library("codes") {
  sources = [ "codes/datastreams_codes.cpp" ]
}

library("datastreams") {
  public_deps = [
    "//library/cpp/string_utils/base64",
    # "//ydb/core/client:server",
    "//ydb/core/grpc_services",
    # "//ydb/core/grpc_services/base",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
    # "//ydb/library/grpc/server",
    "//ydb/public/api/grpc:draft",
    # "//ydb/public/api/protos",
  ]

  deps = [
    # ":codes",
    "//library/cpp/digest/md5",
    # "//ydb/core/base",
    # "//ydb/core/mind",  # peerdir only
    # "//ydb/core/persqueue",
    # "//ydb/core/persqueue/events",
    "//ydb/core/persqueue/public",
    "//ydb/core/persqueue/public:list_topics",
    # "//ydb/core/persqueue/public:partition_key_range",
    "//ydb/core/persqueue/public:utils",
    "//ydb/core/persqueue/public:write_meta",
    "//ydb/core/persqueue/writer:partition_chooser",
    # "//ydb/core/tx/scheme_board",
    # "//ydb/library/cloud_permissions",
    # "//ydb/public/api/grpc",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/datastreams",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/resources",  # peerdir only
    # "//ydb/public/sdk/cpp/src/library/operation_id",  # peerdir only
    "//ydb/services/lib/actors",
    "//ydb/services/lib/sharding",
    # "//ydb/services/persqueue_v1",  # peerdir only
    "//ydb/services/persqueue_v1:actors",
    # "//ydb/services/ydb",  # peerdir only
  ]

  sources = [
    "datastreams_proxy.cpp",
    "grpc_service.cpp",
    "next_token.cpp",
    "put_records_actor.cpp",
    "shard_iterator.cpp",
  ]
}
