library("file_storage") {
  public_deps = [
    # "//library/cpp/cache",
    # "//library/cpp/threading/future",
    "//library/cpp/uri",
    # "//yql/essentials/core/file_storage/defs",
  ]

  deps = [
    "//library/cpp/digest/md5",
    "//library/cpp/http/io",
    # "//library/cpp/logger/global",  # peerdir only
    "//library/cpp/protobuf/util",
    "//library/cpp/resource",
    # "//yql/essentials/core/file_storage/download",
    "//yql/essentials/core/file_storage/http_download",
    "//yql/essentials/core/file_storage/proto",
    # "//yql/essentials/public/issue",
    "//yql/essentials/utils",
    "//yql/essentials/utils/fetch",
    "//yql/essentials/utils/log",
  ]

  sources = [
    "file_storage.cpp",
    "file_storage_decorator.cpp",
    "sized_cache.cpp",
    "storage.cpp",
    "url_meta.cpp",
  ]
}
