library("grpc_connections") {
  public_deps = [
    "//ydb/public/api/grpc",
    # "//ydb/public/sdk/cpp/src/client/common_client",
    # "//ydb/public/sdk/cpp/src/client/extension_common",
    "//ydb/public/sdk/cpp/src/client/impl/internal/common",
    "//ydb/public/sdk/cpp/src/client/impl/internal/db_driver_state",
    "//ydb/public/sdk/cpp/src/client/impl/stats",
    "//ydb/public/sdk/cpp/src/client/impl/internal/plain_status",
    "//ydb/public/sdk/cpp/src/client/impl/internal/rpc_request_settings",
    "//ydb/public/sdk/cpp/src/client/resources",
    "//ydb/public/sdk/cpp/src/library/issue",
  ]

  deps = [
    "//library/cpp/logger",
    "//library/cpp/threading/future",
    "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/client/types/credentials",
    "//ydb/public/sdk/cpp/src/client/types/exceptions",
    "//ydb/public/sdk/cpp/src/client/types/executor",
    "//ydb/public/sdk/cpp/src/client/types/status",
    "//ydb/public/sdk/cpp/src/library/grpc/client",
    "//ydb/public/sdk/cpp/src/library/time",
  ]

  sources = [
    "actions.cpp",
    "grpc_connections.cpp",
  ]
}
