unittest_executable("ut") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/public_http",
    "//ydb/services/kesus",  # peerdir only
    "//ydb/services/persqueue_cluster_discovery",  # peerdir only
    "//yql/essentials/minikql/comp_nodes/llvm16",  # peerdir only
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
    "//yql/essentials/sql/pg_dummy",  # peerdir only
    "//yt/yql/providers/yt/comp_nodes/dq/llvm16",  # peerdir only
    "//yt/yql/providers/yt/comp_nodes/llvm16",  # peerdir only
  ]

  sources = [ "//ydb/core/public_http/http_router_ut.cpp" ]

  include_dirs = [ "//ydb/core/public_http" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
