library("rate_limiter") {
  public_deps = [
    # "//ydb/public/sdk/cpp/src/client/driver",
  ]

  deps = [
    # "//ydb/public/api/grpc",
    # "//ydb/public/sdk/cpp/src/client/common_client:impl",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/make_request",
  ]

  sources = [ "rate_limiter.cpp" ]
}
