library("color") {
  public_deps = [
    "//contrib/restricted/patched/replxx",
  ]

  sources = [ "color/schema.cpp" ]
}

library("highlight") {
  public_deps = [
    ":color",
    "//contrib/libs/ftxui",
    "//contrib/restricted/patched/replxx",
  ]

  deps = [
    "//yql/essentials/sql/v1/highlight",
  ]

  sources = [ "yql_highlighter.cpp" ]
}
