library("ydb_convert") {
  public_deps = [
    "//ydb/core/base",
    "//ydb/core/protos",
    # "//ydb/core/scheme",
    # "//ydb/core/scheme_types",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/library/mkql_proto:protos",
    # "//ydb/public/api/protos",
    "//ydb/public/sdk/cpp/src/client/value",
  ]

  deps = [
    "//library/cpp/json",
    # "//library/cpp/json:writer",
    "//library/cpp/protobuf/json",
    # "//ydb/core/engine",
    "//ydb/core/external_sources",
    # "//ydb/core/formats/arrow:switch",
    # "//ydb/core/kafka_proxy",
    "//ydb/core/persqueue/public:utils",
    "//ydb/core/protos",
    # "//ydb/core/scheme:protos",
    "//ydb/library/aclib",
    # "//ydb/library/conclusion",
    "//ydb/library/mkql_proto",
    "//ydb/library/persqueue/topic_parser",
    "//ydb/library/ydb_issue",
    # "//ydb/library/ydb_issue:proto",
    "//ydb/library/yql/providers/common/db_id_async_resolver",
    # "//ydb/library/yverify_stream",
    # "//yql/essentials/core/expr_nodes",
    # "//yql/essentials/minikql",
    "//yql/essentials/minikql/dom",
    "//yql/essentials/public/decimal",
    "//yql/essentials/public/issue",
    "//yql/essentials/public/issue:protos",
    # "//yql/essentials/public/udf",
    "//yql/essentials/types/binary_json",
    "//yql/essentials/types/dynumber",
    # "//yql/essentials/utils",
  ]

  sources = [
    "column_families.cpp",
    "compression.cpp",
    "external_data_source_description.cpp",
    "external_table_description.cpp",
    "kesus_description.cpp",
    "replication_description.cpp",
    "table_description.cpp",
    "table_profiles.cpp",
    "table_settings.cpp",
    "topic_description.cpp",
    "tx_proxy_status.cpp",
    "ydb_convert.cpp",
  ]
}
