library("abstract") {
  public_deps = [
    # "//ydb/core/formats/arrow:rows",
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/engines/scheme",
  ]

  deps = [
    # "//ydb/core/formats/arrow/accessor/plain",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/common",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/constructor",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/iterator",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator",
    # "//ydb/core/tx/conveyor_composite/usage",
    # "//ydb/library/formats/arrow",
  ]

  sources = [
    "constructor.cpp",
    "metadata.cpp",
    "schema.cpp",
    "source.cpp",
  ]
}
