library("grpc_services") {
  public_deps = [
    "//library/cpp/monlib/service/pages",
    "//ydb/core/actorlib_impl",
    "//ydb/core/base",
    # "//ydb/core/cms/console",
    # "//ydb/core/control/lib",
    # "//ydb/core/fq/libs/control_plane_proxy:utils",
    "//ydb/core/grpc_services/base",
    "//ydb/core/grpc_services/cancelation",
    "//ydb/core/grpc_services/counters",
    "//ydb/core/health_check",
    "//ydb/core/kqp/common",
    "//ydb/core/protos",
    # "//ydb/core/scheme",
    # "//ydb/core/tablet",
    # "//ydb/core/tablet_flat",
    "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    "//ydb/core/tx/tx_proxy:public",
    # "//ydb/core/util",
    "//ydb/core/ydb_convert",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    "//ydb/library/grpc/server",
    # "//ydb/library/persqueue/topic_parser",
    # "//ydb/library/services",
    # "//ydb/library/wilson_ids",
    "//ydb/library/ydb_issue",
    "//ydb/public/api/grpc:draft",
    "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/client/resources",
    "//ydb/public/sdk/cpp/src/library/operation_id",
    # "//yql/essentials/public/issue",
  ]

  deps = [
    # "//contrib/libs/protobuf",
    # "//contrib/libs/xxhash",  # peerdir only
    # "//library/cpp/cache",
    # "//library/cpp/cgiparam",  # peerdir only
    # "//library/cpp/digest/old_crc",
    # "//library/cpp/json",
    "//library/cpp/regex/pcre",
    # "//library/cpp/retry",
    # "//library/cpp/streams/zstd",
    # "//library/cpp/yson",
    "//ydb/core/audit",
    "//ydb/core/audit:audit_config",
    "//ydb/core/backup/common",
    "//ydb/core/backup/regexp",
    # "//ydb/core/blobstorage/base",
    "//ydb/core/blobstorage/events",
    # "//ydb/core/blobstorage/nodewarden",
    # "//ydb/core/client:minikql_compile",
    # "//ydb/core/cms",
    # "//ydb/core/counters_info",
    "//ydb/core/discovery",
    # "//ydb/core/driver_lib/run:_self",
    # "//ydb/core/engine",
    # "//ydb/core/formats",  # peerdir only
    "//ydb/core/fq/libs/audit",
    "//ydb/core/fq/libs/audit:events",
    "//ydb/core/fq/libs/control_plane_proxy:events",
    "//ydb/core/fq/libs/control_plane_storage:util",
    "//ydb/core/fq/libs/events",
    # "//ydb/core/fq/libs/protos",
    "//ydb/core/grpc_services/local_rpc",
    "//ydb/core/grpc_streaming",
    "//ydb/core/io_formats/ydb_dump",
    "//ydb/core/kesus/proxy",
    "//ydb/core/kesus/tablet",
    "//ydb/core/keyvalue",
    # "//ydb/core/kqp/common:events",
    # "//ydb/core/kqp/common:simple",
    # "//ydb/core/kqp/compute_actor:events",
    # "//ydb/core/kqp/executer_actor",
    "//ydb/core/kqp/executer_actor:shards_resolver",
    "//ydb/core/kqp/opt",
    # "//ydb/core/mind",
    # "//ydb/core/mind:bscontroller",
    # "//ydb/core/mind:hive",
    # "//ydb/core/mon",
    "//ydb/core/nbs/cloud/blockstore/config",
    # "//ydb/core/nbs/cloud/blockstore/libs/service",  # peerdir only
    "//ydb/core/nbs/cloud/blockstore/libs/storage/api",
    "//ydb/core/nbs/cloud/blockstore/libs/storage/partition_direct",
    # "//ydb/core/nbs/cloud/blockstore/public/api/protos",  # peerdir only
    # "//ydb/core/nbs/cloud/storage/core/libs/common",  # peerdir only
    # "//ydb/core/nbs/cloud/storage/core/protos",
    # "//ydb/core/node_whiteboard",
    # "//ydb/core/protos:schemeshard",
    "//ydb/core/quoter:public",
    "//ydb/core/security",
    # "//ydb/core/security:ldap_auth_provider",
    "//ydb/core/security:sasl",
    # "//ydb/core/sys_view",  # peerdir only
    # "//ydb/core/test_tablet",
    # "//ydb/core/tx",
    # "//ydb/core/tx/data_events",  # peerdir only
    # "//ydb/core/tx/datashard",
    "//ydb/core/tx/datashard:read_events",  # peerdir only
    # "//ydb/core/tx/replication/controller",
    "//ydb/core/tx/schemeshard/olap/bg_tasks:events",
    "//ydb/core/tx/sharding",  # peerdir only
    # "//ydb/core/tx/tx_proxy",
    "//ydb/core/tx/tx_proxy:read_table",  # peerdir only
    "//ydb/core/tx/tx_proxy:upload_rows",
    "//ydb/library/actors/http",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/cloud_permissions",
    # "//ydb/library/fyamlcpp",
    "//ydb/library/login",
    "//ydb/library/login:sasl",
    # "//ydb/library/mkql_proto",
    # "//ydb/library/protobuf_printer",  # peerdir only
    "//ydb/library/security",
    "//ydb/library/yaml_config",
    # "//ydb/library/yaml_config/tools/util",
    # "//ydb/library/yaml_config:public",
    # "//ydb/public/api/grpc",
    "//ydb/public/lib/fq",
    "//ydb/public/sdk/cpp/src/client/proto",
    "//ydb/public/sdk/cpp/src/library/operation_id:protos",
    # "//ydb/services/ext_index/common",  # peerdir only
    # "//yql/essentials/core/issue",
    # "//yql/essentials/core/issue:protos",
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/dom",
    # "//yql/essentials/parser/pg_wrapper/interface",
    # "//yql/essentials/public/decimal",
    # "//yql/essentials/public/types",  # peerdir only
    # "//yql/essentials/public/udf",
    # "//yql/essentials/types/binary_json",
    # "//yql/essentials/types/dynumber",
    # "//yql/essentials/utils",
  ]

  sources = [
    "audit_dml_operations.cpp",
    "audit_log.cpp",
    "audit_logins.cpp",
    "fs_path_validation.cpp",
    "grpc_endpoint_publish_actor.cpp",
    "grpc_helper.cpp",
    "grpc_mon.cpp",
    "grpc_publisher_service_actor.cpp",
    "grpc_request_proxy.cpp",
    "grpc_request_proxy_handle_methods.cpp",
    "grpc_request_proxy_simple.cpp",
    "local_rate_limiter.cpp",
    "login_page.cpp",
    "operation_helpers.cpp",
    "query/rpc_attach_session.cpp",
    "query/rpc_execute_query.cpp",
    "query/rpc_execute_script.cpp",
    "query/rpc_kqp_tx.cpp",
    "resolve_local_db_table.cpp",
    "rpc_alter_coordination_node.cpp",
    "rpc_alter_table.cpp",
    "rpc_backup.cpp",
    "rpc_begin_transaction.cpp",
    "rpc_bistream_ping.cpp",
    "rpc_bridge.cpp",
    "rpc_calls.cpp",
    "rpc_cancel_operation.cpp",
    "rpc_cluster_state.cpp",
    "rpc_cms.cpp",
    "rpc_commit_transaction.cpp",
    "rpc_common/rpc_common_kqp_session.cpp",
    "rpc_config.cpp",
    "rpc_coordination_session.cpp",
    "rpc_copy_table.cpp",
    "rpc_copy_tables.cpp",
    "rpc_create_coordination_node.cpp",
    "rpc_create_table.cpp",
    "rpc_describe_coordination_node.cpp",
    "rpc_describe_external_data_source.cpp",
    "rpc_describe_external_table.cpp",
    "rpc_describe_path.cpp",
    "rpc_describe_system_view.cpp",
    "rpc_describe_table.cpp",
    "rpc_describe_table_options.cpp",
    "rpc_discovery.cpp",
    "rpc_drop_coordination_node.cpp",
    "rpc_drop_table.cpp",
    "rpc_dynamic_config.cpp",
    "rpc_execute_data_query.cpp",
    "rpc_execute_scheme_query.cpp",
    "rpc_execute_yql_script.cpp",
    "rpc_explain_data_query.cpp",
    "rpc_explain_yql_script.cpp",
    "rpc_export.cpp",
    "rpc_forget_operation.cpp",
    "rpc_fq.cpp",
    "rpc_fq_internal.cpp",
    "rpc_get_operation.cpp",
    "rpc_get_scale_recommendation.cpp",
    "rpc_get_shard_locations.cpp",
    "rpc_import.cpp",
    "rpc_import_data.cpp",
    "rpc_keep_alive.cpp",
    "rpc_keyvalue.cpp",
    "rpc_kh_describe.cpp",
    "rpc_kh_snapshots.cpp",
    "rpc_kqp_base.cpp",
    "rpc_list_objects_in_s3_export.cpp",
    "rpc_list_operations.cpp",
    "rpc_load_rows.cpp",
    "rpc_log_store.cpp",
    "rpc_login.cpp",
    "rpc_maintenance.cpp",
    "rpc_make_directory.cpp",
    "rpc_modify_permissions.cpp",
    "rpc_monitoring.cpp",
    "rpc_nbs.cpp",
    "rpc_nbs_io.cpp",
    "rpc_node_registration.cpp",
    "rpc_object_storage.cpp",
    "rpc_ping.cpp",
    "rpc_prepare_data_query.cpp",
    "rpc_rate_limiter_api.cpp",
    "rpc_read_rows.cpp",
    "rpc_read_table.cpp",
    "rpc_remove_directory.cpp",
    "rpc_rename_tables.cpp",
    "rpc_replication.cpp",
    "rpc_rollback_transaction.cpp",
    "rpc_scheme_base.cpp",
    "rpc_stream_execute_scan_query.cpp",
    "rpc_stream_execute_yql_script.cpp",
    "rpc_test_shard.cpp",
    "rpc_view.cpp",
    "rpc_whoami.cpp",
    "table_settings.cpp",
    "ydb_over_fq/create_session.cpp",
    "ydb_over_fq/describe_table.cpp",
    "ydb_over_fq/execute_data_query.cpp",
    "ydb_over_fq/explain_data_query.cpp",
    "ydb_over_fq/keep_alive.cpp",
    "ydb_over_fq/list_directory.cpp",
  ]
}

slot_interface_group("topic_rpc") {
  link_slot_interface = "topic_rpc"

  link_slot_headers = [ "service_topic.h" ]

  link_slot_flags_from = [ "audit_dml_operations.cpp" ]
}
