# yamake2gn: keep  -- hand-written, do not regenerate

library("ydb_resources") {
    resources = [
        {
            path = "version.txt"
            key = "version.txt"
        },
    ]
}

linked_executable("ydb") {
    link_select = [
        "YqlServicePolicy=exception_policy",
        "allocator=tcmalloc",
        "minikql_codegen=no_llvm",
        "yql_pg_runtime=pg_dummy",
        "yql_pg_sql_translator=pg_dummy",
    ]

    deps = [
        ":ydb_resources",
        "//ydb/apps/ydb/commands",
        "//ydb/public/lib/ydb_cli/commands",
    ]

    sources = [ "main.cpp" ]
}
