config("public_config") {
    include_dirs = [ "." ]
}

contrib_library("libbz2") {
    sources = [
        "blocksort.c",
        "bzlib.c",
        "compress.c",
        "crctable.c",
        "decompress.c",
        "huffman.c",
        "randtable.c",
    ]

    public_configs = [ ":public_config" ]
}
