library("show_create") {
  public_deps = [
    "//ydb/core/kqp/runtime",
    "//ydb/core/protos",
    # "//ydb/library/actors/core",
    "//ydb/public/api/protos",
    # "//yql/essentials/public/issue",
  ]

  deps = [
    # "//contrib/libs/apache/arrow",
    # "//library/cpp/json",
    # "//library/cpp/protobuf/json",
    # "//library/cpp/protobuf/util",
    # "//ydb/core/base",
    # "//ydb/core/engine",
    "//ydb/core/formats/arrow",
    # "//ydb/core/scheme",
    "//ydb/core/sys_view/common",
    # "//ydb/core/tablet",
    "//ydb/core/tx/columnshard/engines/scheme/defaults/protos",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    "//ydb/core/tx/schemeshard/common",
    # "//ydb/core/tx/sequenceproxy",  # peerdir only
    # "//ydb/core/tx/sequenceproxy:public",
    # "//ydb/core/tx/tx_proxy",  # peerdir only
    # "//ydb/core/tx/tx_proxy:public",
    "//ydb/core/ydb_convert",
    "//ydb/library/formats/arrow/protos",
    # "//ydb/library/yql/dq/actors/compute",
    # "//ydb/public/lib/json_value",  # peerdir only
    "//ydb/public/lib/ydb_cli/dump/util",
    # "//ydb/public/sdk/cpp/src/client/types",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/value",
    "//yql/essentials/ast",
    "//yql/essentials/minikql",
    "//yql/essentials/minikql:alloc",
    "//yql/essentials/parser/proto_ast/gen/v1_antlr4",
    "//yql/essentials/sql/settings",
    "//yql/essentials/sql/v1",
    "//yql/essentials/sql/v1/lexer/antlr4",
    "//yql/essentials/sql/v1/lexer/antlr4_ansi",
    "//yql/essentials/sql/v1/proto_parser/antlr4",
    "//yql/essentials/sql/v1/proto_parser/antlr4_ansi",
  ]

  sources = [
    "create_table_formatter.cpp",
    "create_view_formatter.cpp",
    "formatters_common.cpp",
    "show_create.cpp",
  ]
}
