library("backpressure") {
  public_deps = [
    # "//contrib/libs/protobuf",
    "//library/cpp/monlib/dynamic_counters",
    # "//ydb/core/base",
    # "//ydb/core/blobstorage",
    # "//ydb/core/blobstorage/events",
    # "//ydb/core/blobstorage/groupinfo",
    "//ydb/core/blobstorage/lwtrace_probes",
    "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
    "//ydb/library/actors/wilson",
    # "//ydb/library/wilson_ids",
  ]

  deps = [
    # "//library/cpp/containers/intrusive_rb_tree",  # peerdir only
    "//ydb/core/retro_tracing_impl",
  ]

  sources = [
    "event.cpp",
    "load_based_timeout.cpp",
    "queue.cpp",
    "queue_backpressure_client.cpp",
    "unisched.cpp",
  ]
}
