library("scheme_types") {
    public_deps = [
        "//ydb/public/lib/scheme_types",
    ]

    deps = [
        "//yql/essentials/public/decimal",
    ]

    sources = [
        "scheme_decimal_type.cpp",
        "scheme_type_metadata.cpp",
        "scheme_type_registry.cpp",
        "scheme_types_defs.cpp",
    ]
}
