library("cms") {
  public_deps = [ "//ydb/public/sdk/cpp/src/client/driver" ]

  deps = [
    "//library/cpp/threading/future",
    # "//ydb/public/api/grpc",
    # "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/client/common_client:impl",
    "//ydb/public/sdk/cpp/src/client/impl/internal/make_request",
  ]

  sources = [ "cms.cpp" ]
}
