library("common") {
  public_deps = [
    "//contrib/libs/apache/arrow",
    "//ydb/core/base",
    "//ydb/core/formats/arrow:rows",
    "//ydb/library/accessor",
    "//ydb/library/conclusion",
    "//ydb/library/formats/arrow:protos",
  ]

  deps = [
    # "//library/cpp/json:writer",
    # "//ydb/core/protos",
    # "//ydb/core/scheme:protos",
    # "//ydb/core/sys_view:common",
    # "//ydb/core/tx/columnshard/data_sharing/protos",
    # "//ydb/core/tx/columnshard/export/protos",
    # "//ydb/core/tx/columnshard/transactions:protos",
    # "//ydb/library/actors/core",
    # "//ydb/library/formats/arrow:switch",
    # "//ydb/library/yverify_stream",
    # ":protos",
  ]

  sources = [
    "blob.cpp",
    "limits.cpp",
    "path_id.cpp",
    "portion.cpp",
    "reverse_accessor.cpp",
    "scalars.cpp",
    "snapshot.cpp",
    "tablet_id.cpp",
    "thread_safe_optional.cpp",
    "volume.cpp",
  ]

  serialize_enum_headers = [ "portion.h" ]
}

protobuf_library("protos") {
  sources = [
    "protos/blob_range.proto",
    "protos/snapshot.proto",
  ]
}
