library("binding") {
  public_deps = [ ":service" ]

  deps = [ ":static" ]

  sources = [ "binding/name_service.cpp" ]
}

library("column") {
  public_deps = [
    # ":ranking",
    # ":service",
    # "//yql/essentials/sql/v1/complete/analysis/global",
  ]

  deps = [
    "//library/cpp/case_insensitive_string",
    "//yql/essentials/sql/v1/complete/name/object/simple:static",
  ]

  sources = [
    "column/name_service.cpp",
    "column/replicating.cpp",
  ]
}

library("impatient") {
  public_deps = [
    # ":service",
  ]

  sources = [ "impatient/name_service.cpp" ]
}

library("ranking") {
  public_deps = [ ":service" ]

  deps = [
    "//library/cpp/json",
    "//library/cpp/resource",
  ]

  sources = [
    "ranking/dummy.cpp",
    "ranking/frequency.cpp",
    "ranking/ranking.cpp",
  ]

  resources = [
    {
      path = "//yql/essentials/data/language/rules_corr_basic.json"
      key = "rules_corr_basic.json"
    },
  ]
}

library("schema") {
  public_deps = [
    # ":service",
    # "//yql/essentials/sql/v1/complete/name/object",
  ]

  deps = [
    # "//library/cpp/iterator",
    "//library/cpp/threading/future",
  ]

  sources = [ "schema/name_service.cpp" ]
}

library("service") {
  public_deps = [
    "//library/cpp/threading/future",
    "//yql/essentials/sql/v1/complete:core",
  ]

  sources = [ "name_service.cpp" ]
}

library("static") {
  public_deps = [
    # ":ranking",
    # ":service",
    # "//yql/essentials/sql/v1/complete:core",
    "//yql/essentials/sql/v1/complete:text",
  ]

  deps = [
    ":union",
    "//library/cpp/json",
    "//library/cpp/resource",
  ]

  sources = [
    "static/name_index.cpp",
    "static/name_service.cpp",
    "static/name_set.cpp",
    "static/name_set_json.cpp",
  ]

  resources = [
    {
      path = "//yql/essentials/data/language/pragmas_opensource.json"
      key = "pragmas_opensource.json"
    },
    {
      path = "//yql/essentials/data/language/types.json"
      key = "types.json"
    },
    {
      path = "//yql/essentials/data/language/sql_functions.json"
      key = "sql_functions.json"
    },
    {
      path = "//yql/essentials/data/language/udfs_basic.json"
      key = "udfs_basic.json"
    },
    {
      path = "//yql/essentials/data/language/statements_opensource.json"
      key = "statements_opensource.json"
    },
    {
      path = "//yql/essentials/data/language/rules_corr_basic.json"
      key = "rules_corr_basic.json"
    },
  ]
}

library("union") {
  public_deps = [
    ":ranking",
    # ":service",
  ]

  deps = [ "//library/cpp/threading/future" ]

  sources = [ "union/name_service.cpp" ]
}
