library("versions") {
  public_deps = [
    # "//ydb/core/formats/arrow",
    "//ydb/core/formats/arrow:common",
    # "//ydb/core/formats/arrow:save_load",
    # "//ydb/core/tx/columnshard/blobs_action:abstract",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/counters",
    "//ydb/core/tx/columnshard/engines/scheme",
    # "//ydb/core/tx/columnshard/engines/scheme/abstract",
    # "//ydb/core/tx/columnshard/engines/scheme/common",
    # "//ydb/core/tx/data_events:common",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/formats/arrow/accessor/plain",
    # "//ydb/core/formats/arrow:serializer",
    # "//ydb/core/protos",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/abstract",
    # "//ydb/core/tx/columnshard/engines/storage/chunks",
    # "//ydb/core/tx/columnshard/hooks/abstract",
    # "//ydb/core/tx/columnshard/splitter",
    # "//ydb/library/formats/arrow",
  ]

  sources = [
    "abstract_scheme.cpp",
    "filtered_scheme.cpp",
    "preset_schemas.cpp",
    "snapshot_scheme.cpp",
    "versioned_index.cpp",
  ]
}
