unittest_executable("ut_encrypted_storage") {
  deps = [
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//ydb/core/base",
    "//ydb/core/blobstorage/events",
    "//ydb/core/protos",
    "//ydb/core/tablet",
    "//ydb/core/testlib",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx",  # peerdir only
    "//ydb/core/tx/schemeshard",
    "//ydb/core/tx/tx_proxy",  # peerdir only
    "//ydb/library/actors/interconnect",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
  ]

  sources = [
    "//ydb/core/tx/tx_proxy/encrypted_storage_ut.cpp",
    "//ydb/core/tx/tx_proxy/proxy_ut_helpers.cpp",
  ]

  include_dirs = [
    "//ydb/core/tx/tx_proxy",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
