# yamake2gn: keep  -- hand-written, do not regenerate

library("version") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/library/actors/interconnect",
  ]

  deps = [
    "//library/cpp/svnversion",
    "//ydb/core/viewer:json",
    # "//ydb/library/global_plugins",
    # "//ydb/library/yverify_stream",
  ]

  sources = [
    "version.cpp",

    "//ydb/apps/version/version_definition.cpp",
  ]
}
