unittest_executable("ut_worker") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/tx/replication/service",
    "//ydb/core/tx/replication/ut_helpers",
    "//ydb/core/tx/replication/ydb_proxy",
    "//ydb/public/sdk/cpp/src/client/topic",
  ]

  sources = [ "//ydb/core/tx/replication/service/worker_ut.cpp" ]

  include_dirs = [ "//ydb/core/tx/replication/service" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_wrapper",
    "yql_pg_sql_translator=pg",
    "yt_codegen=llvm16",
  ]
}
