library("locks") {
  public_deps = [
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/engines/predicate",
    # "//ydb/services/bg_tasks/abstract",
  ]

  deps = [
    # "//ydb/core/formats/arrow",
    # "//ydb/core/formats/arrow:rows",
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx/columnshard",
    # "//ydb/library/accessor",
    # "//ydb/library/formats/arrow",
    # ":protos",
  ]

  sources = [
    "locks/abstract.cpp",
    "locks/dependencies.cpp",
    "locks/interaction.cpp",
    "locks/read_finished.cpp",
    "locks/read_start.cpp",
    "locks/write.cpp",
  ]
}

protobuf_library("protos") {
  sources = [ "protos/tx_event.proto" ]
}

library("transactions") {
  public_deps = [
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/data_events",
    # "//ydb/core/tx/locks",
  ]

  deps = [
    # "//ydb/core/tx/columnshard/subscriber/events/tx_completed",
    # ":transactions_transactions",
  ]

  sources = [
    "locks_db.cpp",
    "tx_controller.cpp",
  ]

  serialize_enum_headers = [ "tx_controller.h" ]
}

library("transactions_transactions") {
  public_deps = [
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/common",
  ]

  deps = [
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/scheme/versions",
  ]

  sources = [
    "transactions/tx_add_sharding_info.cpp",
    "transactions/tx_finish_async.cpp",
  ]
}
