library("composite_serial") {
  public_deps = [
    "//ydb/core/formats/arrow/accessor:abstract",
    "//ydb/core/formats/arrow/accessor/composite",
  ]

  deps = [
    "//ydb/core/formats/arrow/accessor/sparsed",
    "//ydb/library/actors/core",
    "//ydb/library/actors/prof",
  ]

  sources = [ "accessor.cpp" ]
}
