# yamake2gn: keep  -- hand-written, do not regenerate

library("issue") {
  public_deps = [
    ":protos",
    "//contrib/libs/protobuf",
    "//library/cpp/resource",
    "//yql/essentials/utils",
  ]

  deps = [
    "//library/cpp/colorizer",
  ]

  sources = [
    "yql_issue.cpp",
    "yql_issue_manager.cpp",
    "yql_issue_message.cpp",
    "yql_issue_utils.cpp",
    "yql_warning.cpp",
  ]

  serialize_enum_headers = [ "yql_warning.h" ]
}

protobuf_library("protos") {
  sources = [
    "protos/issue_message.proto",
    "protos/issue_severity.proto",
  ]
}
