unittest_executable("ut") {
  deps = [
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/regex/pcre",  # peerdir only
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//ydb/core/base",
    "//ydb/core/grpc_services/local_rpc",
    "//ydb/core/kqp/ut/common",  # peerdir only
    "//ydb/core/protos",
    "//ydb/core/scheme",
    "//ydb/core/testlib",
    "//ydb/core/testlib/actors",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx",  # peerdir only
    "//ydb/core/tx/datashard",
    "//ydb/core/tx/datashard/ut_common",
    "//ydb/core/tx/schemeshard",
    "//ydb/core/tx/tx_proxy:public",
    "//ydb/core/tx/tx_proxy:upload_rows",
    "//ydb/library/actors/core",
    "//ydb/library/ut",
    "//ydb/public/lib/yson_value",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/result",
    "//yql/essentials/public/issue",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
  ]

  sources = [
    "ut_filter_kmeans.cpp",
    "ut_fulltext.cpp",
    "ut_fulltext_dict.cpp",
    "ut_helpers.cpp",
    "ut_local_kmeans.cpp",
    "ut_prefix_kmeans.cpp",
    "ut_recompute_kmeans.cpp",
    "ut_reshuffle_kmeans.cpp",
    "ut_sample_k.cpp",
    "ut_secondary_index.cpp",
    "ut_unique_index.cpp",
  ]

  include_dirs = [ "//ydb/core/tx/datashard" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
