linked_executable("table-perf") {
  testonly = true

  deps = [
    "//library/cpp/charset/lite",
    "//library/cpp/getopt",
    "//ydb/core/tablet_flat",
    "//ydb/core/tablet_flat/test/libs/rows",
    "//ydb/core/tablet_flat/test/libs/table",
    "//ydb/core/tablet_flat/test/libs/table:model",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
    "//yql/essentials/sql/pg_dummy",  # peerdir only
  ]

  sources = [
    "colons.cpp",
    "main.cpp",
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
