library("binary_json") {
    public_deps = [ "//yql/essentials/minikql/dom" ]
    deps = [
        "//contrib/libs/simdjson",
        "//library/cpp/containers/absl_flat_hash",
        "//library/cpp/json",
        "//yql/essentials/utils",
    ]

    sources = [
        "binary_json/format.cpp",
        "binary_json/read.cpp",
        "binary_json/write.cpp",
    ]

    serialize_enum_headers = [ "binary_json/format.h" ]
}

library("dynumber") {
    sources = [
        "dynumber/dynumber.cpp",
    ]
}

library("uuid") {
    sources = [
        "uuid/uuid.cpp",
    ]
}

group("types") {
    public_deps = [
        ":binary_json",
        ":dynumber",
        ":uuid",
    ]
}
