library("service") {
  public_deps = [
    # "//library/cpp/monlib/dynamic_counters",
    # "//ydb/core/tx/conveyor/usage",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/core",
    # "//ydb/library/signals",
  ]

  deps = [
    # "//library/cpp/lwtrace/mon",
    # "//ydb/core/kqp/query_data",
    # "//ydb/core/tx/conveyor/tracing",
    # "//ydb/library/conclusion",
    # "//ydb/library/services",
  ]

  sources = [
    "service.cpp",
    "worker.cpp",
  ]
}
