unittest_executable("column_shard_config_validator_ut") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/config/validation",
    "//ydb/core/protos",
  ]

  sources = [ "column_shard_config_validator_ut.cpp" ]

  include_dirs = [ "//ydb/core/config/validation" ]

  link_select = [
    "YqlServicePolicy=stub",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
