library("hullcompdelete") {
  public_deps = [
    # "//library/cpp/monlib/service/pages",
    # "//ydb/core/blobstorage/vdisk/huge",
    # "//ydb/core/blobstorage/vdisk/hullop",
  ]

  deps = [
    "//ydb/core/base",
    # "//ydb/core/blobstorage/pdisk",
    "//ydb/core/blobstorage/vdisk/common",
  ]

  sources = [ "hullcompdelete/blobstorage_hullcompdelete.cpp" ]
}

library("hullop") {
  public_deps = [
    # "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/vdisk",
    "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/blobstorage/vdisk/hulldb",
    # "//ydb/core/blobstorage/vdisk/hulldb:bulksst_add",
    "//ydb/core/blobstorage/vdisk/hulldb:cache_block",
    "//ydb/core/blobstorage/vdisk/hulldb:recovery",
    "//ydb/core/blobstorage/vdisk/synclog",
    # "//ydb/core/protos",
  ]

  deps = [
    ":hullcompdelete",
    # "//library/cpp/random_provider",
    "//ydb/core/base",
    # "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/blobstorage/vdisk/balance",
    # "//ydb/core/blobstorage/vdisk/huge",
    # "//ydb/core/blobstorage/vdisk/hulldb:base",
    "//ydb/core/blobstorage/vdisk/hulldb:compstrat",
    # "//ydb/core/blobstorage/vdisk/hulldb:fresh",
    "//ydb/core/blobstorage/vdisk/hulldb:generic",
    # "//ydb/core/blobstorage/vdisk/ingress",
    # "//ydb/core/blobstorage/vdisk/scrub",
    "//ydb/library/actors/wilson",
    # "//ydb/library/wilson_ids",
  ]

  sources = [
    "blobstorage_hull.cpp",
    "blobstorage_hullactor.cpp",
    "blobstorage_hulllog.cpp",
    "blobstorage_hulllogcutternotify.cpp",
    "hullop_compactfreshappendix.cpp",
    "hullop_entryserialize.cpp",
  ]
}
