library("options") {
  public_deps = [
    # "//ydb/core/protos",
    # "//ydb/core/tx/columnshard/data_accessor:abstract",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/abstract",
    # "//ydb/core/tx/schemeshard/olap/common",
    # "//ydb/library/accessor",
  ]

  sources = [
    "schema.cpp",
    "update.cpp",
  ]
}
