library("tiering") {
  public_deps = [
    # "//ydb/core/tx/columnshard/engines/scheme/tiering",
    # "//ydb/core/tx/columnshard/engines/scheme/versions",
    # "//ydb/core/tx/columnshard/engines/storage/actualizer/abstract",
    # "//ydb/core/tx/columnshard/engines/storage/actualizer/common",
    # "//ydb/core/tx/tiering",
  ]

  deps = [
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/data_locks/manager",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/changes/abstract",
    # "//ydb/core/tx/columnshard/engines/changes/actualization/construction",
    # "//ydb/core/tx/columnshard/engines/scheme",
    # "//ydb/core/tx/columnshard/engines/storage/indexes/max",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/abstract",
    # "//ydb/core/tx/columnshard/hooks/abstract",
    # "//ydb/core/tx/columnshard/splitter",
    # "//ydb/library/accessor",
    # "//ydb/library/formats/arrow",
  ]

  sources = [
    "counters.cpp",
    "tiering.cpp",
  ]
}
