unittest_executable("ut_fat") {
  deps = [
    "//contrib/libs/protobuf",
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/regex/pcre",  # peerdir only
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//ydb/core/base",
    "//ydb/core/blobstorage/base",  # peerdir only
    "//ydb/core/blobstorage/crypto",
    "//ydb/core/blobstorage/events",
    "//ydb/core/blobstorage/nodewarden",
    "//ydb/core/blobstorage/pdisk",
    "//ydb/core/blobstorage/vdisk/common",
    "//ydb/core/mind",
    "//ydb/core/mind/bscontroller",
    "//ydb/core/testlib",
    "//ydb/core/testlib/basics",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/util",
  ]

  sources = [ "blobstorage_node_warden_ut_fat.cpp" ]

  include_dirs = [ "//ydb/core/mind" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
