library("common") {
  public_deps = [
    "//ydb/core/base",
    "//ydb/core/protos",
    # "//ydb/library/yverify_stream",
  ]

  deps = [
    ":proto",
    "//contrib/libs/openssl",
    "//library/cpp/json",
    "//ydb/core/util",
  ]

  sources = [
    "checksum.cpp",
    "encryption.cpp",
    "metadata.cpp",
  ]

  serialize_enum_headers = [ "metadata.h" ]
}

protobuf_library("proto") {
  public_deps = [ "//ydb/public/api/protos/annotations" ]
  sources = [ "proto/encrypted_file.proto" ]
}
