library("abstract") {
  public_deps = [
    # "//library/cpp/json:writer",
    # "//ydb/core/formats/arrow:program",
    # "//ydb/core/protos",
    # "//ydb/core/tx/columnshard/engines/storage/chunks",
    # "//ydb/core/tx/columnshard/splitter",
    # "//ydb/core/tx/schemeshard/olap/common",
    # "//ydb/library/accessor",
    # "//ydb/library/conclusion",
    # "//ydb/library/formats/arrow:protos",
    # "//ydb/services/bg_tasks/abstract",
  ]

  deps = [
    # "//contrib/libs/xxhash",
    # "//ydb/core/tx/columnshard/blobs_reader",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/iterator",
    # "//ydb/core/tx/columnshard/engines/storage/indexes/portions",
    # "//ydb/core/tx/columnshard/engines/storage/indexes/skip_index",
    # "//ydb/library/actors/core",
  ]

  sources = [
    "abstract.cpp",
    "checker.cpp",
    "collection.cpp",
    "common.cpp",
    "constructor.cpp",
    "fetcher.cpp",
    "header.cpp",
    "meta.cpp",
  ]

  serialize_enum_headers = [ "common.h" ]
}
