library("init") {
  public_deps = [
    # "//library/cpp/getopt:small",
    "//ydb/core/base",
    # "//ydb/core/driver_lib/run",
    # "//ydb/core/protos",
    # "//ydb/core/util",
    # "//ydb/library/actors/core",
    "//ydb/library/yaml_config",
  ]

  deps = [
    # "//ydb/core/config/validation",
    # "//ydb/core/driver_lib/cli_config_base",
    # "//ydb/library/aclib",
    # "//ydb/library/yaml_json",
    # "//ydb/public/lib/deprecated/kicli",
    # "//ydb/public/lib/ydb_cli/common",
    # "//ydb/public/sdk/cpp/src/client/config",
    # "//ydb/public/sdk/cpp/src/client/discovery",
    # "//ydb/public/sdk/cpp/src/client/driver",
  ]

  sources = [
    "dummy.cpp",
    "init.cpp",
    "init_noop.cpp",
  ]

  serialize_enum_headers = [ "init.h" ]
}
