library("discovery") {
  public_deps = [
    "//ydb/core/base",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/interconnect",
  ]

  deps = [
    "//library/cpp/monlib/dynamic_counters",
    "//ydb/core/blobstorage/events",
    "//ydb/core/tx/scheme_cache",
    # "//ydb/public/api/protos",
  ]

  sources = [ "discovery.cpp" ]
}
