unittest_executable("ut_double_indexed") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/tx/scheme_board",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
    "//yql/essentials/sql/pg_dummy",  # peerdir only
  ]

  sources = [ "//ydb/core/tx/scheme_board/double_indexed_ut.cpp" ]

  include_dirs = [ "//ydb/core/tx/scheme_board" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
