unittest_executable("ut") {
  deps = [
    "//library/cpp/json",
    "//library/cpp/testing/unittest",
    "//ydb/core/log_backend",
  ]

  sources = [ "//ydb/core/log_backend/json_envelope_ut.cpp" ]

  include_dirs = [ "//ydb/core/log_backend" ]

  link_select = [
    "YqlServicePolicy=stub",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
