library("skip_index") {
  public_deps = [
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/scheme/abstract",
    # "//ydb/core/tx/columnshard/engines/scheme/indexes/abstract",
    # "//ydb/core/tx/columnshard/engines/storage/indexes/bits_storage",
    # "//ydb/core/tx/columnshard/engines/storage/indexes/portions",
    # "//ydb/core/tx/columnshard/splitter:abstract",
  ]

  deps = [
    "//ydb/core/tx/columnshard/engines/scheme",
  ]

  sources = [
    "constructor.cpp",
    "index_info_ext.cpp",
    "meta.cpp",
  ]
}
