config("public_config") {
    include_dirs = [ "lib/includes" ]
}

config("private_config") {
    cflags = [
        "-Wno-deprecated-declarations",
        "-Wno-incompatible-pointer-types",
        "-Wno-unused-but-set-variable",
    ]
    defines = [
        "Blowfish_decipher=__libssh2_Blowfish_decipher",
        "Blowfish_encipher=__libssh2_Blowfish_encipher",
        "Blowfish_expand0state=__libssh2_Blowfish_expand0state",
        "Blowfish_expandstate=__libssh2_Blowfish_expandstate",
        "Blowfish_initstate=__libssh2_Blowfish_initstate",
        "Blowfish_stream2word=__libssh2_Blowfish_stream2word",
        "agent_ops_unix=__libssh2_agent_ops_unix",
        "bcrypt_pbkdf=__libssh2_bcrypt_pbkdf",
        "blf_cbc_decrypt=__libssh2_blf_cbc_decrypt",
        "blf_cbc_encrypt=__libssh2_blf_cbc_encrypt",
        "blf_dec=__libssh2_blf_dec",
        "blf_ecb_decrypt=__libssh2_blf_ecb_decrypt",
        "blf_ecb_encrypt=__libssh2_blf_ecb_encrypt",
        "blf_enc=__libssh2_blf_enc",
        "blf_key=__libssh2_blf_key",
        "read_openssh_private_key_from_memory=__libssh2_read_openssh_private_key_from_memory",
        "HAVE_CONFIG_H",
    ]
}

contrib_library("libssh2") {
    deps = [
        "//contrib/libs/openssl",
        "//contrib/libs/zlib",
    ]

    sources = [
        "src/agent_win.c",
        "src/agent.c",
        "src/bcrypt_pbkdf.c",
        "src/blowfish.c",
        "src/channel.c",
        "src/comp.c",
        "src/crypt.c",
        "src/global.c",
        "src/hostkey.c",
        "src/keepalive.c",
        "src/kex.c",
        "src/knownhost.c",
        "src/mac.c",
        "src/misc.c",
        "src/openssl.c",
        "src/packet.c",
        "src/pem.c",
        "src/publickey.c",
        "src/scp.c",
        "src/session.c",
        "src/sftp.c",
        "src/transport.c",
        "src/userauth.c",
        "src/version.c",
    ]

    public_configs = [ ":public_config" ]
    configs = [ ":private_config" ]
}