library("scheme_cache_lib") {
  public_deps = [
    # "//ydb/core/base",
  ]

  deps = [
    "//ydb/core/client/minikql_compile:db_key_resolver",
    "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/library/actors/core",
  ]

  sources = [ "yql_db_scheme_resolver.cpp" ]
}
