library("cancelation") {
  public_deps = [
    ":protos",
    "//ydb/core/base",
    "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/grpc_services/base",
  ]

  sources = [ "cancelation.cpp" ]
}

protobuf_library("protos") {
  public_deps = [ "//ydb/library/actors/protos" ]

  sources = [ "protos/event.proto" ]
}
