library("extractor") {
  public_deps = [
    # "//contrib/libs/apache/arrow",
    # "//library/cpp/json",
    # "//library/cpp/json:writer",
  ]

  deps = [
    # "//library/cpp/json:fast_sax",
    # "//ydb/core/formats/arrow:hash",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/core",
    # "//ydb/library/services",
    # "//yql/essentials/minikql/jsonpath",
    # "//yql/essentials/utils",
  ]

  sources = [
    "extractor/abstract.cpp",
    "extractor/container.cpp",
    "extractor/hash_by_columns.cpp",
  ]

  serialize_enum_headers = [ "extractor/hash_by_columns.h" ]
}

library("metadata") {
  public_deps = [
    # "//contrib/libs/apache/arrow",
    # "//library/cpp/json",
    # "//library/cpp/json:writer",
    # "//ydb/library/accessor",
    # "//ydb/public/api/protos",
    # "//ydb/services/metadata/abstract",
    # "//ydb/services/metadata/manager",
    # ":extractor",
  ]

  deps = [
    # "//ydb/core/ydb_convert",
    # "//ydb/services/metadata/ds_table",
  ]

  sources = [
    "behaviour.cpp",
    "fetcher.cpp",
    "initializer.cpp",
    "manager.cpp",
    "object.cpp",
    "snapshot.cpp",
  ]
}
