unittest_executable("ut") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/metering",
  ]

  sources = [
    "//ydb/core/metering/stream_ru_calculator_ut.cpp",
    "//ydb/core/metering/time_grid_ut.cpp",
  ]

  include_dirs = [ "//ydb/core/metering" ]

  link_select = [
    "YqlServicePolicy=stub",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
