library("erasure") {
  public_deps = [
    "//library/cpp/containers/stack_vector",

    # "//ydb/core/debug",
    "//ydb/library/yverify_stream",
  ]

  deps = [
    "//library/cpp/digest/crc32c",
    "//ydb/library/actors/util",
  ]

  sources = [
    "erasure.cpp",
    "erasure_restore.cpp",
    "erasure_split.cpp",
  ]
}
