library("udf_resolver") {
  public_deps = [
    # "//yql/essentials/core",
    # "//yql/essentials/core/qplayer/storage/interface",
  ]

  deps = [
    # "//library/cpp/yson:node",
    # "//yql/essentials/ast",
    # "//yql/essentials/providers/common/schema/expr",
  ]

  sources = [ "yql_qplayer_udf_resolver.cpp" ]
}
