library("actors") {
  public_deps = [
    # "//ydb/core/grpc_services",
    # "//ydb/core/protos/schemeshard",
    # "//ydb/library/actors/core",
    # "//ydb/public/api/grpc:draft",
    # "//ydb/public/api/protos",
  ]

  deps = [
    # "//library/cpp/digest/md5",
    # "//library/cpp/json",
    # "//ydb/core/base",
    # "//ydb/core/kafka_proxy",
    # "//ydb/core/persqueue/public",
    # "//ydb/core/protos",
    # "//ydb/core/util",
    # "//ydb/core/ydb_convert",
    # "//ydb/library/persqueue/topic_parser",
    # "//ydb/public/sdk/cpp/src/library/jwt",
    # "//ydb/public/sdk/cpp/src/library/persqueue/obfuscate",
    # "//yql/essentials/public/decimal",
  ]

  sources = [
    "consumers_advanced_monitoring_settings.cpp",
    "pq_schema_actor.cpp",
  ]
}
