unittest_executable("ut_subdomain") {
  deps = [
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/regex/pcre",  # peerdir only
    "//library/cpp/svnversion",  # peerdir only
    "//ydb/core/persqueue/events",
    "//ydb/core/protos",
    "//ydb/core/scheme_types",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx",  # peerdir only
    "//ydb/core/tx/columnshard/hooks/testing",  # peerdir only
    "//ydb/core/tx/columnshard/test_helper",
    "//ydb/core/tx/datashard",
    "//ydb/core/tx/schemeshard",
    "//ydb/core/tx/schemeshard/ut_helpers",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
  ]

  sources = [ "ut_subdomain.cpp" ]

  include_dirs = [ "//ydb/core/tx/schemeshard" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
