library("test_helper") {
  testonly = true

  public_deps = [
    # "//contrib/libs/apache/arrow",
    # "//library/cpp/testing/unittest",
    # "//ydb/core/formats/arrow",
    # "//ydb/core/protos",
    # "//ydb/core/scheme",
    # "//ydb/core/scheme_types",
    # "//ydb/core/testlib",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/blobs_action:abstract",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/data_events:common",
    # "//ydb/core/tx/long_tx_service:public",
    # "//ydb/core/tx/tiering",
    # "//ydb/library/accessor",
    # "//ydb/library/formats/arrow:switch",
    # "//ydb/public/sdk/cpp/src/client/value",
    # "//ydb/services/metadata/abstract",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/formats/arrow/program",
    # "//ydb/core/kqp/compute_actor:events",
    # "//ydb/core/sys_view:common",
    # "//ydb/core/testlib/basics",
    # "//ydb/core/tx",
    # "//ydb/core/tx/columnshard/blobs_action:bs",
    # "//ydb/core/tx/columnshard/blobs_action:local",
    # "//ydb/core/tx/columnshard/blobs_action:tier",
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view:portions",
    # "//ydb/core/tx/columnshard/engines/storage/indexes/max",
    # "//ydb/core/tx/columnshard/hooks/testing",
    # "//ydb/core/tx/data_events",
    # "//ydb/core/tx/datashard",
    # "//ydb/core/tx/tiering:tier",
    # "//ydb/core/wrappers",
    # "//ydb/library/actors/core",
    # "//ydb/library/formats/arrow:protos",
    # "//yql/essentials/core/arrow_kernels/request",
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/invoke_builtins",
  ]

  sources = [
    "columnshard_ut_common.cpp",
    "controllers.cpp",
    "helper.cpp",
    "kernels_wrapper.cpp",
    "program_constructor.cpp",
    "shard_reader.cpp",
    "shard_writer.cpp",
  ]
}
