library("sparsed") {
  public_deps = [
    "//contrib/libs/apache/arrow",
    "//ydb/core/formats/arrow/accessor/abstract",
    "//ydb/core/formats/arrow/accessor/common",
    "//ydb/core/formats/arrow/accessor/plain",
    "//ydb/library/accessor",
    "//ydb/library/formats/arrow",
    "//ydb/library/formats/arrow:switch",
  ]

  sources = [
    "accessor.cpp",
    "constructor.cpp",
    "request.cpp",
  ]
}
