library("sparsed") {
  public_deps = [
    "//contrib/libs/apache/arrow",
    "//library/cpp/string_utils/base64",
    "//ydb/core/formats/arrow/accessor:abstract",
    "//ydb/core/formats/arrow/accessor:common",
    "//ydb/core/formats/arrow/accessor:plain",
    "//ydb/library/accessor",
    "//ydb/library/formats/arrow",
    "//ydb/library/formats/arrow:protos",
    "//ydb/library/formats/arrow:switch",
  ]

  sources = [
    "accessor.cpp",
    "constructor.cpp",
    "request.cpp",
  ]
}
