library("ydb") {
  public_deps = [
    # "//library/cpp/retry",
    # "//ydb/core/fq/libs/config:protos",
    # "//ydb/library/accessor",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    # "//ydb/library/security",
    # "//ydb/public/sdk/cpp/src/client/coordination",
    # "//ydb/public/sdk/cpp/src/client/rate_limiter",
    # "//ydb/public/sdk/cpp/src/client/scheme",
    # "//ydb/public/sdk/cpp/src/client/table",
    # "//ydb/public/sdk/cpp/src/client/types/status",
    # "//yql/essentials/public/issue",
  ]

  deps = [
    # "//library/cpp/threading/future",
    # "//ydb/core/base",
    # "//ydb/core/fq/libs/actors:logging",
    # "//ydb/core/fq/libs/events",
    # "//ydb/core/protos",
    # "//ydb/library/query_actor",
    # "//ydb/library/table_creator",
    # "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/adapters/issue",
    # "//ydb/public/sdk/cpp/src/client/driver",
    # "//ydb/public/sdk/cpp/src/client/types",
  ]

  sources = [
    "local_session.cpp",
    "local_table_client.cpp",
    "query_actor.cpp",
    "schema.cpp",
    "sdk_session.cpp",
    "sdk_table_client.cpp",
    "util.cpp",
    "ydb.cpp",
    "ydb_local_connection.cpp",
    "ydb_sdk_connection.cpp",
  ]

  serialize_enum_headers = [ "ydb.h" ]
}
