library("fetch") {
  public_deps = [
    "//library/cpp/http/io",
    "//library/cpp/retry",
    "//library/cpp/uri",
  ]

  deps = [
    "//library/cpp/charset",
    "//library/cpp/http/misc",
    "//library/cpp/openssl/io",
    "//yql/essentials/utils/log",
  ]

  sources = [ "fetch.cpp" ]
}

protobuf_library("proto") {
  sources = [ "proto/fetch_config.proto" ]
}
