library("nbs") {
  deps = [
    # "//ydb/core/grpc_services",
    # "//ydb/core/grpc_services/base",
    # "//ydb/core/jaeger_tracing",
    # "//ydb/library/actors/core",
    # "//ydb/library/grpc/server",
    # "//ydb/public/api/grpc",  # peerdir only
    # "//ydb/public/api/grpc:draft",
  ]

  sources = [ "grpc_service.cpp" ]
}
