library("events") {
  public_deps = [
    ":proto",
    # "//ydb/core/fq/libs/events",
    "//ydb/library/actors/core",
    # "//yql/essentials/public/issue",
  ]

  sources = [ "events/events.cpp" ]
}

protobuf_library("proto") {
  sources = [ "proto/quota_internal.proto" ]
}

library("quota_manager") {
  public_deps = [
    # ":events",
    # "//library/cpp/monlib/dynamic_counters",
    # "//ydb/core/fq/libs/config:protos",
    "//ydb/core/fq/libs/shared_resources",
    "//ydb/core/mon",
  ]

  deps = [
    # "//library/cpp/protobuf/interop",
    # "//ydb/core/fq/libs/control_plane_storage",
    "//ydb/core/fq/libs/ydb",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/services",
    # "//ydb/public/sdk/cpp/src/client/table",
  ]

  sources = [
    "quota_manager.cpp",
    "quota_proxy.cpp",
  ]
}
