library("abstract") {
  public_deps = [
    "//contrib/libs/apache/arrow",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/formats/arrow",
    "//ydb/core/formats/arrow/accessor:abstract",
  ]

  sources = [
    "abstract/chunk_meta.cpp",
    "abstract/chunks.cpp",
  ]
}

library("splitter") {
  public_deps = [
    "//contrib/libs/apache/arrow",
    "//ydb/core/formats/arrow:splitter",
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/scheme",
    "//ydb/library/accessor",
    "//ydb/library/actors/core",
    "//ydb/library/formats/arrow:splitter",
    # ":abstract",
  ]

  deps = [
    "//ydb/library/actors/util",
  ]

  sources = [
    "batch_slice.cpp",
    "blob_info.cpp",
    "chunk_meta.cpp",
    "chunks.cpp",
    "column_info.cpp",
    "settings.cpp",
  ]
}
