library("events") {
  public_deps = [
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/data_sharing/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/tx/columnshard/data_sharing/modification/tasks",
  ]

  sources = [ "change_owning.cpp" ]
}
