config("public_config") {
    include_dirs = [
        "aws-cpp-sdk-core/include",
        "aws-cpp-sdk-s3/include",
    ]
}

config("private_config") {
    defines = [
        "AWS_SDK_VERSION_MAJOR=1",
        "AWS_SDK_VERSION_MINOR=11",
        "AWS_SDK_VERSION_PATCH=37",
        "AWS_TEST_REGION=US_EAST_1",
        "AWS_USE_EPOLL",
        "CURL_HAS_H2",
        "CURL_HAS_TLS_PROXY",
        "ENABLE_CURL_CLIENT",
        "ENABLE_CURL_LOGGING",
        "ENABLE_OPENSSL_ENCRYPTION",
        "ENABLED_REQUEST_COMPRESSION",
        "ENABLED_ZLIB_REQUEST_COMPRESSION",
        "HAS_PATHCONF",
        "HAS_UMASK",
    ]
}

contrib_library("core") {
    public_deps = [
        "//contrib/restricted/aws:crt-cpp",
    ]

    deps = [
        "//contrib/libs/curl",
        "//contrib/libs/openssl",
        "//contrib/libs/zlib",
        "//contrib/restricted/aws:checksums",
        "//contrib/restricted/aws:common",
        "//contrib/restricted/aws:event-stream",
    ]

    sources = [
        "aws-cpp-sdk-core/source/AmazonSerializableWebServiceRequest.cpp",
        "aws-cpp-sdk-core/source/AmazonStreamingWebServiceRequest.cpp",
        "aws-cpp-sdk-core/source/AmazonWebServiceRequest.cpp",
        "aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp",
        "aws-cpp-sdk-core/source/auth/AWSCredentialsProviderChain.cpp",
        "aws-cpp-sdk-core/source/auth/bearer-token-provider/DefaultBearerTokenProviderChain.cpp",
        "aws-cpp-sdk-core/source/auth/bearer-token-provider/SSOBearerTokenProvider.cpp",
        "aws-cpp-sdk-core/source/auth/signer-provider/BearerTokenAuthSignerProvider.cpp",
        "aws-cpp-sdk-core/source/auth/signer-provider/DefaultAuthSignerProvider.cpp",
        "aws-cpp-sdk-core/source/auth/signer/AWSAuthBearerSigner.cpp",
        "aws-cpp-sdk-core/source/auth/signer/AWSAuthEventStreamV4Signer.cpp",
        "aws-cpp-sdk-core/source/auth/signer/AWSAuthSignerCommon.cpp",
        "aws-cpp-sdk-core/source/auth/signer/AWSAuthSignerHelper.cpp",
        "aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp",
        "aws-cpp-sdk-core/source/auth/signer/AWSNullSigner.cpp",
        "aws-cpp-sdk-core/source/auth/SSOCredentialsProvider.cpp",
        "aws-cpp-sdk-core/source/auth/STSCredentialsProvider.cpp",
        "aws-cpp-sdk-core/source/Aws.cpp",
        "aws-cpp-sdk-core/source/client/AdaptiveRetryStrategy.cpp",
        "aws-cpp-sdk-core/source/client/AsyncCallerContext.cpp",
        "aws-cpp-sdk-core/source/client/AWSClient.cpp",
        "aws-cpp-sdk-core/source/client/AWSErrorMarshaller.cpp",
        "aws-cpp-sdk-core/source/client/AWSJsonClient.cpp",
        "aws-cpp-sdk-core/source/client/AWSUrlPresigner.cpp",
        "aws-cpp-sdk-core/source/client/AWSXmlClient.cpp",
        "aws-cpp-sdk-core/source/client/ClientConfiguration.cpp",
        "aws-cpp-sdk-core/source/client/CoreErrors.cpp",
        "aws-cpp-sdk-core/source/client/DefaultRetryStrategy.cpp",
        "aws-cpp-sdk-core/source/client/GenericClientConfiguration.cpp",
        "aws-cpp-sdk-core/source/client/RequestCompression.cpp",
        "aws-cpp-sdk-core/source/client/RetryStrategy.cpp",
        "aws-cpp-sdk-core/source/client/SpecifiedRetryableErrorsRetryStrategy.cpp",
        "aws-cpp-sdk-core/source/config/AWSConfigFileProfileConfigLoader.cpp",
        "aws-cpp-sdk-core/source/config/AWSProfileConfigLoaderBase.cpp",
        "aws-cpp-sdk-core/source/config/ConfigAndCredentialsCacheManager.cpp",
        "aws-cpp-sdk-core/source/config/defaults/ClientConfigurationDefaults.cpp",
        "aws-cpp-sdk-core/source/config/EC2InstanceProfileConfigLoader.cpp",
        "aws-cpp-sdk-core/source/endpoint/AWSEndpoint.cpp",
        "aws-cpp-sdk-core/source/endpoint/AWSPartitions.cpp",
        "aws-cpp-sdk-core/source/endpoint/BuiltInParameters.cpp",
        "aws-cpp-sdk-core/source/endpoint/ClientContextParameters.cpp",
        "aws-cpp-sdk-core/source/endpoint/DefaultEndpointProvider.cpp",
        "aws-cpp-sdk-core/source/endpoint/EndpointProviderBase.cpp",
        "aws-cpp-sdk-core/source/endpoint/internal/AWSEndpointAttribute.cpp",
        "aws-cpp-sdk-core/source/external/cjson/cJSON.cpp",
        "aws-cpp-sdk-core/source/external/tinyxml2/tinyxml2.cpp",
        "aws-cpp-sdk-core/source/Globals.cpp",
        "aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp",
        "aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp",
        "aws-cpp-sdk-core/source/http/HttpClient.cpp",
        "aws-cpp-sdk-core/source/http/HttpClientFactory.cpp",
        "aws-cpp-sdk-core/source/http/HttpRequest.cpp",
        "aws-cpp-sdk-core/source/http/HttpResponse.cpp",
        "aws-cpp-sdk-core/source/http/HttpTypes.cpp",
        "aws-cpp-sdk-core/source/http/Scheme.cpp",
        "aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp",
        "aws-cpp-sdk-core/source/http/standard/StandardHttpResponse.cpp",
        "aws-cpp-sdk-core/source/http/URI.cpp",
        "aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp",
        "aws-cpp-sdk-core/source/monitoring/DefaultMonitoring.cpp",
        "aws-cpp-sdk-core/source/monitoring/HttpClientMetrics.cpp",
        "aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp",
        "aws-cpp-sdk-core/source/net/linux-shared/Net.cpp",
        "aws-cpp-sdk-core/source/net/linux-shared/SimpleUDP.cpp",
        "aws-cpp-sdk-core/source/platform/linux-shared/Environment.cpp",
        "aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp",
        "aws-cpp-sdk-core/source/platform/linux-shared/OSVersionInfo.cpp",
        "aws-cpp-sdk-core/source/platform/linux-shared/Security.cpp",
        "aws-cpp-sdk-core/source/platform/linux-shared/Time.cpp",
        "aws-cpp-sdk-core/source/Region.cpp",
        "aws-cpp-sdk-core/source/utils/ARN.cpp",
        "aws-cpp-sdk-core/source/utils/Array.cpp",
        "aws-cpp-sdk-core/source/utils/base64/Base64.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/Cipher.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/ContentCryptoMaterial.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/ContentCryptoScheme.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/CRC32.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/CryptoBuf.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/CryptoStream.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/EncryptionMaterials.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/factory/Factories.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/KeyWrapAlgorithm.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/MD5.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/Sha1.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/Sha256.cpp",
        "aws-cpp-sdk-core/source/utils/crypto/Sha256HMAC.cpp",
        "aws-cpp-sdk-core/source/utils/DateTimeCommon.cpp",
        "aws-cpp-sdk-core/source/utils/Directory.cpp",
        "aws-cpp-sdk-core/source/utils/DNS.cpp",
        "aws-cpp-sdk-core/source/utils/Document.cpp",
        "aws-cpp-sdk-core/source/utils/EnumParseOverflowContainer.cpp",
        "aws-cpp-sdk-core/source/utils/event/EventDecoderStream.cpp",
        "aws-cpp-sdk-core/source/utils/event/EventEncoderStream.cpp",
        "aws-cpp-sdk-core/source/utils/event/EventHeader.cpp",
        "aws-cpp-sdk-core/source/utils/event/EventMessage.cpp",
        "aws-cpp-sdk-core/source/utils/event/EventStreamBuf.cpp",
        "aws-cpp-sdk-core/source/utils/event/EventStreamDecoder.cpp",
        "aws-cpp-sdk-core/source/utils/event/EventStreamEncoder.cpp",
        "aws-cpp-sdk-core/source/utils/event/EventStreamErrors.cpp",
        "aws-cpp-sdk-core/source/utils/FileSystemUtils.cpp",
        "aws-cpp-sdk-core/source/utils/GetTheLights.cpp",
        "aws-cpp-sdk-core/source/utils/HashingUtils.cpp",
        "aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp",
        "aws-cpp-sdk-core/source/utils/logging/AWSLogging.cpp",
        "aws-cpp-sdk-core/source/utils/logging/ConsoleLogSystem.cpp",
        "aws-cpp-sdk-core/source/utils/logging/CRTLogging.cpp",
        "aws-cpp-sdk-core/source/utils/logging/CRTLogSystem.cpp",
        "aws-cpp-sdk-core/source/utils/logging/DefaultLogSystem.cpp",
        "aws-cpp-sdk-core/source/utils/logging/FormattedLogSystem.cpp",
        "aws-cpp-sdk-core/source/utils/logging/LogLevel.cpp",
        "aws-cpp-sdk-core/source/utils/memory/AWSMemory.cpp",
        "aws-cpp-sdk-core/source/utils/memory/stl/SimpleStringStream.cpp",
        "aws-cpp-sdk-core/source/utils/stream/ConcurrentStreamBuf.cpp",
        "aws-cpp-sdk-core/source/utils/stream/PreallocatedStreamBuf.cpp",
        "aws-cpp-sdk-core/source/utils/stream/ResponseStream.cpp",
        "aws-cpp-sdk-core/source/utils/stream/SimpleStreamBuf.cpp",
        "aws-cpp-sdk-core/source/utils/StringUtils.cpp",
        "aws-cpp-sdk-core/source/utils/TempFile.cpp",
        "aws-cpp-sdk-core/source/utils/threading/Executor.cpp",
        "aws-cpp-sdk-core/source/utils/threading/ReaderWriterLock.cpp",
        "aws-cpp-sdk-core/source/utils/threading/Semaphore.cpp",
        "aws-cpp-sdk-core/source/utils/threading/ThreadTask.cpp",
        "aws-cpp-sdk-core/source/utils/UUID.cpp",
        "aws-cpp-sdk-core/source/utils/xml/XmlSerializer.cpp",
        "aws-cpp-sdk-core/source/Version.cpp",
    ]

    public_configs = [ ":public_config" ]
    configs = [ ":private_config" ]
}

contrib_library("s3") {
    deps = [
        ":core",
    ]

    sources = [
        "aws-cpp-sdk-s3/source/model/AbortIncompleteMultipartUpload.cpp",
        "aws-cpp-sdk-s3/source/model/AbortMultipartUploadRequest.cpp",
        "aws-cpp-sdk-s3/source/model/AbortMultipartUploadResult.cpp",
        "aws-cpp-sdk-s3/source/model/AccelerateConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/AccessControlPolicy.cpp",
        "aws-cpp-sdk-s3/source/model/AccessControlTranslation.cpp",
        "aws-cpp-sdk-s3/source/model/AnalyticsAndOperator.cpp",
        "aws-cpp-sdk-s3/source/model/AnalyticsConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/AnalyticsExportDestination.cpp",
        "aws-cpp-sdk-s3/source/model/AnalyticsFilter.cpp",
        "aws-cpp-sdk-s3/source/model/AnalyticsS3BucketDestination.cpp",
        "aws-cpp-sdk-s3/source/model/AnalyticsS3ExportFileFormat.cpp",
        "aws-cpp-sdk-s3/source/model/ArchiveStatus.cpp",
        "aws-cpp-sdk-s3/source/model/Bucket.cpp",
        "aws-cpp-sdk-s3/source/model/BucketAccelerateStatus.cpp",
        "aws-cpp-sdk-s3/source/model/BucketCannedACL.cpp",
        "aws-cpp-sdk-s3/source/model/BucketLifecycleConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/BucketLocationConstraint.cpp",
        "aws-cpp-sdk-s3/source/model/BucketLoggingStatus.cpp",
        "aws-cpp-sdk-s3/source/model/BucketLogsPermission.cpp",
        "aws-cpp-sdk-s3/source/model/BucketVersioningStatus.cpp",
        "aws-cpp-sdk-s3/source/model/Checksum.cpp",
        "aws-cpp-sdk-s3/source/model/ChecksumAlgorithm.cpp",
        "aws-cpp-sdk-s3/source/model/ChecksumMode.cpp",
        "aws-cpp-sdk-s3/source/model/CloudFunctionConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/CommonPrefix.cpp",
        "aws-cpp-sdk-s3/source/model/CompletedMultipartUpload.cpp",
        "aws-cpp-sdk-s3/source/model/CompletedPart.cpp",
        "aws-cpp-sdk-s3/source/model/CompleteMultipartUploadRequest.cpp",
        "aws-cpp-sdk-s3/source/model/CompleteMultipartUploadResult.cpp",
        "aws-cpp-sdk-s3/source/model/CompressionType.cpp",
        "aws-cpp-sdk-s3/source/model/Condition.cpp",
        "aws-cpp-sdk-s3/source/model/CopyObjectRequest.cpp",
        "aws-cpp-sdk-s3/source/model/CopyObjectResult.cpp",
        "aws-cpp-sdk-s3/source/model/CopyObjectResultDetails.cpp",
        "aws-cpp-sdk-s3/source/model/CopyPartResult.cpp",
        "aws-cpp-sdk-s3/source/model/CORSConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/CORSRule.cpp",
        "aws-cpp-sdk-s3/source/model/CreateBucketConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/CreateBucketRequest.cpp",
        "aws-cpp-sdk-s3/source/model/CreateBucketResult.cpp",
        "aws-cpp-sdk-s3/source/model/CreateMultipartUploadRequest.cpp",
        "aws-cpp-sdk-s3/source/model/CreateMultipartUploadResult.cpp",
        "aws-cpp-sdk-s3/source/model/CSVInput.cpp",
        "aws-cpp-sdk-s3/source/model/CSVOutput.cpp",
        "aws-cpp-sdk-s3/source/model/DefaultRetention.cpp",
        "aws-cpp-sdk-s3/source/model/Delete.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketAnalyticsConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketCorsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketEncryptionRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketIntelligentTieringConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketInventoryConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketLifecycleRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketMetricsConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketOwnershipControlsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketPolicyRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketReplicationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketTaggingRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteBucketWebsiteRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeletedObject.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteMarkerEntry.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteMarkerReplication.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteMarkerReplicationStatus.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteObjectRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteObjectResult.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteObjectsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteObjectsResult.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteObjectTaggingRequest.cpp",
        "aws-cpp-sdk-s3/source/model/DeleteObjectTaggingResult.cpp",
        "aws-cpp-sdk-s3/source/model/DeletePublicAccessBlockRequest.cpp",
        "aws-cpp-sdk-s3/source/model/Destination.cpp",
        "aws-cpp-sdk-s3/source/model/EncodingType.cpp",
        "aws-cpp-sdk-s3/source/model/Encryption.cpp",
        "aws-cpp-sdk-s3/source/model/EncryptionConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/Error.cpp",
        "aws-cpp-sdk-s3/source/model/ErrorDocument.cpp",
        "aws-cpp-sdk-s3/source/model/Event.cpp",
        "aws-cpp-sdk-s3/source/model/EventBridgeConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/ExistingObjectReplication.cpp",
        "aws-cpp-sdk-s3/source/model/ExistingObjectReplicationStatus.cpp",
        "aws-cpp-sdk-s3/source/model/ExpirationStatus.cpp",
        "aws-cpp-sdk-s3/source/model/ExpressionType.cpp",
        "aws-cpp-sdk-s3/source/model/FileHeaderInfo.cpp",
        "aws-cpp-sdk-s3/source/model/FilterRule.cpp",
        "aws-cpp-sdk-s3/source/model/FilterRuleName.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketAccelerateConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketAccelerateConfigurationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketAclRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketAclResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketAnalyticsConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketAnalyticsConfigurationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketCorsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketCorsResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketEncryptionRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketEncryptionResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketIntelligentTieringConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketIntelligentTieringConfigurationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketInventoryConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketInventoryConfigurationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketLifecycleConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketLifecycleConfigurationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketLocationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketLocationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketLoggingRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketLoggingResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketMetricsConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketMetricsConfigurationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketNotificationConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketNotificationConfigurationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketOwnershipControlsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketOwnershipControlsResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketPolicyRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketPolicyResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketPolicyStatusRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketPolicyStatusResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketReplicationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketReplicationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketRequestPaymentRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketRequestPaymentResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketTaggingRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketTaggingResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketVersioningRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketVersioningResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketWebsiteRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetBucketWebsiteResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectAclRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectAclResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectAttributesParts.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectAttributesRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectAttributesResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectLegalHoldRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectLegalHoldResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectLockConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectLockConfigurationResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectRetentionRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectRetentionResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectTaggingRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectTaggingResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectTorrentRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetObjectTorrentResult.cpp",
        "aws-cpp-sdk-s3/source/model/GetPublicAccessBlockRequest.cpp",
        "aws-cpp-sdk-s3/source/model/GetPublicAccessBlockResult.cpp",
        "aws-cpp-sdk-s3/source/model/GlacierJobParameters.cpp",
        "aws-cpp-sdk-s3/source/model/Grant.cpp",
        "aws-cpp-sdk-s3/source/model/Grantee.cpp",
        "aws-cpp-sdk-s3/source/model/HeadBucketRequest.cpp",
        "aws-cpp-sdk-s3/source/model/HeadObjectRequest.cpp",
        "aws-cpp-sdk-s3/source/model/HeadObjectResult.cpp",
        "aws-cpp-sdk-s3/source/model/IndexDocument.cpp",
        "aws-cpp-sdk-s3/source/model/Initiator.cpp",
        "aws-cpp-sdk-s3/source/model/InputSerialization.cpp",
        "aws-cpp-sdk-s3/source/model/IntelligentTieringAccessTier.cpp",
        "aws-cpp-sdk-s3/source/model/IntelligentTieringAndOperator.cpp",
        "aws-cpp-sdk-s3/source/model/IntelligentTieringConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/IntelligentTieringFilter.cpp",
        "aws-cpp-sdk-s3/source/model/IntelligentTieringStatus.cpp",
        "aws-cpp-sdk-s3/source/model/InvalidObjectState.cpp",
        "aws-cpp-sdk-s3/source/model/InventoryConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/InventoryDestination.cpp",
        "aws-cpp-sdk-s3/source/model/InventoryEncryption.cpp",
        "aws-cpp-sdk-s3/source/model/InventoryFilter.cpp",
        "aws-cpp-sdk-s3/source/model/InventoryFormat.cpp",
        "aws-cpp-sdk-s3/source/model/InventoryFrequency.cpp",
        "aws-cpp-sdk-s3/source/model/InventoryIncludedObjectVersions.cpp",
        "aws-cpp-sdk-s3/source/model/InventoryOptionalField.cpp",
        "aws-cpp-sdk-s3/source/model/InventoryS3BucketDestination.cpp",
        "aws-cpp-sdk-s3/source/model/InventorySchedule.cpp",
        "aws-cpp-sdk-s3/source/model/JSONInput.cpp",
        "aws-cpp-sdk-s3/source/model/JSONOutput.cpp",
        "aws-cpp-sdk-s3/source/model/JSONType.cpp",
        "aws-cpp-sdk-s3/source/model/LambdaFunctionConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/LifecycleConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/LifecycleExpiration.cpp",
        "aws-cpp-sdk-s3/source/model/LifecycleRule.cpp",
        "aws-cpp-sdk-s3/source/model/LifecycleRuleAndOperator.cpp",
        "aws-cpp-sdk-s3/source/model/LifecycleRuleFilter.cpp",
        "aws-cpp-sdk-s3/source/model/ListBucketAnalyticsConfigurationsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/ListBucketAnalyticsConfigurationsResult.cpp",
        "aws-cpp-sdk-s3/source/model/ListBucketIntelligentTieringConfigurationsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/ListBucketIntelligentTieringConfigurationsResult.cpp",
        "aws-cpp-sdk-s3/source/model/ListBucketInventoryConfigurationsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/ListBucketInventoryConfigurationsResult.cpp",
        "aws-cpp-sdk-s3/source/model/ListBucketMetricsConfigurationsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/ListBucketMetricsConfigurationsResult.cpp",
        "aws-cpp-sdk-s3/source/model/ListBucketsResult.cpp",
        "aws-cpp-sdk-s3/source/model/ListMultipartUploadsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/ListMultipartUploadsResult.cpp",
        "aws-cpp-sdk-s3/source/model/ListObjectsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/ListObjectsResult.cpp",
        "aws-cpp-sdk-s3/source/model/ListObjectsV2Request.cpp",
        "aws-cpp-sdk-s3/source/model/ListObjectsV2Result.cpp",
        "aws-cpp-sdk-s3/source/model/ListObjectVersionsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/ListObjectVersionsResult.cpp",
        "aws-cpp-sdk-s3/source/model/ListPartsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/ListPartsResult.cpp",
        "aws-cpp-sdk-s3/source/model/LoggingEnabled.cpp",
        "aws-cpp-sdk-s3/source/model/MetadataDirective.cpp",
        "aws-cpp-sdk-s3/source/model/MetadataEntry.cpp",
        "aws-cpp-sdk-s3/source/model/Metrics.cpp",
        "aws-cpp-sdk-s3/source/model/MetricsAndOperator.cpp",
        "aws-cpp-sdk-s3/source/model/MetricsConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/MetricsFilter.cpp",
        "aws-cpp-sdk-s3/source/model/MetricsStatus.cpp",
        "aws-cpp-sdk-s3/source/model/MFADelete.cpp",
        "aws-cpp-sdk-s3/source/model/MFADeleteStatus.cpp",
        "aws-cpp-sdk-s3/source/model/MultipartUpload.cpp",
        "aws-cpp-sdk-s3/source/model/NoncurrentVersionExpiration.cpp",
        "aws-cpp-sdk-s3/source/model/NoncurrentVersionTransition.cpp",
        "aws-cpp-sdk-s3/source/model/NotificationConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/NotificationConfigurationDeprecated.cpp",
        "aws-cpp-sdk-s3/source/model/NotificationConfigurationFilter.cpp",
        "aws-cpp-sdk-s3/source/model/Object.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectAttributes.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectCannedACL.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectIdentifier.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectLockConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectLockEnabled.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectLockLegalHold.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectLockLegalHoldStatus.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectLockMode.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectLockRetention.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectLockRetentionMode.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectLockRule.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectOwnership.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectPart.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectStorageClass.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectVersion.cpp",
        "aws-cpp-sdk-s3/source/model/ObjectVersionStorageClass.cpp",
        "aws-cpp-sdk-s3/source/model/OutputLocation.cpp",
        "aws-cpp-sdk-s3/source/model/OutputSerialization.cpp",
        "aws-cpp-sdk-s3/source/model/Owner.cpp",
        "aws-cpp-sdk-s3/source/model/OwnerOverride.cpp",
        "aws-cpp-sdk-s3/source/model/OwnershipControls.cpp",
        "aws-cpp-sdk-s3/source/model/OwnershipControlsRule.cpp",
        "aws-cpp-sdk-s3/source/model/ParquetInput.cpp",
        "aws-cpp-sdk-s3/source/model/Part.cpp",
        "aws-cpp-sdk-s3/source/model/Payer.cpp",
        "aws-cpp-sdk-s3/source/model/Permission.cpp",
        "aws-cpp-sdk-s3/source/model/PolicyStatus.cpp",
        "aws-cpp-sdk-s3/source/model/Progress.cpp",
        "aws-cpp-sdk-s3/source/model/ProgressEvent.cpp",
        "aws-cpp-sdk-s3/source/model/Protocol.cpp",
        "aws-cpp-sdk-s3/source/model/PublicAccessBlockConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketAccelerateConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketAclRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketAnalyticsConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketCorsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketEncryptionRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketIntelligentTieringConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketInventoryConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketLifecycleConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketLoggingRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketMetricsConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketNotificationConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketOwnershipControlsRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketPolicyRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketReplicationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketRequestPaymentRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketTaggingRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketVersioningRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutBucketWebsiteRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectAclRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectAclResult.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectLegalHoldRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectLegalHoldResult.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectLockConfigurationRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectLockConfigurationResult.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectResult.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectRetentionRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectRetentionResult.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectTaggingRequest.cpp",
        "aws-cpp-sdk-s3/source/model/PutObjectTaggingResult.cpp",
        "aws-cpp-sdk-s3/source/model/PutPublicAccessBlockRequest.cpp",
        "aws-cpp-sdk-s3/source/model/QueueConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/QueueConfigurationDeprecated.cpp",
        "aws-cpp-sdk-s3/source/model/QuoteFields.cpp",
        "aws-cpp-sdk-s3/source/model/Redirect.cpp",
        "aws-cpp-sdk-s3/source/model/RedirectAllRequestsTo.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicaModifications.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicaModificationsStatus.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicationConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicationRule.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicationRuleAndOperator.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicationRuleFilter.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicationRuleStatus.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicationStatus.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicationTime.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicationTimeStatus.cpp",
        "aws-cpp-sdk-s3/source/model/ReplicationTimeValue.cpp",
        "aws-cpp-sdk-s3/source/model/RequestCharged.cpp",
        "aws-cpp-sdk-s3/source/model/RequestPayer.cpp",
        "aws-cpp-sdk-s3/source/model/RequestPaymentConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/RequestProgress.cpp",
        "aws-cpp-sdk-s3/source/model/RestoreObjectRequest.cpp",
        "aws-cpp-sdk-s3/source/model/RestoreObjectResult.cpp",
        "aws-cpp-sdk-s3/source/model/RestoreRequest.cpp",
        "aws-cpp-sdk-s3/source/model/RestoreRequestType.cpp",
        "aws-cpp-sdk-s3/source/model/RoutingRule.cpp",
        "aws-cpp-sdk-s3/source/model/Rule.cpp",
        "aws-cpp-sdk-s3/source/model/S3KeyFilter.cpp",
        "aws-cpp-sdk-s3/source/model/S3Location.cpp",
        "aws-cpp-sdk-s3/source/model/ScanRange.cpp",
        "aws-cpp-sdk-s3/source/model/SelectObjectContentHandler.cpp",
        "aws-cpp-sdk-s3/source/model/SelectObjectContentRequest.cpp",
        "aws-cpp-sdk-s3/source/model/SelectParameters.cpp",
        "aws-cpp-sdk-s3/source/model/ServerSideEncryption.cpp",
        "aws-cpp-sdk-s3/source/model/ServerSideEncryptionByDefault.cpp",
        "aws-cpp-sdk-s3/source/model/ServerSideEncryptionConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/ServerSideEncryptionRule.cpp",
        "aws-cpp-sdk-s3/source/model/SourceSelectionCriteria.cpp",
        "aws-cpp-sdk-s3/source/model/SSEKMS.cpp",
        "aws-cpp-sdk-s3/source/model/SseKmsEncryptedObjects.cpp",
        "aws-cpp-sdk-s3/source/model/SseKmsEncryptedObjectsStatus.cpp",
        "aws-cpp-sdk-s3/source/model/SSES3.cpp",
        "aws-cpp-sdk-s3/source/model/Stats.cpp",
        "aws-cpp-sdk-s3/source/model/StatsEvent.cpp",
        "aws-cpp-sdk-s3/source/model/StorageClass.cpp",
        "aws-cpp-sdk-s3/source/model/StorageClassAnalysis.cpp",
        "aws-cpp-sdk-s3/source/model/StorageClassAnalysisDataExport.cpp",
        "aws-cpp-sdk-s3/source/model/StorageClassAnalysisSchemaVersion.cpp",
        "aws-cpp-sdk-s3/source/model/Tag.cpp",
        "aws-cpp-sdk-s3/source/model/Tagging.cpp",
        "aws-cpp-sdk-s3/source/model/TaggingDirective.cpp",
        "aws-cpp-sdk-s3/source/model/TargetGrant.cpp",
        "aws-cpp-sdk-s3/source/model/Tier.cpp",
        "aws-cpp-sdk-s3/source/model/Tiering.cpp",
        "aws-cpp-sdk-s3/source/model/TopicConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/TopicConfigurationDeprecated.cpp",
        "aws-cpp-sdk-s3/source/model/Transition.cpp",
        "aws-cpp-sdk-s3/source/model/TransitionStorageClass.cpp",
        "aws-cpp-sdk-s3/source/model/Type.cpp",
        "aws-cpp-sdk-s3/source/model/UploadPartCopyRequest.cpp",
        "aws-cpp-sdk-s3/source/model/UploadPartCopyResult.cpp",
        "aws-cpp-sdk-s3/source/model/UploadPartRequest.cpp",
        "aws-cpp-sdk-s3/source/model/UploadPartResult.cpp",
        "aws-cpp-sdk-s3/source/model/VersioningConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/WebsiteConfiguration.cpp",
        "aws-cpp-sdk-s3/source/model/WriteGetObjectResponseRequest.cpp",
        "aws-cpp-sdk-s3/source/S3Client.cpp",
        "aws-cpp-sdk-s3/source/S3ClientConfiguration.cpp",
        "aws-cpp-sdk-s3/source/S3EndpointProvider.cpp",
        "aws-cpp-sdk-s3/source/S3EndpointRules.cpp",
        "aws-cpp-sdk-s3/source/S3ErrorMarshaller.cpp",
        "aws-cpp-sdk-s3/source/S3Errors.cpp",
        "aws-cpp-sdk-s3/source/S3Request.cpp",
    ]

    public_configs = [ ":public_config" ]
    configs = [ ":private_config" ]
}
