library("impl") {
  public_deps = [
    # "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/topic",
    # "//ydb/public/sdk/cpp/src/client/common_client:impl",
  ]

  deps = [
    # "//library/cpp/containers/disjoint_interval_tree",
    # "//library/cpp/string_utils/url",
    # "//library/cpp/threading/future",
    # "//library/cpp/threading/future:subscription",
    # "//ydb/public/api/grpc",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/logger",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/make_request",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/public/sdk/cpp/src/client/table",
    # "//ydb/public/sdk/cpp/src/client/topic/common",
    # "//ydb/public/sdk/cpp/src/client/types",
    # "//ydb/public/sdk/cpp/src/library/decimal",
  ]

  sources = [
    "common.cpp",
    "deferred_commit.cpp",
    "direct_reader.cpp",
    "event_handlers.cpp",
    "offsets_collector.cpp",
    "proto_accessor.cpp",
    "read_session.cpp",
    "read_session_event.cpp",
    "topic.cpp",
    "topic_impl.cpp",
    "transaction.cpp",
    "write_session.cpp",
    "write_session_impl.cpp",
  ]
}
