library("actors") {
  public_deps = [
    # "//library/cpp/containers/disjoint_interval_tree",
    # "//ydb/core/base",
    # "//ydb/core/client/server",
    # "//ydb/core/grpc_services",
    # "//ydb/core/jaeger_tracing",
    # "//ydb/core/kqp/common",
    # "//ydb/core/kqp/common:events",
    # "//ydb/core/persqueue",
    # "//ydb/core/persqueue/events",
    "//ydb/core/persqueue/public",
    # "//ydb/core/persqueue/public:counters",
    # "//ydb/core/persqueue/writer",
    # "//ydb/core/protos",
    # "//ydb/core/scheme",
    # "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    # "//ydb/library/cloud_permissions",
    "//ydb/library/persqueue/topic_parser",
    "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/client/persqueue_public:include",
    # "//ydb/services/lib/actors",
    # "//ydb/services/lib/sharding",
    # "//ydb/services/metadata",
  ]

  deps = [
    # "//library/cpp/json",
    # "//library/cpp/protobuf/util",
    # "//library/cpp/random_provider",
    "//library/cpp/string_utils/base64",
    # "//ydb/core/kqp/common:simple",
    # "//ydb/core/persqueue/common",
    # "//ydb/core/persqueue/public:codecs",
    # "//ydb/core/persqueue/public:write_meta",
    # "//ydb/core/util",
    # "//ydb/core/ydb_convert",
    # "//ydb/library/services",
    # "//ydb/library/wilson_ids",
    # "//ydb/public/lib/base",
    # "//ydb/public/lib/deprecated/kicli",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/public/sdk/cpp/src/library/persqueue/obfuscate",
    # "//ydb/services/metadata/manager",
    # "//yql/essentials/public/issue:protos",
  ]

  sources = [
    "actors/codecs.cpp",
    "actors/commit_offset_actor.cpp",
    "actors/direct_read_actor.cpp",
    "actors/distributed_commit_helper.cpp",
    "actors/helpers.cpp",
    "actors/partition_actor.cpp",
    "actors/partition_writer.cpp",
    "actors/partition_writer_cache_actor.cpp",
    "actors/persqueue_utils.cpp",
    "actors/read_info_actor.cpp",
    "actors/read_init_auth_actor.cpp",
    "actors/read_session_actor.cpp",
    "actors/schema_actors.cpp",
    "actors/update_offsets_in_transaction_actor.cpp",
    "actors/write_session_actor.cpp",
  ]
}

library("persqueue_v1") {
  public_deps = [
    # "//ydb/core/grpc_services",
    # "//ydb/core/grpc_services/base",
    # "//ydb/library/actors/core",
    # "//ydb/library/grpc/server",
    # "//ydb/public/api/grpc",
    # "//ydb/public/api/grpc:draft",
  ]

  deps = [
    # "//library/cpp/monlib/dynamic_counters",
    # "//ydb/core/base",
    # "//ydb/core/client/server",
    # "//ydb/core/mind:address_classification",
    # "//ydb/core/persqueue/public:cluster_tracker",
    # "//ydb/core/tx/scheme_board",
    # "//ydb/library/cloud_permissions",
    # ":actors",
  ]

  sources = [
    "grpc_pq_read.cpp",
    "grpc_pq_schema.cpp",
    "grpc_pq_write.cpp",
    "persqueue.cpp",
    "services_initializer.cpp",
    "topic.cpp",
  ]
}
