library("sqs_json") {
  deps = [
    # "//library/cpp/string_utils/url",
  ]

  sources = [ "sqs_json/sqs_json_client.cpp" ]
}

library("sqs_workload") {
  public_deps = [
    # "//ydb/public/lib/ydb_cli/common",
  ]

  deps = [
    # "//library/cpp/histogram/hdr",
    # "//library/cpp/logger",
    # "//library/cpp/uri",
    # "//ydb/library/backup",
    # "//ydb/public/lib/ydb_cli/commands",
    # "//ydb/public/lib/ydb_cli/commands/topic_workload",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/logger",
    # ":sqs_json",
  ]

  sources = [
    "http_client.cpp",
    "message_groups_locker.cpp",
    "sqs_client_wrapper.cpp",
    "sqs_workload.cpp",
    "sqs_workload_clean.cpp",
    "sqs_workload_clean_scenario.cpp",
    "sqs_workload_init.cpp",
    "sqs_workload_init_scenario.cpp",
    "sqs_workload_read_scenario.cpp",
    "sqs_workload_reader.cpp",
    "sqs_workload_run.cpp",
    "sqs_workload_run_read.cpp",
    "sqs_workload_run_write.cpp",
    "sqs_workload_scenario.cpp",
    "sqs_workload_stats.cpp",
    "sqs_workload_stats_collector.cpp",
    "sqs_workload_write_scenario.cpp",
    "sqs_workload_writer.cpp",
  ]
}
