library("sqs_json") {
  public_deps = [
    # "//contrib/libs/aws-sdk-cpp/aws-cpp-sdk-core",
    "//contrib/libs/aws-sdk-cpp/aws-cpp-sdk-sqs",
  ]

  deps = [ "//library/cpp/string_utils/url" ]

  sources = [ "sqs_json/sqs_json_client.cpp" ]
}

group("sqs_workload") {
  public_deps = [ "//ydb/public/lib/ydb_cli/commands" ]

  deps = [
    # ":sqs_json",  # peerdir only
    # "//contrib/libs/fmt",  # peerdir only
    # "//library/cpp/containers/concurrent_hash",  # peerdir only
    # "//library/cpp/histogram/hdr",  # peerdir only
    # "//library/cpp/unified_agent_client",  # peerdir only
    # "//ydb/library/backup",  # peerdir only
    # "//ydb/public/api/grpc",  # peerdir only
    # "//ydb/public/api/protos",  # peerdir only
    # "//ydb/public/api/protos:annotations",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/draft",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/driver",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/proto",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/table",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/topic",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/types/operation",  # peerdir only
    # "//ydb/public/sdk/cpp/src/client/types/status",  # peerdir only
    # "//ydb/public/sdk/cpp/src/library/operation_id",  # peerdir only
    # "//yql/essentials/public/issue",  # peerdir only
    # "//yql/essentials/public/issue:protos",  # peerdir only
  ]
}
