unittest_executable("indexes") {
  deps = [
    "//library/cpp/json",
    "//library/cpp/threading/local_executor",
    "//ydb/core/client/minikql_compile",
    "//ydb/core/kqp",  # peerdir only
    "//ydb/core/kqp/common",
    "//ydb/core/kqp/gateway",
    "//ydb/core/kqp/host",
    "//ydb/core/kqp/ut/common",
    "//ydb/core/protos",
    "//ydb/core/testlib",
    "//ydb/core/tx/datashard",
    "//ydb/library/yql/providers/common/http_gateway",  # peerdir only
    "//ydb/public/sdk/cpp/adapters/issue",
    "//ydb/public/sdk/cpp/src/client/operation",
    "//ydb/public/sdk/cpp/src/client/proto",
    "//ydb/public/sdk/cpp/src/client/table",
    "//yql/essentials/core/services/mounts",
    "//yql/essentials/providers/common/provider",
    "//yql/essentials/sql/pg_dummy",  # peerdir only
  ]

  sources = [
    "kqp_indexes_multishard_ut.cpp",
    "kqp_indexes_prefixed_vector_ut.cpp",
    "kqp_indexes_ut.cpp",
    "kqp_indexes_vector_ut.cpp",
    "kqp_stream_indexes_ut.cpp",
  ]

  include_dirs = [
    "//ydb/core/kqp",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
