library("pqrb") {
  deps = [
    # "//library/cpp/monlib/dynamic_counters",
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/random_provider",
    # "//library/cpp/string_utils/base64",
    # "//ydb/core/base",
    # "//ydb/core/engine:minikql",
    # "//ydb/core/persqueue/common",
    # "//ydb/core/persqueue/common:proxy",
    # "//ydb/core/persqueue/events",
    # "//ydb/core/persqueue/public",
    # "//ydb/core/persqueue/public:partition_key_range",
    # "//ydb/core/protos",
    # "//ydb/core/protos/schemeshard",
    # "//ydb/core/tablet",
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/core/util",
    # "//ydb/library/actors/core",
    # "//ydb/library/persqueue/topic_parser",
    # "//ydb/library/yverify_stream",
    # "//ydb/public/lib/base",
    # "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/topic",
    # "//ydb/public/sdk/cpp/src/client/persqueue_public",
  ]

  sources = [
    "mirror_describer.cpp",
    "partition_scale_manager.cpp",
    "partition_scale_manager_graph_cmp.cpp",
    "partition_scale_request.cpp",
    "read_balancer.cpp",
    "read_balancer__balancing.cpp",
    "read_balancer__balancing_app.cpp",
    "read_balancer__metrics.cpp",
    "read_balancer__mlp_balancing.cpp",
    "read_balancer_app.cpp",
  ]

  serialize_enum_headers = [ "read_balancer__balancing.h" ]
}
