library("bootstrap") {
  public_deps = [
    # "//library/cpp/logger",
    # "//ydb/core/nbs/cloud/blockstore/libs/diagnostics",
    # "//ydb/core/nbs/cloud/blockstore/libs/vhost",
    # "//ydb/core/nbs/cloud/storage/core/libs/common",
    # "//ydb/core/nbs/cloud/storage/core/libs/diagnostics",
  ]

  deps = [
    # "//ydb/core/nbs/cloud/blockstore/libs/service",
  ]

  sources = [ "bootstrap.cpp" ]
}
