unittest_executable("ut") {
  deps = [
    "//contrib/libs/apache/arrow",
    "//library/cpp/digest/md5",
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/json",
    "//library/cpp/string_utils/base64",
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//ydb/core/formats/arrow",
    "//ydb/core/persqueue/ut/common",
    "//ydb/core/security/certificate_check",
    "//ydb/core/testlib",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx/schemeshard/ut_helpers",  # peerdir only
    "//ydb/library/formats/arrow/switch",
    "//ydb/public/api/grpc/draft",
    "//ydb/public/sdk/cpp/src/client/datastreams",
    "//ydb/public/sdk/cpp/src/client/persqueue_public",
    "//ydb/public/sdk/cpp/src/client/persqueue_public/ut/ut_utils",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/scheme",
    "//ydb/public/sdk/cpp/src/client/table",
    "//ydb/public/sdk/cpp/src/client/topic",
    "//ydb/public/sdk/cpp/src/client/topic/ut/ut_utils",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/types",
    "//ydb/public/sdk/cpp/src/client/value",
    "//ydb/public/sdk/cpp/src/library/grpc/client",  # peerdir only
    "//ydb/services/datastreams",  # peerdir only
    "//ydb/services/lib/sharding",
    "//ydb/services/ydb",
  ]

  sources = [ "//ydb/services/datastreams/datastreams_ut.cpp" ]

  include_dirs = [
    "//ydb/services/datastreams",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
