library("datastreams") {
  public_deps = [
    "//ydb/public/api/grpc:draft",
    "//ydb/public/sdk/cpp/src/client/table",
  ]

  deps = [
    "//library/cpp/threading/future",
    # "//ydb/public/sdk/cpp/src/client/common_client:impl",
    "//ydb/public/sdk/cpp/src/client/impl/internal/make_request",
    # "//ydb/public/sdk/cpp/src/library/issue",
    # "//ydb/public/sdk/cpp/src/library/grpc/client",
  ]

  sources = [ "datastreams.cpp" ]
}
