source_set("pg_dummy") {
    deps += [
        ":settings",
        "//contrib/libs/apache/arrow",
        "//yql/essentials/ast",
        "//yql/essentials/public/udf:_udf", # TODO: no linkage deps - just the include files hell.
    ]

    sources = [
        "pg_dummy/pg_sql_dummy.cpp"
    ]
}

library("settings") {
    deps = [
        "//library/cpp/deprecated/split",
        "//library/cpp/json",
        "//yql/essentials/core/issue",
        "//yql/essentials/parser/lexer_common",
        "//yql/essentials/utils",
    ]

    sources = [
        "settings/partitioning.cpp",
        "settings/translation_settings.cpp",
        "settings/translator.cpp",
    ]
}
