library("common") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/core/tx/columnshard/common",
    # "//ydb/library/accessor",
    "//ydb/library/conclusion",
  ]

  deps = [ "//ydb/core/tx/columnshard/export/protos" ]

  sources = [ "common/identifier.cpp" ]
}

group("export") {
  public_deps = [
    # ":common",  # peerdir only
    "//ydb/core/tx/columnshard",  # peerdir only
    # "//ydb/core/tx/columnshard/export/protos",  # peerdir only
  ]
}
