linked_executable("vector_index_builtin") {
  deps = [
    "//library/cpp/getopt",
    "//ydb/public/sdk/cpp/src/client/driver",
    "//ydb/public/sdk/cpp/src/client/helpers",
    "//ydb/public/sdk/cpp/src/client/query",
    "//ydb/public/sdk/cpp/src/client/table",
  ]

  sources = [
    "main.cpp",
    "vector_index.cpp",
  ]

  link_select = [ "allocator=tcmalloc" ]
}
