library("arrow") {
  public_deps = [ "//yql/essentials/providers/common/codec" ]

  deps = [
    "//yql/essentials/minikql/arrow",
    "//yql/essentials/public/udf:arrow",
  ]

  sources = [
    "arrow/yql_codec_buf_input_stream.cpp",
    "arrow/yql_codec_buf_output_stream.cpp",
  ]
}

library("codec") {
  public_deps = [
    "//library/cpp/enumbitset",
    "//library/cpp/json",
    "//library/cpp/yson",
    "//yql/essentials/ast",
    "//yql/essentials/minikql/computation",
    "//yql/essentials/parser/pg_wrapper/interface",
    "//yql/essentials/utils",
  ]

  deps = [
    "//library/cpp/string_utils/base64",
    "//library/cpp/yson:node",
    "//yql/essentials/core",
    "//yql/essentials/minikql",
    "//yql/essentials/public/decimal",
    "//yql/essentials/public/result_format",
  ]

  sources = [
    "yql_codec.cpp",
    "yql_codec_buf.cpp",
    "yql_codec_type_flags.cpp",
    "yql_json_codec.cpp",
  ]

  serialize_enum_headers = [ "yql_codec_type_flags.h" ]
}

group("yt_arrow_converter_interface") {
}
