import("//yql/essentials/core/expr_nodes_gen/gen.gni")

generate_expr_nodes("gen") {
    sources = [ "yql_kikimr_expr_nodes.json" ]
}

library("provider") {
    deps = [
        ":gen",
        "//ydb/core/protos",
    ]

    sources = [
        "read_attributes_utils.cpp",
        "rewrite_io_utils.cpp",
        "yql_kikimr_datasink.cpp",
        "yql_kikimr_datasource.cpp",
        "yql_kikimr_exec.cpp",
        "yql_kikimr_expr_nodes.cpp",
        "yql_kikimr_gateway.cpp",
        "yql_kikimr_opt_build.cpp",
        "yql_kikimr_opt.cpp",
        "yql_kikimr_provider.cpp",
        "yql_kikimr_results.cpp",
        "yql_kikimr_settings.cpp",
        "yql_kikimr_type_ann_pg.cpp",
        "yql_kikimr_type_ann.cpp",
    ]
}
