import("//contrib/libs/llvm16/llvm.gni")

llvm_library("ExecutionEngine") {
    public_deps = [ "//contrib/libs/llvm16/lib/IR" ]
    deps = [
        "Orc:TargetProcess",
        "RuntimeDyld",
        "//contrib/libs/llvm16/lib/MC",
        "//contrib/libs/llvm16/lib/Object",
        "//contrib/libs/llvm16/lib/TargetParser",
    ]

    sources = [
        "ExecutionEngine.cpp",
        "ExecutionEngineBindings.cpp",
        "GDBRegistrationListener.cpp",
        "SectionMemoryManager.cpp",
        "TargetSelect.cpp",
    ]
}
