library("pretty_printers") {
  deps = [
    # "//contrib/libs/protobuf",
    "//ydb/core/fq/libs/graph_params/proto",
    # "//ydb/library/protobuf_printer",
    "//ydb/library/yql/providers/dq/api/protos",
    # "//yql/essentials/minikql",
  ]

  sources = [
    "graph_params_printer.cpp",
    "minikql_program_printer.cpp",
  ]
}
