unittest_executable("ut") {
  deps = [
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/protobuf/json",
    "//library/cpp/regex/pcre",  # peerdir only
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//ydb/core/cms/console",
    "//ydb/core/testlib",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx/schemeshard",
    "//ydb/core/tx/tx_proxy:public",
    "//ydb/core/wrappers",
    "//ydb/core/wrappers:ut_helpers",
    "//ydb/library/accessor",
    "//ydb/library/actors/core",
    "//ydb/public/lib/yson_value",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/table",
    "//ydb/services/metadata",
    "//ydb/services/metadata/abstract",
    "//ydb/services/metadata/initializer",
    "//ydb/services/metadata/manager",
    "//ydb/services/metadata/secret",
  ]

  sources = [ "ut_init.cpp" ]

  include_dirs = [ "//ydb/services/metadata/initializer" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
