library("sqs_topic") {
  public_deps = [
    # "//ydb/core/client/server",
    # "//ydb/core/grpc_services",
    # "//ydb/library/actors/core",
    # "//ydb/library/grpc/server",
    # "//ydb/public/api/grpc:draft",
  ]

  deps = [
    # "//library/cpp/digest/md5",
    # "//library/cpp/json",
    # "//library/cpp/string_utils/base64",
    # "//ydb/core/base",
    # "//ydb/core/grpc_services/base",
    # "//ydb/core/http_proxy",
    # "//ydb/core/persqueue/events",
    # "//ydb/core/persqueue/public",
    # "//ydb/core/persqueue/public:describer",
    # "//ydb/core/persqueue/public:list_topics",
    # "//ydb/core/persqueue/public:mlp",
    # "//ydb/core/protos",
    # "//ydb/core/ymq/attributes",
    # "//ydb/core/ymq/base",
    # "//ydb/core/ymq/error",
    # "//ydb/library/http_proxy/error",
    # "//ydb/public/api/protos",
    # "//ydb/services/datastreams:codes",
    # "//ydb/services/lib/actors",
    # "//ydb/services/lib/sharding",
    # "//ydb/services/persqueue_v1:actors",
    # "//ydb/services/sqs_topic/protos/receipt",
    # "//ydb/services/sqs_topic/queue_url",
    # "//ydb/services/sqs_topic/queue_url:holder",
  ]

  sources = [
    "actor.cpp",
    "change_message_visibility.cpp",
    "consumer_attributes.cpp",
    "create_queue.cpp",
    "delete_message.cpp",
    "error.cpp",
    "get_queue_attributes.cpp",
    "list_queues.cpp",
    "purge_queue.cpp",
    "receipt.cpp",
    "receive_message.cpp",
    "send_message.cpp",
    "set_queue_attributes.cpp",
    "sqs_topic_proxy.cpp",
    "statuses.cpp",
    "utils.cpp",
  ]
}
