library("service") {
  public_deps = [
    # "//ydb/core/tx/priorities/usage",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//library/cpp/monlib/dynamic_counters",
    # "//ydb/core/kqp/query_data",
    # "//ydb/core/tx/conveyor/usage",
    # "//ydb/library/signals",
  ]

  sources = [
    "counters.cpp",
    "manager.cpp",
    "service.cpp",
  ]
}
