library("direct_block_group") {
  public_deps = [
    # "//ydb/core/blobstorage/ddisk",
    # "//ydb/core/mind:bscontroller",
    # "//ydb/core/nbs/cloud/blockstore/libs/service",
    # "//ydb/core/nbs/cloud/blockstore/libs/service/fast_path_service:storage_transport",
    # "//ydb/library/pdisk_io",
  ]

  deps = [
    # "//ydb/core/nbs/cloud/storage/core/libs/common",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/util",
    # "//ydb/library/actors/wilson",
    # "//ydb/library/wilson_ids",
  ]

  sources = [
    "direct_block_group.cpp",
    "direct_block_group_in_mem.cpp",
    "request.cpp",
  ]
}
