unittest_executable("ut_login") {
  deps = [
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/regex/pcre",  # peerdir only
    "//library/cpp/string_utils/base64",
    "//library/cpp/svnversion",  # peerdir only
    "//ydb/core/grpc_services",
    "//ydb/core/protos",
    "//ydb/core/protos/schemeshard",
    "//ydb/core/security",
    "//ydb/core/security/ldap_auth_provider",
    "//ydb/core/security/ldap_auth_provider:test_utils",
    "//ydb/core/testlib/audit_helpers",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx",  # peerdir only
    "//ydb/core/tx/schemeshard",  # peerdir only
    "//ydb/core/tx/schemeshard/ut_helpers",
    "//ydb/library/actors/http",
    "//ydb/library/login",
    "//ydb/library/login/password_checker",
    "//ydb/library/testlib/service_mocks/ldap_mock",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
  ]

  sources = [ "ut_login.cpp" ]

  include_dirs = [
    "//ydb/core/tx/schemeshard",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
