library("auth") {
  public_deps = [
    # "//ydb/core/base",
    "//ydb/core/kqp/runtime",
    "//ydb/core/protos",
    "//ydb/core/sys_view/common",
    # "//ydb/library/actors/core",
    "//ydb/library/login/protos",
  ]

  deps = [ "//ydb/core/ydb_convert" ]

  sources = [
    "group_members.cpp",
    "groups.cpp",
    "owners.cpp",
    "permissions.cpp",
    "users.cpp",
  ]
}
