library("accessor") {
  public_deps = [
    "//ydb/core/base",
    # "//ydb/core/protos",
    # "//ydb/library/accessor",
  ]

  deps = [
    "//library/cpp/digest/md5",
    # "//ydb/services/metadata/manager",
  ]

  sources = [ "accessor/secret_id.cpp" ]
}

library("secret") {
  public_deps = [
    ":accessor",
    "//ydb/core/base",
    # "//ydb/library/accessor",
    "//ydb/services/metadata/abstract",
    "//ydb/services/metadata/initializer",
    "//ydb/services/metadata/manager",
  ]

  deps = [
    # "//library/cpp/digest/md5",
    "//ydb/core/grpc_services",
    "//ydb/core/grpc_services/local_rpc",
    # "//ydb/services/metadata",
  ]

  sources = [
    "access.cpp",
    "access_behaviour.cpp",
    "checker_access.cpp",
    "checker_secret.cpp",
    "fetcher.cpp",
    "initializer.cpp",
    "manager.cpp",
    "secret.cpp",
    "secret_behaviour.cpp",
    "snapshot.cpp",
  ]
}
