library("resources") {
  public_deps = [
    # "//ydb/library/actors/core",
    "//ydb/library/services",
    # "//ydb/library/signals",
  ]

  deps = [
    # "//contrib/libs/apache/arrow",  # peerdir only
    # "//ydb/core/formats/arrow",  # peerdir only
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [ "memory.cpp" ]
}
