group("data_locks") {
  public_deps = [
    # ":locks",  # peerdir only
    # ":manager",  # peerdir only
  ]
}

library("locks") {
  public_deps = [
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/library/accessor",
  ]

  sources = [
    "locks/abstract.cpp",
    "locks/composite.cpp",
    "locks/list.cpp",
    "locks/snapshot.cpp",
  ]

  plugins = [ "//ydb/core/tx/columnshard/engines/storage" ]
}

library("manager") {
  public_deps = [
    # ":locks",
    "//ydb/core/tx/columnshard/hooks/abstract",
  ]

  deps = [
    # "//ydb/library/actors/core",
  ]

  sources = [ "manager/manager.cpp" ]
}
