protobuf_library("protos") {
    extra_plugins = [
        {
            name = "validation"
            target = "//ydb/public/lib/validation:validation"
        }
    ]

    public_deps = [
        "//ydb/core/nbs/cloud/storage/core/protos",
    ]

    sources = [
        "headers.proto",
        "io.proto",
    ]
}
