unittest_executable("ut_ttl") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/kqp/ut/common",
    "//ydb/core/testlib",
    "//ydb/core/tx/datashard",
    "//ydb/core/tx/schemeshard",
    "//ydb/core/tx/schemeshard/common",
    "//ydb/core/tx/schemeshard/ut_helpers",
    "//yql/essentials/parser/pg_wrapper",  # peerdir only
    "//yql/essentials/sql/pg",  # peerdir only
  ]

  sources = [
    "ut_ttl.cpp",
    "ut_ttl_utility.cpp",
  ]

  include_dirs = [ "//ydb/core/tx/schemeshard" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_wrapper",
    "yql_pg_sql_translator=pg",
    "yt_codegen=llvm16",
  ]
}
