library("transform") {
  public_deps = [
    # "//yql/essentials/ast",
    # "//yql/essentials/core",
    # "//yql/essentials/core/expr_nodes",
    # "//yql/essentials/utils/log",
  ]

  deps = [
    # "//yql/essentials/utils",
  ]

  sources = [
    "yql_exec.cpp",
    "yql_lazy_init.cpp",
    "yql_optimize.cpp",
    "yql_visit.cpp",
  ]
}
