library("runtime") {
  public_deps = [
    # "//contrib/libs/apache/arrow",
    # "//library/cpp/containers/stack_vector",
    # "//library/cpp/time_provider",
    # "//ydb/core/base",
    # "//ydb/core/engine:minikql",
    # "//ydb/core/formats/arrow",
    # "//ydb/core/kqp/common:buffer",
    # "//ydb/core/kqp/common:result_set_format",
    # "//ydb/core/kqp/counters",
    # "//ydb/core/kqp/gateway",
    # "//ydb/core/protos",
    # "//ydb/core/resource_pools",
    # "//ydb/core/scheme",
    # "//ydb/core/scheme_types",
    # "//ydb/core/tablet_flat",
    # "//ydb/core/tx/data_events",
    # "//ydb/core/tx/datashard",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/library/actors/core",
    # "//ydb/library/formats/arrow:validation",
    # "//ydb/library/services",
    # "//ydb/library/yql/dq/actors:compute",
    # "//ydb/library/yql/dq/actors:protos",
    # "//ydb/library/yql/dq/common",
    # "//ydb/library/yql/dq/comp_nodes",
    # "//ydb/library/yql/dq/runtime",
    # "//yql/essentials/ast",
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/computation",
    # "//yql/essentials/parser/pg_wrapper/interface",
    # "//yql/essentials/utils",
  ]

  deps = [
    # "//library/cpp/containers/absl_flat_hash",
    # "//library/cpp/monlib/dynamic_counters",
    # "//library/cpp/regex/pire",
    # "//library/cpp/threading/hot_swap",
    # "//ydb/core/actorlib_impl",
    # "//ydb/core/cms/console",
    # "//ydb/core/engine",
    # "//ydb/core/formats/arrow/accessor/plain",
    # "//ydb/core/kqp/common",
    # "//ydb/core/kqp/common:events",
    # "//ydb/core/kqp/common:simple",
    # "//ydb/core/persqueue/events",
    # "//ydb/core/scheme:protos",
    # "//ydb/core/tx",
    # "//ydb/core/tx/locks",
    # "//ydb/core/tx/schemeshard/olap/schema",
    # "//ydb/core/tx/sequenceproxy:public",
    # "//ydb/core/tx/sharding",
    # "//ydb/library/wilson_ids",
    # "//ydb/library/yql/dq/proto",
    # "//ydb/public/api/protos",
    # "//yql/essentials/minikql/comp_nodes",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/public/udf",
    # "//yql/essentials/public/udf:arrow",
  ]

  sources = [
    "kqp_arrow_memory_pool.cpp",
    "kqp_buffer_lookup_actor.cpp",
    "kqp_compute.cpp",
    "kqp_effects.cpp",
    "kqp_full_text_source.cpp",
    "kqp_fulltext_analyze.cpp",
    "kqp_output_stream.cpp",
    "kqp_program_builder.cpp",
    "kqp_read_actor.cpp",
    "kqp_read_iterator_common.cpp",
    "kqp_read_table.cpp",
    "kqp_scan_data.cpp",
    "kqp_scan_data_meta.cpp",
    "kqp_sequencer_actor.cpp",
    "kqp_sequencer_factory.cpp",
    "kqp_stream_lookup_actor.cpp",
    "kqp_stream_lookup_factory.cpp",
    "kqp_stream_lookup_join_helpers.cpp",
    "kqp_stream_lookup_worker.cpp",
    "kqp_tasks_runner.cpp",
    "kqp_transport.cpp",
    "kqp_vector_actor.cpp",
    "kqp_write_actor.cpp",
    "kqp_write_actor_settings.cpp",
    "kqp_write_table.cpp",
    "scheduler/kqp_compute_scheduler_service.cpp",
    "scheduler/kqp_schedulable_actor.cpp",
    "scheduler/kqp_schedulable_task.cpp",
    "scheduler/tree/dynamic.cpp",
    "scheduler/tree/snapshot.cpp",
  ]
}
