# yamake2gn: keep  -- hand-written, do not regenerate

group("common") {
  public_deps = [ "//ydb/core/tx/schemeshard" ]
}

group("config_shards") {
  public_deps = [ "//ydb/core/tx/schemeshard" ]
}

group("in_store") {
  public_deps = [ "//ydb/core/tx/schemeshard" ]
}

group("resharding") {
  public_deps = [ "//ydb/core/tx/schemeshard" ]
}

group("schema") {
  public_deps = [ "//ydb/core/tx/schemeshard" ]
}

group("transfer") {
  public_deps = [ "//ydb/core/tx/schemeshard" ]
}
