# yamake2gn: keep  -- hand-written, do not regenerate

library("expr_nodes_gen") {
  public_deps = [ "//yql/essentials/utils" ]

  deps = [ "//yql/essentials/ast" ]

  sources = [ "yql_expr_nodes_gen.cpp" ]
}

python_binary("gen") {
    deps = [
        "//contrib/python/Jinja2",
    ]

    main_source = "gen/main.py"
}
