template("generate_expr_nodes") {
    _path = rebase_path(".", "//")
    _unique_name = exec_script("//build/gn/scripts/unique_name.py", [ _path ], "trim string")
    _gen_target = "${_unique_name}_${target_name}_gen"

    python_action_foreach(_gen_target) {
        binary_label = "//yql/essentials/core/expr_nodes_gen:gen"
        sources = invoker.sources
        inputs = [
            "//yql/essentials/core/expr_nodes_gen/yql_expr_nodes_gen.jnj",
        ]
        outputs = [
            "{{source_gen_dir}}/{{source_name_part}}.gen.h",
            "{{source_gen_dir}}/{{source_name_part}}.decl.inl.h",
            "{{source_gen_dir}}/{{source_name_part}}.defs.inl.h",
        ]

        args = [
            rebase_path("yql_expr_nodes_gen.jnj", root_build_dir),
            "{{source}}",
        ] + outputs
    }

    library(target_name) {
        deps = [ ":$_gen_target" ]
    }
}
