unittest_executable("ut_rs") {
  deps = [
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/regex/pcre",  # peerdir only
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//ydb/core/grpc_services/local_rpc",
    "//ydb/core/kqp/ut/common",  # peerdir only
    "//ydb/core/testlib",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx",  # peerdir only
    "//ydb/core/tx/datashard",
    "//ydb/core/tx/datashard/ut_common",
    "//ydb/core/tx/schemeshard",
    "//ydb/core/tx/tx_proxy:public",
    "//ydb/library/ut",
    "//ydb/public/lib/yson_value",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/result",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
  ]

  sources = [ "//ydb/core/tx/datashard/datashard_ut_rs.cpp" ]

  include_dirs = [ "//ydb/core/tx/datashard" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
