library("yt_file_download") {
  public_deps = [
    # "//yql/essentials/core",
    # "//yql/essentials/minikql",
    # "//yt/yql/providers/yt/common",
    # "//yt/yql/providers/yt/gateway/lib",
    # "//yt/yql/providers/yt/provider",
  ]

  deps = [
    # "//library/cpp/streams/brotli",
    # "//library/cpp/yson:node",
    # "//yql/essentials/utils/log",
    # "//yt/cpp/mapreduce/common",
    # "//yt/cpp/mapreduce/interface",
  ]

  sources = [ "yql_yt_file_download.cpp" ]
}
