# yamake2gn: keep  -- hand-written, do not regenerate

library("server") {
  public_deps = [
    "//ydb/core/base",
    # "//ydb/core/grpc_services/base",
    # "//ydb/core/persqueue/events",
    # "//ydb/core/protos",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    "//ydb/library/actors/core",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/grpc/server",
    # "//ydb/library/persqueue/topic_parser",
    # "//ydb/public/api/protos",
    # "//ydb/public/lib/base",
    # "//ydb/public/lib/deprecated/client",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/public/sdk/cpp/src/client/table",
  ]

  deps = [
    # "//library/cpp/json",
    # "//library/cpp/messagebus",
    # "//library/cpp/monlib/messagebus",
    # "//library/cpp/monlib/service",
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/protobuf/json",
    # "//library/cpp/random_provider",
    # "//ydb/core/blobstorage",
    # "//ydb/core/client/metadata",
    # "//ydb/core/cms",
    # "//ydb/core/cms/console",
    "//ydb/core/grpc_services",
    "//ydb/core/grpc_services/counters",
    # "//ydb/core/jaeger_tracing",
    # "//ydb/core/kqp/common",
    # "//ydb/core/mind",
    # "//ydb/core/mon",
    # "//ydb/core/node_whiteboard",
    # "//ydb/core/persqueue/public",
    # "//ydb/core/persqueue/public:cluster_tracker",
    # "//ydb/core/protos/schemeshard",
    # "//ydb/core/scheme",
    "//ydb/core/security",
    # "//ydb/core/tablet",
    # "//ydb/core/test_tablet",
    # "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/protos",
    # "//ydb/library/services",
    # "//ydb/library/wilson_ids",
    # "//ydb/library/ydb_issue",
    # "//ydb/public/lib/deprecated/kicli",
    # "//ydb/services/persqueue_v1:actors",
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/invoke_builtins",
    # "//yql/essentials/public/issue",
  ]

  sources = [
    "grpc_proxy_status.cpp",
    "grpc_server.cpp",
    "ic_nodes_cache_service.cpp",
    "msgbus_blobstorage_config.cpp",
    "msgbus_http_server.cpp",
    "msgbus_server.cpp",
    "msgbus_server_cms.cpp",
    "msgbus_server_configdummy.cpp",
    "msgbus_server_console.cpp",
    "msgbus_server_drain_node.cpp",
    "msgbus_server_fill_node.cpp",
    "msgbus_server_hive_create_tablet.cpp",
    "msgbus_server_ic_debug.cpp",
    "msgbus_server_node_registration.cpp",
    "msgbus_server_persqueue.cpp",
    "msgbus_server_pq_metacache.cpp",
    "msgbus_server_pq_metarequest.cpp",
    "msgbus_server_pq_read_session_info.cpp",
    "msgbus_server_proxy.cpp",
    "msgbus_server_resolve_node.cpp",
    "msgbus_server_scheme_initroot.cpp",
    "msgbus_server_scheme_request.cpp",
    "msgbus_server_tablet_counters.cpp",
    "msgbus_server_tablet_state.cpp",
    "msgbus_server_test_shard_request.cpp",
    "msgbus_server_tx_request.cpp",
    "msgbus_server_types.cpp",

    "//ydb/core/grpc_services/legacy/rpc_legacy.cpp",
  ]
}
