gtest_executable("topic") {
  public_deps = [
    "//contrib/libs/grpc",
    "//contrib/restricted/googletest/googletest",
    "//library/cpp/logger",
    "//library/cpp/threading/future",
    "//ydb/public/api/grpc",
    "//ydb/public/sdk/cpp/src/client/topic",
    "//ydb/public/sdk/cpp/src/client/topic/common",
  ]

  deps = [
    "//ydb/public/api/protos",
    "//ydb/public/sdk/cpp/src/client/persqueue_public",
    "//ydb/public/sdk/cpp/src/client/persqueue_public/impl",
    "//ydb/public/sdk/cpp/src/client/query",
    "//ydb/public/sdk/cpp/src/client/table",
    "//ydb/public/sdk/cpp/src/client/topic/impl",
    "//ydb/public/sdk/cpp/src/library/issue",
    "//ydb/public/sdk/cpp/tests/integration/topic/setup",  # peerdir only
    "//ydb/public/sdk/cpp/tests/integration/topic/utils",  # peerdir only
  ]

  data_deps = [ "//ydb/apps/ydbd" ]

  sources = [
    "basic_usage_it.cpp",
    "describe_topic_it.cpp",
    "local_partition_it.cpp",
    "topic_to_table_it.cpp",
    "trace_it.cpp",
  ]

  test_depends_unbuilt = [ "//ydb/public/tools/ydb_recipe" ]

  link_select = [ "allocator=tcmalloc" ]
}
