group("client") {
  public_deps = [
    # ":metadata",
    # ":minikql_compile",
    # ":scheme_cache_lib",  # peerdir only
    # ":server",  # peerdir only
  ]

  deps = [
    # "//ydb/core/base",  # peerdir only
    # "//ydb/core/engine",  # peerdir only
    # "//ydb/library/grpc/server",  # peerdir only
    # "//ydb/public/lib/deprecated/kicli",  # peerdir only
  ]
}

library("db_key_resolver") {
  public_deps = [
    "//library/cpp/threading/future",
    "//ydb/core/scheme",
    "//ydb/library/actors/core",
  ]

  sources = [ "minikql_compile/db_key_resolver.cpp" ]
}

library("metadata") {
  deps = [
    "//ydb/core/protos",
    # "//ydb/core/scheme_types",
    "//yql/essentials/minikql",
  ]

  sources = [
    "metadata/functions_metadata.cpp",
    "metadata/types_metadata.cpp",
  ]
}

library("minikql_compile") {
  public_deps = [
    ":db_key_resolver",
    ":scheme_cache_lib",
    # "//library/cpp/threading/future",
    "//ydb/core/engine",
    "//ydb/library/actors/core",
    "//yql/essentials/ast",
    "//yql/essentials/minikql",
  ]

  deps = [
    "//ydb/core/base",
    "//ydb/core/kqp/provider",
    # "//ydb/core/scheme",  # peerdir only
    "//ydb/core/tx/scheme_board",
    "//ydb/core/tx/scheme_cache",
    # "//ydb/library/services",
    # "//ydb/library/ydb_issue:proto",
    # "//ydb/public/lib/scheme_types",
    # "//yql/essentials/core",
    "//yql/essentials/core/type_ann",
    # "//yql/essentials/minikql/invoke_builtins",
    "//yql/essentials/providers/common/mkql",
  ]

  sources = [
    "minikql_compile/compile_context.cpp",
    "minikql_compile/compile_result.cpp",
    "minikql_compile/mkql_compile_service.cpp",
    "minikql_compile/yql_expr_minikql.cpp",
  ]
}

library("scheme_cache_lib") {
  public_deps = [
    # "//ydb/core/base",
  ]

  deps = [
    ":db_key_resolver",
    # "//contrib/libs/protobuf",  # peerdir only
    # "//library/cpp/threading/future",  # peerdir only
    # "//ydb/core/protos",  # peerdir only
    # "//ydb/core/scheme",  # peerdir only
    # "//ydb/core/tablet",  # peerdir only
    # "//ydb/core/tx",  # peerdir only
    "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/library/actors/core",
    # "//ydb/public/sdk/cpp/src/library/grpc/client",  # peerdir only
  ]

  sources = [ "scheme_cache_lib/yql_db_scheme_resolver.cpp" ]
}

library("server") {
  public_deps = [
    # "//library/cpp/monlib/service",
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/uri",
    "//ydb/core/base",
    # "//ydb/core/grpc_services/base",
    # "//ydb/core/mon",
    # "//ydb/core/persqueue/events",
    # "//ydb/core/protos",
    "//ydb/core/tablet",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    "//ydb/library/actors/core",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/grpc/server",
    "//ydb/library/persqueue/topic_parser",
    # "//ydb/library/services",
    # "//ydb/public/api/protos",
    # "//ydb/public/lib/base",
    # "//ydb/public/lib/deprecated/client",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/public/sdk/cpp/src/client/table",
  ]

  deps = [
    ":metadata",
    # ":scheme_cache_lib",  # peerdir only
    # "//contrib/libs/grpc",
    # "//library/cpp/deprecated/atomic",  # peerdir only
    # "//library/cpp/json",
    "//library/cpp/messagebus",
    "//library/cpp/messagebus:protobuf",  # peerdir only
    "//library/cpp/monlib/messagebus",
    "//library/cpp/protobuf/json",
    # "//library/cpp/protobuf/util",  # peerdir only
    # "//library/cpp/random_provider",
    # "//library/cpp/threading/future",  # peerdir only
    # "//ydb/core/actorlib_impl",  # peerdir only
    # "//ydb/core/blobstorage/base",  # peerdir only
    # "//ydb/core/blobstorage/events",
    # "//ydb/core/cms",
    # "//ydb/core/cms/console",
    # "//ydb/core/engine",  # peerdir only
    # "//ydb/core/engine:minikql",  # peerdir only
    "//ydb/core/grpc_services",
    # "//ydb/core/jaeger_tracing",
    # "//ydb/core/keyvalue",  # peerdir only
    # "//ydb/core/kqp/common",
    # "//ydb/core/mind",
    # "//ydb/core/node_whiteboard",
    # "//ydb/core/persqueue",  # peerdir only
    # "//ydb/core/persqueue/public",
    # "//ydb/core/persqueue/public:cluster_tracker",
    # "//ydb/core/persqueue/writer",  # peerdir only
    # "//ydb/core/protos:schemeshard",
    # "//ydb/core/scheme",
    "//ydb/core/security",
    # "//ydb/core/security:certificate_check",  # peerdir only
    # "//ydb/core/test_tablet",
    # "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/tx_proxy:public",
    # "//ydb/core/ydb_convert",  # peerdir only
    # "//ydb/core/ymq/actor",  # peerdir only
    # "//ydb/library/aclib",
    # "//ydb/library/actors/helpers",  # peerdir only
    # "//ydb/library/actors/protos",
    # "//ydb/library/protobuf_printer",
    # "//ydb/library/wilson_ids",
    # "//ydb/library/ydb_issue",
    # "//ydb/public/api/grpc",  # peerdir only
    # "//ydb/public/api/grpc:draft",  # peerdir only
    # "//ydb/public/lib/deprecated/kicli",
    # "//ydb/public/sdk/cpp/src/client/resources",
    # "//ydb/services/persqueue_v1",  # peerdir only
    # "//ydb/services/persqueue_v1:actors",
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/invoke_builtins",
    # "//yql/essentials/public/issue",
  ]

  sources = [
    "//ydb/core/grpc_services/legacy/rpc_legacy.cpp",
    "server/grpc_proxy_status.cpp",
    "server/grpc_server.cpp",
    "server/ic_nodes_cache_service.cpp",
    "server/msgbus_blobstorage_config.cpp",
    "server/msgbus_http_server.cpp",
    "server/msgbus_server.cpp",
    "server/msgbus_server_cms.cpp",
    "server/msgbus_server_configdummy.cpp",
    "server/msgbus_server_console.cpp",
    "server/msgbus_server_drain_node.cpp",
    "server/msgbus_server_fill_node.cpp",
    "server/msgbus_server_hive_create_tablet.cpp",
    "server/msgbus_server_ic_debug.cpp",
    "server/msgbus_server_node_registration.cpp",
    "server/msgbus_server_persqueue.cpp",
    "server/msgbus_server_pq_metacache.cpp",
    "server/msgbus_server_pq_metarequest.cpp",
    "server/msgbus_server_pq_read_session_info.cpp",
    "server/msgbus_server_proxy.cpp",
    "server/msgbus_server_resolve_node.cpp",
    "server/msgbus_server_scheme_initroot.cpp",
    "server/msgbus_server_scheme_request.cpp",
    "server/msgbus_server_tablet_counters.cpp",
    "server/msgbus_server_tablet_state.cpp",
    "server/msgbus_server_test_shard_request.cpp",
    "server/msgbus_server_tx_request.cpp",
    "server/msgbus_server_types.cpp",
  ]
}
