config("public_config") {
    cflags = [
        "-Wno-deprecated-volatile",
    ]
}

library("base") {
    public_deps = [
        "generated",
        "//ydb/core/control/lib",
        "//ydb/core/fq/libs/events",
        "//ydb/core/protos",
        "//ydb/core/scheme",
        "//ydb/library/actors/interconnect",
    ]

    deps = [
        "//contrib/libs/snowball",
        "//library/cpp/dot_product",
        "//library/cpp/dwarf_backtrace",
        "//library/cpp/l2_distance",
        "//library/cpp/monlib/dynamic_counters",
        "//library/cpp/monlib/service:pages",
        "//library/cpp/random_provider",
        "//library/cpp/threading/hot_swap",
        "//library/cpp/time_provider",
        "//ydb/core/audit:config",
        "//ydb/core/erasure",
        "//ydb/core/graph:api",
        "//ydb/core/jaeger_tracing",
        "//ydb/library/aclib",
        "//ydb/library/actors/helpers",
        "//ydb/library/actors/util",
        "//ydb/library/actors/wilson",
        "//ydb/library/login",
        "//ydb/library/pdisk_io:device_type",
        "//yql/essentials/minikql",
    ]

    sources = [
        "actor_activity_names.cpp",
        "appdata.cpp",
        "auth.cpp",
        "backtrace.cpp",
        "blobstorage_grouptype.cpp",
        "blobstorage_relevance.cpp",
        "blobstorage.cpp",
        "board_lookup.cpp",
        "board_publish.cpp",
        "board_replica.cpp",
        "boot_type.cpp",
        "bridge.cpp",
        "counters.cpp",
        "domain.cpp",
        "event_filter.cpp",
        "feature_flags_service.cpp",
        "fulltext.cpp",
        "group_stat.cpp",
        "kmeans_clusters.cpp",
        "local_user_token.cpp",
        "localdb.cpp",
        "logoblob.cpp",
        "path.cpp",
        "pool_stats_collector.cpp",
        "row_version.cpp",
        "services_assert.cpp",
        "statestorage_event_filter.cpp",
        "statestorage_guardian.cpp",
        "statestorage_monitoring.cpp",
        "statestorage_proxy.cpp",
        "statestorage_replica.cpp",
        "statestorage.cpp",
        "storage_pools.cpp",
        "subdomain.cpp",
        "table_index.cpp",
        "tablet_killer.cpp",
        "tablet_status_checker.cpp",
        "tablet.cpp",
        "traceid.cpp",
        "tx_processing.cpp",
        "wilson_tracing_control.cpp",
    ]

    serialize_enum_headers = [
        "boot_type.h",
        "memory_controller_iface.h",
    ]

    public_configs = [ ":public_config" ]
}
