library("portion") {
  deps = [
    # "//ydb/core/base",
    # "//ydb/core/formats/arrow",
    # "//ydb/core/keyvalue",
    # "//ydb/core/protos",
    "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/blobs_action/counters",
    "//ydb/core/tx/columnshard/blobs_reader",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/data_accessor",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/scheme",
    # "//ydb/core/tx/columnshard/normalizer/abstract",
    # "//ydb/core/tx/conveyor/usage",
    # "//ydb/core/tx/conveyor_composite/usage",
    # "//ydb/library/actors/core",
  ]

  sources = [
    "broken_blobs.cpp",
    "chunks.cpp",
    "chunks_actualization.cpp",
    "chunks_v0_meta.cpp",
    "clean.cpp",
    "clean_deprecated_snapshot.cpp",
    "clean_empty.cpp",
    "clean_index_columns.cpp",
    "clean_inserted_portions.cpp",
    "clean_sub_columns_portions.cpp",
    "clean_ttl_preset_setting_info.cpp",
    "clean_ttl_preset_setting_version_info.cpp",
    "clean_unused_tables_template.cpp",
    "copy_blob_ids_to_v2.cpp",
    "leaked_blobs.cpp",
    "normalizer.cpp",
    "portion.cpp",
    "restore_appearance_snapshot.cpp",
    "restore_v1_chunks.cpp",
    "restore_v2_chunks.cpp",
    "special_cleaner.cpp",
  ]
}
