library("sub_columns") {
  deps = [
    "//ydb/core/formats/arrow",
    # "//ydb/core/formats/arrow/accessor/common",
    "//ydb/core/formats/arrow/accessor/sparsed",
    "//ydb/core/formats/arrow/accessor/sub_columns",
    # "//ydb/core/tx/columnshard/engines/changes/compaction/common",  # peerdir only
    "//ydb/core/tx/columnshard/engines/changes/compaction:abstract",
    "//ydb/core/tx/columnshard/engines/portions",
  ]

  sources = [
    "builder.cpp",
    "iterator.cpp",
    "logic.cpp",
    "remap.cpp",
  ]
}
