gtest_executable("value") {
  deps = [
    "//contrib/libs/protobuf",
    "//contrib/restricted/googletest/googletest",
    "//ydb/public/api/protos",
    "//ydb/public/sdk/cpp/src/client/params",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/types/exceptions",
    "//ydb/public/sdk/cpp/src/client/value",
  ]

  sources = [ "value_ut.cpp" ]

  link_select = [ "allocator=tcmalloc" ]
}
