library("jsonpath") {
  public_deps = [
    # "//library/cpp/containers/stack_vector",
    # "//library/cpp/json",
    # "//yql/essentials/minikql/jsonpath/parser",
    "//yql/essentials/public/issue",
    # "//yql/essentials/public/udf",
    "//yql/essentials/types/binary_json",
    "//yql/essentials/utils",
  ]

  deps = [
    # "//yql/essentials/ast",  # peerdir only
    # "//yql/essentials/core/issue:protos",
    # "//yql/essentials/minikql/dom",
    # "//yql/essentials/minikql/jsonpath/rewrapper",  # peerdir only
    # "//yql/essentials/minikql/jsonpath/rewrapper:hyperscan",  # peerdir only
    # "//yql/essentials/minikql/jsonpath/rewrapper:re2",  # peerdir only
  ]

  sources = [
    "executor.cpp",
    "jsonpath.cpp",
    "value.cpp",
  ]

  yql_abi_version = "2.27.0"
}
