unittest_executable("discovery") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/discovery",
    "//ydb/core/kqp/ut/common",
    "//yql/essentials/sql/pg_dummy",  # peerdir only
  ]

  sources = [ "kqp_discovery_ut.cpp" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
