library("executer_actor") {
  public_deps = [
    # "//library/cpp/lwtrace",
    "//ydb/core/kqp/common",
    # "//ydb/core/kqp/counters",
    # "//ydb/core/kqp/federated_query",
    # "//ydb/core/kqp/gateway",
    "//ydb/core/kqp/proxy_service",
    # "//ydb/core/kqp/query_data",
    "//ydb/core/protos",
    # "//ydb/core/tx/long_tx_service:public",
    # "//ydb/library/aclib",
    # "//ydb/library/yql/dq/actors:compute",
    # "//ydb/library/yql/dq/actors:protos",
    # "//ydb/library/yql/dq/common",
    # "//ydb/library/yql/dq/runtime",
    # "//yql/essentials/core/pg_settings",
    # ":shards_resolver",
  ]

  deps = [
    # "//ydb/core/actorlib_impl",
    # "//ydb/core/base",
    # "//ydb/core/client/minikql_compile",
    # "//ydb/core/engine:minikql",
    "//ydb/core/fq/libs/checkpointing",
    # "//ydb/core/fq/libs/checkpointing:events",
    # "//ydb/core/grpc_services",
    # "//ydb/core/kqp/common:buffer",
    # "//ydb/core/kqp/common:events",
    # "//ydb/core/kqp/common:simple",
    "//ydb/core/kqp/compute_actor",
    # "//ydb/core/kqp/federated_query:actors",
    # "//ydb/core/kqp/gateway:actors",
    # "//ydb/core/kqp/gateway:local_rpc",
    # "//ydb/core/kqp/gateway:utils",
    # "//ydb/core/kqp/node_service",
    # "//ydb/core/kqp/opt",
    # "//ydb/core/kqp/rm_service",
    # "//ydb/core/kqp/runtime",
    # "//ydb/core/kqp/session_actor",
    # "//ydb/core/persqueue/events",
    # "//ydb/core/protos/schemeshard",
    # "//ydb/core/scheme",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/data_events:common",
    # "//ydb/core/tx/datashard",
    # "//ydb/core/tx/program",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/core/tx/schemeshard/olap/schema",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/core/util",
    # "//ydb/core/ydb_convert",
    # "//ydb/library/actors/async",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/wilson",
    # "//ydb/library/mkql_proto",
    # "//ydb/library/plan2svg",
    # "//ydb/library/wilson_ids",
    # "//ydb/library/ydb_issue",
    # "//ydb/library/yql/dq/comp_nodes",
    # "//ydb/library/yql/dq/tasks",
    # "//ydb/library/yql/providers/common/http_gateway",
    # "//ydb/library/yql/providers/pq/proto",
    # "//ydb/public/api/protos",
    # "//ydb/services/metadata/abstract",
    # "//ydb/services/metadata/secret",
    # "//yql/essentials/core",
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/computation",
    # "//yql/essentials/providers/common/structured_token",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/utils",
    # "//yql/essentials/utils/log",
  ]

  sources = [
    "kqp_data_executer.cpp",
    "kqp_executer_impl.cpp",
    "kqp_executer_stats.cpp",
    "kqp_literal_executer.cpp",
    "kqp_locks_helper.cpp",
    "kqp_partition_helper.cpp",
    "kqp_partitioned_executer.cpp",
    "kqp_planner.cpp",
    "kqp_planner_strategy.cpp",
    "kqp_scan_executer.cpp",
    "kqp_scheme_executer.cpp",
    "kqp_table_resolver.cpp",
    "kqp_tasks_graph.cpp",
    "kqp_tasks_validate.cpp",
    "shard_key_ranges.cpp",
  ]

  serialize_enum_headers = [ "kqp_executer.h" ]
}

library("shards_resolver") {
  public_deps = [
    # "//ydb/core/kqp/common:simple",
    "//ydb/library/actors/core",
    # "//ydb/public/api/protos",
    "//yql/essentials/public/issue",
  ]

  deps = [
    "//ydb/core/base",
  ]

  sources = [ "shards_resolver/kqp_shards_resolver.cpp" ]
}
