library("common") {
  testonly = true

  public_deps = [
    "//ydb/core/kqp/common/events",
    # "//ydb/core/kqp/federated_query/actors",
    "//ydb/core/kqp/ut/common",
    # "//ydb/library/aclib",
    # "//ydb/public/sdk/cpp/src/client/table",
  ]

  deps = [
    # "//ydb/core/kqp/common/simple",
  ]

  sources = [ "helpers.cpp" ]
}
