library("index") {
  public_deps = [
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/engines",
    # "//ydb/core/tx/columnshard/engines/storage/actualizer/abstract",
    # "//ydb/core/tx/columnshard/engines/storage/actualizer/counters",
  ]

  deps = [
    # "//ydb/core/tx/columnshard/engines/storage/actualizer/scheme",
    # "//ydb/core/tx/columnshard/engines/storage/actualizer/tiering",
    # "//ydb/core/tx/columnshard/hooks/abstract",
  ]

  sources = [ "index.cpp" ]
}
