library("pg") {
  deps = [
    # "//yql/essentials/ast",
    # "//yql/essentials/core/issue",
    # "//yql/essentials/core/sql_types",
    # "//yql/essentials/minikql",
    # "//yql/essentials/parser/pg_catalog",
    # "//yql/essentials/parser/pg_wrapper",
    # "//yql/essentials/parser/pg_wrapper/interface",
    # "//yql/essentials/providers/common/provider",
    # "//yql/essentials/sql/settings",
    # "//yql/essentials/utils",
    # "//yql/essentials/utils/log",
  ]

  sources = [
    "optimizer.cpp",
    "pg_sql.cpp",
    "utils.cpp",
  ]
}
