library("lexer") {
  public_deps = [
    # "//yql/essentials/parser/lexer_common",
  ]

  deps = [
    # "//yql/essentials/core/issue:protos",  # peerdir only
    # "//yql/essentials/parser/proto_ast/antlr3",
    # "//yql/essentials/parser/proto_ast/collect_issues",
    "//yql/essentials/parser/proto_ast/gen/v0",
    "//yql/essentials/public/issue",
  ]

  sources = [ "lexer/lexer.cpp" ]
}

library("v0") {
  deps = [
    ":lexer",
    "//contrib/libs/protobuf",
    "//library/cpp/charset:lite",
    # "//library/cpp/containers/stack_vector",
    # "//library/cpp/enumbitset",
    # "//yql/essentials/ast",
    "//yql/essentials/core/issue",  # peerdir only
    # "//yql/essentials/core/issue:protos",
    "//yql/essentials/core/sql_types",
    "//yql/essentials/minikql",
    # "//yql/essentials/parser/proto_ast",
    # "//yql/essentials/parser/proto_ast/collect_issues",
    "//yql/essentials/parser/proto_ast/gen/v0",
    # "//yql/essentials/parser/proto_ast/gen/v0_proto_split",
    # "//yql/essentials/providers/common/provider",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/public/udf",
    "//yql/essentials/sql",
    # "//yql/essentials/sql/settings",
    # "//yql/essentials/utils",
  ]

  sources = [
    "aggregation.cpp",
    "builtin.cpp",
    "context.cpp",
    "insert.cpp",
    "join.cpp",
    "list_builtin.cpp",
    "node.cpp",
    "query.cpp",
    "select.cpp",
    "sql.cpp",
  ]

  serialize_enum_headers = [ "node.h" ]
}
