library("arrow") {
    deps = [
        "//contrib/libs/apache/arrow",
        "//yql/essentials/public/udf",
    ]

    sources = [
        "args_dechunker.cpp",
        "bit_util.cpp",
        "block_builder.cpp",
        "block_item_comparator.cpp",
        "block_item_hasher.cpp",
        "block_item.cpp",
        "block_reader.cpp",
        "block_type_helper.cpp",
        "memory_pool.cpp",
        "udf_arrow_helpers.cpp",
        "util.cpp",
    ]
}
