library("overload_manager") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/tx/columnshard",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/kqp/query_data",
    # "//ydb/library/signals",
  ]

  sources = [
    "overload_manager_actor.cpp",
    "overload_manager_service.cpp",
    "overload_subscribers.cpp",
  ]
}
