config("public_config") {
    include_dirs = [ "include" ]
}

contrib_library("numeric_conversion") {
    public_deps = [
        "//contrib/restricted/boost/conversion",
        "//contrib/restricted/boost/mpl",
        "//contrib/restricted/boost/throw_exception",
    ]

    public_configs = [ ":public_config" ]
}
