# yamake2gn: keep  -- hand-written, do not regenerate

library("tasks") {
  public_deps = [
    "//ydb/core/tx/columnshard/blobs_action:abstract",
    "//ydb/core/tx/columnshard/common",
    "//ydb/core/tx/columnshard/data_sharing/common/session",
    "//ydb/core/tx/columnshard/data_sharing/initiator/controller",
    "//ydb/core/tx/columnshard/data_sharing/protos",
    "//ydb/library/conclusion",
  ]

  deps = [
    "//ydb/core/tx/columnshard/data_sharing/manager:shared_blobs",
  ]

  sources = [ "modification.cpp" ]
}
