library("persqueue_public") {
  public_deps = [
    "//ydb/public/sdk/cpp/src/client/topic",
    # "//ydb/public/sdk/cpp/src/client/common_client",
    # "//ydb/public/sdk/cpp/src/client/driver",
  ]

  deps = [
    # "//library/cpp/logger",
    # "//ydb/public/api/grpc:draft",
    # "//ydb/public/sdk/cpp/src/client/types",
  ]

  serialize_enum_headers = [
    "include/control_plane.h",
    "include/read_events.h",
    "include/write_events.h",
    "include/write_session.h",
  ]
}
