library("format") {
  public_deps = [
    # "//yql/essentials/public/issue",
    # "//yql/essentials/sql/v1/lexer",
    # "//yql/essentials/sql/v1/proto_parser",
    # "//yql/essentials/sql:settings",
  ]

  deps = [
    # "//library/cpp/protobuf/util",
    # "//library/cpp/resource",
    # "//yql/essentials/core/sql_types",
    # "//yql/essentials/parser/lexer_common",
  ]

  sources = [ "sql_format.cpp" ]
}
