library("helpers") {
  public_deps = [
    "//ydb/core/kqp/provider",
    "//ydb/core/protos",
  ]

  deps = [
    "//ydb/core/kqp/common",
    "//ydb/library/yql/dq/opt",
    "//yql/essentials/utils/log",
  ]

  sources = [ "kqp_opt.cpp" ]
}

library("opt") {
  public_deps = [
    ":helpers",
    "//ydb/core/kqp/gateway:actors",
    "//ydb/core/kqp/provider",
    "//ydb/core/protos",
    # "//library/cpp/json:writer",
    "//ydb/core/kqp/common",
    # "//ydb/core/kqp/expr_nodes",
    # "//ydb/core/kqp/opt/logical",
    # "//ydb/core/statistics:service",
    # "//ydb/core/statistics",
    # "//ydb/library/yql/dq/opt",
    # "//yql/essentials/ast",
    # "//yql/essentials/core",
    # "//yql/essentials/core/cbo",
    # "//yql/essentials/utils/log",
  ]

  deps = [
    # "//library/cpp/containers/absl_flat_hash",
    # "//library/cpp/json",
    # "//library/cpp/protobuf/json",
    # "//ydb/core/base",
    # "//ydb/core/kqp/gateway",
    "//ydb/core/kqp/opt/peephole",
    "//ydb/core/kqp/opt/physical",
    # "//ydb/library/formats/arrow:protos",
    # "//ydb/library/yql/dq/actors:protos",
    # "//ydb/library/yql/dq/common",
    # "//ydb/library/yql/dq/tasks",
    # "//ydb/library/yql/dq/type_ann",
    # "//ydb/library/yql/providers/dq/common",
    # "//ydb/library/yql/providers/dq/expr_nodes",
    # "//ydb/library/yql/providers/s3/expr_nodes",
    # "//ydb/library/yql/providers/s3/statistics",
    # "//ydb/library/yql/utils/plan",
    # "//ydb/public/lib/value",
    # "//ydb/public/lib/ydb_cli/common",
    # "//yql/essentials/core/dq_integration",
    # "//yql/essentials/core/expr_nodes",
    "//yql/essentials/core/services",
    # "//yql/essentials/core/type_ann",
    # "//yql/essentials/providers/common/provider",
    # "//yql/essentials/utils",
  ]

  sources = [
    "kqp_column_statistics_requester.cpp",
    "kqp_column_statistics_utils.cpp",
    "kqp_constant_folding_transformer.cpp",
    "kqp_opt_build_phy_query.cpp",
    "kqp_opt_build_txs.cpp",
    "kqp_opt_effects.cpp",
    "kqp_opt_hash_func_propagate_transformer.cpp",
    "kqp_opt_kql.cpp",
    "kqp_opt_phase.cpp",
    "kqp_opt_phy_check.cpp",
    "kqp_opt_phy_finalize.cpp",
    "kqp_opt_sink_precompute.cpp",
    "kqp_query_blocks_transformer.cpp",
    "kqp_query_plan.cpp",
    "kqp_statistics_transformer.cpp",
    "kqp_type_ann.cpp",
  ]

  serialize_enum_headers = [ "kqp_query_plan.h" ]
}
