library("actors") {
  public_deps = [
    # "//library/cpp/monlib/metrics",
    # "//library/cpp/random_provider",
    # "//library/cpp/time_provider",
    # "//ydb/core/fq/libs/compute/common",
    # "//ydb/core/fq/libs/config:protos",
    # "//ydb/core/fq/libs/events",
    # "//ydb/core/fq/libs/private_client",
    # "//ydb/core/fq/libs/shared_resources",
    # "//ydb/core/fq/libs/signer",
    # "//ydb/core/mon",
    # "//ydb/library/actors/core",
    # "//ydb/library/yql/providers/common/http_gateway",
    # "//ydb/library/yql/providers/dq/actors",
    # "//ydb/library/yql/providers/dq/provider",
    # "//ydb/library/yql/providers/dq/worker_manager:interface",
    # "//ydb/library/yql/providers/pq/cm_client",
    # "//ydb/library/yql/providers/pq/gateway/abstract",
    # "//ydb/library/yql/providers/s3/actors_factory",
    # "//ydb/public/api/protos",
    # "//ydb/public/lib/fq",
    # "//yql/essentials/minikql/computation",
    # "//yql/essentials/providers/common/metrics",
    # "//yql/essentials/providers/common/proto",
  ]

  deps = [
    # "//library/cpp/json:yson",
    # "//library/cpp/protobuf/interop",
    # "//library/cpp/protobuf/util",
    # "//library/cpp/retry",
    # "//library/cpp/scheme",
    # "//library/cpp/string_utils/quote",
    # "//library/cpp/yson:node",
    # "//ydb/core/fq/libs/checkpoint_storage",
    # "//ydb/core/fq/libs/checkpointing",
    # "//ydb/core/fq/libs/checkpointing_common",
    # "//ydb/core/fq/libs/common",
    # "//ydb/core/fq/libs/compute/ydb",
    # "//ydb/core/fq/libs/config",
    # "//ydb/core/fq/libs/control_plane_config",
    # "//ydb/core/fq/libs/control_plane_storage",
    # "//ydb/core/fq/libs/control_plane_storage:events",
    # "//ydb/core/fq/libs/db_id_async_resolver_impl",
    # "//ydb/core/fq/libs/gateway",
    # "//ydb/core/fq/libs/metrics",
    # "//ydb/core/fq/libs/rate_limiter/utils",
    # "//ydb/core/fq/libs/read_rule",
    # "//ydb/core/fq/libs/result_formatter",
    # "//ydb/core/fq/libs/tasks_packer",
    # "//ydb/core/kqp/federated_query",
    # "//ydb/core/kqp/proxy_service:script_executions_utils",
    # "//ydb/library/actors/http",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/mkql_proto",
    # "//ydb/library/security",
    # "//ydb/library/services",
    # "//ydb/library/yql/dq/actors",
    # "//ydb/library/yql/dq/actors:compute",
    # "//ydb/library/yql/dq/actors:protos",
    # "//ydb/library/yql/dq/common",
    # "//ydb/library/yql/providers/dq/common",
    # "//ydb/library/yql/providers/dq/counters",
    # "//ydb/library/yql/providers/dq/provider:exec",
    # "//ydb/library/yql/providers/generic/connector/libcpp",
    # "//ydb/library/yql/providers/generic/provider",
    # "//ydb/library/yql/providers/pq/proto",
    # "//ydb/library/yql/providers/pq/provider",
    # "//ydb/library/yql/providers/pq/task_meta",
    # "//ydb/library/yql/providers/s3/proto",
    # "//ydb/library/yql/providers/s3/provider",
    # "//ydb/library/yql/providers/solomon/gateway",
    # "//ydb/library/yql/providers/solomon/provider",
    # "//ydb/library/yql/providers/ydb/provider",
    # "//ydb/library/yql/utils/actor_log",
    # "//ydb/public/sdk/cpp/src/client/driver",
    # "//ydb/public/sdk/cpp/src/client/result",
    # "//ydb/public/sdk/cpp/src/client/table",
    # "//ydb/public/sdk/cpp/src/client/value",
    # "//yql/essentials/ast",
    # "//yql/essentials/core/dq_integration:transform",
    # "//yql/essentials/core/facade",
    # "//yql/essentials/core/services",
    # "//yql/essentials/core/services:mounts",
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/comp_nodes",
    # "//yql/essentials/providers/common/codec",
    # "//yql/essentials/providers/common/comp_nodes",
    # "//yql/essentials/providers/common/provider",
    # "//yql/essentials/providers/common/schema/mkql",
    # "//yql/essentials/providers/common/udf_resolve",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/public/issue:protos",
    # "//yql/essentials/sql:settings",
    # "//yql/essentials/utils",
  ]

  sources = [
    "clusters_from_connections.cpp",
    "error.cpp",
    "nodes_health_check.cpp",
    "nodes_manager.cpp",
    "pending_fetcher.cpp",
    "proxy_private.cpp",
    "rate_limiter.cpp",
    "rate_limiter_resources.cpp",
    "result_writer.cpp",
    "run_actor.cpp",
    "table_bindings_from_bindings.cpp",
    "task_get.cpp",
    "task_ping.cpp",
    "task_result_write.cpp",
  ]
}

group("logging") {
  public_deps = [
    "//ydb/library/actors/core",
    "//ydb/library/services",
  ]
}
