library("service") {
  public_deps = [
    # "//ydb/services/ext_index/common",
    # "//ydb/services/ext_index/metadata",
    # "//ydb/services/metadata",
    # "//ydb/services/metadata/ds_table",
    # "//ydb/services/metadata/initializer",
  ]

  deps = [
    # "//contrib/libs/apache/arrow",
    # "//ydb/core/formats/arrow",
    # "//ydb/core/scheme",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/public/api/protos",
    # "//ydb/services/metadata/manager",
    # "//ydb/services/metadata/request",
  ]

  sources = [
    "activation.cpp",
    "add_data.cpp",
    "add_index.cpp",
    "deleting.cpp",
    "executor.cpp",
  ]
}
