library("script_executions_utils") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/public/api/protos",
    "//yql/essentials/public/issue",
  ]

  deps = [
    # "//contrib/libs/protobuf",
    "//library/cpp/blockcodecs",
    "//library/cpp/protobuf/interop",
    # "//ydb/core/tx/datashard",
    # "//ydb/library/yverify_stream",
  ]

  sources = [
    "kqp_script_execution_compression.cpp",
    "kqp_script_execution_retries.cpp",
  ]
}
