library("audit") {
    public_deps = [
        "//ydb/library/actors/http",
    ]

    deps = [
        "//library/cpp/cgiparam",
        "//ydb/core/audit",
        "//ydb/core/audit:config",
        "//ydb/core/base",
        "//ydb/core/util",
    ]

    sources = [
        "audit/audit_denylist.cpp",
        "audit/audit.cpp",
        "audit/url_matcher.cpp",
    ]
}

library("mon") {
    deps = [
        ":audit",
        "//library/cpp/json",
        "//ydb/core/base",
        "//ydb/library/aclib",
        "//ydb/public/sdk/cpp/src/client/types:status",
    ]

    sources = [
        "crossref.cpp",
        "mon.cpp",
    ]
}
