library("job") {
  public_deps = [
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/computation",
    # "//yql/essentials/providers/common/codec",
    # "//yql/essentials/public/langver",
    # "//yql/essentials/public/udf",
    # "//yt/cpp/mapreduce/interface",
    "//yt/cpp/mapreduce/io",
    "//yt/yql/providers/yt/codec",
  ]

  deps = [
    "//library/cpp/random_provider",
    "//library/cpp/streams/brotli",
    "//library/cpp/time_provider",
    # "//library/cpp/yson:node",
    "//yql/essentials/minikql/comp_nodes",
    "//yql/essentials/minikql/invoke_builtins",
    "//yql/essentials/parser/pg_catalog",
    # "//yql/essentials/parser/pg_wrapper/interface",
    "//yql/essentials/providers/common/comp_nodes",
    # "//yql/essentials/providers/common/provider",
    "//yql/essentials/providers/common/schema:mkql",
    "//yql/essentials/providers/common/schema:parser",
    # "//yql/essentials/utils",
    "//yql/essentials/utils/backtrace",
    "//yt/cpp/mapreduce/client",
    # "//yt/cpp/mapreduce/common",
    "//yt/cpp/mapreduce/library/user_job_statistics",
    # "//yt/yql/providers/yt/common",
    "//yt/yql/providers/yt/comp_nodes",
    "//yt/yql/providers/yt/lib/infer_schema",
    "//yt/yql/providers/yt/lib/lambda_builder",
    # "//yt/yql/providers/yt/lib/mkql_helpers",
  ]

  sources = [
    "yql_job_base.cpp",
    "yql_job_calc.cpp",
    "yql_job_factory.cpp",
    "yql_job_infer_schema.cpp",
    "yql_job_stats_writer.cpp",
    "yql_job_user.cpp",
    "yql_job_user_base.cpp",
  ]
}
