library("log_backend") {
  public_deps = [
    # "//library/cpp/logger",
    # "//ydb/core/driver_lib/run",
  ]

  deps = [
    # "//library/cpp/json",
    # "//library/cpp/unified_agent_client",
    # "//ydb/core/base",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  sources = [
    "json_envelope.cpp",
    "log_backend.cpp",
    "log_backend_build.cpp",
  ]
}
