config("public_config") {
    include_dirs = [ "include" ]
}

config("private_config") {
    include_dirs = [ "src" ]
    defines = [
        "POCO_ENABLE_CPP11",
        "POCO_ENABLE_CPP14",
        "POCO_HAVE_FD_EPOLL",
        "POCO_NO_AUTOMATIC_LIBS",
        "POCO_OS_FAMILY_UNIX",
        "POCO_UNBUNDLED",
    ]
}

contrib_library("Crypto") {
    public_deps = [
        "//contrib/libs/openssl",
        "//contrib/libs/poco/Foundation",
    ]

    sources = [
        "src/Cipher.cpp",
        "src/CipherFactory.cpp",
        "src/CipherImpl.cpp",
        "src/CipherKey.cpp",
        "src/CipherKeyImpl.cpp",
        "src/CryptoException.cpp",
        "src/CryptoStream.cpp",
        "src/CryptoTransform.cpp",
        "src/DigestEngine.cpp",
        "src/ECDSADigestEngine.cpp",
        "src/ECKey.cpp",
        "src/ECKeyImpl.cpp",
        "src/EVPPKey.cpp",
        "src/KeyPair.cpp",
        "src/KeyPairImpl.cpp",
        "src/OpenSSLInitializer.cpp",
        "src/PKCS12Container.cpp",
        "src/RSACipherImpl.cpp",
        "src/RSADigestEngine.cpp",
        "src/RSAKey.cpp",
        "src/RSAKeyImpl.cpp",
        "src/X509Certificate.cpp",
    ]

    public_configs = [ ":public_config" ]
    configs = [
        ":private_config",
        "//build/gn/config:no_warnings",
    ]
}
