library("categories_bloom") {
  deps = [
    # "//contrib/libs/apache/arrow",
    # "//library/cpp/deprecated/atomic",
    # "//ydb/core/formats/arrow",
    # "//ydb/core/protos",  # peerdir only
    "//ydb/core/tx/columnshard/engines/portions",
    "//ydb/core/tx/columnshard/engines/protos",
    "//ydb/core/tx/columnshard/engines/scheme/indexes:abstract",
    "//ydb/core/tx/columnshard/engines/storage/indexes/portions",
    # "//ydb/core/tx/columnshard/engines/storage/indexes/portions:extractor",
    "//ydb/core/tx/columnshard/engines/storage/indexes/skip_index",
    # "//ydb/core/tx/program",
    "//ydb/core/tx/schemeshard/olap/schema",
    # "//ydb/library/formats/arrow:hash",
  ]

  sources = [
    "constructor.cpp",
    "header.cpp",
    "meta.cpp",
  ]
}
