library("constructor") {
  public_deps = [
    "//ydb/core/formats/arrow:program",
    # "//ydb/core/formats/arrow:reader",
    # "//ydb/core/tx/columnshard/common",
    "//ydb/core/tx/columnshard/engines/reader/abstract",
    # "//ydb/core/tx/columnshard/engines/reader/common",
    # "//ydb/core/tx/columnshard/engines/scheme",
    # "//ydb/library/formats/arrow",
  ]

  deps = [
    # "//ydb/core/kqp/compute_actor",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/iterator",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator:collections",
    # "//ydb/core/tx/columnshard/transactions:locks",
  ]

  sources = [
    "read_metadata.cpp",
    "resolver.cpp",
  ]
}
