library("infer_schema") {
  public_deps = [
    # "//library/cpp/yson:node",
    # "//yql/essentials/utils/threading",
    "//yt/cpp/mapreduce/interface",
  ]

  deps = [
    # "//library/cpp/yson",
    # "//yql/essentials/core/issue",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/utils",
    # "//yql/essentials/utils/log",
    # "//yt/cpp/mapreduce/common",
    # "//yt/yql/providers/yt/lib/yt_rpc_helpers",
    "//yt/yt/client",
    # "//yt/yt/library/auth",
  ]

  sources = [
    "infer_schema.cpp",
    "infer_schema_rpc.cpp",
  ]
}
