# yamake2gn: keep  -- hand-written, do not regenerate

library("db_key_resolver") {
  public_deps = [
    "//ydb/core/scheme",
    "//ydb/library/actors/core",
    "//library/cpp/threading/future",
  ]

  sources = [ "db_key_resolver.cpp" ]
}

library("minikql_compile") {
  public_deps = [
    ":db_key_resolver",
    # "//library/cpp/threading/future",
    "//ydb/core/client/scheme_cache_lib",
    "//ydb/core/engine",
    # "//ydb/core/scheme",
    "//yql/essentials/ast",
    "//yql/essentials/minikql",
  ]

  deps = [
    "//library/cpp/monlib/dynamic_counters",
    "//library/cpp/random_provider",
    "//ydb/core/base",
    "//ydb/core/kqp/provider",
    "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/scheme_cache",
    "//ydb/library/actors/core",
    # "//ydb/library/services",
    # "//ydb/library/ydb_issue:proto",
    # "//ydb/public/lib/scheme_types",
    # "//yql/essentials/core",
    "//yql/essentials/core/type_ann",
    # "//yql/essentials/minikql/invoke_builtins",
    "//yql/essentials/providers/common/mkql",
  ]

  sources = [
    "compile_context.cpp",
    "compile_result.cpp",
    "mkql_compile_service.cpp",
    "yql_expr_minikql.cpp",
  ]
}
