contrib_library("Support") {
    deps = [
        "//contrib/libs/llvm16/lib/Demangle",
        "//contrib/libs/zlib",
    ]

    sources = [
        "ABIBreak.cpp",
        "AddressRanges.cpp",
        "Allocator.cpp",
        "AMDGPUMetadata.cpp",
        "APFixedPoint.cpp",
        "APFloat.cpp",
        "APInt.cpp",
        "APSInt.cpp",
        "ARMAttributeParser.cpp",
        "ARMBuildAttrs.cpp",
        "ARMWinEH.cpp",
        "Atomic.cpp",
        "AutoConvert.cpp",
        "Base64.cpp",
        "BinaryStreamError.cpp",
        "BinaryStreamReader.cpp",
        "BinaryStreamRef.cpp",
        "BinaryStreamWriter.cpp",
        "BLAKE3/blake3_avx2_x86-64_unix.S",
        "BLAKE3/blake3_avx512_x86-64_unix.S",
        "BLAKE3/blake3_dispatch.c",
        "BLAKE3/blake3_neon.c",
        "BLAKE3/blake3_portable.c",
        "BLAKE3/blake3_sse2_x86-64_unix.S",
        "BLAKE3/blake3_sse41_x86-64_unix.S",
        "BLAKE3/blake3.c",
        "BlockFrequency.cpp",
        "BranchProbability.cpp",
        "BuryPointer.cpp",
        "CachePruning.cpp",
        "Caching.cpp",
        "Chrono.cpp",
        "circular_raw_ostream.cpp",
        "CodeGenCoverage.cpp",
        "COM.cpp",
        "CommandLine.cpp",
        "Compression.cpp",
        "ConvertUTF.cpp",
        "ConvertUTFWrapper.cpp",
        "CrashRecoveryContext.cpp",
        "CRC.cpp",
        "CSKYAttributeParser.cpp",
        "CSKYAttributes.cpp",
        "DAGDeltaAlgorithm.cpp",
        "DataExtractor.cpp",
        "Debug.cpp",
        "DebugCounter.cpp",
        "DeltaAlgorithm.cpp",
        "DivisionByConstantInfo.cpp",
        "DJB.cpp",
        "DynamicLibrary.cpp",
        "ELFAttributeParser.cpp",
        "ELFAttributes.cpp",
        "Errno.cpp",
        "Error.cpp",
        "ErrorHandling.cpp",
        "ExtensibleRTTI.cpp",
        "FileCollector.cpp",
        "FileOutputBuffer.cpp",
        "FileUtilities.cpp",
        "FoldingSet.cpp",
        "FormattedStream.cpp",
        "FormatVariadic.cpp",
        "GlobPattern.cpp",
        "GraphWriter.cpp",
        "Hashing.cpp",
        "InitLLVM.cpp",
        "InstructionCost.cpp",
        "IntEqClasses.cpp",
        "IntervalMap.cpp",
        "ItaniumManglingCanonicalizer.cpp",
        "JSON.cpp",
        "KnownBits.cpp",
        "LEB128.cpp",
        "LineIterator.cpp",
        "Locale.cpp",
        "LockFileManager.cpp",
        "LowLevelType.cpp",
        "ManagedStatic.cpp",
        "MathExtras.cpp",
        "MD5.cpp",
        "MemAlloc.cpp",
        "Memory.cpp",
        "MemoryBuffer.cpp",
        "MemoryBufferRef.cpp",
        "MSP430AttributeParser.cpp",
        "MSP430Attributes.cpp",
        "NativeFormatting.cpp",
        "OptimizedStructLayout.cpp",
        "Optional.cpp",
        "Parallel.cpp",
        "Path.cpp",
        "PluginLoader.cpp",
        "PrettyStackTrace.cpp",
        "Process.cpp",
        "Program.cpp",
        "RandomNumberGenerator.cpp",
        "raw_os_ostream.cpp",
        "raw_ostream.cpp",
        "regcomp.c",
        "regerror.c",
        "Regex.cpp",
        "regexec.c",
        "regfree.c",
        "regstrlcpy.c",
        "RISCVAttributeParser.cpp",
        "RISCVAttributes.cpp",
        "RISCVISAInfo.cpp",
        "RWMutex.cpp",
        "ScaledNumber.cpp",
        "ScopedPrinter.cpp",
        "SHA1.cpp",
        "SHA256.cpp",
        "Signals.cpp",
        "Signposts.cpp",
        "SmallPtrSet.cpp",
        "SmallVector.cpp",
        "SourceMgr.cpp",
        "SpecialCaseList.cpp",
        "Statistic.cpp",
        "StringExtras.cpp",
        "StringMap.cpp",
        "StringRef.cpp",
        "StringSaver.cpp",
        "SuffixTree.cpp",
        "SymbolRemappingReader.cpp",
        "SystemUtils.cpp",
        "TarWriter.cpp",
        "Threading.cpp",
        "ThreadPool.cpp",
        "TimeProfiler.cpp",
        "Timer.cpp",
        "ToolOutputFile.cpp",
        "TrigramIndex.cpp",
        "Twine.cpp",
        "TypeSize.cpp",
        "Unicode.cpp",
        "UnicodeCaseFold.cpp",
        "UnicodeNameToCodepoint.cpp",
        "UnicodeNameToCodepointGenerated.cpp",
        "Valgrind.cpp",
        "VersionTuple.cpp",
        "VirtualFileSystem.cpp",
        "Watchdog.cpp",
        "WithColor.cpp",
        "xxhash.cpp",
        "YAMLParser.cpp",
        "YAMLTraits.cpp",
        "Z3Solver.cpp",
    ]

    configs = [
        "//contrib/libs/llvm16:public_config",
        "//contrib/libs/llvm16:private_config",
    ]
}
