unittest_executable("ut_vacuum") {
  deps = [
    "//ydb/core/testlib",
    "//ydb/core/testlib/default",  # peerdir only
    "//ydb/core/tx/datashard",  # peerdir only
    "//ydb/core/tx/datashard/ut_common",
  ]

  sources = [ "//ydb/core/tx/datashard/datashard_ut_vacuum.cpp" ]

  include_dirs = [
    "//ydb/core/tx/datashard",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
