# yamake2gn: keep  -- hand-written, do not regenerate

library("diagnostics") {
  public_deps = [ "//ydb/library/actors/core" ]

  deps = [
    "//contrib/libs/fmt",
    "//library/cpp/monlib/service/pages",
    "//ydb/core/mon",
    "//ydb/core/protos",
    "//ydb/core/tx/columnshard/blobs_action:abstract",
    "//ydb/core/tx/columnshard/counters",
    "//ydb/core/tx/columnshard/engines",
  ]

  sources = [ "scan_diagnostics_actor.cpp" ]
}
