unittest_executable("storage") {
  deps = [
    "//contrib/libs/fmt",
    "//ydb/core/kqp",  # peerdir only
    "//ydb/core/kqp/ut/common",
    "//ydb/core/kqp/ut/olap/combinatory",  # peerdir only
    "//ydb/core/kqp/ut/olap/helpers",
    "//ydb/core/testlib",  # peerdir only
    "//ydb/core/tx/columnshard",  # peerdir only
    "//ydb/core/tx/columnshard/data_locks/locks",
    "//ydb/core/tx/columnshard/engines/changes/abstract",
    "//ydb/core/tx/columnshard/engines/scheme/abstract",
    "//ydb/core/tx/columnshard/hooks/testing",
    "//ydb/core/tx/columnshard/test_helper",
    "//ydb/core/wrappers",
    "//yql/essentials/sql/pg_dummy",  # peerdir only
  ]

  sources = [
    "compaction_ut.cpp",
    "compression_ut.cpp",
  ]

  include_dirs = [
    "//ydb/core/kqp",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
