library("barriers") {
  public_deps = [
    # ":base",
    # ":base_types",
    # ":fresh",
    ":generic",
    # ":hulldb",
    # "//ydb/core/blobstorage/vdisk",
    # "//ydb/core/blobstorage/vdisk/ingress",
    # "//ydb/library/actors/util",
  ]

  deps = [
    # "//ydb/core/blobstorage/base",  # peerdir only
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [
    "barriers/barriers_chain.cpp",
    "barriers/barriers_essence.cpp",
    "barriers/barriers_public.cpp",
    "barriers/barriers_tree.cpp",
  ]
}

library("base") {
  public_deps = [
    # ":fresh",
    # ":generic",
    # "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/blobstorage/vdisk",
    "//ydb/core/blobstorage/vdisk/common",
    "//ydb/core/blobstorage/vdisk/ingress",
    # "//ydb/core/blobstorage/vdisk/protos",
    # "//ydb/core/protos",
    # "//ydb/library/actors/util",
  ]

  deps = [
    ":base_types",
    # "//library/cpp/monlib/service/pages",
    "//ydb/core/base",
  ]

  sources = [
    "base/blobstorage_hulldefs.cpp",
    "base/blobstorage_hullsatisfactionrank.cpp",
  ]
}

library("base_types") {
  public_deps = [
    # ":base",
    "//ydb/core/base",
    # "//ydb/core/blobstorage/groupinfo",
    # "//ydb/core/blobstorage/vdisk/common",
    "//ydb/core/blobstorage/vdisk/ingress",
    # "//ydb/core/protos",
    # "//ydb/library/actors/util",
  ]

  deps = [
    # "//contrib/libs/xxhash",
  ]

  sources = [
    "base/blobstorage_blob.cpp",
    "base/hullbase_barrier.cpp",
  ]
}

library("bulksst_add") {
  public_deps = [
    ":generic",
    # ":hulldb",
  ]

  deps = [
    # "//ydb/core/blobstorage/vdisk/common",  # peerdir only
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [ "bulksst_add/hulldb_bulksst_add.cpp" ]
}

library("cache_block") {
  public_deps = [ ":hulldb" ]

  deps = [
    # ":base",
    # "//ydb/core/blobstorage/vdisk/protos",  # peerdir only
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [ "cache_block/cache_block.cpp" ]
}

library("compstrat") {
  public_deps = [
    ":generic",
    # ":hulldb",
    # "//ydb/core/blobstorage/vdisk",
  ]

  deps = [
    # ":base",  # peerdir only
    "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [
    "compstrat/hulldb_compstrat_defs.cpp",
    "compstrat/hulldb_compstrat_selector.cpp",
  ]
}

library("fresh") {
  public_deps = [
    ":base",
    ":base_types",
    # ":generic",
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/threading/skip_list",
    "//ydb/core/base",
    # "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/vdisk",
    "//ydb/core/blobstorage/vdisk/protos",
  ]

  deps = [
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [
    "fresh/fresh_appendix.cpp",
    "fresh/fresh_data.cpp",
    "fresh/fresh_datasnap.cpp",
    "fresh/fresh_segment.cpp",
  ]
}

library("generic") {
  public_deps = [
    # ":base",
    # ":base_types",
    # ":bulksst_add",
    ":fresh",
    # "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/blobstorage/vdisk",
    # "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/blobstorage/vdisk/huge",
    # "//ydb/core/blobstorage/vdisk/hullop:hullcompdelete",
    # "//ydb/core/blobstorage/vdisk/protos",
    # "//ydb/core/util",
  ]

  deps = [
    # "//library/cpp/monlib/service/pages",
    # "//ydb/core/blobstorage/vdisk/hullop",
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [
    "generic/blobstorage_hulloptlsn.cpp",
    "generic/hulldb_bulksstmngr.cpp",
    "generic/hullds_idx.cpp",
    "generic/hullds_idxsnap.cpp",
    "generic/hullds_sst.cpp",
    "generic/hullds_sstslice.cpp",
    "generic/hullds_sstvec.cpp",
  ]
}

group("hulldb") {
  public_deps = [
    ":barriers",
    ":base",
    ":generic",
    # "//ydb/core/blobstorage/vdisk",
  ]

  deps = [
    # ":bulksst_add",  # peerdir only
    # ":compstrat",  # peerdir only
    # ":fresh",  # peerdir only
    # ":recovery",  # peerdir only
    # "//ydb/core/blobstorage/base",  # peerdir only
    # "//ydb/core/blobstorage/vdisk/common",  # peerdir only
    # "//ydb/core/protos",  # peerdir only
  ]
}

library("recovery") {
  public_deps = [
    ":barriers",
    ":bulksst_add",
    ":cache_block",
    # ":hulldb",
    # "//ydb/core/blobstorage/vdisk/protos",
  ]

  deps = [
    # "//contrib/libs/protobuf",
    # "//ydb/core/blobstorage/base",  # peerdir only
    # "//ydb/core/blobstorage/vdisk/common",  # peerdir only
    # "//ydb/core/protos",  # peerdir only
  ]

  sources = [ "recovery/hulldb_recovery.cpp" ]
}
