library("common_client") {
  public_deps = [
    # "//ydb/public/sdk/cpp/src/client/types",
    # "//ydb/public/sdk/cpp/src/client/types/credentials",
  ]

  deps = [
    # "//ydb/public/sdk/cpp/src/client/impl/internal/common",
  ]

  sources = [ "settings.cpp" ]
}

library("impl") {
  public_deps = [
    # "//ydb/public/sdk/cpp/src/client/common_client",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/grpc_connections",
    # "//ydb/public/sdk/cpp/src/client/types/exceptions",
    # "//ydb/public/sdk/cpp/src/library/time",
  ]

  sources = [ "impl/client.cpp" ]
}
