library("basics") {
  testonly = true

  public_deps = [
    # "//contrib/libs/protobuf",
    "//ydb/core/audit",
    "//ydb/core/base",
    # "//ydb/core/blobstorage/crypto",
    "//ydb/core/blobstorage/dsproxy:mock",
    "//ydb/core/blobstorage/nodewarden",
    "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/formats",
    # "//ydb/core/protos",
    # "//ydb/core/scheme",
    "//ydb/core/tablet_flat",
    "//ydb/core/testlib/actors",
    # "//ydb/core/tx/datashard",
    "//ydb/core/tx/schemeshard",
    # "//ydb/core/util",
    # "//ydb/library/actors/interconnect",
  ]

  deps = [
    # "//library/cpp/regex/pcre",  # peerdir only
    # "//library/cpp/testing/unittest",  # peerdir only
    # "//ydb/core/blobstorage",  # peerdir only
    "//ydb/core/client:server",
    "//ydb/core/cms/console",
    "//ydb/core/control",
    "//ydb/core/mind",
    # "//ydb/core/node_whiteboard",
    "//ydb/core/quoter",
    "//ydb/core/quoter:public",
    "//ydb/core/statistics:service",  # peerdir only
    "//ydb/core/statistics:service_id",
    "//ydb/core/sys_view:service",
    # "//ydb/core/tablet",
    # "//ydb/core/tx",
    "//ydb/core/tx/columnshard",
    "//ydb/core/tx/columnshard/column_fetching",
    "//ydb/core/tx/columnshard/data_accessor:cache_policy",
    "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/scheme_cache",
    "//ydb/library/actors/dnsresolver",
    # "//ydb/library/actors/interconnect:rdma",
    "//ydb/library/keys",  # peerdir only
    # "//ydb/library/pdisk_io",
    # "//ydb/services/kesus",  # peerdir only
    # "//ydb/services/persqueue_cluster_discovery",  # peerdir only
    # "//ydb/services/ydb",  # peerdir only
    "//yql/essentials/minikql",
    "//yql/essentials/minikql/invoke_builtins",
    # "//yql/essentials/minikql/invoke_builtins/llvm16",  # peerdir only
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
    # "//yt/yql/providers/yt/comp_nodes/dq/llvm16",  # peerdir only
    # "//yt/yql/providers/yt/comp_nodes/llvm16",  # peerdir only
  ]

  sources = [
    "appdata.cpp",
    "helpers.cpp",
    "runtime.cpp",
    "services.cpp",
  ]
}

group("pg") {
  testonly = true

  deps = [
    # ":basics",  # peerdir only
    # "//yql/essentials/parser/pg_wrapper",  # peerdir only
    # "//yql/essentials/sql/pg",  # peerdir only
  ]
}
