unittest_executable("ut") {
  deps = [
    "//library/cpp/testing/gmock_in_unittest",
    "//library/cpp/testing/unittest",
    "//ydb/core/client/minikql_compile",
    "//ydb/core/kqp/gateway",
    "//ydb/core/kqp/gateway/actors",
    "//ydb/core/kqp/gateway:interface",
    "//ydb/core/kqp/provider",
    "//ydb/core/kqp/ut/common",
    "//ydb/core/resource_pools",
    "//yql/essentials/ast",
    "//yql/essentials/sql/pg_dummy",  # peerdir only
    "//yql/essentials/sql/v1",
  ]

  sources = [
    "//ydb/core/kqp/provider/read_attributes_utils_ut.cpp",
    "//ydb/core/kqp/provider/yql_kikimr_gateway_ut.cpp",
    "//ydb/core/kqp/provider/yql_kikimr_provider_ut.cpp",
  ]

  include_dirs = [ "//ydb/core/kqp/provider" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
    "yt_codegen=llvm16",
  ]
}
