# yamake2gn: keep  -- hand-written, do not regenerate

config("private_config") {
  cflags = [ "-Wno-deprecated-enum-enum-conversion" ]
}

library("common") {
  public_deps = [
    # "//ydb/public/sdk/cpp/src/client/types",
  ]

  deps = [
    "//library/cpp/cgiparam",
    "//library/cpp/uri",
    "//ydb/public/sdk/cpp/src/client/types/exceptions",
  ]

  sources = [
    "balancing_policies.cpp",
    "client_pid.cpp",
    "getenv.cpp",
    "parser.cpp",
  ]

  configs = [ ":private_config" ]
}
