slot_interface_group("dq") {
  public_deps = [
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/computation",
  ]

  link_slot_interface = "yt_codegen"

  link_slot_headers = [ "dq_yt_factory.h" ]

  link_slot_flags_from = [ "dq_yt_factory.cpp" ]

  link_slot_codegen = [
    "//yql/essentials/public/issue/protos",
    "//yql/essentials/public/types",
  ]
}
