slot_interface_group("comp_nodes") {
  public_deps = [
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/computation",
    # "//yql/essentials/providers/common/codec",
    # "//yql/essentials/public/udf",
    # "//yt/cpp/mapreduce/interface",
    # "//yt/yql/providers/yt/codec",
  ]

  link_slot_interface = "yt_codegen"

  link_slot_headers = [
    "yql_mkql_block_table_content.h",
    "yql_mkql_input.h",
    "yql_mkql_output.h",
    "yql_mkql_table_content.h",
  ]

  link_slot_flags_from = [ "yql_mkql_block_table_content.cpp" ]
}

slot_interface_group("dq") {
  public_deps = [
    # "//yql/essentials/minikql",
    # "//yql/essentials/minikql/computation",
  ]

  link_slot_interface = "yt_codegen"

  link_slot_headers = [ "dq/dq_yt_factory.h" ]

  link_slot_flags_from = [ "dq/dq_yt_factory.cpp" ]
}
