library("common") {
  testonly = true

  public_deps = [
    # "//library/cpp/testing/unittest",
    # "//ydb/core/persqueue/events",
    "//ydb/core/persqueue/public/describer",
    "//ydb/core/persqueue/public/mlp",
    # "//ydb/core/testlib",
    # "//ydb/public/sdk/cpp/src/client/query",
    "//ydb/public/sdk/cpp/src/client/topic/ut/ut_utils:test_setup",
  ]

  deps = [
    # "//ydb/public/sdk/cpp/src/client/persqueue_public/ut/ut_utils",  # peerdir only
    "//ydb/public/sdk/cpp/src/client/topic/ut/ut_utils",  # peerdir only
  ]

  sources = [ "common.cpp" ]
}
