unittest_executable("ut_replication") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/protos",
    "//ydb/core/testlib/pg",  # peerdir only
    "//ydb/core/tx/replication/controller",
  ]

  sources = [ "//ydb/core/tx/replication/controller/replication_ut.cpp" ]

  include_dirs = [ "//ydb/core/tx/replication/controller" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_wrapper",
    "yql_pg_sql_translator=pg",
    "yt_codegen=llvm16",
  ]
}
