# yamake2gn: keep  -- hand-written, do not regenerate

config("private_config") {
  cflags = [ "-Wno-implicit-const-int-float-conversion" ]
}

library("sharding") {
  public_deps = [
    "//ydb/core/formats/arrow",
    # "//ydb/core/scheme_types",
    "//ydb/core/tx/columnshard/common",
    # "//ydb/library/accessor",
    "//ydb/library/formats/arrow:hash",
    # "//ydb/library/formats/arrow:validation",
    # "//ydb/services/bg_tasks/abstract",
    "//yql/essentials/public/udf",
  ]

  deps = [
    # "//ydb/core/formats/arrow/hash",
    "//ydb/core/protos",
    # "//ydb/core/tx/columnshard/common:protos",
    "//yql/essentials/minikql",
    # "//yql/essentials/utils",
  ]

  sources = [
    "hash.cpp",
    "hash_intervals.cpp",
    "hash_modulo.cpp",
    "hash_slider.cpp",
    "random.cpp",
    "sharding.cpp",
    "unboxed_reader.cpp",
  ]

  configs = [ ":private_config" ]
}
