unittest_executable("pg") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/kqp",  # peerdir only
    "//ydb/core/kqp/common/events",
    "//ydb/core/kqp/common/simple",
    "//ydb/core/kqp/executer_actor",
    "//ydb/core/kqp/ut/common",
    "//ydb/public/lib/ut_helpers",
    "//ydb/public/sdk/cpp/src/client/proto",
    "//yql/essentials/parser/pg_catalog",
    "//yql/essentials/parser/pg_wrapper",  # peerdir only
    "//yql/essentials/parser/pg_wrapper/interface",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
    "//yql/essentials/sql/pg",  # peerdir only
    "//yql/essentials/utils/log",
  ]

  sources = [
    "kqp_pg_ut.cpp",
    "pg_catalog_ut.cpp",
  ]

  include_dirs = [
    "//ydb/core/kqp",  # peerdir only
  ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_wrapper",
    "yql_pg_sql_translator=pg",
    "yt_codegen=llvm16",
  ]
}
