library("abstract") {
    public_deps = [
        "//ydb/library/actors/core",
    ]

    deps = [
        ":protos",
        "//library/cpp/string_utils/base64",
        "//ydb/core/base",
    ]

    sources = [
        "abstract/interface.cpp",
    ]
}

protobuf_library("protos") {
    sources = [
        "protos/container.proto",
    ]
}
