library("minikql") {
  public_deps = [
    # "//ydb/core/engine",
    "//ydb/core/scheme",
    # "//ydb/core/tablet",
    "//ydb/core/tablet_flat",
    # "//yql/essentials/minikql",
  ]

  deps = [
    # "//library/cpp/containers/stack_vector",
    "//ydb/core/base",
    "//ydb/core/client/minikql_compile",
    # "//ydb/core/formats",
    "//ydb/core/protos",
    # "//ydb/core/tx/locks",
    "//ydb/library/ydb_issue/proto",
    "//ydb/library/yql/public/ydb_issue",
    "//ydb/public/api/protos",
    "//yql/essentials/minikql/computation",
    # "//yql/essentials/parser/pg_wrapper/interface",
  ]

  sources = [
    "flat_local_tx_factory.cpp",
    "minikql_engine_host.cpp",
  ]
}
