library("actor") {
  public_deps = [
    # "//library/cpp/logger",
    # "//library/cpp/monlib/dynamic_counters",
    # "//ydb/core/base",
    # "//ydb/core/http_proxy",
    # "//ydb/core/protos",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/core/ymq/actor/cfg",
    # "//ydb/core/ymq/base",
    # "//ydb/core/ymq/proto",
    # "//ydb/library/folder_service",
    # "//ydb/library/folder_service:proto",
    # "//ydb/library/http_proxy/authorization",
    # "//ydb/library/http_proxy/error",
    # "//ydb/library/ycloud/api",
    # "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/client/types/credentials",
    # "//ydb/public/sdk/cpp/src/library/grpc/client",
  ]

  deps = [
    # "//contrib/libs/openssl",
    # "//library/cpp/containers/intrusive_rb_tree",
    # "//library/cpp/digest/md5",
    # "//library/cpp/json",
    # "//library/cpp/logger:global",
    # "//library/cpp/lwtrace/mon",
    # "//library/cpp/monlib/metrics",
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/scheme",
    # "//library/cpp/string_utils/base64",
    # "//ydb/core/audit",
    # "//ydb/core/client/minikql_compile",
    # "//ydb/core/engine",
    # "//ydb/core/kesus/tablet",
    # "//ydb/core/kqp/common",
    # "//ydb/core/mind:address_classification",
    # "//ydb/core/mon",
    # "//ydb/core/node_whiteboard",
    # "//ydb/core/protos/schemeshard",
    # "//ydb/core/quoter:public",
    # "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/core/util",
    # "//ydb/core/ymq/actor/cloud_events",
    # "//ydb/core/ymq/attributes",
    # "//ydb/core/ymq/error",
    # "//ydb/core/ymq/queues/common",
    # "//ydb/core/ymq/queues/fifo",
    # "//ydb/core/ymq/queues/std",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    # "//ydb/library/mkql_proto:protos",
    # "//ydb/library/security",
    # "//ydb/library/services",
    # "//ydb/library/ycloud/impl",
    # "//ydb/library/yverify_stream",
    # "//ydb/public/lib/deprecated/kicli",
    # "//ydb/public/lib/value",
    # "//ydb/public/sdk/cpp/src/client/iam",
    # "//ydb/public/sdk/cpp/src/client/params",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/public/sdk/cpp/src/client/table",
    # "//ydb/public/sdk/cpp/src/client/types",
    # "//yql/essentials/minikql",
    # "//yql/essentials/public/issue",
  ]

  sources = [
    "actor.cpp",
    "auth_factory.cpp",
    "auth_mocks.cpp",
    "auth_multi_factory.cpp",
    "change_visibility.cpp",
    "cleanup_queue_data.cpp",
    "count_queues.cpp",
    "create_queue.cpp",
    "create_user.cpp",
    "delete_message.cpp",
    "delete_queue.cpp",
    "delete_user.cpp",
    "error.cpp",
    "executor.cpp",
    "fifo_cleanup.cpp",
    "garbage_collector.cpp",
    "get_queue_attributes.cpp",
    "get_queue_url.cpp",
    "index_events_processor.cpp",
    "infly.cpp",
    "list_dead_letter_source_queues.cpp",
    "list_permissions.cpp",
    "list_queue_tags.cpp",
    "list_queues.cpp",
    "list_users.cpp",
    "local_rate_limiter_allocator.cpp",
    "log.cpp",
    "message_delay_stats.cpp",
    "metering.cpp",
    "modify_permissions.cpp",
    "monitoring.cpp",
    "node_tracker.cpp",
    "proxy_actor.cpp",
    "proxy_service.cpp",
    "purge.cpp",
    "purge_queue.cpp",
    "queue_leader.cpp",
    "queue_schema.cpp",
    "queues_list_reader.cpp",
    "receive_message.cpp",
    "retention.cpp",
    "schema.cpp",
    "send_message.cpp",
    "service.cpp",
    "set_queue_attributes.cpp",
    "sha256.cpp",
    "tag_queue.cpp",
    "untag_queue.cpp",
    "user_settings_names.cpp",
    "user_settings_reader.cpp",
  ]

  serialize_enum_headers = [
    "events.h",
    "fifo_cleanup.h",
    "metering.h",
    "queue_schema.h",
  ]
}
