library("result") {
  public_deps = [
    # "//ydb/public/sdk/cpp/src/client/value",
  ]

  deps = [
    # "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/client/proto",
    # "//ydb/public/sdk/cpp/src/client/types/fatal_error_handlers",
  ]

  sources = [
    "out.cpp",
    "proto_accessor.cpp",
    "result.cpp",
  ]

  serialize_enum_headers =
      [ "ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/result/result.h" ]
}
