library("usage") {
  public_deps = [
    # "//ydb/core/base",
    "//ydb/core/protos",
    "//ydb/library/accessor",
    "//ydb/library/signals",
    # "//ydb/library/actors/core",
    # "//ydb/library/conclusion",
  ]

  sources = [
    "abstract.cpp",
    "config.cpp",
    "events.cpp",
    "service.cpp",
    "stage_features.cpp",
  ]
}
