library("abstract") {
  public_deps = [
    "//library/cpp/json",
    # "//ydb/core/formats/arrow/program",
    # "//ydb/core/protos",
    "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/splitter",
    # "//ydb/core/tx/schemeshard/olap/common",
    # "//ydb/library/accessor",
    # "//ydb/library/conclusion",
    "//ydb/library/formats/arrow:protos",
    "//ydb/services/bg_tasks:abstract",
  ]

  deps = [
    "//contrib/libs/xxhash",
    # "//ydb/core/formats/arrow",  # peerdir only
    # "//ydb/core/tx/columnshard/engines/storage/indexes/skip_index",
    # "//ydb/library/actors/core",
    # "//yql/essentials/core/arrow_kernels/request",  # peerdir only
  ]

  sources = [
    "abstract/abstract.cpp",
    "abstract/checker.cpp",
    "abstract/collection.cpp",
    "abstract/common.cpp",
    "abstract/constructor.cpp",
    "abstract/header.cpp",
    "abstract/meta.cpp",
  ]

  serialize_enum_headers = [ "abstract/common.h" ]
}

group("indexes") {
  public_deps = [
    # ":abstract",  # peerdir only
  ]
}
