library("antlr4") {
  public_deps = [
    # "//yql/essentials/parser/common",
  ]

  deps = [
    # "//yql/essentials/core/issue",
  ]

  sources = [ "antlr4/error_listener.cpp" ]
}

library("common") {
  public_deps = [
    "//contrib/libs/antlr4_cpp_runtime",
    "//yql/essentials/public/issue",
  ]

  sources = [ "error.cpp" ]
}
