library("computation") {
  public_deps = [
    "//contrib/libs/apache/arrow",
    # "//library/cpp/cache",
    # "//library/cpp/enumbitset",
    # "//library/cpp/random_provider",
    # "//library/cpp/threading/future",
    # "//library/cpp/time_provider",
    "//yql/essentials/minikql",
    "//yql/essentials/minikql/arrow",
    # "//yql/essentials/public/langver",
    "//yql/essentials/public/udf",
    "//yql/essentials/public/udf:arrow",
    # "//yql/essentials/utils",
  ]

  deps = [
    # "//library/cpp/containers/stack_vector",
    "//library/cpp/monlib/dynamic_counters",
    # "//library/cpp/packedtypes",
    # "//library/cpp/resource",
    # "//library/cpp/yson:node",
    # "//yql/essentials/parser/pg_wrapper/interface",
    "//yql/essentials/public/decimal",
  ]

  sources = [
    "mkql_block_builder.cpp",
    "mkql_block_impl.cpp",
    "mkql_block_reader.cpp",
    "mkql_block_transport.cpp",
    "mkql_block_trimmer.cpp",
    "mkql_computation_node.cpp",
    "mkql_computation_node_holders.cpp",
    "mkql_computation_node_impl.cpp",
    "mkql_computation_node_pack.cpp",
    "mkql_computation_node_pack_impl.cpp",
    "mkql_computation_pattern_cache.cpp",
    "mkql_custom_list.cpp",
    "mkql_datum_validate.cpp",
    "mkql_validate.cpp",
    "mkql_value_builder.cpp",
    "presort.cpp",
  ]
}
