protobuf_library("protos") {
  deps = [
    "//ydb/core/protos",
    "//ydb/core/scheme:protos",
  ]

  sources = [
    "protos/flat_table_part.proto",
    "protos/flat_table_shard.proto",
  ]
}

protobuf_library("private_proto") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/library/actors/protos",
  ]

  sources = [ "flat_executor.proto" ]
}

library("tablet_flat") {
  public_deps = [
    # "//library/cpp/containers/absl_flat_hash",
    # "//library/cpp/containers/stack_vector",
    # "//library/cpp/lwtrace",
    # "//library/cpp/time_provider",
    # "//ydb/core/control/lib",
    # "//ydb/core/protos",
    # "//ydb/core/util",
    # "//ydb/library/actors/core",
    # "//ydb/library/actors/wilson",
    # "//ydb/library/services",
    # "//ydb/library/wilson_ids",
    # "//ydb/library/yverify_stream",
  ]

  deps = [
    # ":private_proto",
    # ":protos",
    # "//library/cpp/blockcodecs",
    # "//library/cpp/digest/crc32c",
    # "//library/cpp/html/pcdata",
    # "//library/cpp/http/io",
    # "//library/cpp/json",
    # "//library/cpp/json:writer",
    # "//library/cpp/lwtrace/mon",
    # "//library/cpp/monlib/dynamic_counters",
    # "//library/cpp/monlib/service/pages",
    # "//library/cpp/protobuf/json",
    # "//library/cpp/random_provider",
    # "//library/cpp/string_utils/base64",
    # "//ydb/core/base",
    # "//ydb/core/cms/console",
    # "//ydb/core/engine:minikql",
    # "//ydb/core/io_formats/cell_maker",
    # "//ydb/core/scheme",
    # "//ydb/core/scheme:protos",
    # "//ydb/core/scheme_types",
    # "//ydb/core/tablet",
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/actors/util",
    # "//yql/essentials/types/binary_json",
    # "//yql/essentials/types/dynumber",
  ]

  sources = [
    "defs.cpp",
    "flat_backup.cpp",
    "flat_bio_actor.cpp",
    "flat_boot_lease.cpp",
    "flat_boot_misc.cpp",
    "flat_comp.cpp",
    "flat_comp_create.cpp",
    "flat_comp_gen.cpp",
    "flat_database.cpp",
    "flat_dbase_apply.cpp",
    "flat_dbase_scheme.cpp",
    "flat_exec_broker.cpp",
    "flat_exec_commit.cpp",
    "flat_exec_commit_mgr.cpp",
    "flat_exec_seat.cpp",
    "flat_executor.cpp",
    "flat_executor_backup.cpp",
    "flat_executor_bootlogic.cpp",
    "flat_executor_borrowlogic.cpp",
    "flat_executor_compaction_logic.cpp",
    "flat_executor_counters.cpp",
    "flat_executor_db_mon.cpp",
    "flat_executor_gclogic.cpp",
    "flat_executor_recovery.cpp",
    "flat_executor_snapshot.cpp",
    "flat_executor_tx_env.cpp",
    "flat_executor_txloglogic.cpp",
    "flat_executor_vacuum_logic.cpp",
    "flat_fwd_misc.cpp",
    "flat_load_blob_queue.cpp",
    "flat_mem_warm.cpp",
    "flat_page_label.cpp",
    "flat_part_charge_create.cpp",
    "flat_part_charge_range.cpp",
    "flat_part_dump.cpp",
    "flat_part_index_iter_create.cpp",
    "flat_part_loader.cpp",
    "flat_part_outset.cpp",
    "flat_part_overlay.cpp",
    "flat_part_slice.cpp",
    "flat_range_cache.cpp",
    "flat_row_versions.cpp",
    "flat_sausage_meta.cpp",
    "flat_sausagecache.cpp",
    "flat_stat_part_group_iter_create.cpp",
    "flat_stat_table.cpp",
    "flat_stat_table_btree_index.cpp",
    "flat_stat_table_btree_index_histogram.cpp",
    "flat_store_hotdog.cpp",
    "flat_table.cpp",
    "flat_table_committed.cpp",
    "flat_table_misc.cpp",
    "flat_table_observer.cpp",
    "flat_table_part.cpp",
    "probes.cpp",
    "shared_cache_counters.cpp",
    "shared_handle.cpp",
    "shared_sausagecache.cpp",
    "tablet_flat_executed.cpp",
    "tablet_flat_executor.cpp",
  ]

  serialize_enum_headers = [
    "flat_comp_gen.h",
    "flat_executor_compaction_logic.h",
    "flat_executor_recovery.h",
    "flat_executor_vacuum_logic.h",
    "flat_page_iface.h",
    "flat_part_loader.h",
    "flat_row_eggs.h",
    "flat_scan_iface.h",
    "shared_cache_events.h",
    "shared_cache_s3fifo.h",
  ]
}
