library("tablet_flat") {
    public_deps = [
        "//library/cpp/containers/absl_flat_hash",
    ]

    deps = [
        "//ydb/core/base",
        "//ydb/core/scheme",
        "//ydb/core/scheme_types",
        "//ydb/core/tablet",
    ]

    sources = [
        "defs.cpp",
        "flat_backup.cpp",
        "flat_boot_lease.cpp",
        "flat_boot_misc.cpp",
        "flat_comp.cpp",
        "flat_comp_create.cpp",
        "flat_comp_gen.cpp",
        "flat_database.cpp",
        "flat_dbase_scheme.cpp",
        "flat_dbase_apply.cpp",
        "flat_exec_broker.cpp",
        "flat_exec_commit.cpp",
        "flat_exec_commit_mgr.cpp",
        "flat_exec_seat.cpp",
        "flat_executor.cpp",
        "flat_executor_backup.cpp",
        "flat_executor_bootlogic.cpp",
        "flat_executor_borrowlogic.cpp",
        "flat_executor_compaction_logic.cpp",
        "flat_executor_counters.cpp",
        "flat_executor_db_mon.cpp",
        "flat_executor_gclogic.cpp",
        "flat_bio_actor.cpp",
        "flat_executor_recovery.cpp",
        "flat_executor_snapshot.cpp",
        "flat_executor_tx_env.cpp",
        "flat_executor_txloglogic.cpp",
        "flat_executor_vacuum_logic.cpp",
        "flat_fwd_misc.cpp",
        "flat_load_blob_queue.cpp",
        "flat_mem_warm.cpp",
        "flat_sausagecache.cpp",
        "flat_sausage_meta.cpp",
        "flat_part_charge_create.cpp",
        "flat_part_charge_range.cpp",
        "flat_page_label.cpp",
        "flat_part_dump.cpp",
        "flat_part_index_iter_create.cpp",
        "flat_part_loader.cpp",
        "flat_part_overlay.cpp",
        "flat_part_outset.cpp",
        "flat_part_slice.cpp",
        "flat_range_cache.cpp",
        "flat_row_versions.cpp",
        "flat_stat_table.cpp",
        "flat_stat_table_btree_index.cpp",
        "flat_stat_table_btree_index_histogram.cpp",
        "flat_stat_part_group_iter_create.cpp",
        "flat_store_hotdog.cpp",
        "flat_table.cpp",
        "flat_table_part.cpp",
        "flat_table_misc.cpp",
        "flat_table_observer.cpp",
        "flat_table_committed.cpp",
        "probes.cpp",
        "shared_handle.cpp",
        "shared_cache_counters.cpp",
        "shared_sausagecache.cpp",
        "tablet_flat_executor.cpp",
        "tablet_flat_executed.cpp",
    ]
}
