config("public_config") {
    include_dirs = [ "include" ]
}

contrib_library("multi_index") {
    public_deps = [
        "//contrib/restricted/boost/bind",
        "//contrib/restricted/boost/container_hash",
        "//contrib/restricted/boost/move",
        "//contrib/restricted/boost/tuple",
    ]

    public_configs = [ ":public_config" ]
}
