library("pgproxy") {
  public_deps = [
    ":protos",
    "//ydb/core/raw_socket",
    "//ydb/library/actors/core",
    # "//ydb/library/services",
  ]

  deps = [
    "//library/cpp/string_utils/base64",
    "//ydb/core/base",
    # "//ydb/core/protos",  # peerdir only
    # "//ydb/library/actors/interconnect",
    # "//ydb/library/actors/protos",  # peerdir only
  ]

  sources = [
    "pg_connection.cpp",
    "pg_proxy.cpp",
    "pg_proxy_types.cpp",
  ]
}

protobuf_library("protos") {
  sources = [ "protos/pgproxy.proto" ]
}
