library("common") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/library/accessor",
    "//ydb/library/conclusion",
    "//ydb/library/signals",
    "//ydb/library/yverify_stream",
    "//ydb/public/api/protos",
    "//yql/essentials/core/issue:protos",
  ]

  sources = [
    "common/error_codes.cpp",
    "common/modification_type.cpp",
    "common/signals_flow.cpp",
  ]

  serialize_enum_headers = [ "common/signals_flow.h" ]
}

library("data_events") {
  public_deps = [
    ":common",
    "//contrib/libs/apache/arrow",
    "//library/cpp/lwtrace",
    "//ydb/core/base",
    "//ydb/core/formats/arrow:reader",
    "//ydb/core/protos",
    "//ydb/core/scheme",
    "//ydb/core/tx/columnshard/common",
    "//ydb/core/tx/long_tx_service:public",
    "//ydb/core/tx/scheme_cache",
    "//ydb/library/accessor",
    "//ydb/library/actors/core",
    "//ydb/library/actors/util",
    "//ydb/library/actors/wilson",
    "//ydb/library/conclusion",
    "//ydb/library/formats/arrow:modifier",
    "//ydb/library/signals",
    "//ydb/public/api/protos",
    "//yql/essentials/core/issue",
    "//yql/essentials/public/issue",
  ]

  deps = [
    "//ydb/core/formats/arrow",
    "//ydb/core/tablet",
    "//ydb/core/tx/columnshard",
    "//ydb/core/tx/columnshard/splitter",
    "//ydb/core/tx/sharding",
  ]

  sources = [
    "columnshard_splitter.cpp",
    "shard_writer.cpp",
    "shards_splitter.cpp",
    "write_data.cpp",
  ]
}
