protobuf_library("opentelemetry-proto") {
    sources = [
        "opentelemetry/proto/collector/logs/v1/logs_service.proto",
        "opentelemetry/proto/collector/metrics/v1/metrics_service.proto",
        "opentelemetry/proto/collector/profiles/v1development/profiles_service.proto",
        "opentelemetry/proto/collector/trace/v1/trace_service.proto",
        "opentelemetry/proto/common/v1/common.proto",
        "opentelemetry/proto/logs/v1/logs.proto",
        "opentelemetry/proto/metrics/v1/metrics.proto",
        "opentelemetry/proto/profiles/v1development/profiles.proto",
        "opentelemetry/proto/resource/v1/resource.proto",
        "opentelemetry/proto/trace/v1/trace.proto",
    ]

    proto_public_include_dirs = [ "." ]
}
