import("//yql/essentials/core/expr_nodes_gen/gen.gni")

generate_expr_nodes("gen") {
    sources = [ "yql_expr_nodes.json" ]
}

library("expr_nodes") {
    public_deps = [
        "//yql/essentials/core/issue",
    ]

    deps = [
        ":gen",
    ]

    sources = [
        "yql_expr_nodes.cpp",
    ]
}
