library("operations") {
  public_deps = [
    "//ydb/core/protos",
    "//ydb/services/metadata/manager",
  ]

  deps = [
    # "//library/cpp/json",
    "//ydb/core/formats/arrow",
    # "//ydb/core/kqp/gateway/utils",
    "//ydb/core/kqp/provider",
    "//ydb/core/protos/schemeshard",
    # "//ydb/core/tx/columnshard/data_accessor/abstract",
    "//ydb/core/tx/columnshard/engines/scheme/indexes/abstract",
    # "//ydb/core/tx/columnshard/engines/storage/optimizer/abstract",
    # "//ydb/library/actors/core",
  ]

  sources = [
    "abstract.cpp",
    "add_column.cpp",
    "alter_column.cpp",
    "alter_sharding.cpp",
    "drop_column.cpp",
    "drop_index.cpp",
    "upsert_index.cpp",
    "upsert_opt.cpp",
  ]
}
