library("tablet") {
  public_deps = [
    # "//ydb/core/grpc_services/base",
    # "//ydb/library/actors/core",
    # "//ydb/library/grpc/server",
    # "//ydb/public/api/grpc:draft",
  ]

  deps = [
    # "//ydb/core/grpc_services",
    # "//ydb/core/grpc_services/tablet",
  ]

  sources = [ "ydb_tablet.cpp" ]
}
