library("nodewarden") {
  public_deps = [
    "//ydb/core/base",
    "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/crypto",
    "//ydb/core/blobstorage/dsproxy",
    "//ydb/core/blobstorage/incrhuge",
    "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/cms/console",
    "//ydb/core/mind:group_mapper",
    # "//ydb/core/node_whiteboard",
    # "//ydb/core/protos",
    "//ydb/core/util",
    # "//ydb/library/actors/core",
    "//ydb/library/pdisk_io",
  ]

  deps = [
    "//contrib/libs/xxhash",
    "//library/cpp/digest/crc32c",
    # "//library/cpp/json",
    "//library/cpp/lwtrace/mon",
    "//library/cpp/openssl/crypto",
    # "//library/cpp/protobuf/json",
    "//library/cpp/streams/zstd",
    # "//library/cpp/time_provider",
    "//ydb/core/audit",
    "//ydb/core/blob_depot:agent",
    "//ydb/core/blobstorage/bridge/proxy",
    "//ydb/core/blobstorage/bridge/syncer",
    # "//ydb/core/blobstorage/common",
    "//ydb/core/blobstorage/ddisk",
    "//ydb/core/blobstorage/dsproxy:mock",
    "//ydb/core/blobstorage/events",
    # "//ydb/core/blobstorage/groupinfo",
    "//ydb/core/blobstorage/vdisk",
    "//ydb/core/blobstorage/vdisk/repl",
    "//ydb/core/blobstorage/vdisk/syncer",
    "//ydb/core/config/validation",
    # "//ydb/core/control/lib",
    "//ydb/core/mind:nameserver_table_builder",
    "//ydb/core/tablet",
    "//ydb/core/tx/scheme_board",
    "//ydb/library/aclib",
    "//ydb/library/keys",
    "//ydb/library/pdisk_io",
    # "//ydb/library/yaml_config",
    "//ydb/library/yaml_json",
    # "//ydb/library/yverify_stream",
  ]

  sources = [
    "distconf.cpp",
    "distconf_binding.cpp",
    "distconf_bridge.cpp",
    "distconf_cache.cpp",
    "distconf_connectivity.cpp",
    "distconf_console.cpp",
    "distconf_dynamic.cpp",
    "distconf_fsm.cpp",
    "distconf_generate.cpp",
    "distconf_invoke_bridge.cpp",
    "distconf_invoke_common.cpp",
    "distconf_invoke_state_storage.cpp",
    "distconf_invoke_static_group.cpp",
    "distconf_invoke_storage_config.cpp",
    "distconf_mon.cpp",
    "distconf_persistent_storage.cpp",
    "distconf_quorum.cpp",
    "distconf_scatter_gather.cpp",
    "distconf_selfheal.cpp",
    "distconf_statestorage_config_generator.cpp",
    "distconf_validate.cpp",
    "group_stat_aggregator.cpp",
    "node_warden_cache.cpp",
    "node_warden_group.cpp",
    "node_warden_group_resolver.cpp",
    "node_warden_impl.cpp",
    "node_warden_mon.cpp",
    "node_warden_pdisk.cpp",
    "node_warden_pipe.cpp",
    "node_warden_proxy.cpp",
    "node_warden_resource.cpp",
    "node_warden_scrub.cpp",
    "node_warden_stat_aggr.cpp",
    "node_warden_vdisk.cpp",
  ]
}
