library("request") {
  public_deps = [
    "//yql/essentials/ast",
    "//yql/essentials/minikql",
    "//yql/essentials/providers/common/mkql",
    # "//yql/essentials/public/langver",
  ]

  deps = [
    "//yql/essentials/core",
  ]

  sources = [ "request.cpp" ]

  serialize_enum_headers = [ "request.h" ]
}
