linked_executable("decrypt") {
  deps = [
    "//library/cpp/getopt",
    "//ydb/core/backup/common",
  ]

  sources = [ "main.cpp" ]

  link_select = [
    "YqlServicePolicy=stub",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
