# yamake2gn: keep  -- hand-written, do not regenerate

library("constructor") {
  public_deps = [
    "//ydb/core/tx/columnshard/engines/reader/abstract",
    "//ydb/core/tx/columnshard/engines/reader/common_reader/constructor:shard",
  ]

  deps = [
    "//ydb/core/tx/columnshard/counters",
    "//ydb/core/tx/columnshard/engines",
    "//ydb/core/tx/columnshard/engines/predicate",
    "//ydb/core/tx/columnshard/engines/reader/plain_reader/iterator",
    "//ydb/core/tx/columnshard/hooks/abstract",
    "//ydb/core/tx/time_cast",
  ]

  sources = [
    "constructor.cpp",
    "read_metadata.cpp",
  ]
}
