library("actors") {
  public_deps = [
    # "//contrib/libs/protobuf",
    # "//library/cpp/containers/disjoint_interval_tree",
    # "//ydb/core/base",
    "//ydb/core/client/server",
    "//ydb/core/grpc_services",
    # "//ydb/core/jaeger_tracing",
    # "//ydb/core/kqp/common",
    # "//ydb/core/kqp/common/events",
    # "//ydb/core/persqueue",
    # "//ydb/core/persqueue/events",
    "//ydb/core/persqueue/public",
    "//ydb/core/persqueue/public/counters",
    "//ydb/core/persqueue/public:utils",
    "//ydb/core/persqueue/writer",
    "//ydb/core/persqueue/writer:partition_chooser",
    "//ydb/core/protos",
    # "//ydb/core/scheme",
    # "//ydb/core/tablet",
    # "//ydb/core/tx/scheme_board",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/util",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    # "//ydb/library/cloud_permissions",
    "//ydb/library/persqueue/topic_parser",
    "//ydb/library/services",
    # "//ydb/library/wilson_ids",
    "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/client/persqueue_public:include",
    "//ydb/services/lib/actors",
    # "//ydb/services/lib/sharding",
    # "//ydb/services/metadata",
  ]

  deps = [
    # "//library/cpp/json",
    # "//library/cpp/protobuf/util",
    # "//library/cpp/random_provider",
    "//library/cpp/string_utils/base64",
    # "//ydb/core/kqp/common/simple",
    # "//ydb/core/kqp/topics",  # peerdir only
    "//ydb/core/persqueue/common",
    # "//ydb/core/persqueue/public/cluster_tracker",  # peerdir only
    "//ydb/core/persqueue/public/codecs",
    "//ydb/core/persqueue/public/write_meta",
    # "//ydb/core/ydb_convert",
    # "//ydb/public/lib/base",
    # "//ydb/public/lib/deprecated/kicli",
    # "//ydb/public/sdk/cpp/src/client/proto",
    "//ydb/public/sdk/cpp/src/library/persqueue/obfuscate",
    # "//ydb/services/metadata/manager",
    "//yql/essentials/public/issue/protos",
  ]

  sources = [
    "codecs.cpp",
    "commit_offset_actor.cpp",
    "direct_read_actor.cpp",
    "distributed_commit_helper.cpp",
    "helpers.cpp",
    "partition_actor.cpp",
    "partition_writer.cpp",
    "partition_writer_cache_actor.cpp",
    "persqueue_utils.cpp",
    "read_info_actor.cpp",
    "read_init_auth_actor.cpp",
    "read_session_actor.cpp",
    "schema_actors.cpp",
    "update_offsets_in_transaction_actor.cpp",
    "write_session_actor.cpp",
  ]
}
