library("data_reader") {
  public_deps = [
    # "//ydb/core/kqp/compute_actor",
    # "//ydb/core/tx/columnshard",
    "//ydb/core/tx/columnshard/blobs_reader",
    "//ydb/core/tx/columnshard/data_accessor",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/common",
    "//ydb/core/tx/conveyor_composite/usage",
    "//ydb/core/tx/limiter/grouped_memory/tracing",
    "//ydb/core/tx/limiter/grouped_memory/usage",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/core",
    # "//ydb/library/signals",
  ]

  deps = [
    # "//ydb/core/tx/columnshard/engines/scheme/versions",
    "//ydb/library/yql/dq/actors",
  ]

  sources = [
    "actor.cpp",
    "contexts.cpp",
    "fetcher.cpp",
    "fetching_executor.cpp",
    "fetching_steps.cpp",
  ]

  serialize_enum_headers = [ "contexts.h" ]
}
