library("recovery") {
  public_deps = [
    "//ydb/core/base",
    "//ydb/core/tablet_flat",
  ]

  deps = [
    "//library/cpp/protobuf/json",
    "//library/cpp/string_utils/base64",
    "//ydb/core/engine:minikql",
    "//ydb/core/io_formats/cell_maker",
    "//ydb/core/protos",
    "//ydb/library/actors/core",
    "//yql/essentials/types/binary_json",
  ]

  sources = [ "flat_executor_recovery.cpp" ]

  serialize_enum_headers = [ "flat_executor_recovery.h" ]
}
