library("tx") {
  public_deps = [
    "//ydb/core/base",
    "//ydb/core/protos",
    "//ydb/library/actors/core",
    "//ydb/library/conclusion",
    # "//ydb/library/services",
  ]

  deps = [
    # "//ydb/core/tablet",  # peerdir only
    # "//ydb/core/tablet_flat",  # peerdir only
    # "//ydb/core/util",  # peerdir only
    # "//ydb/library/aclib",  # peerdir only
  ]

  sources = [
    "message_seqno.cpp",
    "tx.cpp",
    "tx_proxy_schemereq.cpp",
  ]
}
