library("workload_service") {
  public_deps = [
    # "//library/cpp/monlib/dynamic_counters",
    "//ydb/core/resource_pools",
    "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/cms/console",
    # "//ydb/core/fq/libs/compute/common",  # peerdir only
    "//ydb/core/kqp/common/events",
    # "//ydb/core/kqp/common/simple",
    "//ydb/core/kqp/workload_service/actors",
    "//ydb/core/kqp/workload_service/actors:cpu_load_actors",  # peerdir only
    "//ydb/core/kqp/workload_service/common",
    "//ydb/core/kqp/workload_service/tables",
    "//ydb/core/mind:tenant_node_enumeration",
    "//ydb/core/protos",
    # "//ydb/library/actors/interconnect",
  ]

  sources = [ "kqp_workload_service.cpp" ]
}
