library("facade") {
  public_deps = [
    "//library/cpp/random_provider",
    # "//library/cpp/threading/future",
    "//library/cpp/time_provider",
    # "//yql/essentials/core",
    # "//yql/essentials/core/credentials",
    # "//yql/essentials/core/file_storage",
    # "//yql/essentials/core/layers",
    # "//yql/essentials/core/qplayer/storage/interface",
    "//yql/essentials/core/services",
    # "//yql/essentials/core/url_lister/interface",
    # "//yql/essentials/core/url_preprocessing/interface",
    "//yql/essentials/providers/common/gateways_utils",
    # "//yql/essentials/providers/common/proto",
    "//yql/essentials/providers/config",
    "//yql/essentials/providers/result/provider",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/public/langver",
    # "//yql/essentials/sql",
  ]

  deps = [
    # "//library/cpp/deprecated/split",
    # "//library/cpp/string_utils/base64",
    # "//library/cpp/yson",
    # "//library/cpp/yson:node",
    "//yql/essentials/core/extract_predicate",
    "//yql/essentials/core/langver",
    "//yql/essentials/core/qplayer/udf_resolver",
    "//yql/essentials/core/qplayer/url_lister",
    # "//yql/essentials/core/type_ann",
    # "//yql/essentials/parser/pg_wrapper/interface",
    # "//yql/essentials/providers/common/activation",
    "//yql/essentials/providers/common/arrow_resolve",
    # "//yql/essentials/providers/common/config",
    "//yql/essentials/providers/common/provider",
    "//yql/essentials/providers/common/udf_resolve",
    "//yql/essentials/sql/v1",
    "//yql/essentials/sql/v1/lexer:antlr4",
    "//yql/essentials/sql/v1/lexer:antlr4_ansi",
    "//yql/essentials/sql/v1/proto_parser:antlr4",
    "//yql/essentials/sql/v1/proto_parser:antlr4_ansi",
    # "//yql/essentials/utils",
    # "//yql/essentials/utils/log",
  ]

  sources = [ "yql_facade.cpp" ]
}
