library("cbo") {
  public_deps = [
    # "//yql/essentials/core",
  ]

  deps = [
    # "//library/cpp/disjoint_sets",
    # "//library/cpp/iterator",
    # "//yql/essentials/utils/log",
  ]

  sources = [
    "cbo_hints.cpp",
    "cbo_interesting_orderings.cpp",
    "cbo_optimizer_new.cpp",
  ]

  serialize_enum_headers = [ "cbo_optimizer_new.h" ]
}
