library("backtrace") {
    deps = [
        "//contrib/libs/backtrace",
        "//contrib/libs/libunwind",
        "//library/cpp/malloc:api",
    ]

    sources = [
        "backtrace.cpp",
        "backtrace_lib.cpp",
        "backtrace_linux.cpp",
        "symbolize.cpp",
        "symbolizer_linux.cpp",
    ]
}
