library("response") {
  public_deps = [ "//ydb/core/kqp/common" ]

  deps = [
    "//ydb/core/kqp/federated_query",
    "//ydb/core/ydb_convert",
    "//yql/essentials/public/issue",
  ]

  sources = [ "kqp_response.cpp" ]
}

library("session_actor") {
  public_deps = [
    # "//library/cpp/json",
    # "//ydb/core/docapi",
    "//ydb/core/kqp/common",
    ":response",
    # "//ydb/core/kqp/provider",
    # "//ydb/core/protos",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//library/cpp/time_provider",
    # "//ydb/core/actorlib_impl",
    # "//ydb/core/base",
    # "//ydb/core/control/lib",
    # "//ydb/core/engine",
    # "//ydb/core/kqp/common:buffer",
    # "//ydb/core/kqp/common:compilation",
    # "//ydb/core/kqp/common:events",
    # "//ydb/core/kqp/common:simple",
    # "//ydb/core/kqp/compile_service",
    "//ydb/core/kqp/counters",
    # "//ydb/core/kqp/executer_actor",
    # "//ydb/core/kqp/executer_actor:shards_resolver",
    "//ydb/core/kqp/federated_query",
    "//ydb/core/kqp/gateway",
    # "//ydb/core/kqp/gateway:actors",
    # "//ydb/core/kqp/host",
    # "//ydb/core/kqp/opt",
    # "//ydb/core/kqp/rm_service",
    # "//ydb/core/protos/schemeshard",
    # "//ydb/core/sys_view:common",
    # "//ydb/core/sys_view:service",
    # "//ydb/core/tablet",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/schemeshard",
    # "//ydb/core/tx/tx_proxy",
    # "//ydb/core/util",
    # "//ydb/core/ydb_convert",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/async",
    # "//ydb/library/actors/wilson",
    # "//ydb/library/persqueue/topic_parser",
    # "//ydb/library/wilson_ids",
    # "//ydb/library/ydb_issue",
    # "//ydb/library/yql/dq/actors:compute",
    # "//ydb/library/yql/dq/runtime",
    # "//ydb/library/yql/utils/actor_log",
    # "//ydb/public/sdk/cpp/src/library/operation_id",
    # "//yql/essentials/public/issue",
  ]

  sources = [
    "kqp_query_state.cpp",
    "kqp_query_stats.cpp",
    "kqp_session_actor.cpp",
    "kqp_temp_tables_manager.cpp",
    "kqp_worker_actor.cpp",
    "kqp_worker_common.cpp",
  ]
}
