library("columns") {
  public_deps = [
    "//ydb/core/formats/arrow/accessor/abstract",
    "//ydb/core/formats/arrow:dictionary",
    # "//ydb/core/formats/arrow/serializer",
    # "//ydb/core/protos",
    "//ydb/core/scheme_types",
    "//ydb/core/tx/columnshard/engines/scheme/defaults:common",
    "//ydb/core/tx/schemeshard/olap/common",
    # "//ydb/library/accessor",
  ]

  deps = [
    # "//ydb/core/formats/arrow",
    # "//ydb/core/scheme",
    # "//ydb/core/tx/schemeshard",
    "//ydb/library/formats/arrow:validation",
    "//yql/essentials/minikql",
    # "//yql/essentials/parser/pg_wrapper",
  ]

  sources = [
    "schema.cpp",
    "update.cpp",
  ]
}
