config("public_config") {
    include_dirs = [ "include" ]
}

contrib_library("xpressive") {
    public_deps = [
        "//contrib/restricted/boost/core",
        "//contrib/restricted/boost/exception",
        "//contrib/restricted/boost/numeric_conversion",
        "//contrib/restricted/boost/proto",
    ]

    public_configs = [ ":public_config" ]
}
