library("common") {
  testonly = true

  public_deps = [
    # "//library/cpp/testing/unittest",
    "//ydb/core/kqp/workload_service/common",
    "//ydb/core/protos",
    # "//ydb/core/testlib/actors",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/public/lib/yson_value",
    # "//ydb/public/sdk/cpp/src/client/query",
    # "//ydb/public/sdk/cpp/src/client/scheme",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/kqp/common/events",
    # "//ydb/core/kqp/common/simple",
    "//ydb/core/kqp/executer_actor",
    "//ydb/core/kqp/ut/common",
    "//ydb/core/kqp/workload_service/actors",
    "//ydb/core/kqp/workload_service/tables",
    # "//ydb/core/node_whiteboard",
    # "//ydb/library/yql/providers/common/http_gateway",
    "//ydb/library/yql/utils/actor_log",
  ]

  sources = [ "kqp_workload_service_ut_common.cpp" ]
}
