library("antlr4") {
  public_deps = [
    "//contrib/libs/antlr4-c3",
    "//contrib/libs/antlr4_cpp_runtime",
  ]

  sources = [ "antlr4/vocabulary.cpp" ]
}

library("check") {
  deps = [
    ":complete",
    "//yql/essentials/ast",
    "//yql/essentials/sql/v1/complete/analysis/yql",
    "//yql/essentials/sql/v1/complete/name/cluster:static",
    "//yql/essentials/sql/v1/complete/name/object/simple",
    "//yql/essentials/sql/v1/complete/name/object/simple:static",
    "//yql/essentials/sql/v1/complete/name/service:cluster",
    "//yql/essentials/sql/v1/complete/name/service:ranking",
    "//yql/essentials/sql/v1/complete/name/service:schema",
    "//yql/essentials/sql/v1/complete/name/service:union",
    "//yql/essentials/sql/v1/lexer",
    "//yql/essentials/sql/v1/lexer:antlr4_pure",
    "//yql/essentials/sql/v1/lexer:antlr4_pure_ansi",
  ]

  sources = [ "check/check_complete.cpp" ]
}

library("complete") {
  public_deps = [
    ":core",
    # "//library/cpp/threading/future",
    # "//yql/essentials/sql/v1/complete/name/service",
    "//yql/essentials/sql/v1/complete/name/service:ranking",
    "//yql/essentials/sql/v1/lexer",
  ]

  deps = [
    ":syntax",
    # ":text",
    "//library/cpp/yson:node",
    "//yql/essentials/sql/v1/complete/analysis/global",
    "//yql/essentials/sql/v1/complete/analysis/local",
    # "//yql/essentials/sql/v1/complete/name/object/simple:static",
    "//yql/essentials/sql/v1/complete/name/service:binding",
    "//yql/essentials/sql/v1/complete/name/service:column",
    # "//yql/essentials/sql/v1/complete/name/service:schema",
    # "//yql/essentials/sql/v1/complete/name/service:static",
    "//yql/essentials/sql/v1/complete/name/service:union",
  ]

  sources = [
    "configuration.cpp",
    "name_mapping.cpp",
    "sql_complete.cpp",
  ]
}

library("core") {
  public_deps = [
    "//library/cpp/yson:node",
  ]

  deps = [
    "//yql/essentials/core/sql_types",
  ]

  sources = [
    "core/environment.cpp",
    "core/input.cpp",
    "core/name.cpp",
    "core/statement.cpp",
  ]
}

library("syntax") {
  public_deps = [
    ":antlr4",
    # "//contrib/libs/antlr4_cpp_runtime",
    "//yql/essentials/parser/antlr_ast/gen/v1_antlr4",
  ]

  deps = [
    "//contrib/libs/re2",
    "//yql/essentials/public/issue",
    "//yql/essentials/sql/v1/lexer/regex",
    "//yql/essentials/sql/v1/reflect",
    "//yql/essentials/sql:settings",
  ]

  sources = [
    "syntax/ansi.cpp",
    "syntax/format.cpp",
    "syntax/grammar.cpp",
  ]
}

library("text") {
  sources = [
    "text/case.cpp",
    "text/word.cpp",
  ]
}
