unittest_executable("ut_table_writer") {
  deps = [
    "//library/cpp/testing/unittest",
    "//ydb/core/backup/impl",
    "//ydb/core/protos",
    "//ydb/core/tx/replication/ut_helpers",  # peerdir only
  ]

  sources = [ "//ydb/core/backup/impl/table_writer_ut.cpp" ]

  include_dirs = [ "//ydb/core/backup/impl" ]

  link_select = [
    "YqlServicePolicy=exception_policy",
    "allocator=tcmalloc",
    "minikql_codegen=llvm16",
    "topic_rpc=persqueue_v1",
    "yql_pg_runtime=pg_wrapper",
    "yql_pg_sql_translator=pg",
    "yt_codegen=llvm16",
  ]
}
