library("duplicates") {
  public_deps = [
    # "//ydb/core/formats/arrow",
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/blobs_reader",
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/reader/common_reader/iterator",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator:collections",
    # "//ydb/library/actors/core",
    # "//ydb/library/conclusion",
    # "//ydb/library/range_treap",
  ]

  deps = [
    # "//ydb/core/formats/arrow:common",
    # "//ydb/core/formats/arrow:reader",
    # "//ydb/core/formats/arrow:rows",
    # "//ydb/core/tx/columnshard/column_fetching",
    # "//ydb/core/tx/columnshard/common",
    # "//ydb/core/tx/columnshard/engines/reader/simple_reader/iterator",
    # "//ydb/core/tx/columnshard/engines/scheme/abstract",
    # "//ydb/core/tx/conveyor/usage",
    # "//ydb/core/tx/conveyor_composite/usage",
    # "//ydb/core/tx/limiter/grouped_memory/usage",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/interconnect",
  ]

  sources = [
    "common.cpp",
    "context.cpp",
    "events.cpp",
    "executor.cpp",
    "manager.cpp",
    "merge.cpp",
    "private_events.cpp",
    "splitter.cpp",
  ]
}
