library("audit") {
  public_deps = [ "//ydb/core/protos" ]

  deps = [
    "//library/cpp/json",
    "//library/cpp/logger",
    "//ydb/core/util",
    "//ydb/library/actors/core",
    "//ydb/library/services",
    "//ydb/public/api/protos",
  ]

  sources = [
    "audit_log_impl.cpp",
    "login_op.cpp",
  ]
}

library("audit_config") {
  public_deps = [ "//ydb/library/aclib:protos" ]

  deps = [ "//ydb/core/protos" ]

  sources = [ "audit_config/audit_config.cpp" ]
}
