library("scheme") {
  public_deps = [
    # "//ydb/public/sdk/cpp/src/client/driver",
  ]

  deps = [
    # "//ydb/public/api/grpc",
    # "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/client/common_client:impl",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/make_request",
  ]

  sources = [
    "out.cpp",
    "scheme.cpp",
  ]

  serialize_enum_headers =
      [ "ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/scheme/scheme.h" ]
}
