library("partition_key_range") {
  public_deps = [
    "//ydb/core/scheme",
    # "//yql/essentials/public/decimal",
  ]

  deps = [
    "//library/cpp/digest/md5",
    # "//ydb/core/protos",
    "//ydb/library/actors/core",
    "//ydb/services/lib/sharding",
  ]

  sources = [
    "partition_key_range.cpp",
    "partition_key_range_sequence.cpp",
  ]
}
