library("chunks") {
  public_deps = [
    # "//ydb/core/tx/columnshard/counters",
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/columnshard/engines/scheme/versions",
    # "//ydb/core/tx/columnshard/splitter",
    # "//ydb/core/tx/columnshard/splitter:abstract",
  ]

  deps = [
    # "//ydb/core/formats/arrow:splitter",
  ]

  sources = [
    "column.cpp",
    "data.cpp",
  ]
}
