library("balance") {
  public_deps = [
    # "//ydb/core/blobstorage/base",
    # "//ydb/core/blobstorage/vdisk/hulldb",
    # "//ydb/core/blobstorage/vdisk/hulldb:generic",
  ]

  deps = [
    # "//ydb/core/blobstorage/groupinfo",
    # "//ydb/core/blobstorage/vdisk/common",
    # "//ydb/core/blobstorage/vdisk/hullop",
    # "//ydb/core/blobstorage/vdisk/ingress",
    # "//ydb/core/blobstorage/vdisk/repl",
    # "//ydb/core/blobstorage/vdisk/synclog",
    # "//ydb/core/util",
  ]

  sources = [
    "balancing_actor.cpp",
    "deleter.cpp",
    "handoff_map.cpp",
    "sender.cpp",
    "utils.cpp",
  ]
}
