library("proto") {
  public_deps = [
    "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/topic",
    # "//ydb/public/sdk/cpp/src/client/coordination",
    # "//ydb/public/sdk/cpp/src/client/export",
    # "//ydb/public/sdk/cpp/src/client/import",
    # "//ydb/public/sdk/cpp/src/client/monitoring",
    # "//ydb/public/sdk/cpp/src/client/table",
  ]

  deps = [
    "//ydb/public/sdk/cpp/src/client/params",
    "//ydb/public/sdk/cpp/src/client/value",
  ]

  sources = [ "accessor.cpp" ]
}
