library("kesus") {
  public_deps = [
    # "//ydb/core/grpc_services",
    # "//ydb/core/grpc_services/base",
    # "//ydb/library/actors/core",
    # "//ydb/library/grpc/server",
    # "//ydb/public/api/grpc",
  ]

  deps = [
    # "//ydb/core/base",
    # "//ydb/core/grpc_streaming",
    # "//ydb/core/kesus/proxy",
    # "//ydb/core/kesus/tablet",
    # "//ydb/public/sdk/cpp/src/client/resources",
  ]

  sources = [ "grpc_service.cpp" ]
}
