library("common") {
  public_deps = [
    "//ydb/library/accessor",
    "//ydb/library/conclusion",
  ]

  deps = [
    ":protos",
    "//contrib/libs/apache/arrow",
    "//ydb/core/formats/arrow",
    "//ydb/core/scheme_types",
    "//ydb/library/actors/core",
    "//ydb/library/formats/arrow:switch",
  ]

  sources = [ "common/scalar.cpp" ]
}

protobuf_library("protos") {
  sources = [ "protos/data.proto" ]
}
