library("scheme_cache") {
  public_deps = [
    "//ydb/core/base",
    # "//ydb/core/persqueue/public",
    # "//ydb/core/persqueue/writer",
    "//ydb/core/protos",
    # "//ydb/core/scheme",
    # "//ydb/core/scheme_types",
    # "//ydb/core/tx/locks",
    # "//ydb/library/aclib",
    # "//ydb/library/login:protos",
  ]

  sources = [ "scheme_cache.cpp" ]

  serialize_enum_headers = [ "scheme_cache.h" ]
}
