library("http_client") {
  public_deps = [
    # "//library/cpp/threading/future",
    # "//yt/cpp/mapreduce/client",
    # "//yt/cpp/mapreduce/common",
    # "//yt/cpp/mapreduce/http",
    # "//yt/cpp/mapreduce/interface",
  ]

  deps = [
    # "//library/cpp/yson:node",
    # "//library/cpp/yt/yson_string",
    # "//yt/cpp/mapreduce/interface:logging",
    # "//yt/cpp/mapreduce/io",
  ]

  sources = [
    "raw_batch_request.cpp",
    "raw_client.cpp",
    "raw_requests.cpp",
    "rpc_parameters_serialization.cpp",
  ]
}
