library("coordination") {
  public_deps = [
    # "//ydb/public/sdk/cpp/src/client/driver",
  ]

  deps = [
    # "//ydb/public/api/grpc",
    # "//ydb/public/sdk/cpp/src/client/common_client:impl",
    # "//ydb/public/sdk/cpp/src/client/impl/internal/make_request",
    # "//ydb/public/sdk/cpp/src/client/proto",
  ]

  sources = [
    "coordination.cpp",
    "proto_accessor.cpp",
  ]

  serialize_enum_headers = [
    "ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/coordination/coordination.h",
  ]
}
