library("common") {
    deps = [
        "//contrib/libs/aws-sdk-cpp:core",
        "//contrib/libs/aws-sdk-cpp:s3",
        "//contrib/libs/ftxui",
        "//contrib/libs/openssl",
        "//library/cpp/yaml",
        "//ydb/public/sdk/cpp/src/client/types:status",
    ]

    sources = [
        "common/aws.cpp",
        "common/cert_format_converter.cpp",
        "common/client_command_options.cpp",
        "common/colors.cpp",
        "common/command_utils.cpp",
        "common/command.cpp",
        "common/common.cpp",
        "common/config.cpp",
        "common/csv_parser.cpp",
        "common/describe.cpp",
        "common/download_manager.cpp",
        "common/duration.cpp",
        "common/examples.cpp",
        "common/format.cpp",
        "common/ftxui.cpp",
        "common/interactive.cpp",
        "common/interruptable.cpp",
        "common/log.cpp",
        "common/normalize_path.cpp",
        "common/parameter_stream.cpp",
        "common/parameters.cpp",
        "common/pg_dump_parser.cpp",
        "common/pretty_table.cpp",
        "common/print_operation.cpp",
        "common/print_utils.cpp",
        "common/profile_manager.cpp",
        "common/progress_bar.cpp",
        "common/progress_indication.cpp",
        "common/query_stats.cpp",
        "common/query_utils.cpp",
        "common/recursive_list.cpp",
        "common/recursive_remove.cpp",
        "common/retry_func.cpp",
        "common/root.cpp",
        "common/scheme_printers.cpp",
        "common/sys.cpp",
        "common/tabbed_table.cpp",
        "common/waiting_bar.cpp",
        "common/ydb_path.cpp",
        "common/ydb_updater.cpp",
        "common/yt.cpp",
    ]
}
