library("buffer") {
  public_deps = [
    ":simple",
    "//ydb/library/yql/dq/actors:protos",
    "//yql/essentials/public/issue",
  ]

  sources = [ "buffer/events.cpp" ]
}

library("common") {
  public_deps = [
    # "//library/cpp/json:writer",
    # "//library/cpp/lwtrace",
    # "//library/cpp/string_utils/base64",
    # "//ydb/core/control/lib",
    # "//ydb/core/engine",
    # "//ydb/core/grpc_services/cancelation",
    # "//ydb/core/kqp/counters",
    # "//ydb/core/kqp/executer_actor",
    # "//ydb/core/kqp/expr_nodes",
    # "//ydb/core/kqp/gateway",
    # "//ydb/core/kqp/provider",
    # "//ydb/core/protos",
    # "//ydb/core/resource_pools",
    # "//ydb/core/scheme",
    # "//ydb/core/scheme_types",
    # "//ydb/core/tx/data_events",
    # "//ydb/core/tx/datashard",
    # "//ydb/core/tx/scheme_cache",
    # "//ydb/core/tx/sharding",
    # "//ydb/core/util",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    # "//ydb/library/mkql_proto:protos",
    # "//ydb/library/services",
    # "//ydb/library/yql/dq/actors",
    # "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/library/operation_id",
    # "//yql/essentials/ast",
    # "//yql/essentials/minikql",
    # ":compilation",
    # ":events",
    # ":shutdown",
    # ":simple",
  ]

  deps = [
    # "//library/cpp/protobuf/json",
    # "//ydb/core/base",
    # "//ydb/core/tx/locks",
    # "//ydb/public/sdk/cpp/src/library/operation_id:protos",
    # "//yql/essentials/core",
    # "//yql/essentials/core/dq_integration",
    # "//yql/essentials/core/expr_nodes",
    # "//yql/essentials/core/services",
    # "//yql/essentials/parser/pg_wrapper/interface",
    # "//yql/essentials/public/issue",
    # "//yql/essentials/public/udf",
  ]

  sources = [
    "control.cpp",
    "kqp.cpp",
    "kqp_batch_operations.cpp",
    "kqp_event_impl.cpp",
    "kqp_lwtrace_probes.cpp",
    "kqp_resolve.cpp",
    "kqp_row_builder.cpp",
    "kqp_ru_calc.cpp",
    "kqp_script_executions.cpp",
    "kqp_timeouts.cpp",
    "kqp_tx.cpp",
    "kqp_tx_manager.cpp",
    "kqp_types.cpp",
    "kqp_user_request_context.cpp",
    "kqp_yql.cpp",
  ]

  serialize_enum_headers = [
    "kqp_resolve.h",
    "kqp_tx_info.h",
    "kqp_yql.h",
  ]
}

library("compilation") {
  public_deps = [
    # "//library/cpp/lwtrace",
    # "//ydb/core/kqp/common",
    # "//ydb/core/kqp/counters",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    # "//yql/essentials/ast",
    # "//yql/essentials/public/issue",
    # ":simple",
  ]

  deps = [
    # "//ydb/core/util",
  ]

  sources = [
    "compilation/events.cpp",
    "compilation/result.cpp",
  ]
}

library("events") {
  public_deps = [
    # "//ydb/core/protos",
    # "//ydb/core/resource_pools",
    # "//ydb/core/scheme",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    # "//ydb/library/yql/dq/actors",
    # "//ydb/public/api/protos",
    # "//ydb/public/sdk/cpp/src/library/operation_id",
    # "//yql/essentials/public/issue",
    # ":compilation",
    # ":result_set_format",
    # ":shutdown",
    # ":simple",
  ]

  deps = [
    # "//ydb/core/grpc_services/base",
    # "//ydb/core/grpc_services/cancelation",
    # "//ydb/core/kqp/common",
    # "//yql/essentials/core/issue",
  ]

  sources = [
    "events/events.cpp",
    "events/query.cpp",
    "events/script_executions.cpp",
    "events/workload_service.cpp",
  ]
}

library("result_set_format") {
  public_deps = [
    # "//ydb/library/yql/dq/runtime",
    # "//ydb/public/api/protos",
  ]

  deps = [
    # "//ydb/core/formats/arrow",
    # "//ydb/core/kqp/common",
    # "//ydb/library/mkql_proto",
    # "//ydb/public/lib/scheme_types",
    # "//yql/essentials/minikql",
    # "//yql/essentials/utils",
  ]

  sources = [
    "result_set_format/kqp_formats_arrow.cpp",
    "result_set_format/kqp_result_set_builders.cpp",
  ]
}

library("shutdown") {
  public_deps = [
    ":simple",
    "//ydb/core/protos",
    "//ydb/library/actors/core",
  ]

  deps = [ "//library/cpp/deprecated/atomic" ]

  sources = [
    "shutdown/controller.cpp",
    "shutdown/events.cpp",
    "shutdown/state.cpp",
  ]
}

library("simple") {
  public_deps = [
    # "//ydb/core/base",
    # "//ydb/core/protos",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    # "//ydb/public/api/protos",
    # "//yql/essentials/core/pg_settings",
  ]

  deps = [
    # "//library/cpp/random_provider",
  ]

  sources = [
    "simple/helpers.cpp",
    "simple/kqp_event_ids.cpp",
    "simple/query_id.cpp",
    "simple/reattach.cpp",
    "simple/services.cpp",
    "simple/settings.cpp",
    "simple/temp_tables.cpp",
  ]
}
