library("arrow") {
    deps = [
        "//contrib/libs/apache/arrow",
        "//yql/essentials/minikql",
        "//yql/essentials/types:binary_json",
        "//yql/essentials/types:dynumber",
        "//yql/essentials/utils",
    ]

    sources = [
        "arrow/kqp_formats_arrow.cpp",
    ]
}

library("common") {
    public_deps = [
        ":events",
    ]

    deps = [
        "//ydb/core/base",
        "//yql/essentials/public/issue",
        "//yql/essentials/public/udf",
    ]

    sources = [
        "control.cpp",
        "kqp_batch_operations.cpp",
        "kqp_event_impl.cpp",
        "kqp_lwtrace_probes.cpp",
        "kqp_resolve.cpp",
        "kqp_row_builder.cpp",
        "kqp_ru_calc.cpp",
        "kqp_script_executions.cpp",
        "kqp_timeouts.cpp",
        "kqp_tx_manager.cpp",
        "kqp_tx.cpp",
        "kqp_types.cpp",
        "kqp_user_request_context.cpp",
        "kqp_yql.cpp",
        "kqp.cpp",
    ]
}

library("events") {
    public_deps = [
        ":result_set_format",
        ":simple",
        "//ydb/core/grpc_services:cancelation",
    ]

    deps = [
        "//yql/essentials/core/issue",
    ]

    sources = [
        "events/events.cpp",
        "events/query.cpp",
        "events/script_executions.cpp",
        "events/workload_service.cpp",
    ]
}

library("result_set_format") {
    public_deps = [
        "//contrib/libs/apache/arrow",
    ]

    deps = [
        "//ydb/core/formats/arrow",
        "//yql/essentials/minikql",
        "//yql/essentials/utils",
    ]

    sources = [
        "result_set_format/kqp_result_set_builders.cpp",
    ]
}

library("simple") {
    public_deps = [
        "//ydb/core/base",
    ]

    sources = [
        "simple/helpers.cpp",
        "simple/kqp_event_ids.cpp",
        "simple/query_id.cpp",
        "simple/reattach.cpp",
        "simple/services.cpp",
        "simple/settings.cpp",
        "simple/temp_tables.cpp",
    ]
}
