library("formats") {
  public_deps = [
    # "//yt/yt/client",
    # "//yt/yt/core",
  ]

  deps = [
    # "//library/cpp/string_utils/base64",  # peerdir only
    # "//yt/yt/library/skiff_ext",
    # "//yt/yt_proto/yt/formats",  # peerdir only
  ]

  sources = [
    "config.cpp",
    "format.cpp",
    "parser.cpp",
    "schemaful_writer.cpp",
    "versioned_writer.cpp",
  ]
}
