unittest_executable("ut") {
  deps = [
    "//library/cpp/getopt",  # peerdir only
    "//library/cpp/svnversion",  # peerdir only
    "//library/cpp/testing/unittest",
    "//ydb/core/base",  # peerdir only
    "//ydb/core/blobstorage",  # peerdir only
    "//ydb/core/blobstorage/vdisk/hulldb/cache_block",
    "//ydb/core/erasure",  # peerdir only
  ]

  sources =
      [ "//ydb/core/blobstorage/vdisk/hulldb/cache_block/cache_block_ut.cpp" ]

  include_dirs = [ "//ydb/core/blobstorage/vdisk/hulldb/cache_block" ]

  link_select = [
    "YqlServicePolicy=stub",
    "allocator=tcmalloc",
    "minikql_codegen=no_llvm",
    "yql_pg_runtime=pg_dummy",
    "yql_pg_sql_translator=pg_dummy",
  ]
}
