library("testlib") {
  testonly = true

  public_deps = [
    # "//contrib/libs/apache/arrow",
    # "//contrib/libs/protobuf",
    "//library/cpp/testing/unittest",
    # "//library/cpp/threading/future",
    # "//library/cpp/yson",
    # "//ydb/core/base",
    "//ydb/core/blobstorage/dsproxy:mock",
    # "//ydb/core/blobstorage/pdisk",
    # "//ydb/core/client",
    "//ydb/core/client:db_key_resolver",
    "//ydb/core/client:minikql_compile",
    "//ydb/core/client:server",
    "//ydb/core/cms/console",
    "//ydb/core/driver_lib/run:config",
    # "//ydb/core/engine:minikql",
    # "//ydb/core/fq/libs/shared_resources:interface",
    # "//ydb/core/http_proxy",
    "//ydb/core/kesus/tablet",
    "//ydb/core/keyvalue",
    "//ydb/core/kqp/federated_query",
    "//ydb/core/kqp/federated_query:actors",
    "//ydb/core/mind",
    "//ydb/core/mind:address_classification",
    # "//ydb/core/mind:hive",
    # "//ydb/core/persqueue/common:proxy",
    "//ydb/core/persqueue/public:cluster_tracker",
    # "//ydb/core/persqueue/public:utils",
    "//ydb/core/protos",
    # "//ydb/core/scheme",
    "//ydb/core/security",
    "//ydb/core/security:token_manager",
    "//ydb/core/tablet",
    # "//ydb/core/tablet_flat",
    "//ydb/core/testlib/actors",
    "//ydb/core/testlib/basics",
    # "//ydb/core/tx",
    # "//ydb/core/tx/replication/service",
    # "//ydb/core/tx/schemeshard",
    "//ydb/core/util",
    # "//ydb/library/accessor",
    # "//ydb/library/aclib",
    # "//ydb/library/actors/core",
    "//ydb/library/grpc/server",
    # "//ydb/library/mkql_proto:protos",
    # "//ydb/library/persqueue/topic_parser",
    # "//ydb/library/yql/providers/s3/actors_factory",
    # "//ydb/public/api/protos",
    # "//ydb/public/lib/deprecated/client",
    # "//ydb/public/lib/deprecated/kicli",
    # "//ydb/public/sdk/cpp/src/client/driver",
    # "//ydb/public/sdk/cpp/src/client/persqueue_public",
    # "//ydb/public/sdk/cpp/src/client/result",
    # "//ydb/public/sdk/cpp/src/client/table",
    # "//yql/essentials/minikql",
  ]

  deps = [
    # "//library/cpp/regex/pcre",
    # "//library/cpp/testing/gmock_in_unittest",
    # "//ydb/core/blobstorage/base",  # peerdir only
    # "//ydb/core/blobstorage/events",
    "//ydb/core/client:metadata",
    "//ydb/core/config/init",
    "//ydb/core/driver_lib/run",
    # "//ydb/core/driver_lib/version",  # peerdir only
    # "//ydb/core/engine",
    # "//ydb/core/formats",
    # "//ydb/core/formats/arrow",
    # "//ydb/core/fq/libs/checkpoint_storage",
    # "//ydb/core/fq/libs/control_plane_proxy",
    # "//ydb/core/fq/libs/control_plane_storage:service_id",
    "//ydb/core/fq/libs/db_id_async_resolver_impl",
    "//ydb/core/fq/libs/init",
    "//ydb/core/fq/libs/mock",
    # "//ydb/core/fq/libs/shared_resources",  # peerdir only
    # "//ydb/core/graph/api",
    "//ydb/core/grpc_services",
    # "//ydb/core/grpc_services/base",
    # "//ydb/core/grpc_services/local_rpc",
    "//ydb/core/health_check",
    "//ydb/core/kafka_proxy",
    "//ydb/core/kesus/proxy",
    "//ydb/core/kqp",  # peerdir only
    # "//ydb/core/kqp/common",
    "//ydb/core/kqp/finalize_script_service",
    "//ydb/core/kqp/proxy_service",
    "//ydb/core/kqp/rm_service",
    # "//ydb/core/kqp/ut/common",
    "//ydb/core/metering",
    "//ydb/core/mind:bscontroller",
    "//ydb/core/mind:tenant_node_enumeration",
    "//ydb/core/mon_alloc",
    # "//ydb/core/node_whiteboard",
    "//ydb/core/persqueue",
    "//ydb/core/persqueue/pqtablet/cache",
    # "//ydb/core/protos:schemeshard",
    "//ydb/core/security:ldap_auth_provider",
    "//ydb/core/statistics:aggregator",
    # "//ydb/core/statistics:service_id",
    "//ydb/core/sys_view:processor",
    "//ydb/core/sys_view:service",
    "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/data_accessor:cache_policy",
    "//ydb/core/tx/columnshard/overload_manager",
    "//ydb/core/tx/conveyor/service",
    # "//ydb/core/tx/conveyor/usage",
    "//ydb/core/tx/conveyor_composite/service",
    "//ydb/core/tx/conveyor_composite/usage",
    "//ydb/core/tx/coordinator",
    # "//ydb/core/tx/datashard",
    # "//ydb/core/tx/general_cache:usage",
    "//ydb/core/tx/limiter/grouped_memory/service",
    "//ydb/core/tx/long_tx_service",
    # "//ydb/core/tx/long_tx_service:public",
    "//ydb/core/tx/mediator",
    "//ydb/core/tx/priorities/service",  # peerdir only
    # "//ydb/core/tx/priorities/usage",
    "//ydb/core/tx/replication/controller",
    "//ydb/core/tx/sequenceproxy",
    "//ydb/core/tx/sequenceshard",
    # "//ydb/core/tx/time_cast",
    "//ydb/core/tx/tx_allocator",
    # "//ydb/core/tx/tx_proxy:public",
    "//ydb/core/viewer",
    # "//ydb/library/actors/http",
    # "//ydb/library/actors/interconnect",
    "//ydb/library/folder_service:mock",
    "//ydb/library/grpc/server:actors",
    "//ydb/library/security",
    # "//ydb/library/services",
    # "//ydb/library/yql/dq/actors:compute",
    # "//ydb/library/yql/utils/actor_log",
    # "//ydb/public/lib/base",
    "//ydb/public/lib/yson_value",
    # "//ydb/public/sdk/cpp/src/client/query",
    "//ydb/public/sdk/cpp/src/client/topic:codecs",  # peerdir only
    # "//ydb/public/sdk/cpp/src/library/grpc/client",  # peerdir only
    "//ydb/services/auth",
    "//ydb/services/cms",
    "//ydb/services/datastreams",
    # "//ydb/services/deprecated/persqueue_v0",
    "//ydb/services/discovery",
    "//ydb/services/ext_index/common",
    "//ydb/services/ext_index/service",
    "//ydb/services/fq",
    "//ydb/services/kesus",
    # "//ydb/services/metadata",
    "//ydb/services/metadata/ds_table",
    "//ydb/services/monitoring",
    "//ydb/services/persqueue_cluster_discovery",
    "//ydb/services/persqueue_v1",
    "//ydb/services/rate_limiter",
    "//ydb/services/replication",
    "//ydb/services/tablet",
    "//ydb/services/view",
    "//ydb/services/ydb",
    # "//ydb/services/ymq",
    # "//yql/essentials/minikql/comp_nodes/llvm16",  # peerdir only
    "//yql/essentials/minikql/invoke_builtins",
    # "//yql/essentials/public/issue",
    "//yql/essentials/public/udf/service/exception_policy",  # peerdir only
    # "//yql/essentials/types/binary_json",
    # "//yt/yql/providers/yt/codec:codegen",  # peerdir only
    # "//yt/yql/providers/yt/comp_nodes/dq/llvm16",  # peerdir only
    # "//yt/yql/providers/yt/comp_nodes/llvm16",  # peerdir only
  ]

  sources = [
    "actor_helpers.cpp",
    "common_helper.cpp",
    "cs_helper.cpp",
    "fake_coordinator.cpp",
    "storage_helpers.cpp",
    "tablet_flat_dummy.cpp",
    "tablet_helpers.cpp",
    "tenant_runtime.cpp",
    "test_client.cpp",
    "tx_helpers.cpp",
  ]
}
