library("column_fetching") {
  public_deps = [
    # "//ydb/core/tx/columnshard/engines/portions",
    # "//ydb/core/tx/general_cache/source",
    # "//ydb/core/tx/general_cache/usage",
    # "//ydb/core/tx/limiter/grouped_memory/usage",
    # "//ydb/library/actors/core",
  ]

  deps = [
    # "//ydb/core/tx/columnshard",
    # "//ydb/core/tx/columnshard/data_accessor:abstract",
  ]

  sources = [
    "cache_policy.cpp",
    "manager.cpp",
  ]
}
