library("initializer") {
  public_deps = [
    # "//library/cpp/threading/future",
    # "//library/cpp/time_provider",
    "//ydb/core/base",
    # "//ydb/library/accessor",
    # "//ydb/library/actors/core",
    "//ydb/public/api/protos",
    "//ydb/services/metadata/abstract",
    # "//ydb/services/metadata/ds_table",
    "//ydb/services/metadata/manager",
    "//ydb/services/metadata/request",
    "//ydb/services/metadata/request:config",
  ]

  deps = [
    "//ydb/core/grpc_services",  # peerdir only
    # "//ydb/core/grpc_services/base",  # peerdir only
    "//ydb/core/grpc_services/local_rpc",
    # "//ydb/services/metadata",
  ]

  sources = [
    "accessor_init.cpp",
    "behaviour.cpp",
    "common.cpp",
    "events.cpp",
    "fetcher.cpp",
    "initializer.cpp",
    "manager.cpp",
    "object.cpp",
    "snapshot.cpp",
  ]
}
